### ISSUE TITLE
Kotlin: auto-generated methods for implementation with delegation are taken into account in coverage report

### ISSUE THREAD

**Issue by qwwdfsad** [jacoco/jacoco#1002]
### Steps to reproduce

* JaCoCo version:  0.8.5.201910111838
* Operating system: macOS Catalina 10.15
* Tool integration: JaCoCo Gradle plugin
* Complete executable reproducer: https://github.com/qwwdfsad/coverage-test, package `coverage.delegates`, run command ` ./gradlew test jacocoTestReport`, report directory: `build/jacocoHtml`
* Steps: 
Implement any interface with delegation. Example from the reproducer:
```
class DelegatedList : List<Int> by ArrayList() {
    override val size: Int
        get() = 42
}
```

and use it as 
```
val list = DelegatedList()
```

### Expected behaviour
Coverage reports only one missing method, `size` 

### Actual behaviour
All `List` methods are reported as not covered

**Comment by Godin** [comment]
After compilation of [your example](https://github.com/qwwdfsad/coverage-test/tree/3c4083e4de9102e0dd62d7fa7fbda3613b037370) (`./gradlew test jacocoTestReport`) with following `DelegationExample.kt`

```
package coverage.delegates


class DelegatedList : List<Int> by ArrayList() {
    // Overridden method that should be shown as "not covered"
    override val size: Int
        get() = 42
}
```

execution of

```
javap -v -p build/classes/kotlin/main/coverage/delegates/DelegatedList.class
```

shows that there are far more methods than you currently see in the report

![report](https://user-images.githubusercontent.com/138671/73211423-7d13f000-414c-11ea-9a18-16805b2c0a50.png)

Methods generated by Kotlin compiler, which are marked as `ACC_SYNTHETIC` or do not have `LineNumberTable`, are already not shown in the report thanks to contribution of your colleague @goodwinnk ❤️ (see #689 and corresponding [`SyntheticFilter`](https://github.com/jacoco/jacoco/blob/v0.8.5/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/SyntheticFilter.java) and [`KotlinGeneratedFilter`](https://github.com/jacoco/jacoco/blob/v0.8.5/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinGeneratedFilter.java)):

```
  public java.lang.Object get(int);
    descriptor: (I)Ljava/lang/Object;
    flags: (0x1041) ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: iload_1
         2: invokevirtual #66                 // Method get:(I)Ljava/lang/Integer;
         5: areturn
      LineNumberTable:
        line 4: 0
```

```
  public java.lang.Integer get(int);
    descriptor: (I)Ljava/lang/Integer;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=3, locals=2, args_size=2
         0: aload_0
         1: getfield      #27                 // Field $$delegate_0:Ljava/util/ArrayList;
         4: iload_1
         5: invokevirtual #68                 // Method java/util/ArrayList.get:(I)Ljava/lang/Object;
         8: dup
         9: ldc           #70                 // String get(...)
        11: invokestatic  #73                 // Method kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull:(Ljava/lang/Object;Ljava/lang/String;)V
        14: checkcast     #32                 // class java/lang/Integer
        17: areturn
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      18     0  this   Lcoverage/delegates/DelegatedList;
            0      18     1 index   I
    RuntimeInvisibleAnnotations:
      0: #51()
        org.jetbrains.annotations.NotNull
```

```
  public boolean contains(int);
    descriptor: (I)Z
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: getfield      #27                 // Field $$delegate_0:Ljava/util/ArrayList;
         4: iload_1
         5: invokestatic  #43                 // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
         8: invokevirtual #45                 // Method java/util/ArrayList.contains:(Ljava/lang/Object;)Z
        11: ireturn
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      12     0  this   Lcoverage/delegates/DelegatedList;
            0      12     1 element   I
```

Whereas generated methods that you see (`contains(Object)`, `lastIndexOf(Object)` and `indexOf(Object)`) are not marked as `ACC_SYNTHETIC` and have `LineNumberTable`:

```
  public final boolean contains(java.lang.Object);
    descriptor: (Ljava/lang/Object;)Z
    flags: (0x0051) ACC_PUBLIC, ACC_FINAL, ACC_BRIDGE
    Code:
      stack=2, locals=2, args_size=2
         0: aload_1
         1: instanceof    #32                 // class java/lang/Integer
         4: ifeq          10
         7: goto          12
        10: iconst_0
        11: ireturn
        12: aload_0
        13: aload_1
        14: checkcast     #34                 // class java/lang/Number
        17: invokevirtual #37                 // Method java/lang/Number.intValue:()I
        20: invokevirtual #39                 // Method contains:(I)Z
        23: ireturn
      StackMapTable: number_of_entries = 2
        frame_type = 10 /* same */
        frame_type = 1 /* same */
      LineNumberTable:
        line 4: 0
```

----

Also for a following IMO similar example

```
interface Base<E> {
    fun contains(e: E): Boolean
}

class BaseImpl<E> : Base<E> {
    override fun contains(e: E): Boolean = false
}

class Derived : Base<Int> by BaseImpl()
```

using the same Kotlin compiler version `1.3.61` as in your example, execution of

```
kotlinc Example.kt
javap -v -p Derived.class
```

shows that generated methods either do not have `LineNumberTable` or marked as `ACC_SYNTHETIC`:

```
  public boolean contains(int);
    descriptor: (I)Z
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: getfield      #18                 // Field $$delegate_0:LBaseImpl;
         4: iload_1
         5: invokestatic  #37                 // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
         8: invokevirtual #39                 // Method BaseImpl.contains:(Ljava/lang/Object;)Z
        11: ireturn
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      12     0  this   LDerived;
            0      12     1     e   I

  public boolean contains(java.lang.Object);
    descriptor: (Ljava/lang/Object;)Z
    flags: (0x1041) ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: aload_1
         2: checkcast     #25                 // class java/lang/Number
         5: invokevirtual #29                 // Method java/lang/Number.intValue:()I
         8: invokevirtual #31                 // Method contains:(I)Z
        11: ireturn
      LineNumberTable:
        line 9: 0
```

----

AFAIK methods generated by Java compiler and marked as `ACC_BRIDGE` also always marked as `ACC_SYNTHETIC`. So I'm wondering why this is not the case in your example? Why there is difference between the two above examples (your and my)? In other words - can Kotlin compiler be updated to mark generated `ACC_BRIDGE` methods in the first example also as `ACC_SYNTHETIC` as it does in the second example?

Or can Kotlin compiler be updated to not produce line numbers for the generated methods in both examples? 

If Kotlin compiler can be updated, then methods will be filtered out from the report without changes on our side thanks to already existing filters 😉

----

At a quick glance maybe we can update filters in JaCoCo to do the exclusion of methods marked as `ACC_BRIDGE` even if they are not marked as `ACC_SYNTHETIC` and have `LineNumberTable`. However this IMO anyway requires answer on the following question - how and when Kotlin Compiler generates such and other methods marked as `ACC_BRIDGE`? For example - looking at #773 seems that in past for implementation of default arguments Kotlin compiler was erroneously marking `ACC_STATIC` methods as `ACC_BRIDGE`, which is not the case anymore.

----

We are interested in improvements of JaCoCo reports for Kotlin as well as in improvements of our validation tests for it. And we can try to find answers on the above questions in code of compiler, however maybe you @qwwdfsad can help us and simply forward and get answers directly from developers of compiler? 😉 Thank you in advance!

**Comment by qwwdfsad** [comment]
Thanks for the detailed write-up!

>So I'm wondering why this is not the case in your example?

After some investigation, I've figured it out: it's because it is `List` is a "special" interface (it has its own Kotlin declaration, but actually mapped by the compiled to `java.util.List`) and the methods that are not synthetic are marked with `UnsafeVariance`. Feeling lucky to pick this one for test :)

Unfortunately, no one in the team knows **for sure** why exactly these very bridges are not synthetic. It could be either some Java interoperability issues from early days or just an oversight.

Changing this behaviour is possible, but requires tremendous effort: it is potentially a breaking change that can affect debugging, source code compatibility (in Java interop layer), binary compatibility and observable changes in runtime behaviour. So first it should be thoroughly investigated, then approved by the [language committee](https://kotlinlang.org/foundation/language-committee-guidelines.html) and gracefully changed within two major versions of the language.
Taking into account insignificance of this problem for the general public, it's unlikely to happen.

I realize that "we don't know for sure why this is happening but won't change that" is not very convincing, so it's really up to you to decide whether you want to support such filter (though it would be really nice)

**Comment by marchof** [comment]
The `synthetic` flag has a important side-effect: You cannot compile source code against synthetic members. Also `synthetic` members are not available in IDEs (code completion). Maybe this is the reason here?

**Comment by Godin** [comment]
@qwwdfsad seems that you're mainly talking about `ACC_SYNTHETIC`, so what about the second option - can Kotlin compiler be updated to not produce line numbers in these generated methods?

----

@marchof on the other hand, Java Virtual Machine Specification starting from 7 Edition contains (https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.6):

> **ACC_BRIDGE** | 0x0040 | A bridge **method, generated by the compiler**.
> ACC_SYNTHETIC | 0x1000 | Declared synthetic; not present in the source code.
> ...
> **The ACC_BRIDGE flag is used to indicate** a bridge **method generated by a Java compiler**.
>
> A method may be marked with the ACC_SYNTHETIC flag to indicate that it was generated by a compiler and does not appear in source code, unless it is one of the methods named in §4.7.8.

which indeed can be interpreted as sole `ACC_BRIDGE` is enough to consider method as generated and so exclude from coverage reports. Definitely for Java this won't change anything in case of javac and ECJ, hopefully for Kotlin will exclude only methods discussed here, don't know about other JVM languages. So @marchof which following option you would prefer

1. add new `BridgeFilter` which will be language neutral
2. or update `SyntheticFilter`
3. add new `KotlinBridgeFilter` with guard condition `KotlinGeneratedFilter.isKotlinClass(context)`
4. or update `KotlinGeneratedFilter`

?

**Comment by marchof** [comment]
@Godin Clearly option 1. Preferring general definitions of the VM specification over language specific pattern matching.

**Comment by qwwdfsad** [comment]
>can Kotlin compiler be updated to not produce line numbers in these generated methods?

It is a smaller change, but its consequences are not clear as well. These methods will become inconsistent with the rest of the bridges (NB: javac generates line numbers for synthetic bridges), stacktraces will become a bit uglier (and, what's more important, unnavigable in IDEA) and another tooling may already rely on these line numbers.

In general, we can change things like this if it is a serious bug in the codegen, a missing optimization at the bytecode level or clearly a redundant and unreachable bytecode.
Everything else, while possible and maybe even reasonable in the general sense, is unlikely to happen. Any change in the language (even small one such as adding a modifier) requires a serious effort from a large group of people and is, potentially, a breaking change. And while we have a lot of other work on the table, it would be really hard to convince the team to spend effort on codegen changes.
