### ISSUE TITLE
Too low coverage reported with exceptions thrown from methods

### ISSUE THREAD

**Issue by Vampire** [jacoco/jacoco#1003]
### Steps to reproduce

* JaCoCo version:  0.8.5.201910111838
* Operating system: Win 10
* Tool integration: Gradle
* Complete executable reproducer: [foo.zip](https://github.com/jacoco/jacoco/files/4120269/foo.zip)
* Steps: `./gradlew test`

### Behaviour

The coverage is measured too low if you look at the generated report.
All lines in the methods are actually covered.
Differences between the methods:
- `...` vs. `...2` => `System.out.println("Foo");` added
- `foo` vs. `bar`, `baz` vs. `bam`, `boo` vs. `hoo` => return type
- `foo`/`bar` vs. `baz`/`bam` vs. `boo`/`hoo` => `sneakyThrow` vs. `unsneakyThrow` vs. `throw`

- The only examples that show fully covered, even without the `println` are the ones with `throw`.
- For the others the `if (throwable instanceof` line shows yellow, unless the `println` is added which makes not much sense (maybe bytecode-wise, but not for the average JaCoCo user).
- And the `sneakyThrow` and `unsneakyThrow` lines are red. I would maybe understand if they are yellow, as the actual successful returning of the method call or the actual method is not covered, but showing the lines as uncovered is not right from a users perspective.

**Comment by marchof** [comment]
This a limitation in the design of JaCoCo, please see our [FAQ](https://www.jacoco.org/jacoco/trunk/doc/faq.html):

**Q: Source code lines with exceptions show no coverage. Why?**

JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding line of source code is not marked as covered.

**Comment by Vampire** [comment]
@marchof I can understand this for the lines where a method throws an exception, even though lines which `throw` directly are handled properly. 
But shouldn't the `if` be green, even without the `System.out.println("Foo");`?

**Comment by Godin** [comment]
@Vampire 

> the `if (throwable instanceof` line shows yellow, unless the println is added

> But shouldn't the `if` be green, even without the `System.out.println("Foo");`?

This is a known issue - #321

**Comment by Vampire** [comment]
Ah, great, thanks and sorry for the dup then. :-)
