### ISSUE TITLE
Using ASM to modify Java classfiles without recomputing stack map frames results in VerifyErrors in downstream agents

### ISSUE THREAD

**Issue by kyle-cackett** [jacoco/jacoco#1009]
### Steps to reproduce

* JaCoCo version:  0.8.5
* Operating system: Linux (Ubuntu) & Mac OSX
* Tool integration: CLI
* Complete executable reproducer: https://github.com/kyle-cackett/class-instrumentation
* Steps: Run `./gradlew run`

This reproducer uses the Java Allocation Instrumenter agent to perform bytecode manipulation on classes that have themselves already been modified by JaCoCo which results in a `java.lang.VerifyError`. We believe the root cause of this issue is that JaCoCo uses ASM to write modified class files _without computing stack map frames_ [by passing 0 as a flag to the ClassWriter object](https://github.com/jacoco/jacoco/blob/17313eba38b68ab43595a0f3e07d8a32e2e12a06/org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java#L76-L82). This flag is mapped to [MethodWriter.COMPUTE_NOTHING](https://gitlab.ow2.org/asm/asm/blob/9c3711bd3f832e663f801fcbde10ce1c449ea83f/asm/src/main/java/org/objectweb/asm/ClassWriter.java#L264) within the ASM framework which means that neither stack map frames nor the maximum stack size are computed. 

The interaction between agents which modify bytecode but do not recompute stack map frames and agents which assume that stack map frames exist (such as the Java Allocation Instrumenter) leads to VerifyErrors when the JVM attempts to verify the twice-modified classes. In an attempt to address this issue quickly, I have also opened [an issue with the Java Allocation Instrumenter project](https://github.com/google/allocation-instrumenter/issues/35) which contains additional information about the problem.

We recommend that JaCoCo pass in a flag to the `ClassWriter` which results in valid stack map frames in the modified files (e.g. [ClassWriter.COMPUTE_FRAMES](https://www.javadoc.io/static/org.ow2.asm/asm/7.3.1/org/objectweb/asm/ClassWriter.html#COMPUTE_FRAMES) or [ClassWriter.COMPUTE_MAXS](https://www.javadoc.io/doc/org.ow2.asm/asm/latest/org/objectweb/asm/ClassWriter.html#COMPUTE_MAXS))

### Expected behaviour

The application should run successfully, printing the following lines:
```
$ ./gradlew run
[…]
allocating FatalException
class instrumentation.FatalException
BUILD SUCCESSFUL in 550ms
[…]
```
### Actual behaviour
The application fails, printing the following lines:
```
$ ./gradlew run
[…]
Verification for instrumentation.FatalException failed
java.lang.VerifyError
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at com.google.monitoring.runtime.instrumentation.ConstructorInstrumenter.instrumentClass(ConstructorInstrumenter.java:84)
        at instrumentation.App.main(App.java:13)
End class verification for: instrumentation.FatalException
RedefineClasses-0x2: verify_byte_codes exception: 'java/lang/VerifyError'
[…]
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1
[…]
BUILD FAILED in 568ms
[…]
```

(In case of exceptions provide FULL STACKTRACE)

**Comment by marchof** [comment]
Hi @kyle-cackett JaCoCo creates valid stackmap frames by incrementally adjusting the existing ones. We have extensive [tests](https://github.com/jacoco/jacoco/blob/master/org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/FramesTest.java) for this.

We do explicitly not use ASM with `COMPUTE_FRAMES` as this is a expensive operation which results in **loading** dependent classes which in turn would break any multi-classloader application.

If we find some time we will try to understand what the root cause is for the failure in your reproducer.

**Comment by Godin** [comment]
JaCoCo does not use `ClassWriter.COMPUTE_FRAMES` and this is not a mistake, because this option requires knowledge of type hierarchies that might not be available at a time of instrumentation. Instead JaCoCo tracks and updates frames without doing their full recomputation. Update requires original frames to be correct.

Furthermore in your example (https://github.com/kyle-cackett/class-instrumentation) seems that verification fails for `$jacocoInit`, whose frames are predefined - https://github.com/jacoco/jacoco/blob/v0.8.5/org.jacoco.core/src/org/jacoco/core/internal/instr/ClassFieldProbeArrayStrategy.java#L99

So I strongly believe that the issue is in another agent, what seems to be already confirmed - https://github.com/google/allocation-instrumenter/issues/35#issuecomment-580591930

**Comment by kyle-cackett** [comment]
While the suggested solution may not be appropriate, based on the fact that the MRE fails _only_ when the JaCoCo agent is included and the issue is resolved when other agents set the `ClassWriter.COMPUTE_FRAMES` flag it still seems possible that something odd may be going on with the stack map frame code. If JaCoCo has independently developed stack map frame modification logic I would request that someone look into the MRE before closing.

One strange observation we had was that when the `-XX:+UnlockDiagnosticVMOptions` and `-XX:+VerboseVerification` JVM options are set it appears as though the problematic class is verified twice, once successfully and once unsuccessfully. During the second failed verification the StackMapTable associated with the `jacocoInit` method is empty whereas during the initial successful verification it is not.

First verification (SUCCEEDS):
```
Verifying class instrumentation..FatalException with new format
Verifying method instrumentation..FatalException.$jacocoInit()[Z
StackMapTable: frame_count = 1
table = {
  bci: @50
  flags: { }
  locals: { }
  stack: { '[Z' }
 }
Verifying method instrumentation.FatalException.<init>(Ljava/lang/String;)V
StackMapTable: frame_count = 0
table = {
 }
Verifying method instrumentation.FatalException.<init>(Ljava/lang/Throwable;)V
StackMapTable: frame_count = 0
table = {
 }
Verifying method instrumentation.FatalException.<init>(Ljava/lang/String;Ljava/lang/Throwable;)V
StackMapTable: frame_count = 0
table = {
 }
End class verification for: instrumentation.FatalException
```
Second verification (FAILS):
```
Verifying class instrumentation.FatalException with new format
Verifying method instrumentation.FatalException.$jacocoInit()[Z
StackMapTable: frame_count = 0
table = {
 }
Verification for instrumentation.FatalException failed

**Comment by marchof** [comment]
@kyle-cackett As mentioned by @Godin JaCoCo does exactly create the correct stack map frame as shown in your first verification. If another agent drops this frame this has to be fixed in the respective project.

**Comment by kyle-cackett** [comment]
@marchof Thanks for the response! The one part of this investigation that doesn't quite fall into place for me is the fact that the other agent was using the `ClassWriter.COMPUTE_MAXS` flag when writing its bytecode which, according to the ASM Javadoc, should be acceptable provided that the class being modified has "[valid stack map frames](https://www.javadoc.io/doc/org.ow2.asm/asm/latest/org/objectweb/asm/ClassWriter.html#COMPUTE_MAXS)".

So although the issue at hand will be resolved by the other agent defensively using the `ClassWriter.COMPUTE_FRAMES` flag it's still a little unclear to me why that should be necessary if the JaCoCo agent is indeed producing bytecode with valid stack map frames in the first place.

Having said that, I've just learned about ASM and stack map frames over the last few days so am far from being an expert. I mainly wanted to ensure that someone with more knowledge of the subject verified that there isn't a latent issue on the JaCoCo side of the equation.

Thank you again for your help and attention on this and if you are convinced that all is well in the JaCoCo agent I am also satisfied.

**Comment by marchof** [comment]
@kyle-cackett Please note that `ClassWriter.COMPUTE_FRAMES` comes with [bad side effects](https://www.javadoc.io/doc/org.ow2.asm/asm/latest/org/objectweb/asm/ClassWriter.html#getCommonSuperClass-java.lang.String-java.lang.String-) and the other agent might find a better way to keep/adjust stackmap frames correctly.

**Comment by Godin** [comment]
> it's still a little unclear to me why that should be necessary if the JaCoCo agent is indeed producing bytecode with valid stack map frames in the first place

@kyle-cackett Because of `ClassReader.SKIP_FRAMES` in https://github.com/google/allocation-instrumenter/blob/java-allocation-instrumenter-3.2.0/src/main/java/com/google/monitoring/runtime/instrumentation/ConstructorInstrumenter.java#L123

You can modify your example (https://github.com/kyle-cackett/class-instrumentation/tree/e1a00fef4c6b126159ef33b8e8bdc7510ca69972) as following

```diff
diff --git i/build.gradle w/build.gradle
index cdc46f8..b1c03fa 100644
--- i/build.gradle
+++ w/build.gradle
@@ -22,7 +22,7 @@ application {
         "-XX:+UnlockDiagnosticVMOptions",
         "-XX:+VerboseVerification",
         "-XX:TraceRedefineClasses=2",
-        "-javaagent:${buildDir}/install/${project.name}/lib/org.jacoco.agent-0.8.5-runtime.jar=destfile=/tmp/coverage.exec",
+//        "-javaagent:${buildDir}/install/${project.name}/lib/org.jacoco.agent-0.8.5-runtime.jar=destfile=/tmp/coverage.exec",
         "-javaagent:${buildDir}/install/${project.name}/lib/java-allocation-instrumenter-3.2.0.jar=manualOnly",
         ]
 }
diff --git i/src/main/java/instrumentation/FatalException.java w/src/main/java/instrumentation/FatalException.java
index 44f1b20..f38b4d8 100644
--- i/src/main/java/instrumentation/FatalException.java
+++ w/src/main/java/instrumentation/FatalException.java
@@ -12,5 +12,8 @@ public class FatalException extends RuntimeException {

   public FatalException(Throwable cause) {
     super(cause);
+    if (cause instanceof Exception) {
+        System.out.println();
+    }
   }
 }
```

and you'll see failure even without JaCoCo.

**Comment by kyle-cackett** [comment]
@Godin Thank you for tying off that loose end. A fix for this issue has been integrated into the other agent.
