### ISSUE TITLE
Groovy Closure - Generated Methods are not covered

### ISSUE THREAD

**Issue by anumalasri** [jacoco/jacoco#1021]
### Steps to reproduce

* JaCoCo version:   0.8.5
* Operating system: Mac
* Tool integration: Gradle
* Complete executable reproducer:  https://github.com/anumalasri/groovy-closure-jacoco
* Steps: (what exactly are you doing with the above reproducer?)
Running Jacoco coverage on Groovy classes, which has few closures. 

### Expected behaviour
Closures class must be covered completely, by ignoring generated methods.  As Closures are generated classes, some of methods in these should be ignored in coverage.  https://github.com/jacoco/jacoco/wiki/FilteringOptions#groovy

### Actual behaviour
Generated methods in Closure class are not covered. Hence, coverage no# are impacting.
![image](https://user-images.githubusercontent.com/27963315/74344161-27f5f200-4d7a-11ea-87fc-59c46cb2a8ac.png)

(In case of exceptions provide FULL STACKTRACE)

**Comment by aalmiray** [comment]
This appears to be a problem on the Groovy side. Public accessors for captured arguments should be annotated with `@Generated` but aren't. See https://issues.apache.org/jira/browse/GROOVY-9396

**Comment by aalmiray** [comment]
Fixed in Groovy 3.0.1 released on 2020/02/17
