### ISSUE TITLE
Coverage test failure for mybatis mapper methods which have multiple parameters without @Param

### ISSUE THREAD

**Issue by zrlw** [jacoco/jacoco#1025]
### Steps to reproduce

* JaCoCo version:  0.8.2
* Operating system: Win10 
* Tool integration: Maven
IDE: Eclipse 4.10.0
Project Type: Springboot 2.1.1 
Mybatis: 3.4.6
Jdk: 1.8
* Steps
1. mapper.xml snippet: 
```
<select id="getUsers" resultMap="baseResultMap">
      SELECT * FROM user  WHERE FirstName = #{firstName} AND LastName = #{lastName}
</select>
```
2. mapper.java snippet:  
```
List<User> getUsers(String firstName, String lastName);
```
3. the program run ok, but jacoco coverage test failure for getUsers, the error message in log:
```
org.apache.ibatis.binding.BindingException: Parameter 'firstName' not found.  Available parameters are [arg1, arg0, param1, param2]  
```
it seemed jacoco javaagent do not pass correct parameter name to mybatis because i saw parameter names listed in mapper.class:
```
public abstract java.util.List getUsers(java.lang.String firstName, java.lang.String lastName);  
```
Method parameters:  
firstName  
lastName  

### Expected behaviour
pass actual parameter name 'firstName', 'lastName' to mybatis  

### Actual behaviour
pass arg0, arg1, param1, param2 to mybatis
  
### Exceptions snippet:  

```
Caused by: org.apache.ibatis.binding.BindingException: Parameter 'firstName' not found. Available parameters are [arg1, arg0, param1, param2]  
               at org.apache.ibatis.binding.MapperMethod$ParamMap.get(MapperMethod.java:204) ~[mybatis-3.4.6.jar:3.4.6]  
...
```

**Comment by Godin** [comment]
@zrlw As shows following example - JaCoCo does not change names of parameters:

given `Example.java`

```
import java.lang.reflect.Method;
import java.lang.reflect.Parameter;

class Example {
        public static void main(String[] args) throws Exception {
                print(Example.class);
        }

        static void print(Class<?> cls) throws Exception {
                for (Method m : cls.getDeclaredMethods()) {
                        System.out.println(m.getName());
                        for (Parameter p : m.getParameters()) {
                                System.out.println("  " + p.getName());
                        }
                }
        }

        void getUsers(String firstName, String lastName) {
        }
}
```

execution of

```
java -version \
    && javac -parameters Example.java \
    && java -javaagent:jacoco-0.8.2/lib/jacocoagent.jar Example
```

produces

```
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
main
  args
print
  cls
$jacocoInit
getUsers
  firstName
  lastName
```

So instead of snippets please provide **complete** reproducer e.g. GitHub repository.

**Comment by zrlw** [comment]
you are right, 
it's not JaCoCo's problem, it's JMockit's problem.
if use JMockit @Injectable to inject a mapper to the test Class, then all followed test Classes which inject the mapper by @Autowired will only pass arg0,...,param1,... to mybatis.
