### ISSUE TITLE
tomcat7-maven-plugin start up when use jacoco-maven-plugin  with  offline mode 

### ISSUE THREAD

**Issue by funaiy** [jacoco/jacoco#1027]
Hi,
I use Jacoco offline mode in my project ,  when i run web  by tomcat7-maven-plugin,  it is always failed! the message is：  
     Instantiation of bean failed; nested exception is java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_035b120/Offline  

I track the t tomcat7-maven-plugin startup log:
```
[INFO] >>> tomcat7-maven-plugin:2.2:run (default-cli) > process-classes @ ... >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce) @  ... ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @  ... ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @  ... ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 76 source files to ...
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.4:instrument (default-instrument) @ ... ---
[INFO] 
[INFO] <<< tomcat7-maven-plugin:2.2:run (default-cli) < process-classes @ ... <<<
```
I think the reason is jacoco do not   restore-instrumented-classes, how can i fix this problem. 

Thank you!

**Comment by funaiy** [comment]
this is my jacoco config:
```
  <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.4</version>
                <executions>
                    <execution>
                        <id>default-instrument</id>
                        <goals>
                            <goal>instrument</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-restore-instrumented-classes</id>
                        <phase>test</phase>
                        <goals>
                            <goal>restore-instrumented-classes</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <configuration>
                            <dataFile>${project.build.directory}/coverage.exec</dataFile>
                        </configuration>
                    </execution>

                </executions>
            </plugin>
```
I want export report in test phase ,so  i set restore-instrumented-classes in test phase

**Comment by Godin** [comment]
> Instantiation of bean failed; nested exception is java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_035b120/Offline

@funaiy quoting FAQ at https://www.jacoco.org/jacoco/trunk/doc/faq.html :

> ### Why do I get a NoClassDefFoundError or ClassNotFoundException for class org.jacoco.agent[...]Offline?
> If you use offline instrumentation the instrumented classes get a direct dependency on the JaCoCo runtime. Therefore jacocoagent.jar of the same JaCoCo version must be on the classpath and accessible from by the instrumented classes.

**Comment by funaiy** [comment]
i have add this dependcy:
```
        <dependency>
            <groupId>org.jacoco</groupId>
            <artifactId>org.jacoco.agent</artifactId>
            <classifier>runtime</classifier>
        </dependency>
```

but the result is false too !

**Comment by Godin** [comment]
@funaiy there is nothing to add to https://github.com/jacoco/jacoco/issues/1027#issuecomment-597002854 , because partial snippets are not debuggable. So either provide **complete example** (e.g. as GitHub repository) or investigate by yourself why in your case this dependency can't be accessed by instrumented classes.
