### ISSUE TITLE
Add ip info in report sessions page

### ISSUE THREAD

**Issue by sandy320** [jacoco/jacoco#1029]
### Scenario
* JaCoCo version: 0.8.5
* Operating system: linux
* Tool integration: ant
* Description:
Add jacoco-agent to every nodes of micro-service, and collect/merge their exec with ant.
The seesions page only show the session id which is not so clear for costomer.

### Current Behaviour
The sessions page of report only show the session id whichi is not so readable.

### Wanted Behaviour
Add the ip in every dump info

**Comment by marchof** [comment]
The default session id is created from the local host name plus a random integer. JaCoCo is a universal tool and has no idea about your micro-service setup. Therefore session id can be configured according to your needs, see [documentation](https://www.jacoco.org/jacoco/trunk/doc/agent.html).

**Comment by Godin** [comment]
The session id is configurable and you can set it to any value you want, e.g. one that contains IP - see agent options on page https://www.jacoco.org/jacoco/trunk/doc/agent.html
