### ISSUE TITLE
Kotlin Destructing declarations show as untested

### ISSUE THREAD

**Issue by georgemarin** [jacoco/jacoco#1030]
### Steps to reproduce

* JaCoCo version: 0.8.5.201910111838
* Operating system:macOS Catalina 10.15.3
* Tool integration: Maven 
* Complete executable reproducer: private repository, cannot provide
* Steps:
 1. declare variables using kotlin's destructing declarations
 2. run the test coverage
 3. notice the code shows as untested 

### Expected behavior

 Getter shows as untested

### Actual behavior
Getter shows as untested

```
        val (jobId, processedRecords, errorRecords) = response

        assertEquals(errorRecords, 5)
        assertEquals(jobId, "foo")
        assertEquals(processedRecords, 5)
```

**Comment by Godin** [comment]
> ### Actual behavior
> Getter shows as untested

This is expected behavior, because destructuring declaration doesn't use getters - quoting https://kotlinlang.org/docs/reference/multi-declarations.html :

> ```
> val (name, age) = person
> ```
> 
> A destructuring declaration is compiled down to the following code:
> 
> ```
> val name = person.component1()
> val age = person.component2()
> ```
