### ISSUE TITLE
When using JDK1.6 for was, was cannot be started after jacoco is configured, and there is no exception log output for was

### ISSUE THREAD

**Issue by lyujunjie** [jacoco/jacoco#1031]
When using JDK1.6 for was, was cannot be started after jacoco is configured, and there is no exception log output for was

Is it true that the package of jacoco 0.8.5 provided by the official website can only be used in JDK1.8 or above. If so, is it necessary to compile 1.6 version of jacoco by yourself. There is no problem testing under the Tomcat container

**Comment by Godin** [comment]
> Is it true that the package of jacoco 0.8.5 provided by the official website can only be used in JDK1.8 or above

No - quoting https://www.jacoco.org/jacoco/trunk/doc/faq.html :

> the **minimum JRE version required by the JaCoCo runtime (e.g. the agent) and the JaCoCo tools is 1.5**

----

> When using JDK1.6 for was, was cannot be started after jacoco is configured, and there is no exception log output for was

No idea what "was" means in your context. And we don't investigate issues in absence of **complete example** and **exact steps to reproduce**.
