### ISSUE TITLE
Stuck at jacoco task

### ISSUE THREAD

**Issue by slott** [jacoco/jacoco#1041]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling bug report!

### Steps to reproduce

* JaCoCo version:  0.8.5
* Operating system: osx
* Tool integration: Gradle
* Complete executable reproducer: Company code - can't share
* Steps: When building

### Expected behaviour
Expect build to complete

### Actual behaviour
Stuck at jacoco task

(In case of exceptions provide FULL STACKTRACE)

Not sure what is going on - but if I break (ctrl + c) and run again it _always_ works - so its not a blocking issue - just very very frustrating.
Its especially pronounced when switching between branches - then the first build almost always gets stuck at jacoco task.

Is there anything I can provide that would help with the investigation ?

I have a _very_ large build script as we have a pretty big and successful app - so its the ultimate jacoco integration test :)

**Comment by marchof** [comment]
> Stuck at jacoco task

What exactly does this mean? Never returns? Error?

**Comment by slott** [comment]
<img width="358" alt="wine-scanner-android — -bash — 208×42 2020-04-08 10-21-37" src="https://user-images.githubusercontent.com/32587/78761380-cec5cb80-7982-11ea-9b51-7f585cb55f5e.png">

When running the build task it often get stuck at the jacoco task and never continues.

**Comment by Godin** [comment]
@slott What would you do if such happens with your Java application? Gradle is also Java application, so for example, one can at least enable debug logs, attach a debugger and do the threads dump.

**Comment by slott** [comment]
Here is a jstack trace
[out.txt](https://github.com/jacoco/jacoco/files/4450888/out.txt)

and a sample using the system dialog
[Sample of java.txt](https://github.com/jacoco/jacoco/files/4450890/Sample.of.java.txt)

I hope this will be enough.

Have a great easter

**Comment by marchof** [comment]
I can't spot an issue in the stack dump. All threads where JaCoCo is involved are in "RUNNABLE" state. It could also be an issue with Gradle or Android.

WIthout a reproducer we're not able to debug this. Sorry.

**Comment by slott** [comment]
Thanks for looking. I'll try my luck with AS developers again and hope they will take it seriously this time around. Anyone else finding this can continue there: https://issuetracker.google.com/issues/154069245
