### ISSUE TITLE
Jacoco 'check' goal ignores 'dataFile' configuration in a multi-module maven project

### ISSUE THREAD

**Issue by sergeymeshkov** [jacoco/jacoco#1047]
I set up a multimodule Maven project with a separate module which should run integration tests (test module). After running `mvn clean verify` Jacoco generates valid coverage report and jacoco.exec file, which is located in the target folder, however, `check` goal ignores 'dataFile' configuration and skip goal.

### Steps to reproduce

* JaCoCo version: 0.8.5
* Operating system: Ubuntu 18.04.4 LTS
* Tool integration: Maven
* Complete executable reproducer: https://github.com/sergeymeshkov/jacoco-issue
* Steps:  From project root run `mvn clean verify`

### Expected behaviour
Jacoco goal `check` is executed and checking the minimum coverage ratio based on jacoco.exec file

### Actual behaviour
Jacoco goal `check` ignores `dataFile` configuration and is NOT executed

```
[INFO] --- jacoco-maven-plugin:0.8.5:check (jacoco-check) @ test ---
[INFO] Skipping JaCoCo execution due to missing classes directory:/home/jacoco-issue/test/target/classes
```

**Comment by Godin** [comment]
`destFile` is configuration of `prepare-agent` - see https://www.jacoco.org/jacoco/trunk/doc/prepare-agent-mojo.html

`check` and `report` use `dataFile`- see https://www.jacoco.org/jacoco/trunk/doc/check-mojo.html#dataFile and https://www.jacoco.org/jacoco/trunk/doc/report-mojo.html respectively

`check` is executed for the current module like `report`
and can not be used for other modules like `report-aggregate` - #902
