### ISSUE TITLE
Code Coverage is Zero for JUnit 5

### ISSUE THREAD

**Issue by ddsharpe** [jacoco/jacoco#1048]
### Steps to reproduce

* JaCoCo version:  .8.5.201910111838
* Operating system: MacOS
* Tool integration: Maven
* Complete executable reproducer: https://github.com/ddsharpe/jacoco-junit5
* Steps: 
run "mvn clean verify"
navigate to report with a browser or editor at
jacoco-junit5/tests/target/site/jacoco-aggregate/index.html

### Expected behaviour
Code coverage should be greater than 0%

### Actual behaviour
Code coverage is reported as 0%

**Comment by ddsharpe** [comment]
NOTE: Converting this project back to JUnit 4 will change the code coverage reported to 73%

**Comment by Godin** [comment]
Execution of

```
git clone https://github.com/ddsharpe/jacoco-junit5
cd jacoco-junit5
mvn clean verify
```

produces

```
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ module1 ---
[INFO] Surefire report directory: /private/tmp/jacoco-junit5/module1/target/surefire-reports

Running com.acme.module1.Module1Test
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

...
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ module2 ---
[INFO] Surefire report directory: /private/tmp/jacoco-junit5/module2/target/surefire-reports

Running com.acme.module2.Module2Test
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

...
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ tests ---
[INFO] Surefire report directory: /private/tmp/jacoco-junit5/tests/target/surefire-reports

Running com.acme.its.ModulesTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

No tests - no coverage.

To execute JUnit 5 tests you need at least `maven-surefire-plugin` version `2.22.0` - see https://issues.apache.org/jira/browse/SUREFIRE-1330
Exactly as shown in JUnit 5 user guide at https://junit.org/junit5/docs/current/user-guide/ and in examples at https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-starter-maven

After

```
diff --git i/pom.xml w/pom.xml
index d46fdd8..958e183 100644
--- i/pom.xml
+++ w/pom.xml
@@ -41,6 +41,11 @@
   <build>
     <pluginManagement>
       <plugins>
+        <plugin>
+          <groupId>org.apache.maven.plugins</groupId>
+          <artifactId>maven-surefire-plugin</artifactId>
+          <version>2.22.2</version>
+        </plugin>
         <plugin>
           <groupId>org.apache.maven.plugins</groupId>
           <artifactId>maven-compiler-plugin</artifactId>
```

execution of

```
mvn clean verify
```

produces

<img width="919" alt="Tests" src="https://user-images.githubusercontent.com/138671/79618649-f0554e80-810a-11ea-9f0b-6bc807c628fe.png">
