### ISSUE TITLE
Jacoco: Delta Coverage

### ISSUE THREAD

**Issue by prathapar** [jacoco/jacoco#1049]
### Steps to reproduce

Developer fix a bug **or** developer created/updated (new) feature and create Pull Request. Pull request build can not generate the coverage only for piece of code, instead it is giving coverage for entire code. 

it is very difficult to figure out the coverage for the new code. manually we have to go and see enough coverage is written by developer or not. This is really difficult task for every PR and everyday.

Please help me how to get delta coverage . 

* JaCoCo version:  (from right bottom corner of JaCoCo report)
We are using Jacoco - 0.8.5  for coverage, it is working fine when we build entire repository.

* Operating system:
  RHEL.

* Tool integration: Maven / Ant / CLI / API (for others please report to respective project)
  Maven
* Complete executable reproducer: (e.g. GitHub Repo)
  GHE.
* Steps: (what exactly are you doing with the above reproducer?)

### Expected behaviour
Tt is very difficult to figure out the coverage for the new code. manually we have to go and see enough coverage is written by developer or not. This is really difficult task for every PR and everyday.

### Actual behaviour
When developer fix a bug **or** developer created/updated (new) feature and create Pull Request. Pull request build can not generate the coverage only for piece of code, instead it is giving coverage for entire code

Please help me how to get delta coverage . 

(In case of exceptions provide FULL STACKTRACE)

**Comment by Godin** [comment]
Quoting https://github.com/jacoco/jacoco/issues/935#issuecomment-527602207 :

> JaCoCo does not provide such an feature. You might consider using SonarQube which offers "coverage on new code".

or any other third-party integration ( https://www.jacoco.org/jacoco/trunk/doc/integrations.html ) that provides such feature, such as Codecov, Coveralls, etc.
