### ISSUE TITLE
Jacoco .exec empty and .html coverage 0%

### ISSUE THREAD

**Issue by PiroX4256** [jacoco/jacoco#1051]
Hi,
we are trying to export our code coverage to sonarqube using JaCoCo on a Windows 10 machine with IntelliJ IDEA IDE. We have linked maven 3 in enviromental variables.
The problem is that when we are going to produce our report with mvn clean install the .exec file appears empty, and the xml/html file reports a coverage of 0%.
We also tried mvn test, mvn verify and to force dump (it returns an error "Connection refused").

How can we solve it?

We are using the version 14 of Java, 0.85 (we tried also 0.86-SNAP) of Jacoco, 2.22.1 of surefire plugin.

Here's a copy of our pom.xml file:

https://pastebin.com/aiDU2dGL

**Comment by marchof** [comment]
Bug template ignored --> we cannot investigate.
