### ISSUE TITLE
jUnit 4.13 assertThrows() does not count towards coverage

### ISSUE THREAD

**Issue by jetersen** [jacoco/jacoco#1053]
### Steps to reproduce

* JaCoCo version: 0.8.5
* Operating system: N/A
* Tool integration: Maven
* Complete executable reproducer: https://github.com/jenkinsci/configuration-as-code-plugin/blob/28622da82672b0006621a2370e1ecd403f61629d/test-harness/src/test/java/io/jenkins/plugins/casc/YamlMaxAliasesCollection.java#L25-L35
* Steps: Run test

### Expected behaviour
Expected https://codecov.io/gh/jenkinsci/configuration-as-code-plugin/pull/1375/diff#D1-64 to be covered

### Actual behaviour
https://codecov.io/gh/jenkinsci/configuration-as-code-plugin/pull/1375/diff#D1-64 is not included in the coverage.

**Comment by Godin** [comment]
> Steps: Run test

Yes - please make sure that you actually run your tests:

`YamlMaxAliasesCollection.java` is not executed by `maven-surefire-plugin` as a test - see https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#includes

After renaming it to `YamlMaxAliasesCollectionTest.java` execution of
```
mvn -Pjacoco verify
```

generates following `target/site/jacoco-aggregate/configuration-as-code/io.jenkins.plugins.casc.yaml/YamlUtils.java.html`

<img width="1229" alt="report" src="https://user-images.githubusercontent.com/138671/82799226-fe209100-9e79-11ea-95b1-c928d6ad2090.png">

**Comment by jetersen** [comment]
Whoops my bad! Thanks for debugging for me @Godin Terrible sorry.
