### ISSUE TITLE
Jacoco doesn't seem to report code coverage for Kotlin sealed class with overriding correctly

### ISSUE THREAD

**Issue by luongvo** [jacoco/jacoco#1058]
### Steps to reproduce

* JaCoCo version:  0.8.5.201910111838
* Operating system: macOS 10.15.4
* Tool integration: Gradle
* Complete executable reproducer: code below 👇 
* Steps: (what exactly are you doing with the above reproducer?)

### Expected behaviour
Jacoco should cover the getter of parent sealed class

### Actual behaviour
Jacoco reports the getter of parent sealed class as uncovered

### Sample code

**sealed class with overriding**
```
sealed class OtpBundle(
    open val email: String
) : Parcelable {

    @Parcelize
    data class ForLogin(
        override val email: String,
        val preAuthToken: String
    ) : OtpBundle(email)

    @Parcelize
    data class ForRegister(
        override val email: String,
        val preAuthToken: String
    ) : OtpBundle(email)
}

val bundle: OtpBundle = OtpBundle.ForLogin("email", "token")
tvEmail.text = bundle.email
```
![image](https://user-images.githubusercontent.com/16315358/84344949-43f98b00-abd6-11ea-8cf0-88a2f5035e9c.png)

**sealed class without overriding**
```
sealed class OtpBundle(
     val email2: String
) : Parcelable {

    @Parcelize
    data class ForLogin(
        val email: String,
        val preAuthToken: String
    ) : OtpBundle(email)

    @Parcelize
    data class ForRegister(
        val email: String,
        val preAuthToken: String
    ) : OtpBundle(email)
}

val bundle: OtpBundle = OtpBundle.ForLogin("email", "token")
tvEmail.text = bundle.email2
```
![image](https://user-images.githubusercontent.com/16315358/84344956-48be3f00-abd6-11ea-83f7-5ae347f40948.png)

**Comment by Godin** [comment]
In your first example with `override` there is only use of getter of `email` in `ForLogin`, but no use of getter of `email` in `OtpBundle`.
