### ISSUE TITLE
jacoco report doesn't display images in Azure Devops

### ISSUE THREAD

**Issue by gt97** [jacoco/jacoco#1061]
Azure Devops can upload jacoco report.

For security reasons the images are not uploaded 
(https://developercommunity.visualstudio.com/content/problem/363333/jacoco-css-and-resources-missing-after-publishcode.html)

![image](https://user-images.githubusercontent.com/40632454/85124123-ad5a4900-b229-11ea-9082-53845c6e4d25.png)

Is it possible to fix it?
For example this is a possible solution, but I would like not to execute code out of maven.
https://www.npmjs.com/package/jacoco-html-asset-bundle

Regards

**Comment by marchof** [comment]
Please ask this question to Microsoft. JaCoCo reports are standard HTML pages which render well on a standard web server, see for example: https://www.jacoco.org/jacoco/trunk/coverage/

**Comment by dandragut** [comment]
@gt97 We found the same issue - although this issue can be fixed by Microsoft, we intend to come with a PR to produce the colors through CSS, avoiding the issue altering the images served from disk (see Cobertura reports for an example). (Y)
