### ISSUE TITLE
Indirect methods calls not being covered

### ISSUE THREAD

**Issue by mehrarohit2502** [jacoco/jacoco#1062]
I am using jacoco-maven-plugin [0.6.4.201312101107,),sonar-mavenplugin 3.3.0.603,maven-surefire-plugin 2.14.1 and facing an issue with indirect coverage i.e. Class A calls Class B (dao class),there are unit tests in class A which run Class b code but there are no unit tests in class B as such ,so indirectly the code is being covered but it does not consider Class B in coverage at all and shows 0% against it ,both the classes are in different modules.

Tried quite a few things like report-aggregate but nothing seems to work.Appreciate any help on this.

Some solutions  talkabout cross module coverage but they have tests in both the modules but in my case the class in other module does not have any tests at all.

**Comment by mehrarohit2502** [comment]
@marchof This has been declined as a question ,does it mean that this problem already has a solution and hence no work is required and should be posted on some other forum ?

**Comment by jjlharrison** [comment]
See the [README](https://github.com/jacoco/jacoco/blob/master/README.md).
