### ISSUE TITLE
JaCoCo randomly generates 0% test coverage reports

### ISSUE THREAD

**Issue by dzikoysk** [jacoco/jacoco#1066]
### Steps to reproduce

* JaCoCo version: 0.8.5 (jacoco-maven-plugin)
* Operating system: Windows & Linux
* Tool integration: Maven
* Complete executable reproducer: https://github.com/dzikoysk/reposilite
* Steps: Just execute tests and generate report

### Expected behaviour
Properly executed report

### Actual behaviour
Well, it's hard to say is it my fault or is it some kind of bug. I've spend a lot of time checking similar problems and I was not able to figure it out (stackoverflow, issues on github and your forum). The forum contains a lot of unresolved topics and it is also hard to find something useful there due to primitive search options and illegible interface. 

I've discovered this problem during the investigation of randomly dropped coverage by Codecov.com. As you can see https://codecov.io/gh/dzikoysk/reposilite/commits the coverage is 94% or 0% and it happens without modifying build process. 

* https://community.codecov.io/t/codecov-randomly-drops-coverage/1671

Codecov works fine, but my reports sometimes contains invalid data - all of these builds pass the CI. To resolve this problem I've tried a lot of different configurations and I've even rebuild project to get rid of parent module, but it looks like it is not a good direction. I've used this configuration in my other projects and I never experienced similar problem. For instance, another project with the same configuration which I've already posted in another issue (#1035):

* https://github.com/panda-lang/panda/blob/master/panda/pom.xml

**Comment by marchof** [comment]
It looks like you're using Thread.interrupt() in your code base. For some older JDK versions in this case the shutdown sequence can be broken which means exec files are not written properly (see #394).

- What is the size of the JaCoCo exec files in both situations?
- What is the exact JDK version you're using to execute your tests?

**Comment by dzikoysk** [comment]
Interesting, it also looks like it should be fixed on 8u172+

* `jacoco.exec` file is naturally empty when coverage test is not performed
* Travis uses openjdk version "1.8.0_252" (https://travis-ci.com/github/dzikoysk/reposilite/jobs/357617813#L188)

I'll try to workaround this interrupt call on console thread anyway and we will see 🤔

**Comment by dzikoysk** [comment]
Yeah, removing the `consoleThread.interrupt()` call fixed problem, I've received consistently a few positive coverage results. Thanks for your help, I wouldn't have come across this solution without your help, it looks like I'm cursed by edge cases lately.

**Comment by marchof** [comment]
Thanks for the fast feedback @dzikoysk! I'm still a bit concerned though:

1. It should be fixed in the JDK you're using
2. The problem only happened when the main thread exited in interrupted state. Is `consoleThread` the main thread in your case?

**Comment by dzikoysk** [comment]
Yeah, the issue you've linked points that the fix was backported to 8u172. I can test it on a newer version of Java to check the results if needed.

No, it is a deamon thread ([ConsoleThread.java](https://github.com/dzikoysk/reposilite/blob/master/reposilite-backend/src/main/java/org/panda_lang/reposilite/console/ConsoleThread.java)) spawned to handle cli. The `interrupt()` call is performed during the shutdown process ([Reposilite#shutdown](https://github.com/dzikoysk/reposilite/blob/5f8a6c49256e20d2a16cbf33e1724b124a070a4f/reposilite-backend/src/main/java/org/panda_lang/reposilite/Reposilite.java#L134)).

**Comment by dzikoysk** [comment]
Ok - generates `jacoco.exec`
Err - `jacoco.exec` is empty

| Version | `consoleThread.interrupt()` | Fixed |
| :---: | :---: | :---: |
| 8u151 | Err | Ok |
| 8u172 | Err | Ok |
| GraalVM 19.2.0.1 (8u222) | Err | Ok |
| 11.0.1 | Err | Ok |
| GraalVM 19.3.0 (11.0.1) | Err | Ok |
| 14.0.1 | Err | Ok |

During these tests I was just switching this flag -> [Reposilite#launch](https://github.com/dzikoysk/reposilite/blob/5f8a6c49256e20d2a16cbf33e1724b124a070a4f/reposilite-backend/src/main/java/org/panda_lang/reposilite/Reposilite.java#L109)
