### ISSUE TITLE
method is not covered if it throws exception

### ISSUE THREAD

**Issue by cnzhujie** [jacoco/jacoco#1067]
```java
    public static void testMethodException() {
        try {
            System.out.println(1);
            method1WillThrowException();//this line has been executed, but not covered in report
        } catch (Exception e) {
            System.out.println(2);
            method2WillThrowException();//this line has been executed, but not covered in report
        } finally {
            System.out.println(3);
        }
    }

    private static void method1WillThrowException() {
        System.out.println("method1WillThrowException");
        throw new RuntimeException("");
    }

    private static void method2WillThrowException() {
        System.out.println("method1WillThrowException");
        throw new RuntimeException("");
    }
```

![image](https://user-images.githubusercontent.com/4935935/86437134-6e061f00-bd36-11ea-8826-5ec570de46fa.png)

Code Example
[example.zip](https://github.com/jacoco/jacoco/files/4868012/example.zip)

**Comment by marchof** [comment]
This a know limitation of JaCoCo. See [FAQ](https://www.jacoco.org/jacoco/trunk/doc/faq.html):

> **Source code lines with exceptions show no coverage. Why?**
> 
> JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding line of source code is not marked as covered.
