### ISSUE TITLE
IRuntime implementation uses the Java logging API to report coverage data

### ISSUE THREAD

**Issue by CoderColinhan** [jacoco/jacoco#1070]
code branch: 0.8.3

according to doc
https://www.jacoco.org/jacoco/trunk/doc/api/org/jacoco/core/runtime/LoggerRuntime.html

This IRuntime implementation uses the Java logging API to report coverage data

but, in source code, I did not find  the code to  invoke  LoggerRuntime

please help

**Comment by marchof** [comment]
LoggerRuntime is currently not used.
