### ISSUE TITLE
How to force Jacoco to use a specific version in Gradle

### ISSUE THREAD

**Issue by winfoozmnayef** [jacoco/jacoco#1073]
Based on the release notes in version [0.8.3][1] the not-null assertion operator is filtered out, I'm using Jacoco version 0.8.5 like this:

```groovy
jacoco {
    toolVersion = "0.8.5"
}
```

But it's telling me that `Not covered by tests (8 conditions)`

[![Not covered by tests (8 conditions)][2]][2]

I'm using `com.dicedmelon.gradle:jacoco-android` [Github link][3]

I think `toolVersion = "0.8.5"` not working or something like that, so for that I need a way to force Jacoco version.

Is there any way to fix this issue?
  [1]: https://github.com/jacoco/jacoco/releases/tag/v0.8.3
  [2]: https://i.stack.imgur.com/WpmIq.png
  [3]: https://github.com/arturdm/jacoco-android-gradle-plugin

**Comment by marchof** [comment]
The grade plugin is not maintained by the JaCoCo project. Please check with the Gradle project.
