### ISSUE TITLE
Methods used in test appear red in report

### ISSUE THREAD

**Issue by THausherr** [jacoco/jacoco#1074]
### Steps to reproduce

* JaCoCo version:  JaCoCo 0.8.5.201910111838
* Operating system: W10
* Tool integration: Maven 3.6.3
* Complete executable reproducer: (e.g. GitHub Repo)
https://github.com/apache/pdfbox

* Steps: (what exactly are you doing with the above reproducer?)
  1- get the repo
  2- build with `mvn install  -Dorg.apache.pdfbox.examples.pdmodel.tsa=https://freetsa.org/tsr`
  3- the build makes a lot of output, and "TSA test successful" should appear twice (if not, then you didn't use the TSA option above). The test this is about, `TestCreateSignature.java`, signs a PDF and makes a timestamp, then verifies the signature and the timestamp and the certificates.
  4- when running this the second time, it is enough to build the examples subproject only (but don't forget the TSA option).

### Expected behaviour

examples/target/site/jacoco/org.apache.pdfbox.examples.signature/SigUtils.html
should have the methods `extractTimeStampTokenFromSignerInformation` and `validateTimestampToken` in mostly green. I have verified that these methods are used when the test runs.

### Actual behaviour
the methods are red

[SigUtils-jacoco.zip](https://github.com/jacoco/jacoco/files/4943722/SigUtils-jacoco.zip)

**Comment by Godin** [comment]
> I have verified that these methods are used when the test runs.

How?

Addition of

```diff
@@ -260,6 +260,11 @@ public class SigUtils
     public static TimeStampToken extractTimeStampTokenFromSignerInformation(SignerInformation signerInformation)
             throws CMSException, IOException, TSPException
     {
+        if (true) {
+            System.err.println("!!! Hello !!!");
+            throw new RuntimeException();
+        }
+
         if (signerInformation.getUnsignedAttributes() == null)
         {
             return null;
@@ -280,6 +285,11 @@ public class SigUtils
     public static void validateTimestampToken(TimeStampToken timeStampToken)
             throws TSPException, CertificateException, OperatorCreationException, IOException
     {
+        if (true) {
+            System.err.println("!!! Hello !!!");
+            throw new RuntimeException();
+        }
+
         // https://stackoverflow.com/questions/42114742/
         @SuppressWarnings("unchecked") // TimeStampToken.getSID() is untyped
         Collection<X509CertificateHolder> tstMatches =
```

results in neither printing a line nor failing tests.

----

`TestCreateSignature` calls its own `extractTimeStampTokenFromSignerInformation` and `validateTimestampToken` methods.

----

And call hierarchy in IntelliJ IDEA for methods under question does not show any test

<img width="811" alt="call hierarchy for extractTimeStampTokenFromSignerInformation" src="https://user-images.githubusercontent.com/138671/87903608-b6bf1700-ca5c-11ea-985f-4db6f2a338c3.png">

<img width="811" alt="call hierarchy for validateTimestampToken" src="https://user-images.githubusercontent.com/138671/87903428-41ebdd00-ca5c-11ea-9788-c8572379ed06.png">

**Comment by THausherr** [comment]
> testCreateSignature calls its own extractTimeStampTokenFromSignerInformation and validateTimestampToken methods.

Ooops. Aaargh. Sorry. (Yes I tested that it is called, but had "navigated to it" and didn't realize it was in the same class. I probably botched the DRY refactoring)

![grafik](https://user-images.githubusercontent.com/6665575/87905876-cab94780-ca61-11ea-998f-5c0077aa611e.png)
