### ISSUE TITLE
Jacoco reports 0% coverage after code changes that do no include jacoco config changes

### ISSUE THREAD

**Issue by abelsromero** [jacoco/jacoco#1076]
### Steps to reproduce

* JaCoCo version:  (from right bottom corner of JaCoCo report)
0.8.2.201808211720 and 0.8.5
* Operating system:
Linux, 5.6.19-2-MANJARO
* Tool integration: Maven / Ant / CLI / API (for others please report to respective project)
Maven
* Complete executable reproducer: (e.g. GitHub Repo)
**Repo + branch**: https://github.com/abelsromero/asciidoctor-maven-plugin/tree/copy/feature/synchronize-resources-in-refresh-mojo
**Brach**: copy/feature/synchronize-resources-in-refresh-mojo

* Steps: (what exactly are you doing with the above reproducer?)
1. Clone repo
2. Checkout branch
3. **ERROR case** Checkout any commit after previous one, for example the most recent.
4. **ERROR case** Run `mvn clean test jacoco:report` and check report generate under *target/site/jacoco/index.html*, should show
![image](https://user-images.githubusercontent.com/5781153/89219436-10ccea00-d5d0-11ea-9595-146fb3a0e8c8.png)

### Expected behaviour
Should show coverage data, for example, to see **OK case**
1. Checkout commit `d90e6379dea67c61463d2aef44364e764ce73979` with comment "adds missing tests to AsciidoctorRefreshMojoTest"
2. Run `mvn clean test jacoco:report` and check report generate under *target/site/jacoco/index.html*, should show
![image](https://user-images.githubusercontent.com/5781153/89219284-c3e91380-d5cf-11ea-871b-cf8aabea8fab.png)

### Actual behaviour
See description of ERROR case in reproduced *Steps*

### EXTRA information
* Only error shown is "java.lang.instrument.IllegalClassFormatException: Error while instrumenting org/jruby/ext/openssl/impl/ASN1Registry.", which has been known for a long time. I assume is not related.
* What could be related is that the tests redirect System.out & System.in to verify a batch process through messages in the console.

**Comment by marchof** [comment]
The [first commit](https://github.com/abelsromero/asciidoctor-maven-plugin/commit/9a11bc186a4215bafdcca5a850c72296010e0407) after the **OK case** seems to add several threading and wait conditions. I'm pretty sure this results in a interrupted state of the main thread which in turn causes a problem in old JDKs versions. See issue #394.

Out of curiosity: what is the exact JDK version your're using to execute the tests?

**Comment by abelsromero** [comment]
Thanks for such quick answer!

Runnig latest Java11
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/xxx/.sdkman/candidates/maven/current
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /home/xxx/.sdkman/candidates/java/11.0.7.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.6.19-2-manjaro", arch: "amd64", family: "unix"
```

Same as in the other issue I noted `jacoco.exe` has 0 bytes, copying it manually inside target dir and running without `clean` works. If the issue is due to thread, it's still odd, becuase it's a refactor of previous code that never caused issues.

**Comment by marchof** [comment]
Well, it's a raise condition. So changing you code a little might trigger it.

Anyways, the commit I linked above looks very suspicious: It's not about a specific component under test. Any other API or framework you're using can leave the main thread in interrupted state.

What scares me though is that it happens with 11.0.7.

/cc @Godin

**Comment by abelsromero** [comment]
If it helps, this serves as workarrond.
```xml
    <configuration>
        <forkCount>2</forkCount>
        <reuseForks>true</reuseForks>
    </configuration>
```

Still I will try to see if I can find anything in the code. I noted that after tests the build waits for some time, so could be something is hung.

**Comment by abelsromero** [comment]
I found that `maven-surefire-plugin` version `3.0.0-M4` (and above) also fixes the problem. I will still try to see how I am messing the main thread.
Thanks a lot!

At this point I don't think it makes sense to tag this as a jacoco issue?

**Comment by abelsromero** [comment]
Found the offending code and fixed it, it was a side effect of the code changes.  Without your help I wouldn't have been able to find it.

**Comment by marchof** [comment]
Can you please share what the problem was?

**Comment by abelsromero** [comment]
I found the other component was doing some extra looping, causing it to wait for input.

Adding this test to the project reproduces the issue in my fixed branch.

This will 
```java
    @Test
    public void should_generate_0_coverage_jacoco() {
        Thread thread = new Thread(() -> {
            Scanner scanner = new Scanner(System.in);
            String s = scanner.nextLine();
            System.out.println("waiting for: " + s);
        });
        thread.start();
    }
```
