### ISSUE TITLE
Jacoco HTML report displays wrong "created with" version

### ISSUE THREAD

**Issue by philbrown-mdt** [jacoco/jacoco#1077]
### Steps to reproduce

* JaCoCo version:  ~(from right bottom corner of JaCoCo report)~
  * Lower Right Version of report shows 0.8.4.201905082037
  * Version used within Gradle config is 0.7.6.201602180812
* Operating system: Windows 10
* Tool integration: Gradle 5.6.2
* Complete executable reproducer: N/A
* Steps:
  1. Configure Gradle such that jacoco plugin toolVersion is set to 0.7.6.201602180812. This will look something like:
        ````groovy
        apply plugin: 'jacoco'
        jacoco {
            toolVersion = '0.7.6.201602180812'
        }
        ````
  2. Run unit tests with coverage

### Expected behavior

Generated report should show "Created with JaCoCo 0.7.6.201602180812" in the lower right corner

### Actual behavior

Generated report shows "Created with JaCoCo 0.8.4.201905082037" in the lower right corner

-----

I also reported this on the [Gradle issues tracker](https://github.com/gradle/gradle/issues/14033), since it may be an issue with the JaCoCo plugin.

**Comment by marchof** [comment]
Obviously the wrong version was used for report generation. Please follow this up with the Gradle project. We do not maintain the Gradle integration here.

**Comment by Godin** [comment]
Furthermore, steps to reproduce are definitely incomplete because

with following `build.gradle`
```
apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.12'
}

apply plugin: 'jacoco'
jacoco {
    toolVersion = '0.7.6.201602180812'
}
```

`src/main/java/Example.java`
```
class Example {}
```

`src/test/java/ExampleTest.java`
```
public class ExampleTest {
  @org.junit.Test
  public void test() {
  }
}
```

using
```
------------------------------------------------------------
Gradle 5.6.2
------------------------------------------------------------

Build time:   2019-09-05 16:13:54 UTC
Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_242 (AdoptOpenJDK 25.242-b08)
OS:           Mac OS X 10.15.5 x86_64
```

execution of
```
gradle test jacocoTestReport`
```

produces `build/reports/jacoco/test/html/index.html`

with expected
```
Created with JaCoCo 0.7.6.201602180812
```

<img width="902" alt="Screenshot 2020-08-06 at 10 16 35" src="https://user-images.githubusercontent.com/138671/89502737-c0b77880-d7c5-11ea-96aa-1d4ab17a8749.png">

**Comment by philbrown-mdt** [comment]
Thanks @Godin for pointing that out. I am also creating a Gradle task of type JacocoTestReport to configure my file filter, exec files, etc- could that be modifying the expected version?

**Comment by Godin** [comment]
Unlikely that in absence of **complete** reproducer somebody would like to spend his time on blind guesses of what you have and how configured, at least definitely not me. Sorry.
