### ISSUE TITLE
Exclude while generating jacoco Report doesnt change coverage numbers but in report those classes are removed.

### ISSUE THREAD

**Issue by SaurabhAhuja-Dev** [jacoco/jacoco#1081]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling bug report!

### Steps to reproduce

* JaCoCo version:  0.8.5 (https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin/0.8.5)
* Operating system:
* Tool integration: - Gradle (https\://services.gradle.org/distributions/gradle-4.10.2-all.zip)
* Complete executable reproducer: (e.g. GitHub Repo) https://stackoverflow.com/questions/29887805/filter-jacoco-coverage-reports-with-gradle , cannot share internal company source code.
* Steps: (what exactly are you doing with the above reproducer?)
./gradlew jacocoTestReport

### Expected behaviour
When exclude is provided in "classDirectories" then its shud change numbers for files excluded in report.

### Actual behaviour
Coverage numbers are coming same though in jacoco report classes are no more shown.
(In case of exceptions provide FULL STACKTRACE)

**Comment by Godin** [comment]
Given following **complete example** that you can try by yourself

`src/main/java/A.java`
```
class A {
    void a() {
    }
}
```

`src/main/java/B.java`
```
class B {
    void b() {
    }
}
```

`src/test/java/ExampleTest.java`
```
public class ExampleTest {
    @org.junit.Test
    public void test() {
        new A().a();
        new B().b();
    }
}
```

and `build.gradle`
```
apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.12'
}

apply plugin: 'jacoco'
jacoco {
    toolVersion = '0.8.5'
}
```

using
```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_242 (AdoptOpenJDK 25.242-b08)
OS:           Mac OS X 10.15.5 x86_64
```

execution of
```
gradle clean test jacocoTestReport
```

produces following report

<img width="1035" alt="Screenshot 2020-08-13 at 14 02 52" src="https://user-images.githubusercontent.com/138671/90127558-ad785000-dd65-11ea-89b5-5e37d1c3e676.png">

after addition of the following to `build.gradle`
```diff --git i/build.gradle w/build.gradle
+
+jacocoTestReport {
+    afterEvaluate {
+        classDirectories = files(classDirectories.files.collect {
+                fileTree(dir: it, exclude: 'B.class')
+            })
+    }
+}
```

execution of the same command produces following report

<img width="1035" alt="Screenshot 2020-08-13 at 14 03 27" src="https://user-images.githubusercontent.com/138671/90127538-a3565180-dd65-11ea-842a-21a4dff321fc.png">

So as you can see above, exclusion of classes from the analysis does actually change numbers as expected.
