### ISSUE TITLE
Why some lines which should be covered shows blank in html report

### ISSUE THREAD

**Issue by sandy320** [jacoco/jacoco#1082]
Scenario
JaCoCo version: 0.8.5
![jacoco](https://user-images.githubusercontent.com/53594306/90106154-9a6f7b00-dd79-11ea-8813-d5f5d74227f7.png)

There are some blank lines between the greens.
As the code logic, the blank lines should be covered, why does not show green?

https://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Thank you!

**Comment by Godin** [comment]
Unlikely that somebody will be able to make a correct guess blindly in the absence of **complete reproducer**, or even have a will to waste his time on such guesses. Wild guess that comes to my mind quickly - is that analyzed class file doesn't correspond to source file, e.g. source file was modified after it was compiled into class file.
