### ISSUE TITLE
JaCoCoReport Code Coverage Report: Some lines still show yellow background although they are covered.

### ISSUE THREAD

**Issue by U-F-O** [jacoco/jacoco#1084]
### Steps to reproduce

* JaCoCo version: Created with JaCoCo 0.8.4.201905082037
* Operating system: Windows and Linux
* Tool integration: Gradlew
* Complete executable reproducer: 
* Steps: 

I add two methods, like the following. After running "gradlew test", there's still yellow background. Usually for other methods, I can throw an exception to avoid this case, but for the method like set and get. no exception can be thrown.  

![image](https://user-images.githubusercontent.com/12891499/90265102-abf17980-de84-11ea-95c4-883d4ef822ec.png)

### Expected behaviour

No yellow background displayed.

### Actual behaviour

yellow background displayed

**Comment by marchof** [comment]
Please provide complete executable reproducer. Thx.

**Comment by U-F-O** [comment]
@marchof  I've found the problem. thanks for your attention. I close it.

**Comment by Godin** [comment]
@U-F-O to help future readers could you please describe what was the problem?
