### ISSUE TITLE
New Kotlin IR Compiler Backend breaks generated code filter

### ISSUE THREAD

**Issue by Grisu118** [jacoco/jacoco#1086]
Jacoco 0.8.2 introduced filtering of generated methods in kotlin (https://github.com/jacoco/jacoco/pull/689).

When I use the kotlin 1.4.0 with the new IR Compiler Backend, the filters do not work. You find below the example from above pull request updated to kotlin 1.4.0. With a comment where you can enable / disable the new compiler backend. 

### Steps to reproduce

* JaCoCo version: 0.8.5
* Operating system: Windows 10
* Tool integration: Gradle 6.6
* Complete executable reproducer: [example.zip](https://github.com/jacoco/jacoco/files/5112767/example.zip)

* Steps: `gradlew clean jacocoTestReport`

### Expected behaviour
Generated methods are excluded, like with `useIR = false`
![jacoco_kotlin](https://user-images.githubusercontent.com/4274139/90962828-466c4100-e4b3-11ea-88e4-827d440b524d.png)

### Actual behaviour
Generated methods are not excluded, with `useIR = true`
![jacoco_kotlin_ir](https://user-images.githubusercontent.com/4274139/90962844-600d8880-e4b3-11ea-912d-d23745d90724.png)

**Comment by Godin** [comment]
@Grisu118 if there is a change in the bytecode generated by Kotlin compiler, then why don't you report this to developers of compiler ? :wink: CC @qwwdfsad @alefas @antonarhipov

----

For example for `DataClass.kt`
```
data class DataClass(var x: Int)
```

after execution of `kotlin-compiler-1.4.0/bin/kotlinc -Xuse-ir DataClass.kt`
execution of `javap -v -p DataClass.class`
shows that generated methods have `LineNumberTable`

```
  public int hashCode();
    descriptor: ()I
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: getfield      #13                 // Field x:I
         4: ireturn
      LineNumberTable:
        line 1: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   LDataClass;
```

which was not the case before and is not the case in the absence of `-Xuse-ir`,
what breaks https://github.com/jacoco/jacoco/pull/689 implemented by one of compiler developers @goodwinnk at that time

----

Using our validation tests one can observe other changes in how the Kotlin compiler generates bytecode:

```diff
--- c/org.jacoco.core.test.validation.kotlin/pom.xml
+++ w/org.jacoco.core.test.validation.kotlin/pom.xml
@@ -26,7 +26,7 @@

   <properties>
     <bytecode.version>6</bytecode.version>
-    <kotlin.version>1.3.61</kotlin.version>
+    <kotlin.version>1.4.0</kotlin.version>
   </properties>

   <dependencies>
@@ -43,7 +43,7 @@
     <dependency>
       <groupId>org.jetbrains.kotlinx</groupId>
       <artifactId>kotlinx-coroutines-core</artifactId>
-      <version>1.0.1</version>
+      <version>1.3.9</version>
     </dependency>
   </dependencies>

@@ -60,6 +60,11 @@
             <goals>
               <goal>compile</goal>
             </goals>
+            <configuration>
+              <args>
+                <arg>-Xuse-ir</arg>
+              </args>
+            </configuration>
           </execution>
         </executions>
       </plugin>
```

**Comment by qwwdfsad** [comment]
I'll investigate it on our side

**Comment by qwwdfsad** [comment]
We'll consider it a bug for now: https://youtrack.jetbrains.com/issue/KT-41903

Also, we (again) discussed a potential solution for coverage and bytecode processing tools and decided to experiment with `@kotlin.Generated` (https://youtrack.jetbrains.com/issue/KT-41906) to have a consistent marker for most of the autogenerated members

**Comment by Godin** [comment]
@qwwdfsad first of all thanks a lot! :heart:

> We'll consider it a bug for now: https://youtrack.jetbrains.com/issue/KT-41903

As of today title is "JVM IR: do not generate LineNumberTable in auto-generated members of data classes",
however quoting https://github.com/jacoco/jacoco/issues/1086#issuecomment-686358824

> Using our validation tests one can observe other changes in how the Kotlin compiler generates bytecode

😉  for another example for the following `DelegatedList.kt` that is not about data classes

```
class DelegatedList : List<Int> by ArrayList()
```

execution of

```
kotlin-compiler-1.4.10/bin/kotlinc DelegatedList.kt \
    && javap -v -p DelegatedList.class
```

shows

```
  public int getSize();
    descriptor: ()I
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: getfield      #20                 // Field $$delegate_0:Ljava/util/ArrayList;
         4: invokevirtual #30                 // Method java/util/ArrayList.size:()I
         7: ireturn
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       8     0  this   LDelegatedList;
```

but execution with `-Xuse-ir`

```
kotlin-compiler-1.4.10/bin/kotlinc -Xuse-ir DelegatedList.kt \
    && javap -v -p DelegatedList.class
```

shows that `LineNumberTable` appears

```
  public int getSize();
    descriptor: ()I
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: getfield      #20                 // Field $$delegate_0:Ljava/util/ArrayList;
         4: invokevirtual #99                 // Method java/util/ArrayList.size:()I
         7: ireturn
      LineNumberTable:
        line 1: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       8     0  this   LDelegatedList;
```

**Comment by qwwdfsad** [comment]
Thanks, it is also being fixed :) https://youtrack.jetbrains.com/issue/KT-41960

**Comment by Godin** [comment]
After https://github.com/jacoco/jacoco/pull/1162, https://github.com/jacoco/jacoco/pull/1164, https://github.com/jacoco/jacoco/pull/1166, https://github.com/jacoco/jacoco/pull/1172, https://github.com/jacoco/jacoco/pull/1174, https://github.com/jacoco/jacoco/pull/1178 and https://github.com/jacoco/jacoco/pull/1181
our validation tests pass
with Kotlin compiler version `1.5.0` that uses new IR backend
as well as with Kotlin compiler version `1.4.32` with option `-Xuse-ir`
So I'm closing this ticket.
