### ISSUE TITLE
Non-existent (invisible?) static analysis block shows 75% code coverage

### ISSUE THREAD

**Issue by Fernal73** [jacoco/jacoco#1087]
From StackOverflow [Question](https://stackoverflow.com/questions/63560283/jacoco-code-coverage-non-existent-static-block-shows-only-75-coverage)

### Steps to reproduce

* JaCoCo version:  0.85
* Operating system: Linux
* Tool integration: Maven 
* Complete executable reproducer: https://github.com/Fernal73/DSAlgos 
* Steps: Run Jacoco on project and check report for BrickSortParallel class.

### Expected behaviour
No static block or incomplete coverage for class expected.
### Actual behaviour
50% code coverage displayed for static block (not visible).

**Comment by marchof** [comment]
Your code uses the `assert` keyword which results in a static initializer:

    static {};
      descriptor: ()V
      flags: (0x0008) ACC_STATIC
      Code:
        stack=1, locals=0, args_size=0
           0: ldc           #72                 // class ds/BrickSortParallel
           2: invokevirtual #73                 // Method java/lang/Class.desiredAssertionStatus:()Z
           5: ifne          12
           8: iconst_1
           9: goto          13
          12: iconst_0
          13: putstatic     #31                 // Field $assertionsDisabled:Z
          16: return
        LineNumberTable:
          line 19: 0
        StackMapTable: number_of_entries = 2
          frame_type = 12 /* same */
          frame_type = 64 /* same_locals_1_stack_item */
            stack = [ int ]

This is a know limitation. The workaround is to not use `assert`.

**Comment by marchof** [comment]
Duplicate #613.

**Comment by Fernal73** [comment]
I've flagged the method that uses assert with a @Generated annotation. Doesn't that filter that out?

**Comment by Fernal73** [comment]
Another question wrt to the Google Group:
https://groups.google.com/g/jacoco/c/k7yvGHGExvg

I can't seem to create a new thread online. Is the only way to do it is email the group, instead?

**Comment by marchof** [comment]
@Fernal73 The method as such will be excluded due to the `@Generated` annotation. But the Java compiler creates additional infrastructure for assertions in the static initializer.

**Comment by marchof** [comment]
@Fernal73 Does the "New conversation" button nut work for you?

<img width="658" alt="image" src="https://user-images.githubusercontent.com/1936262/91185950-b3b7e600-e6ee-11ea-9de9-8804ab4dd6f7.png">

**Comment by Fernal73** [comment]
No.
![Screenshot_2020-08-25-20-35-36-771_com android chrome](https://user-images.githubusercontent.com/24714685/91191776-d22fd880-e712-11ea-8fc3-a82df94b1cab.jpg)
![Screenshot_2020-08-25-20-35-23-546_com android chrome](https://user-images.githubusercontent.com/24714685/91191803-dc51d700-e712-11ea-985d-3040d72964ea.jpg)

**Comment by Fernal73** [comment]
> @Fernal73 The method as such will be excluded due to the `@Generated` annotation. But the Java compiler creates additional infrastructure for assertions in the static initializer.

Thanks for clearing that up. I wasn't aware that it's a static initialiser. Evidently, I'm not familiar with java byte code. I had removed the assert statement earlier but then felt it's a good idea to push it into a `@Generated` method. I guess I didn't notice that the code coverage earlier was incomplete because of the static block it generates. It's a shame , really, since assertions can be useful without having to use an external API.

**Comment by marchof** [comment]
@Fernal73 Not true, JDK nowadays provides APIs for this, for example `java.util.Objects.nonNull()`

**Comment by Fernal73** [comment]
> @Fernal73 Does the "New conversation" button nut work for you?
> 
> <img alt="image" width="658" src="https://user-images.githubusercontent.com/1936262/91185950-b3b7e600-e6ee-11ea-9de9-8804ab4dd6f7.png">

Why nut? Is the email group only for the crazies over there?

**Comment by Fernal73** [comment]
> @Fernal73 Not true, JDK nowadays provides APIs for this, for example `java.util.Objects.nonNull()`

I discovered this [excellent explanation on StackOverflow](https://stackoverflow.com/a/40919125/3924108).
