### ISSUE TITLE
Support filters by cyclomatic complexity or annotation

### ISSUE THREAD

**Issue by DanielYWoo** [jacoco/jacoco#1088]
### Scenario

* JaCoCo version: all versions
* Operating system: not OS specific
* Tool integration: Gradle
* Description of your use case: 

### Current Behaviour
Currently we set the quality gate for Unit Test Coverage like 80%. But there are some very simple methods not necessarily need to be tested (e,g. setter/getter/method will just a few lines). To focus on the complicated classes/methods, we hope JaCoco can provide either a global filter to filter out those simple methods based on the cyclomatic complexity score, or with annotation.

### Wanted Behaviour
cyclomatic complexity filter
Here is how we use Gradle https://docs.gradle.org/6.1/userguide/jacoco_plugin.html#sec:jacoco_report_violation_rules
We hope JaCoCo can provide new interface so Gradle can filter out simple methods like this:
```
jacocoTestCoverageVerification {
    violationRules {
        rule {
            filters {
               cyclomaticComplextiyBelow = 4
            }            

            limit {
                counter = 'LINE'
                value = 'TOTALCOUNT'
                maximum = 0.3
            }
        }
    }
}
```

Another option is to have an annotation so developer can define fine-grained filter for class/method in their code.
```
@JaCoCoIgnore
public class MyClass { ... }

public class AnotherClass {
    @JaCoCoIgnore public void mySimpleMethod() { ... }
}
``` 
Lombok has a @Generated annotation and JaCoco will ignore those classes. We can add that annotation manually to class/method. Since JaCoCo already supports filtering by Lombok annotations, maybe JaCoCo can have its own annotation for this. 

### Possible Workarounds
Use Lombok @Generated annotation to mark un-wanted classes/methods.

**Comment by marchof** [comment]
To be honest I don't think we will add more complexity to the JaCoCo rules. Please consider a tool like SonarQube to configure advanced code quality rules.

**Comment by DanielYWoo** [comment]
Yes, since JaCoCo already provides all the coverage data, it makes sense for SonarQube to consume those data and build more versatile rules. I raised this issue because I tried to do that in SonarQube before, and it's a little complicated to write a rule class. Anyway, if you don't have a plan, maybe that will be our only choice. Thanks for your confirmation anyway.

**Comment by marchof** [comment]
Well I simply don't think we're going in the right direct if we add more reporting capabilities in JaCoCo. There are better tools for this which can combine different metrics beside code coverage and also can show figures over time. Thanks für your understanding!
