### ISSUE TITLE
javaagent excludes isn't working

### ISSUE THREAD

**Issue by PadrePadrone** [jacoco/jacoco#1093]
My goal is to exclude some classes from the coverage results/reports

* JaCoCo version:  0.8.5
* Operating system: Linux
* Tool integration: agent/CLI
* Complete executable reproducer: ?
* Steps: (what exactly are you doing with the above reproducer?)

I'm running a java program with javaagent as an argument to the jvm, and 'excludes' as a javaagent parameter:

-javaagent:tools/org/jacoco/download-0.8.5/lib/jacocoagent.jar=excludes=com.a.model.*,destfile=/tmp/coco/out.coco

Then I'm generating a report using jacoco CLI:

java -jar tools/org/jacoco/download-0.8.5/lib/jacococli.jar report /tmp/coco/*.coco  --classfiles ./target/classes  --html /tmp/coco/report --sourcefiles ./src/main/java

### Expected behaviour
Generated report will not include coverage of classes under com.a.model

### Actual behaviour
Generated report includes coverage of all classes under com.a.model

I also tried to use an explicit class name (i.e. com.a.model.ActiveElement) as 'excludes' value, report included this class
Also tried to use * as 'excludes' value, expecting it to exclude all classes. Generated report was full.

**Comment by Godin** [comment]
Quoting https://www.jacoco.org/jacoco/trunk/doc/faq.html

> ### Why do I see classes in the coverage report although I excluded them in the JaCoCo agent configuration?
>
> The includes and excludes options of the JaCoCo agent determine for which classes execution data is collected. Except for technical corner cases these options are normally not required. If you exclude classes, no execution data is collected for them.
>
> Report creation is a separate step where all class files which should show up in the report are explicitly provided. Coverage is determined from the provided execution data. If execution data is missing for a particular class, this class is shown as not covered because the report generator cannot distinguish whether the class was excluded from instrumentation or not executed.
>
> If you want to exclude classes from the report please configure the respective report generation tool accordingly.

----

In case of command line interface supply `--classfiles` with a directory with classes that you want to see in report, i.e. without classes that you want to exclude.

**Comment by PadrePadrone** [comment]
Sorry, I could be missing something in my understanding of the jacoco flow.
From the text above: 
"If you exclude classes, no execution data is collected for them"
If excluded classes do not exist in the execution data, how do they appear in the reports generated from these execution files? 

As for your suggestion for the CLI reporting: 
1. If I have the following classes hierarchy: a/classes and a/b/classes and I want to exclude a/b/classes, how do I do that?
2. This could also mean passing many (tens) directories to the --classfiles.

**Comment by Godin** [comment]
> "If you exclude classes, no execution data is collected for them"
> If excluded classes do not exist in the execution data, how do they appear in the reports generated from these execution files?

Read the second paragraph:

> Report creation is a separate step where all class files which should show up in the report are explicitly provided. Coverage is determined from the provided execution data. If execution data is missing for a particular class, this class is shown as not covered because the report generator cannot distinguish whether the class was excluded from instrumentation or not executed.

Report generation uses and shows provided classes, not the classes in execution data.

----

> As for your suggestion for the CLI reporting:
> If I have the following classes hierarchy: a/classes and a/b/classes and I want to exclude a/b/classes, how do I do that?

Either remove `a/b/classes` and use `--classfiles a`,
or use `--classfiles a/classes`.

> This could also mean passing many (tens) directories to the --classfiles.

Yes, or prepare a directory with required classes and pass only one option `--classfiles` with this directory, e.g. by copy and/or removal as shown above.

There is no dedicated option for exclusions in the case of command line interface. Even if there will be such option, then you'll anyway need to specify "tens" of exclusions 😉

**Comment by PadrePadrone** [comment]
Got it, I removed the excluded class files and it is working. thanks!

IMHO, an elegant solution would be to mark the excluded classes as 'excluded', in the execution files.
This will provide the reporting tools, the information they need.

**Comment by marchof** [comment]
> IMHO, an elegant solution would be to mark the excluded classes as 'excluded', in the execution files.
> This will provide the reporting tools, the information they need.

This does not work: The JaCoCo agent only sees the classes which are actually loaded by the application. Even if add a new entry to the exec file to mark these classes as "excluded", classes which are not executed at all (=> never seen by the agent) will not get such a record in the exec file.

Really, the scope of the report is defined when you create the report, not when you configure the agent!

**Comment by bladeandmaster88** [comment]
javaagent:/jvm-sandbox/jacocoagent.jar=excludes=cn/xxx/bme/pay/channel/blueocean/sao/request/**:cn/xxx/bme/pay/channel/blueocean/sao/model/Credentials:cn.xxx.bme.pay.channel.payme.sao.model.Credentials,address=0.0.0.0,port=17088,output=tcpserver,append=true    多个类之间用:隔开
