### ISSUE TITLE
Filter out hibernate-generated methods

### ISSUE THREAD

**Issue by fenuks** [jacoco/jacoco#1095]
### Scenario
* JaCoCo version: 0.8,6
* Operating system: Linux
* Tool integration: Maven
* Description of your use case:
[Hibernate Bytecode Enhancements](https://docs.jboss.org/hibernate/orm/5.0/topical/html/bytecode/BytecodeEnhancement.html) generates various methods, all starting with common prefix `$$_hibernate_`. Jacoco should ignore these. Sadly, maven hibernate plugin has no option to mark these methods are generated. I've tried to filter them out with [configuration options](https://github.com/jacoco/jacoco/wiki/FilteringOptions#filters-based-on-excludes-configuration), but without success.

### Current Behaviour
`$$_hibernate_*` methods are included in coverage reports.

### Wanted Behaviour
`$$_hibernate_*` methods should not be included in coverage reports.

### Possible Workarounds
Adding filter to jacoco plugin exclude configuration, but I was unable to do so. I've tried `*#$$_hibernate`, `*#$$_hibernate*`, `*#$$_hibernate*(*)`. None seems to be working.

**Comment by marchof** [comment]
Please open a bug at hibernate to mark those methods as `synthetic`. The JaCoCo will filter them out.

JaCoCo is a general purpose coverage tool and cannot provide specific filters for all the libraries that exist

**Comment by fenuks** [comment]
There is open issue at hibernate bugtracker: https://hibernate.atlassian.net/browse/HHH-13824.

Until it get fixed on hibernate side, which may take long time, could you tell me if it is possible to filter out these methods with JaCoCo `<exclude>` filter?

**Comment by marchof** [comment]
Thanks for the link! ❤️ 

Unfortunately exclude filter only work on class file level. There is no option to specify filters on method level.

**Comment by fenuks** [comment]
Thank you for the reply. I will wait then, or perhaps see myself if making such change in hibernate is difficult. I suppose it should be fairly easy.
