### ISSUE TITLE
Kotlin interface methods with default arguments not filtered.

### ISSUE THREAD

**Issue by pusolito** [jacoco/jacoco#1096]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling bug report!

### Steps to reproduce

* JaCoCo version:  0.8.6
* Operating system: Mac OS 10.15.4
* Tool integration: Gradle
* Complete executable reproducer: https://github.com/nacular/doodle/blob/master/Core/src/commonMain/kotlin/io/nacular/doodle/drawing/Renderer.kt

```kotlin
interface Renderer {
    // ...

    fun line(start: Point, end: Point, stroke: Stroke)
    fun path(points: List<Point>, fill: Fill, fillRule: FillRule? = null)

    // ...
}
```

### Expected behaviour

All methods in the interface that do not have implementations should be filtered/ignored. This should be the case for the `path` method for example.

### Actual behaviour

Any method with a default parameter is marked as having a missed instruction.

Element | Missed Instructions | Cov. | Missed Branches | Cov. | Missed | Cxty | Missed | Lines | Missed | Methods
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
arc$default(Renderer, Point, double, Measure, Measure, Stroke, Fill, int, Object) |   | 0% |   | n/a | 1 | 1 | 1 | 1 | 1 | 1
wedge$default(Renderer, Point, double, Measure, Measure, Stroke, Fill, int, Object) |   | 0% |   | n/a | 1 | 1 | 1 | 1 | 1 | 1
path$default(Renderer, List, Stroke, Fill, Renderer.FillRule, int, Object) |   | 0% |   | n/a | 1 | 1 | 1 | 1 | 1 | 1
path$default(Renderer, Path, Stroke, Fill, Renderer.FillRule, int, Object) |   | 0% |   | n/a | 1 | 1 | 1 | 1 | 1 | 1
path$default(Renderer, List, Fill, Renderer.FillRule, int, Object) |   | 0% |   | n/a | 1 | 1 | 1 | 1 | 1 | 1
path$default(Renderer, Path, Fill, Renderer.FillRule, int, Object) |   | 0% |   | n/a | 1 | 1 | 1 | 1 | 1 | 1
poly$default(Renderer, Polygon, Stroke, Fill, int, Object) |   | 0% |   | n/a | 1 | 1 | 1 | 1 | 1 | 1
Total | 92 of 92 | 0% | 0 of 0 | n/a | 7 | 7 | 7 | 7 | 7 | 7

**Comment by Godin** [comment]
> All methods in the interface that do not have implementations should be filtered/ignored.

In Kotlin arbitrary expressions can be used as default argument values (see https://github.com/jacoco/jacoco/issues/773) even in interfaces and they add executable code to interfaces, see for example

```
interface Example {
    fun example(a: String, b: String =
            if (a.length > 0)
                "foo"
            else
                "bar");
}
```
