### ISSUE TITLE
Jacoco executes all android project variant test tasks

### ISSUE THREAD

**Issue by volsahin** [jacoco/jacoco#1101]
* JaCoCo version:  0.8.5
* Gradle Version: 4.0.1 for android (Gradle 6.1.1)
* Operating system: MacOS
* Tool integration: Android, Gradle
* Complete executable reproducer: See code snippet below
* Steps: See problem section

### Expected behaviour
JacocoReport task to execute specified dependent variant only.

### Actual behaviour
JacocoReport task executes all variants

### Problem
There are build variants like dev,prep,prod in our project.
I have a distinct jacoco.gradle file which i apply to my module level gradle file.

`apply from '../scripts/jacoco.gradle'`

In jacoco.gradle file i have a task like this

```
project.afterEvaluate {
    tasks.create(name: "testReport", type: JacocoReport, dependsOn: testDevDebugUnitTest) {
        reports {
            xml.enabled = true
            html.enabled = true
        }

        def classDirectories = fileTree(dir: "$project.buildDir/tmp/kotlin-classes/devDebug", excludes: someExcludedFiles)
        def sourceDirectories = "$project.projectDir/src/main/java"
        def executionData = fileTree(dir: $projectDir.buildDir, includes: ['jacoco/testDevDebugUnitTest.exec', 'outputs/code-coverage/connected/*coverage.ec'])

        getClassDirectories().setFrom(files([classDirectories]))
        getSourceDirectories().setFrom(files([sourceDirectories]))
        getExecutionData().setFrom(files([executionData]))
    }
}
```
After i execute testReport task, gradle executes all flavors like testDevDebugUnitTest, testDevReleaseUnitTest, testProdDebugUnitTest, testProdReleaseUnitTest and it results with a plus one hour task execution. If i delete dependsOn part and execute again, then it executes all variant tasks again, no change. It used to work well but maybe after updating gradle plugin or jacoco, this task became a problematic one. What is the reason behind it, any ideas?

**Comment by marchof** [comment]
As you can see [here](https://www.jacoco.org/jacoco/trunk/doc/integrations.html
) Grade is a 3rd party integration and not maintained by us. Please submit this to the Gradle project.
