### ISSUE TITLE
Jacoc coverage check failed due to exclusions appears as 0% coverage

### ISSUE THREAD

**Issue by sudheerah** [jacoco/jacoco#1108]
I have use below configuration in jacoco plugin

```
<plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <dataFile>${user.dir}/target/jacoco.exec</dataFile>
                    <excludes>
                        <exclude>**/*myclass</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <id>agent-for-ut</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <configuration>
                            <append>true</append>
                            <destFile>${user.dir}/target/jacoco.exec</destFile>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jacoco-site</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${user.dir}/target/coverage-reports/jacoco</outputDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jacoco-check</id>
                        <phase>test</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <rule>
                                    <limits>
                                        <limit>
                                            <counter>LINE</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>80%</minimum>
                                        </limit>
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
But issue is when add exclusion, coverage percentage reduced further (become worse) as excluded packages become 0%.

Is there a solution for this?

**Comment by Godin** [comment]
`excludes` for `report` and `check` must refer to class files, so seems that you're missing `.class` file extension

```
<exclude>**/*myclass.class</exclude>
```

**Comment by sudheerah** [comment]
@Godin Sorry if my question is not clear.
As per docs (https://www.eclemma.org/jacoco/trunk/doc/check-mojo.html) the default element type is BUNDLE. So exclusions work fine. As you mentioned class also can be excluded.

The question I have is when I check` jacoco.exec` file via IntelliJ after run above pom.xml, those exclusions packages become 0%. Because of that the check percentage drop further. I was under impressions after exclusions the whole packge/class completely remove from the `jacoco.exec` file.

**Comment by Godin** [comment]
You seem to also configure `exclusions` for `prepare-agent`. This means that agent won't instrument class and hence indeed won't record anything about it into `jacoco.exec`.

**Comment by sudheerah** [comment]
Yes that's correct. so my expectation is, completely remove class from `jacoco.exec` rather than showing 0% which impact the total check as I mentioned. 

Is there a way to do that?

**Comment by Godin** [comment]
> completely remove class from `jacoco.exec`

Please read 
"Why do I see classes in the coverage report although I excluded them in the JaCoCo agent configuration?"
in
https://www.jacoco.org/jacoco/trunk/doc/faq.html

> rather than showing 0%

I already told you in https://github.com/jacoco/jacoco/issues/1108#issuecomment-711130048 that to exclude a class from `report` and `check` you should correctly configure `excludes` for these goals:

```
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <excludes>
                                <exclude>**/*Example.class</exclude>
                            </excludes>
                            <rules>
                                <rule>
                                    <limits>
                                        <limit>
                                            <counter>LINE</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>80%</minimum>
                                        </limit>
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
```

`excludes` for `prepare-agent` and `check` are different - first one accepts names of classes `org/example/Example`, whereas second one is about names of files `org/example/Example.class`.

**Comment by sudheerah** [comment]
ok. T tried below, but still I can see 0% against myclass

<plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <dataFile>${user.dir}/target/jacoco.exec</dataFile>
                    <excludes>
                        <exclude>**/*myclass</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <id>agent-for-ut</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <configuration>
                            <append>true</append>
                            <destFile>${user.dir}/target/jacoco.exec</destFile>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jacoco-site</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <configuration>
                             <excludes>
                                  <exclude>**/*myclass.class</exclude>
                            </excludes>
                            <outputDirectory>${user.dir}/target/coverage-reports/jacoco</outputDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jacoco-check</id>
                        <phase>test</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                             <excludes>
                                  <exclude>**/*myclass.class</exclude>
                            </excludes>
                            <rules>
                                <rule>
                                    <limits>
                                        <limit>
                                            <counter>LINE</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>80%</minimum>
                                        </limit>
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by Godin** [comment]
Given

`src/main/java/example/A.java`

```
package example;

class A {
}
```

`src/main/java/example/B.java`

```
package example;

class B {
}
```

`src/test/java/example/ExampleTest.java`

```
package example;

import org.junit.Test;

public class ExampleTest {
  @Test
  public void test() {
    new A();
  }
}
```

and `pom.xml`

```
<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>example</artifactId>
  <version>0.1-SNAPSHOT</version>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.6</version>
        <executions>
          <execution>
            <id>prepare-agent</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report-and-check</id>
            <goals>
              <goal>report</goal>
              <goal>check</goal>
            </goals>
            <configuration>
              <excludes>
                <exclude>example/B.class</exclude>
              </excludes>
              <rules>
                <rule>
                  <limits>
                    <limit>
                      <counter>LINE</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>100%</minimum>
                    </limit>
                  </limits>
                </rule>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

execution of

```
mvn verify
```

succeeds

```
[INFO] --- jacoco-maven-plugin:0.8.6:report (report-and-check) @ example ---
[INFO] Loading execution data file /private/tmp/j/target/jacoco.exec
[INFO] Analyzed bundle 'example' with 1 classes
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.6:check (report-and-check) @ example ---
[INFO] Loading execution data file /private/tmp/j/target/jacoco.exec
[INFO] Analyzed bundle 'example' with 1 classes
[INFO] All coverage checks have been met.
```

even if `example/B.java` has zero coverage
and produces following report

<img width="913" alt="Screenshot 2020-10-18 at 14 15 03" src="https://user-images.githubusercontent.com/138671/96367192-8adf2a80-114c-11eb-9dd0-83558aeb1f3d.png">

while without

```
                <exclude>example/B.class</exclude>
```

fails

```
[INFO] --- jacoco-maven-plugin:0.8.6:report (report-and-check) @ example ---
[INFO] Loading execution data file /private/tmp/j/target/jacoco.exec
[INFO] Analyzed bundle 'example' with 2 classes
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.6:check (report-and-check) @ example ---
[INFO] Loading execution data file /private/tmp/j/target/jacoco.exec
[INFO] Analyzed bundle 'example' with 2 classes
[WARNING] Rule violated for bundle example: lines covered ratio is 0.50, but expected minimum is 1.00
```

and produces following report

<img width="913" alt="Screenshot 2020-10-18 at 14 16 55" src="https://user-images.githubusercontent.com/138671/96367198-97fc1980-114c-11eb-965e-d92717be1675.png">

**Comment by sudheerah** [comment]
@Godin Thanks for detail explanation. 

Just one more clarification, I tried to do exclusion in the highest level as below expecting the particular classes will remove from `jacoco.exec` file. 

```
            plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <dataFile>${user.dir}/target/jacoco.exec</dataFile>
                    <excludes>
                        <exclude>**/*myclass</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
```


But when I open the file I could see 0%. (I know this nothing to do with report and check) Is this expected as per https://stackoverflow.com/a/40410773/2303693

**Comment by Godin** [comment]
> I tried to do exclusion in the top level as below expecting the particular classes will remove from `jacoco.exec` file.

When you specify `configuration` "in the top level" it applies to all goals, however as was already explained - for `report` and `check` goals `excludes` specify names of files, whereas names of classes for `prepare-agent`.

Using the same example from https://github.com/jacoco/jacoco/issues/1108#issuecomment-711159451
with following `pom.xml`

```
<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>example</artifactId>
  <version>0.1-SNAPSHOT</version>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.6</version>
        <configuration>
          <excludes>
            <exclude>example/A.class</exclude>
          </excludes>
        </configuration>
        <executions>
          <execution>
            <id>prepare-agent</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report-and-check</id>
            <goals>
              <goal>report</goal>
              <goal>check</goal>
            </goals>
            <configuration>
              <rules>
                <rule>
                  <limits>
                    <limit>
                      <counter>LINE</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>100%</minimum>
                    </limit>
                  </limits>
                </rule>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

after execution of `mvn clean verify` 
following command

```
java -jar jacoco-0.8.6/lib/jacococli.jar execinfo target/jacoco.exec | grep example
```

shows that `jacoco.exec` contains `example/A`

```
25aee8d92c5362e2    1 of   1   example/A
fdcca0cd19f8d732    2 of   2   example/ExampleTest
```

Whereas using the following `pom.xml`

```
<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>example</artifactId>
  <version>0.1-SNAPSHOT</version>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.6</version>
        <configuration>
          <excludes>
            <exclude>example/A</exclude>
          </excludes>
        </configuration>
        <executions>
          <execution>
            <id>prepare-agent</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report-and-check</id>
            <goals>
              <goal>report</goal>
              <goal>check</goal>
            </goals>
            <configuration>
              <rules>
                <rule>
                  <limits>
                    <limit>
                      <counter>LINE</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>100%</minimum>
                    </limit>
                  </limits>
                </rule>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

after execution of `mvn clean verify`
same command

```
java -jar jacoco-0.8.6/lib/jacococli.jar execinfo target/jacoco.exec | grep example
```

shows that `jacoco.exec` does not contain `example/A`

```
fdcca0cd19f8d732    2 of   2   example/ExampleTest
```

Once again please pay attention to the difference between
file name `example/A.class` in the first case
and class name `example/A` in the second case.

In the first case file `example/A.class` is excluded from generation of report, but class `example/A` is not excluded from instrumentation and appears in `jacoco.exec`.

In the second case vise versa - class `example/A` is excluded from instrumentation and does not appear in `jacoco.exec`, but not excluded from generation of report and appears in it.

----

> when I check jacoco.exec file via IntelliJ

> But when I open the jacoco.exec file I could see 0%.

Yes - in both above cases IntelliJ shows

<img width="294" alt="Run_and_Menubar" src="https://user-images.githubusercontent.com/138671/96441573-08b53b80-120a-11eb-9042-b78a9425bda9.png">

<img width="570" alt="example_–_ExampleTest_java" src="https://user-images.githubusercontent.com/138671/96441699-3bf7ca80-120a-11eb-92bc-7edbededc115.png">

Integration with IntelliJ is not developed by us here, so how IntelliJ shows the content of `jacoco.exec` is a question to developers of IntelliJ.

However as was already pointed in https://github.com/jacoco/jacoco/issues/1108#issuecomment-711151271
https://www.jacoco.org/jacoco/trunk/doc/faq.html
states
> report generator cannot distinguish whether the class was excluded from instrumentation or not executed

See that above `example/B` is not presented in both cases - `jacoco.exec` contains information about only executed classes and based only on `jacoco.exec` impossible to distinguish whether class was excluded from instrumentation or not executed.

And that's why generation of report requires explicit specification of class files included into the report.

And so that's probably why IntelliJ always shows all classes.
