### ISSUE TITLE
NPE in CoverageTransformer when trying to debug unit tests.

### ISSUE THREAD

**Issue by jlorusso-bc** [jacoco/jacoco#1110]
I'm hitting a NullPointerException when trying to debug a unit test (running through gradle in IntelliJ).
This appears to be happening on every unit test within the project, but not happening for unit tests in another project.

filter:130, CoverageTransformer (org.jacoco.agent.rt.internal_43f5073)
transform:86, CoverageTransformer (org.jacoco.agent.rt.internal_43f5073)
transform:188, TransformerManager (sun.instrument)
transform:428, InstrumentationImpl (sun.instrument)
defineAnonymousClass:-1, Unsafe (sun.misc)
spinInnerClass:326, InnerClassLambdaMetafactory (java.lang.invoke)
buildCallSite:194, InnerClassLambdaMetafactory (java.lang.invoke)
metafactory:304, LambdaMetafactory (java.lang.invoke)
invokeStatic_L6_L:-1, 416841088 (java.lang.invoke.LambdaForm$DMH)
reinvoke:-1, 1727361096 (java.lang.invoke.LambdaForm$BMH)
invoke_MT:-1, 1041365481 (java.lang.invoke.LambdaForm$MH)
makeSite:302, CallSite (java.lang.invoke)
linkCallSiteImpl:307, MethodHandleNatives (java.lang.invoke)
linkCallSite:297, MethodHandleNatives (java.lang.invoke)
loadTestEngines:37, ServiceLoaderTestEngineRegistry (org.junit.platform.launcher.core)
create:87, LauncherFactory (org.junit.platform.launcher.core)
create:67, LauncherFactory (org.junit.platform.launcher.core)
processAllTestClasses:97, JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor (org.gradle.api.internal.tasks.testing.junitplatform)
access$000:79, JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor (org.gradle.api.internal.tasks.testing.junitplatform)
stop:75, JUnitPlatformTestClassProcessor (org.gradle.api.internal.tasks.testing.junitplatform)
stop:61, SuiteTestClassProcessor (org.gradle.api.internal.tasks.testing)
invoke0:-1, NativeMethodAccessorImpl (sun.reflect)
invoke:62, NativeMethodAccessorImpl (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:498, Method (java.lang.reflect)
dispatch:36, ReflectionDispatch (org.gradle.internal.dispatch)
dispatch:24, ReflectionDispatch (org.gradle.internal.dispatch)
dispatch:33, ContextClassLoaderDispatch (org.gradle.internal.dispatch)
invoke:94, ProxyDispatchAdapter$DispatchingInvocationHandler (org.gradle.internal.dispatch)
stop:-1, $Proxy2 (com.sun.proxy)
stop:132, TestWorker (org.gradle.api.internal.tasks.testing.worker)
invoke0:-1, NativeMethodAccessorImpl (sun.reflect)
invoke:62, NativeMethodAccessorImpl (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:498, Method (java.lang.reflect)
dispatch:36, ReflectionDispatch (org.gradle.internal.dispatch)
dispatch:24, ReflectionDispatch (org.gradle.internal.dispatch)
dispatch:182, MessageHubBackedObjectConnection$DispatchWrapper (org.gradle.internal.remote.internal.hub)
dispatch:164, MessageHubBackedObjectConnection$DispatchWrapper (org.gradle.internal.remote.internal.hub)
run:412, MessageHub$Handler (org.gradle.internal.remote.internal.hub)
onExecute:64, ExecutorPolicy$CatchAndRecordFailures (org.gradle.internal.concurrent)
run:48, ManagedExecutorImpl$1 (org.gradle.internal.concurrent)
runWorker:1149, ThreadPoolExecutor (java.util.concurrent)
run:624, ThreadPoolExecutor$Worker (java.util.concurrent)
run:56, ThreadFactoryImpl$ManagedThreadRunnable (org.gradle.internal.concurrent)
run:748, Thread (java.lang)

**Comment by ilayaraja97** [comment]
Hey @jlorusso-bc do you not face this issue? My teammate has the issue and is having a hard time solving it.
