### ISSUE TITLE
Jacoco + android no coverage com.android.tools.build:gradle:4.1.0

### ISSUE THREAD

**Issue by mtrakal** [jacoco/jacoco#1113]
### Steps to reproduce

* JaCoCo version:  0.8.6 (tested with 0.8.5 too)
* Operating system: Windows 10 and Bitrise virtual (ubuntu?)
* Tool integration: gradle
* Complete executable reproducer: not provided, NDA
* Steps: 
integrate jacoco with Android which uses: 
```
 ext {
        compileSdkVer = 30
        targetSdkVer = 30
        minSdkVer = 21
        gradleBuildToolsVer = '4.1.0'
}
dependencies {
        classpath "com.android.tools.build:gradle:${gradleBuildToolsVer}"
}
```
gradlew jacocoTestReport

### Expected behaviour
Test coverage show actual result

### Actual behaviour
All test coverage is 0

When downgrade `gradleBuildToolsVer` to version `4.0.1` jacoco works as expected

**Comment by mtrakal** [comment]
related, so maybe it's not on Jacoco, but on Google: https://issuetracker.google.com/issues/171125857 but who know...

**Comment by Godin** [comment]
> related, so maybe it's not on Jacoco, but on Google: https://issuetracker.google.com/issues/171125857 but who know...

given that

> When downgrade `gradleBuildToolsVer` to version `4.0.1` jacoco works as expected

the issue is in `com.android.tools.build`
