### ISSUE TITLE
Feature: Support Cobertura output format for coverage

### ISSUE THREAD

**Issue by dragetd** [jacoco/jacoco#1114]
* JaCoCo version: JaCoCo 0.8.5.201910111838
* Operating system: Gentoo x86 linux-5.4.72-gentoo
* Tool integration: Maven / Gradle
* Description of your use case:

I am using Jacoco in a CI/CD envionrment with GitLab. GitLab is an alternative Git-based platform for project-management that has integrated CI/CD functionality. It allows parsing Cobertura based coverage reports and integrating them directly in the Diff view for a merge request. The functionality is described here: https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html#maven-example

The recommendation is to use the well supported and modern coverage tool Jacoco. But the common parsing format for coverage is based on Cobertura. To bridge that gap, they recommend using two little converter scripts that convert the coverage report to Cobertura compatible format, based on these scripts: https://gitlab.com/haynes/jacoco2cobertura

Eventho this is a viable approach, I wonder how difficult it would be to implement a feature to output Cobertura format directly from JaCoCo.

A random example for the format I found online:
https://gist.github.com/apetro/fcfffb8c4cdab2c1061d

### Possible Workarounds

If such functionality is out of the scope of this project, I do not think there is any viable workaround. Instead, users should use scripts like https://gitlab.com/haynes/jacoco2cobertura or GitLab should integrate parsing the JaCoCo XML format.

**Comment by marchof** [comment]
Indeed, this is out of scope of the project. Please understand that we cannot maintain file formats of other products - especially if those products are not actively maintained any more.

**Comment by dragetd** [comment]
The reasoning was, that this is a common format used also by other projects.

Examples:
* https://istanbul.js.org/docs/advanced/alternative-reporters/#cobertura (JS)
* https://coverage.readthedocs.io/en/coverage-5.0.4/cmd.html#xml-reporting (Python)
* https://rubygems.org/gems/simplecov-cobertura (Ruby)
* https://github.com/t-yuki/gocover-cobertura (Go)
* https://plugins.jenkins.io/cobertura/ (Jenkins read support)
* https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-code-coverage?tabs=linux (.net)

So it is pretty far spread, little chance of ever changing. I would still love to see support for it, but understand, that there is no interest from your side. Would you still prefer not to support it, even it was contributed externally via a PR?

**Comment by marchof** [comment]
This can be a perfect tool separate from JaCoCo.

Please understand that we have no time to take care of all the questions and issue that arise from the integration with all those tools, especially if we don't own the file format.
