### ISSUE TITLE
publish org.jacoco.agent.rt to maven central

### ISSUE THREAD

**Issue by maxandersen** [jacoco/jacoco#1117]
### Scenario

* JaCoCo version: 8+
* Operating system: OSX
* Tool integration: CLI (with jbang)
* Description of your use case: 

### Current Behaviour

Today I have to download the `org.jacoco:org.jacoco.agent:0.8.6` artifact  or jacoco download for then to unzip to get the actual agent jar.

### Wanted Behaviour

I would like to have the `org.jacoco.agent.rt` available in maven central so I can refer to it with https://jbang.dev and do this:

`jbang run --javaagent=org.jacoco:org.jacoco.agent.rt:0.8.6 script.java`

### Possible Workarounds

No good ones, except maybe using `com.github.jacoco.jacoco:org.jacoco.agent.rt:v0.8.4` from https://jitpack.io/#jacoco/jacoco/v0.8.4 but that requires adding jitpack maven repo.

**Comment by marchof** [comment]
Hi Max, please find the Maven coordinates of our artifacts here:

https://www.jacoco.org/jacoco/trunk/doc/repo.html

The packaged agent has the following coordinates

* groupId = org.jacoco
* artifactId = org.jacoco.agent
* type = runtime

**Comment by maxandersen** [comment]
No. That jar has a the actual agent embedded. 

It is not usable as javaagent standalone as it does not have the proper manifest nor classes.

**Comment by marchof** [comment]
Please note the classifier **runtime**. I just double checked. The coordinates above get you the agent with the proper manifest:

```
$ curl -O https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.8.6/org.jacoco.agent-0.8.6-runtime.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  285k  100  285k    0     0  1239k      0 --:--:-- --:--:-- --:--:-- 1233k
$ unzip -p org.jacoco.agent-0.8.6-runtime.jar META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: JaCoCo Java Agent
Automatic-Module-Name: org.jacoco.agent.rt
Premain-Class: org.jacoco.agent.rt.internal_f3994fa.PreMain
Implementation-Version: 0.8.6
Archiver-Version: Plexus Archiver
Built-By: root
Created-By: Apache Maven
Build-Jdk: 1.8.0_265
Implementation-Vendor: Mountainminds GmbH & Co. KG
```

**Comment by maxandersen** [comment]
Ah gotcha! it works:

`jbang --javaagent=org.jacoco:org.jacoco.agent:0.8.6:runtime karate.java`

yay!
