### ISSUE TITLE
org.jacoco:org.jacoco.cli:0.8.6 manifest.mf have no main class

### ISSUE THREAD

**Issue by maxandersen** [jacoco/jacoco#1118]
### Steps to reproduce

* JaCoCo version:  0.8.6
* Operating system: OSX
* Tool integration: CLI
* Steps: 

### Expected behaviour

be able to run jacoco client directly from the maven artifact. No need to specify main class.

### Actual behaviour

`jbang org.jacoco:org.jacoco.cli:0.8.6` fails with no main class having to do this full line:

`jbang --main org.jacoco.cli.internal.Main org.jacoco:org.jacoco.cli:0.8.6`

would be great to actually set main class so jacoco becomes easy to run.

**Comment by marchof** [comment]
Hi Max, nice to have you here :)

to run the command line tool from the jar you need the "nodeps" type. It meant for standalone usage and has the proper Main-Class header in the manifest:

Does jbang allow to specify a artifact type?

Cheers,
-marc

**Comment by maxandersen** [comment]
> Does jbang allow to specify a artifact type?

It does.

```
❯ jbang org.jacoco:org.jacoco.cli:0.8.6:nodeps
[jbang] Resolving dependencies...
[jbang]     Resolving org.jacoco:org.jacoco.cli:0.8.6:nodeps...Done
[jbang] Dependencies resolved
Command line interface for JaCoCo.

Usage: java -jar jacococli.jar --help | <command>
 <command> : dump|instrument|merge|report|classinfo|execinfo|version
 --help    : show help
 --quiet   : suppress all output on stdout

Argument "<command>" is required
```
