### ISSUE TITLE
enable `jbang cli@jacoco` and `jbang --javaagent agent@jacoco ...`

### ISSUE THREAD

**Issue by maxandersen** [jacoco/jacoco#1120]
now with #1118 and #1117  figured out would you be interested in being able to let anyone run jacoco ?

i.e. without java or jbang installed you can today do:
`curl -Ls https://sh.jbang.dev | bash -s - org.jacoco:org.jacoco.cli:0.8.6:nodeps`

of course just jbang works with: 
`jbang org.jacoco:org.jacoco.cli:0.8.6:nodeps`

or use the agent directly using `jbang --javagent org.jacoco:org.jacoco.agent:0.8.6:runtime ...`

Now if you made a `github.com/jacoco/jbang-catalog` with a `jbang-catalog.json` anyone could 
instead of having to refer to that long artifact do:

`jbang cli@jacoco` and `jbang --javaagent=agent@jacoco yourapp.java`

*`jbang-catalog.json`*:
```json
{
  "catalogs": {},
  "aliases": {
    "cli": {
      "script-ref": "org.jacoco:org.jacoco.cli:RELEASE:nodeps"
    },
    "agent": {
      "script-ref": "org.jacoco:org.jacoco.agent:RELEASE:runtime"
    }
  }
}
```

wdyt ?

**Comment by marchof** [comment]
Here we go: https://github.com/jacoco/jbang-catalog/

You have write access to that repo. Please feel free to adjust it to your needs.

Cool!

**Comment by maxandersen** [comment]
doh - turns out jbang doesn't handle the new fancy defaults of using something else than `master` - I'll need to see if can find a fix for that; until then you need to use

`jbang cli@jacoco/jbang-catalog/main`

you ok to rename its default to master for now or I need to fix jbang first ? :)

**Comment by marchof** [comment]
This is default. You have write access to the repo. Do what ever you prefer ;)

**Comment by maxandersen** [comment]
ack :) i'll revert it once i find a way to handle it in jbang.

**Comment by maxandersen** [comment]
hmm...@maxandersen don't seem to have write access though...and I don't see an invite to join org/team/repo ?

**Comment by marchof** [comment]
Please double-check your mail (spam folder)?

<img width="913" alt="image" src="https://user-images.githubusercontent.com/1936262/98437207-b5375e80-20e0-11eb-985d-c64981f3aa08.png">

**Comment by maxandersen** [comment]
okey - found it; but only have push access so can't actually change settings of the repo :)

**Comment by maxandersen** [comment]
doesn't matter - I found a way to have it work - will release it tonight.
