### ISSUE TITLE
viewmodelscope.launch shows partial code coverage

### ISSUE THREAD

**Issue by yuvaraj119** [jacoco/jacoco#1123]
At the function getDetails(str) viewModelScope.launch it shows partially covered in jacoco and sonarqube report.
Not able to figure out how to cover.

It shows 1 of 3, so there are 3 cases that have to be covered in JUnit.

Assumption:
1 case - it can be the success of the launch - do(green)
2 case - it can be a failure - how to make viewModelScope.launch fails in JUnit?
3 case -?

function getDetails(string)=viewModelScope.launch {
//some code
}

JaCoCo report shows 2 of 3:
https://i.stack.imgur.com/FdH54.png

Sonarqube report shows 1 of 3:-
https://i.stack.imgur.com/X43OU.png
https://i.stack.imgur.com/QSmdy.png

StackOverflow link - https://stackoverflow.com/questions/64594799/viewmodelscope-launch-shows-partial-code-coverage-in-sonarqube

kotlinVersion = '1.4.10'
coroutinesVersion = '1.3.0'
JaCoCo - 0.8.6
sonarqube - 7.8

**Comment by marchof** [comment]
Please provide executable reproducer, thx.

**Comment by yuvaraj119** [comment]
> 
> 
> Please provide executable reproducer, thx.

ok I will create a sample project in github and add a link for reference

**Comment by yuvaraj119** [comment]
Sorry there was some wrong data based on a different version of Jacoco used in the project I will close this as its working as expected
