### ISSUE TITLE
jacococli report generation using a spring jar file generates code coverage report for all packages including spring dependencies

### ISSUE THREAD

**Issue by karthick4kumaran** [jacoco/jacoco#1125]
I have a jacoco agent that is attached to a webservice. I executed my automation test cases and extracted the **jacoco-client.exec** from the webservice using the ExecutionDataClient. Now I am trying to generate a jacoco report for the webservice using the **jacoco-client.exec** file.

I am using the below command to generate the report.
java -jar jacococli.jar report jacoco-client.exec --classfiles rest-service2-0.0.1-SNAPSHOT.jar --html report

The webservice code repo is present as a separate repo and it is not a part of the automation code repo. So I cannot provide the classfiles path directly in the above command. So instead i am providing the application jar.

The issue is, jacoco is generating the code coverage report for all the maven dependencies in the jar along with the original code. But I need the code coverage for the application code alone and not the dependencies code. I am entirely new to using jacoco and don't know how to proceed further. Can someone please help me with this please.

<img width="1661" alt="Screenshot 2020-11-24 at 8 29 20 PM" src="https://user-images.githubusercontent.com/65916491/100111131-c67bbb80-2e93-11eb-8319-ce8202d5875a.png">

**Comment by marchof** [comment]
This is a bug tracker. Please consider the mailing list to ask general questions. You might find people there with a similar setup. Thx.
