### ISSUE TITLE
Jacoco HTML report  with java else statement should not marked with any color！

### ISSUE THREAD

**Issue by hardy1213** [jacoco/jacoco#1127]
JaCoCo version: 0.8.5

### Steps to reproduce

* JaCoCo version:  0.8.5(Created with JaCoCo 0.8.5.201910111838)
* Operating system: Linux
* Tool integration: API

### Expected behaviour
        Jacoco HTML report not marker any color for java else statement

### Actual behaviour

![image](https://user-images.githubusercontent.com/16552761/101116239-a8deec80-361f-11eb-83da-816a86c3c8a4.png)

**Comment by hardy1213** [comment]
Below is my validation result:

![image](https://user-images.githubusercontent.com/16552761/101116623-75e92880-3620-11eb-9e1b-a28cbe215111.png)

In fact, the statement is not marked with any color！

**Comment by marchof** [comment]
Line number information is derived from the debug information in the compiled class files. So this highly depends on the used compiler version.

To investigate, please provide

1) The exact version of the compiler you're using (e.g. the JDK that is used in your Maven build)
2) Please provide source file and class file of the example above
3) What would help a lot would be a executable reproducer that we can use to debug outside your environment,

**Comment by hardy1213** [comment]
> Line number information is derived from the debug information in the compiled class files. So this highly depends on the used compiler version.
> 
> To investigate, please provide
> 
    
**Bold font reply as follows**
> 1. The exact version of the compiler you're using (e.g. the JDK that is used in your Maven build)
     **java version "1.8.0_121"
    Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)**
> 2. Please provide source file and class file of the example above
   **As attached zip.file**
[source&class.zip](https://github.com/jacoco/jacoco/files/5649950/source.class.zip)

> 3. What would help a lot would be a executable reproducer that we can use to debug outside your environment,
   **okay**

**Comment by Godin** [comment]
@hardy1213  According to [your screenshot](
https://user-images.githubusercontent.com/16552761/101116239-a8deec80-361f-11eb-83da-816a86c3c8a4.png) red `else` is at line number `159`.

Execution of 

```
javap -v -p ThirdService.class | grep "line 159"
```

shows that line number `159` associated with instruction at offset `291`.

And execution of

```
javap -v -p ThirdService.class | grep " 291:" -B 12
```

shows

```
       262: ldc           #8                  // String 00
       264: aload         12
       266: invokevirtual #75                 // Method com/huifu/sspm/integration/realme/EntCorporationVerifyRespBO.getResp_cd:()Ljava/lang/String;
       269: invokevirtual #31                 // Method java/lang/String.equals:(Ljava/lang/Object;)Z
       272: ifne          291
       275: new           #21                 // class com/huifu/sspm/biz/exception/BizException
       278: dup
       279: getstatic     #53                 // Field com/huifu/sspm/util/enums/respcode/RespCodeEnum.CREDIT_CHECK_ERROR:Lcom/huifu/sspm/util/enums/respcode/RespCodeEnum;
       282: invokevirtual #54                 // Method com/huifu/sspm/util/enums/respcode/RespCodeEnum.getCode:()Ljava/lang/String;
       285: ldc           #76                 // String 法人四要素认证失败，请核实！
       287: invokespecial #56                 // Method com/huifu/sspm/biz/exception/BizException."<init>":(Ljava/lang/String;Ljava/lang/String;)V
       290: athrow
       291: goto          306
```

that this instruction is `goto` on execution path where `REALME_CHECK_RESP_CODE_SUCCESS.equals(respBO.getResp_cd())` evaluates to `true`. And to me seems that line with this condition is indeed marked as partially covered on your screenshot. So I believe that line of `else` will be marked as green when you'll add test for this case.

----

For the following simplified code similar to yours

```
class Example {
    void example(boolean b) {
        if (b) {
            Object o = null;
            if (b) {
                System.out.println(o);
            }
        } else {
            System.out.println();
        }
    }
}
```

`javac` compiler (OpenJDK versions 1.8.0_121 , 11.0.9 and even 15.0.1) produces similar bytecode with line number of `else`

<img width="490" alt="javac-1" src="https://user-images.githubusercontent.com/138671/101500399-b6250f80-396e-11eb-97ca-556ca9b5ea66.png">

while does not produce for

```
class Example {
    void example(boolean b) {
        if (b) {
            System.out.println();
        } else {
            System.out.println();
        }
    }
}
```

<img width="490" alt="javac-2" src="https://user-images.githubusercontent.com/138671/101500749-2fbcfd80-396f-11eb-9ead-86e2435824fc.png">

However Eclipse Compiler version 3.23.0 produces bytecode with line number of `else` in both cases:

<img width="490" alt="ecj-1" src="https://user-images.githubusercontent.com/138671/101500452-cc32d000-396e-11eb-957c-184f856fce08.png">

<img width="490" alt="ecj-2" src="https://user-images.githubusercontent.com/138671/101500724-2764c280-396f-11eb-855b-f577a31be854.png">

----

As @marchof already said about JaCoCo

> Line number information is derived from the debug information in the compiled class files.

And whether or not `javac` compiler should produce bytecode with line number of `else` is a question to developers of compiler - https://bugreport.java.com/
