### ISSUE TITLE
Coverage 0% in data class (Kotlin)

### ISSUE THREAD

**Issue by jspinsanti** [jacoco/jacoco#1146]
### Steps to reproduce

* JaCoCo version:  0.8.6
* Operating system: Ubuntu 20.04.1 LTS
* Tool integration: Maven
* Complete executable reproducer:

Create a basic data class in Kotlin as follows:
```
data class MyDataClass(
  val myField: String
)
``` 
IMO:
* I expect that the coverage will be 100%
* no test required
* no annotation `@Generated` should be added to ignore coverage

### Expected behaviour
I expect that the coverage of data class will be 100%
### Actual behaviour
Current coverage is 0%

![MyDataClass-1](https://user-images.githubusercontent.com/12845908/102784718-8963f580-437b-11eb-8429-5e6217306af5.png)
![MyDataClass-2](https://user-images.githubusercontent.com/12845908/102784744-8ec14000-437b-11eb-8373-cfc1c7674cf6.png)

**Comment by Godin** [comment]
See
* https://github.com/jacoco/jacoco/issues/900#issuecomment-504448726
* https://youtrack.jetbrains.com/issue/KT-18383#focus=Comments-27-2890396.0-0
* https://github.com/jacoco/jacoco/pull/923#issuecomment-523768056
