### ISSUE TITLE
Code Coverage issue in Android Automotive Car Emulator

### ISSUE THREAD

**Issue by keshavmix** [jacoco/jacoco#1158]
Objective is to get 100% code coverage for instrumentation test in Android Automotive Car Emulator API 29.

I am trying to run coverage report on android test(instrumentation test) using jacoco version 0.8.0 till 0.8.6 on Android Automotive Car Emulator API 29, test cases are executing successfully but code coverage is 0% for instrumentation test(espresso test). Generated coverage.ec file is empty in the car emulator. 

I also noticed that code coverage is 100% for unit test. I tried the same configuration and testing in Android generic mobile emulator(Pixel 2 API 29) but in this case both unit and instrumentation test shows 100% code coverage. 

Below are logs for both Android emulator. I have already added READ/WRITE permissions also.

Android Automotive Car Emulator API 29 - Failed
```
05:47:47 V/InstrumentationResultParser: Error: Failed to generate Emma/JaCoCo coverage.13:32
05:47:47 V/InstrumentationResultParser:
05:47:47 V/InstrumentationResultParser: Time: 2.987
05:47:47 V/InstrumentationResultParser:
05:47:47 V/InstrumentationResultParser: OK (2 tests)
05:47:47 V/InstrumentationResultParser:
05:47:47 V/InstrumentationResultParser:
05:47:47 V/InstrumentationResultParser: Error: Failed to generate Emma/JaCoCo coverage.
05:47:47 V/InstrumentationResultParser: INSTRUMENTATION_CODE: -1 
```

Android generic mobile emulator(Pixel 2 API 29) - Success
```
04:23:59 V/InstrumentationResultParser: Time: 3.089
04:23:59 V/InstrumentationResultParser:
04:23:59 V/InstrumentationResultParser: OK (2 tests)
04:23:59 V/InstrumentationResultParser:
04:23:59 V/InstrumentationResultParser:
04:23:59 V/InstrumentationResultParser: Generated code coverage data to data/data/com.sampleapp.jacocoandroidtest/coverage.ec
04:23:59 V/InstrumentationResultParser: INSTRUMENTATION_CODE: -1 
```
Thanks for your support.
Keshav

**Comment by marchof** [comment]
See: https://groups.google.com/g/jacoco/c/3o-_-OtR_as
