### ISSUE TITLE
Kotlin Multiplatform support

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [jacoco/jacoco#1161]
### Scenario

* JaCoCo version: 0.8.6
* Tool integration: Gradle

### Current Behaviour
If I have code that only is in `commonMain` source set and I only add tests in `commonTest`, it is marked as uncovered.

Meanwhile, if I use expect/actual approach and I have an `expect` in `commonMain`, `actual` in `jvmMain` which is tested in `jvmMain`, it is marked as covered.

### Wanted Behaviour

Common code should be marked as covered if it only depends on common code and common tests.

**Comment by marchof** [comment]
Gradle plugin is developed by Gradle project (see https://www.jacoco.org/jacoco/trunk/doc/integrations.html).

Please report the issue there. Thx!
