### ISSUE TITLE
Jacoco reporting incomplete coverage for record constructors

### ISSUE THREAD

**Issue by adambom** [jacoco/jacoco#1170]
For records with a nonzero number of constructor arguments, Jacoco is reporting either partial or missing coverage for constructors. It reports missing coverage when a custom constructor is defined and partial coverage when there is no custom constructor defined.

### Steps to reproduce

* JaCoCo version:  0.8.6.202009150832
* Operating system: Mac OS Catalina 10.15.5
* Tool integration: Gradle plugin
* Complete executable reproducer: See code snippet below
* Steps: Run test `BugIllustrationTest#testIllustrateBug`

#### Create the following test class

```java
package com.jacoco.bug;

import lombok.experimental.UtilityClass;

// UtilityClass is not necessary to reproduce behavior
@UtilityClass
class BugIllustration {

  record RecordNoConstructorNoArguments() {}

  record RecordNoConstructorOneArgument(String arg) {}

  record RecordWithConstructorAndArgument(String arg) {

    public RecordWithConstructorAndArgument {
      this.arg = arg.toLowerCase();
    }
  }

}
```

#### Create the following test cases

```java
package com.jacoco.bug;

import org.junit.jupiter.api.Test;

public class BugIllustrationTest {

  @Test
  public void testIllustrateBug() {
    new BugIllustration.RecordNoConstructorNoArguments();
    new BugIllustration.RecordNoConstructorOneArgument("a");
    new BugIllustration.RecordWithConstructorAndArgument("a");
  }

  @Test
  public void testIllustrateWorkaround() {
    new BugIllustration.RecordNoConstructorNoArguments();

    var a = new BugIllustration.RecordNoConstructorOneArgument("a");
    a.arg();
    a.toString();
    a.hashCode();
    a.equals(new BugIllustration.RecordNoConstructorOneArgument("a"));

    var b = new BugIllustration.RecordWithConstructorAndArgument("a");
    b.arg();
    b.toString();
    b.hashCode();
    b.equals(new BugIllustration.RecordNoConstructorOneArgument("a"));
  }
}
```

Running the first test case `testIllustrateBug` on its own produces the output shown in "Actual behaviour". I also wrote another test, `testIllustrateWorkaround` to show that by manually calling the accessors, toString, equals, and hash code we can work around the problem to produce the expected output.

### Expected behaviour

<img width="457" alt="Screen Shot 2021-03-26 at 10 00 57 AM" src="https://user-images.githubusercontent.com/294597/112667161-2b332c80-8e1a-11eb-9849-79464f573388.png">

### Actual behaviour

<img width="472" alt="Screen Shot 2021-03-26 at 10 01 25 AM" src="https://user-images.githubusercontent.com/294597/112667415-72212200-8e1a-11eb-8fe2-ec24938fa8a9.png">

**Comment by marchof** [comment]
@adambom Can you please provide a executable reproducer (e.g. Github repo) with maven build so we we can debug the issue?

As a first step you may also attach the class files which are create by your example.

**Comment by marchof** [comment]
@adambom BTW, as this is only reproducible with Lombok I strongly assume this is due to extra code created by this framework. In this case please open a bug at Lombok, they need to annotate generated code, otherwise JaCoCo will report it.

**Comment by Godin** [comment]
> as this is only reproducible with Lombok

@marchof actually @adambom wrote

> UtilityClass is not necessary to reproduce behavior

However for the

```
class Example {

  record RecordNoConstructorNoArguments() {}

  record RecordNoConstructorOneArgument(String arg) {}

  record RecordWithConstructorAndArgument(String arg) {

    public RecordWithConstructorAndArgument {
      this.arg = arg.toLowerCase();
    }
  }

}
```

`javac` produces

```
Example.java:10: error: cannot assign a value to final variable arg
      this.arg = arg.toLowerCase();
          ^
1 error
```

While without `this`

```
class Example {

  record RecordNoConstructorNoArguments() {}

  record RecordNoConstructorOneArgument(String arg) {}

  record RecordWithConstructorAndArgument(String arg) {

    public RecordWithConstructorAndArgument {
      arg = arg.toLowerCase();
    }
  }

  public static void main(String[] args) {
    new RecordNoConstructorOneArgument("a");
    new RecordWithConstructorAndArgument("a");
  }
}
```

execution of

```
javac Example.java -d classes
java -javaagent:jacoco-0.8.6/lib/jacocoagent.jar -cp classes Example
java -jar jacoco-0.8.6/lib/jacococli.jar report jacoco.exec --classfiles classes --sourcefiles . --html report
```

indeed produces following report

<img width="1060" alt="source" src="https://user-images.githubusercontent.com/138671/112736244-8a478d00-8f51-11eb-98d0-6ac60b9c204e.png">

however @adambom if in the report you'll look on classes instead of source, then you'll see that both partial and missing coverage are caused by absence of calls to `arg`

<img width="1068" alt="RecordWithConstructorAndArgument" src="https://user-images.githubusercontent.com/138671/112736302-0b068900-8f52-11eb-8d6e-6dc487244cfe.png">

<img width="1065" alt="RecordNoConstructorOneArgument" src="https://user-images.githubusercontent.com/138671/112736303-0d68e300-8f52-11eb-81cd-32248a297512.png">

and actually this is expected behaviour - if you do not plan to use component of a record, then why declare it?

**Comment by marchof** [comment]
@Godin Thanks for looking into this!

**Comment by adambom** [comment]
> if you do not plan to use component of a record, then why declare it?

But what about if you use the component's private accessor? For instance:

```java

record RecordWithConstructorAndArgument(String arg) {

  public RecordWithConstructorAndArgument {
    arg = arg.toLowerCase();
  }

  String upperCaseArg() {
    return arg.toUpperCase();
  }
}
```

Sure, I'm not using the public accessor, but I still need the property declared. Shouldn't this count as coverage if `upperCaseArg()` is called during a test?

**Comment by Godin** [comment]
If you don't plan to rely on equality based on `toLowerCase()`, nor its `hashCode`, nor its value, then why not normalize to `arg.toUpperCase()` in constructor?

**Comment by adambom** [comment]
> If you don't plan to rely on equality based on `toLowerCase()`, nor its `hashCode`, nor its value, then why not normalize to `arg.toUpperCase()` in constructor?

You're missing the point. That could be a `sayHello` method that just prints the value of `arg`. The point is that you shouldn't need to use the public accessor for the constructor to be considered covered, so long as you're accessing it privately.
