### ISSUE TITLE
Jacoco report shows 0% coverage when using includes tag 

### ISSUE THREAD

**Issue by SSDivya** [jacoco/jacoco#1177]
### Steps to reproduce

* JaCoCo version: 0.8.2
* Operating system: Windows 10
* Tool integration: Maven
* Complete executable reproducer: 
	
   We are using the below plugin to generate report for some classes

```
	<plugin>
		<groupId>org.jacoco</groupId>
		<artifactId>jacoco-maven-plugin</artifactId>
		<version>0.8.2</version>
		<configuration>
			<includes>
				<include>com/demo/controller/Sample.class</include>
			</includes>
		</configuration>
		<executions>
		<execution>
			<id>jacoco-initialize</id>
		<goals>
			<goal>prepare-agent</goal>
		</goals>
		</execution>
		<execution>
			<id>jacoco-site</id>
		<phase>package</phase>
		<goals>
			<goal>report</goal>
		</goals>
		</execution>
		</executions>
	</plugin>
```

* Steps: 
	 1.We are trying to Generate Jacoco report for particular class mentioned in the includes tag
	 2.We are using this goal 'clean jacoco:prepare-agent install jacoco:report' to generate report

### Expected behaviour
Jacoco Report should be generated with the classes that are provided inside the includes tag with the correct coverage percentage

### Actual behaviour
Report is getting generated with the mentioned classes only but with 0% coverage

**Comment by Godin** [comment]
@SSDivya looks like #34, so this should do the job:

```
<plugin>
	<groupId>org.jacoco</groupId>
	<artifactId>jacoco-maven-plugin</artifactId>
	<version>0.8.2</version>
	<executions>
		<execution>
			<id>jacoco-initialize</id>
			<goals>
				<goal>prepare-agent</goal>
			</goals>
		</execution>
		<execution>
			<id>jacoco-site</id>
			<phase>package</phase>
			<goals>
				<goal>report</goal>
			</goals>
			<configuration>
				<includes>
					<include>com/demo/controller/Sample.class</include>
				</includes>
			</configuration>
		</execution>
	</executions>
</plugin>
```
