### ISSUE TITLE
Support pom packaged projects for prepare-agent

### ISSUE THREAD

**Issue by eswdd** [jacoco/jacoco#118]
We currently use jacoco to instrument a server we run up prior to invoking integration tests against it. The server is run as part of a CI build by invoking a maven project using the exec:java goal, whereupon there is no opportunity to load the jacoco agent or otherwise integrate. The maven project is run from within another maven project and we would like to pass the agent properties as an environment variable when invoking this project - all doable except that we can't run the jacoco plugin to generate the agent string since it is packaged as a pom project. We'd like the ability to run this particular plugin within a pom packaged project.

**Comment by Godin** [comment]
This was fixed in 0.6.5.
