### ISSUE TITLE
Kotlin constructors with `DefaultConstructorMarker` not covered

### ISSUE THREAD

**Issue by binkley** [jacoco/jacoco#1195]
(Apologies if this is a duplicate issue.  I did not find a straight-forward matching issue.)

### Scenario

* JaCoCo version: 0.8.7
* Operating system: MacOS (not relevant)
* Tool integration: Maven (not relevant)
* Description of your use case: https://github.com/binkley/layers-kt

JaCoCo coverage reports state that the Kotlin constructors with `DefaultConstructorMarker` are not covered.  This appears in the Maven coverage reports.  Example is `layers-kt-lib/target/site/jacoco/hm.binkley.layers.util/ArrayMutableStack.html` after executing `./mvnw clean verify` for the above project.  This concern happens across the board for me; `ArrayMutableStack` is just one example.

### Current Behavior

Coverage reports complaining about `DefaultConstructorMarker` with Kotlin code.

### Wanted Behavior

JaCoCo ignores the generated JVM bytecode for constructors with `DefaultConstructorMarker` as the last parameter.  This is Kotlin-specific, unfortunately.

It may be the case that if Kotlin's compiler annotated these constructors as generated, then JaCoCo would automatically do the right thing.  Using `javap` is not turning up anything helpful for annotations.

### Possible Workarounds

Not clear.  I do not want to ignore my class's default constructors.  However:

1. There is not clear way in JaCoCo to ignore a method (constructor) with specific parameters using only JaCoCo configuration
2. Using `@lombok.Generated` is a workaround most times, but is not applicable here for _actual Kotlin generated code_ (ironic, I understand)
3. Ignoring the classes involved leaves me with no means to enforce coverage for class methods

**Comment by Godin** [comment]
> Coverage reports complaining about DefaultConstructorMarker with Kotlin code.
>
> Wanted Behavior
> JaCoCo ignores the generated JVM bytecode for constructors with DefaultConstructorMarker as the last parameter. 

Appearance of constructors with DefaultConstructorMarker as the last parameter in reports is intentional - please see #888

> `ArrayMutableStack` is just one example

in this case for your

```
open class ArrayMutableStack<T>(
    private val elements: MutableList<T> = mutableListOf(),
) : MutableStack<T>, MutableList<T> by elements.toMutableList()
```

constructor with `DefaultConstructorMarker` is shown as uncovered, because there is no construction of `ArrayMutableStack` that uses default parameter value.

For example after

```diff --git i/layers-kt-lib/src/main/kotlin/hm/binkley/layers/util/MutableStack.kt w/layers-kt-lib/src/main/kotlin/hm/binkley/layers/util/MutableStack.kt
index ddd049c..fd50569 100644
--- i/layers-kt-lib/src/main/kotlin/hm/binkley/layers/util/MutableStack.kt
+++ w/layers-kt-lib/src/main/kotlin/hm/binkley/layers/util/MutableStack.kt
@@ -16,7 +16,7 @@ open class ArrayStack<T>(
 ) : Stack<T>, List<T> by elements.toList()

 fun <T> mutableStackOf(): MutableStack<T> =
-    ArrayMutableStack(mutableListOf())
+    ArrayMutableStack()

 fun <T> mutableStackOf(vararg elements: T): MutableStack<T> =
     ArrayMutableStack(mutableListOf(*elements))
```

execution of `mvn clean verify` produces

<img width="1180" alt="Screenshot 2021-05-31 at 23 38 37" src="https://user-images.githubusercontent.com/138671/120244016-5f3b2b80-c269-11eb-939f-0f4a22f42699.png">
