### ISSUE TITLE
 would jacoco support java code increment coverage rate

### ISSUE THREAD

**Issue by chujidiy** [jacoco/jacoco#1202]
Hello! 

    For example, we have a java project,  released V1.0 last week,  and released V2.0 yesterday。
    Then we started test。
    We want to know the  coverage rate among the java codes which changed between V2.0 and V1.0 with jacoco , when finished test。We want to do a quick test。
     would jacoco support java code increment coverage rate？

**Comment by marchof** [comment]
JaCoCo does not support this and there are no plans to implement this. There are tools like SonarQube which have metrics like "Coverage on new code".

**Comment by chujidiy** [comment]
@marchof thank you , i'll be familiar with SonarQube
