### ISSUE TITLE
Static fields with @Generated are not ignored

### ISSUE THREAD

**Issue by maksutspahi** [jacoco/jacoco#1204]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling bug report!

### Steps to reproduce

* JaCoCo version:  0.8.7.202105040129
* Lombok version: 1.18.8
* Operating system: MacOS 10.15.7
* Tool integration: Maven
* Steps: 
![image](https://user-images.githubusercontent.com/4736471/123484696-745d6d00-d611-11eb-8b2e-61dc758362b9.png)

### Expected behaviour
The code part to be ignored from report
`private static final Logger log = LoggerFactory.getLogger(MaxService.class);`

### Actual behaviour
Static code part is still included in the report as not covered.

Note: Lombok annotation `@Slf4j` has same results with with 'lombok.addLombokGeneratedAnnotation = true'

Code with imports:

```
import lombok.Generated;
import lombok.extern.slf4j.Slf4j;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MaxService {

    @Generated
    private static final Logger log = LoggerFactory.getLogger(MaxService.class);

    private String payment;

    @Generated
    public MaxService(String payment) {
        this.payment = payment;
    }

    public MaxService() {
    }
}
```

Example with lombok log annotation @Slf4j source:
```
@Slf4j
@NoArgsConstructor
public class MaxService {
}
```

Generated source:
```
public class MaxService {
    @Generated
    private static final Logger log = LoggerFactory.getLogger(MaxService.class);

    @Generated
    public MaxService() {
    }
}
```
Result (constructor is ignored as expected but not the logger):
![image](https://user-images.githubusercontent.com/4736471/123485634-26496900-d613-11eb-9fc9-6eca148e2fe1.png)

**Comment by marchof** [comment]
Hi @maksutspahi the annotation only works on methods. In your case a static initializer methods is created by the compiler which code is then detected by JaCoCo. I don't think it is possible to properly map initialization code to the respective static field. Probably this would evolve complex data flow analysis. So I would consider this as a known limitation.

But please feel free to share ideas how to solve this or even provide a pull request!

**Comment by maksutspahi** [comment]
Thank you for the explanation.
