### ISSUE TITLE
Filter of Java 16 record accessors

### ISSUE THREAD

**Issue by ice1000** [jacoco/jacoco#1215]
### Scenario

* JaCoCo version: 0.8.7
* Operating system: unrelated
* Tool integration: unrelated
* Description of your use case: I'm using jacoco with Java 16 records.

### Current Behaviour

The record accessors are unused because I'm using them as fields. I do not want jacoco to report a missed branch for this very simple reason.

![image](https://user-images.githubusercontent.com/16398479/130311898-82ed3cb9-51c4-4fbd-9a6e-9c0e93d63d55.png)

### Wanted Behaviour

These branches are filtered out.

### Possible Workarounds

Idk.

**Comment by Chessray** [comment]
Some developers will prefer using the fields, others (including myself) the accessors. What a coverage should _really_ check is that _every_ field is being used directly _or_ via the accessor. So JaCoCo would somehow need to realize that they're basically the same. Is that possible?

**Comment by ice1000** [comment]
> Some developers will prefer using the fields, others (including myself) the accessors. What a coverage should _really_ check is that _every_ field is being used directly _or_ via the accessor. So JaCoCo would somehow need to realize that they're basically the same. Is that possible?

I don't think it's possible

**Comment by Thunderforge** [comment]
I think we should go ahead and filter all accessors in records, just like we do for `toString()`, `hashCode()`, and `equals()`.

Because these methods are generated by the compiler, there isn’t any reason to test that they are working correctly in our code. 

While as-is this behavior does find unused fields, I don’t see that as being in scope for Jacoco; Jacoco doesn’t check for unused instance variables and instead leaves those for tools like PMD.

**Comment by esfomeado** [comment]
This would be a welcome feature since I have to rely on workarounds to get coverage at 100%.

**Comment by TheConen** [comment]
Standing before the same problem: I have records that are pure data classes without any methods, so there is nothing to test there. However, Jacoco still reports this as not being covered, which in turn causes Sonar to fail because there is not enough coverage on the new code (being only the records). Does anyone have a workaround for this?

**Comment by esfomeado** [comment]
@TheConen The workaround is to make dumb tests that all they do is the accessors value.

**Comment by ice1000** [comment]
I think I sort of get the idea of how to implement those (by modifying `RecordFilter` class), but I don't want to install maven.

**Comment by ice1000** [comment]
Also, I'm unsure how to properly write tests...

**Comment by esfomeado** [comment]
I can give you a hand with the implementation and write the tests.

**Comment by ice1000** [comment]
> I can give you a hand with the implementation and write the tests.

Ok, I'll see what I can do, thanks!

**Comment by ice1000** [comment]
I created #1393, please take a look!

**Comment by nascivini** [comment]
Hello folks,

Any information about a new release of Jacoco including this fix? On Maven Central repository, specifically

**Comment by ice1000** [comment]
> Hello folks,
> 
> Any information about a new release of Jacoco including this fix? On Maven Central repository, specifically

FYI I tested this with codecov and I don't see any coverage changes lol

**Comment by Godin** [comment]
@ice1000 for the following `RecordExample.java`

```
record RecordExample(int x) {
    public static void main(String[] args) {
        new RecordExample(42);
    }
}
```

using

```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
```

after compilation

```
javac RecordExample.java
```

generation of report with JaCoCo version `0.8.8`

```
java -javaagent:jacoco-0.8.8/lib/jacocoagent.jar=destfile=0.8.8.exec -cp . RecordExample
java -jar jacoco-0.8.8/lib/jacococli.jar report 0.8.8.exec --classfiles RecordExample.class --sourcefiles . --html report-0.8.8
```

produces

<img width="856" alt="Screenshot 2023-04-01 at 01 33 06" src="https://user-images.githubusercontent.com/138671/229250113-81d683b2-4fb2-4466-8e25-472135dc6515.png">

whereas using JaCoCo `0.8.9-SNAPSHOT`

```
java -javaagent:jacoco-0.8.9-SNAPSHOT/lib/jacocoagent.jar=destfile=0.8.8.exec -cp . RecordExample
java -jar jacoco-0.8.9-SNAPSHOT/lib/jacococli.jar report 0.8.9.exec --classfiles RecordExample.class --sourcefiles . --html report-0.8.9
```

<img width="856" alt="Screenshot 2023-04-01 at 01 32 47" src="https://user-images.githubusercontent.com/138671/229250129-0eb7a44d-7203-407e-930d-e1111d43c66e.png">

Clearly showing that record accessors are filtered-out.

So regarding

> FYI I tested this with codecov

ready to bet that something wrong in your test or codecov, and not in JaCoCo.

----

@nascivini 

> Any information about a new release of Jacoco including this fix?

See https://www.jacoco.org/jacoco/trunk/doc/faq.html

> ### When will feature X be released?
> **JaCoCo is maintained by volunteers in their free time. Since we cannot guarantee free capacity, we do not commit to particular release dates.** Typically, you can expect a couple of releases every year.
>
> In the [change log](https://www.jacoco.org/jacoco/trunk/doc/changes.html), you can see all features that have been implemented in master branch and will be available with the next release. And in the meantime you can test latest build of master branch ([Maven SNAPSHOT](https://www.jacoco.org/jacoco/trunk/doc/repo.html)) and provide feedback to us.

Release of `0.8.9` is happening this weekend and so should be available in Maven Central on Monday.

**Comment by ice1000** [comment]
> ready to bet that something wrong in your test or codecov, and not in JaCoCo.

I agree, but all I did was using the default setup so probably codecov is in itself fundamentally wrong on calculating the coverages LOL

Anyways, no means to blame JaCoCo! I was just sharing my observation.
