### ISSUE TITLE
Jacoco does not work with Spring Boot 2.5.4

### ISSUE THREAD

**Issue by himasz** [jacoco/jacoco#1220]
When upgrading to spring boot version 2.5.4, Jacoco stopped working. It shows 0 coverage where it has than 80% coverage in some of them .  

>             <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.7</version>
                <configuration>
                    <excludes>
                        <exclude>cloud/hgs/rmi/api/RmiApiApplication.class</exclude>
                        <exclude>cloud/hgs/rmi/api/RmiApiImporterApplication.class</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>jacoco-check</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <rule>
                                    <element>PACKAGE</element>
                                    <limits>
                                        <limit>
                                            <counter>METHOD</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>0.5</minimum>
                                        </limit>
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by marchof** [comment]
Do you create JaCoCo HTML reports? In this case please check the "Sessions" page (link on the top right corner):

1) Do you see your classes under test listed?
2) Do the classes have a link?

In any case please provide the details in the bug template, e.g. JaCoCo version in use.

**Comment by Godin** [comment]
@himasz in addition to what was asked/said by @marchof 

> In any case please provide the details in the bug template, e.g. JaCoCo version in use

here is this template that you ignored 

<img width="747" alt="template" src="https://user-images.githubusercontent.com/138671/72797784-140b1480-3c42-11ea-8f87-c4bd0f70d7bb.png">

in absence of **complete executable example** 
we have no idea how to reproduce your problem.

----

Also regarding

> When upgrading to spring boot version 2.5.4, Jacoco stopped working

then why do you think that the issue is on JaCoCo side, but not on Spring Boot side?

**Comment by nagygr** [comment]
Unfortunately my project is closed source and I'm not allowed to share it, but I have experienced a similar though not exactly identical issue. I have a Spring Boot project and the JaCoCo report (build/reports/jacoco/test/html/index.html) shows 100% for all of the packages and in every category. Yet, the rules for full INSTRUCTION and LINE coverage fail (the error message says that the coverage is 0.95 and not 1.0).

I know that without the code you will not be able to help with this, I'm just writing to let you know that there really might be something wrong here.

**Comment by marchof** [comment]
If you find the time to extract a reproducer which you can share feel free to open an new issue!

**Comment by rakshitavasthy** [comment]
I was facing same thing with springboot 2.7.7. Later found out junit 4 was being used for tests. Got it working after upgrading to junit5
