### ISSUE TITLE
Incorrect coverage occurs on the ubuntu-20.04 operating system

### ISSUE THREAD

**Issue by LCDZhao-Z** [jacoco/jacoco#1222]
### Steps to reproduce

* JaCoCo version:  ```0.8.7``` or ```0.8.6```
* Operating system: ```ubuntu-20.04```
* Tool integration: ```Maven```
* Complete executable reproducer:    https://github.com/esastack/esa-servicekeeper
* Steps: 
step1: Set ```ubuntu-20.04``` in workflows
step2: Run github action
step3: Download ```jacobo.xml``` from codecov

### Expected behaviour
The expected coverage of ```io.esastack.servicekeeper.core.configsource.ExternalConfig``` in ```jacobo.xml``` should be as shown below that is also the result of ```ubuntu-18.04``` or other operating systems：
```xml
<class sourcefilename="ExternalConfig.java" name="io/esastack/servicekeeper/core/configsource/ExternalConfig">
#...leave out redundant methods
  <method name="isAllEmpty" line="79" desc="()Z">
    <counter covered="73" missed="0" type="INSTRUCTION"/>
    <counter covered="45" missed="1" type="BRANCH"/>
    <counter covered="23" missed="0" type="LINE"/>
    <counter covered="23" missed="1" type="COMPLEXITY"/>
    <counter covered="1" missed="0" type="METHOD"/>
  </method>

  <method name="toString" line="106" desc="()Ljava/lang/String;">
    <counter covered="147" missed="0" type="INSTRUCTION"/>
    <counter covered="22" missed="2" type="BRANCH"/>
    <counter covered="35" missed="0" type="LINE"/>
    <counter covered="11" missed="2" type="COMPLEXITY"/>
    <counter covered="1" missed="0" type="METHOD"/>
  </method>
#...leave out redundant methods
</class>
```
### Actual behaviour
This is the result of ```ubuntu-20.04```.
```xml
<class sourcefilename="ExternalConfig.java" name="io/esastack/servicekeeper/core/configsource/ExternalConfig">
#...leave out redundant methods
  <method name="isAllEmpty" line="79" desc="()Z">
    <counter covered="0" missed="73" type="INSTRUCTION"/>
    <counter covered="0" missed="46" type="BRANCH"/>
    <counter covered="0" missed="23" type="LINE"/>
    <counter covered="0" missed="24" type="COMPLEXITY"/>
    <counter covered="0" missed="1" type="METHOD"/>
  </method>

  <method name="toString" line="106" desc="()Ljava/lang/String;">
    <counter covered="0" missed="147" type="INSTRUCTION"/>
    <counter covered="0" missed="24" type="BRANCH"/>
    <counter covered="0" missed="35" type="LINE"/>
    <counter covered="0" missed="13" type="COMPLEXITY"/>
    <counter covered="0" missed="1" type="METHOD"/>
  </method>
#...leave out redundant methods
</class>
```

**Comment by marchof** [comment]
Hi @LCDZhao-Z, can you please have a look in the *.exec files from both builds? You can use the JaCoCo CLI to inspect them.

- Are the same classes listed?
- Do they have the same ids?

**Comment by Godin** [comment]
> step3: Download jacobo.xml **from codecov**

@LCDZhao-Z why do you think that the issue is on JaCoCo side and not with CodeCov third-party service?

Please have a look at file `servicekeeper-core/target/site/jacoco/jacoco.xml` produced in GitHub Actions on Ubuntu 20.04 - as you can see in https://github.com/esastack/esa-servicekeeper/pull/28 it contains expected numbers.

**Comment by LCDZhao-Z** [comment]
@Godin I run it in my forked   https://github.com/LCDZhao-Z/esa-servicekeeper/tree/show-jacoco-xml-in-github-action

**Comment by LCDZhao-Z** [comment]
I run 'Show jacoco.xml' in my forked repository: https://github.com/LCDZhao-Z/esa-servicekeeper/tree/show-jacoco-xml-in-github-action.
But the jacoco.xml becomes expected and codecov's coverage also becomes as expected when I add 'Show jacoco.xml'.
 Codecov's coverage: https://app.codecov.io/gh/LCDZhao-Z/esa-servicekeeper/branch/show-jacoco.xml/commits?page=1
And the coverage of codecov is still expected when I delete 'Show jacoco.xml'.The previous problems do not recur.

**Comment by LCDZhao-Z** [comment]
Thank you for your suggestion. I don't know whether I changed a part of my code or another three-party problem. My problem has been solved now. @Godin
