### ISSUE TITLE
Jacoco HTML coverage report line numbers not readable for very long files

### ISSUE THREAD

**Issue by dhendriks** [jacoco/jacoco#1227]
### Steps to reproduce

* JaCoCo version: 0.8.7
* Operating system: Linux
* Tool integration: Maven
* Complete executable reproducer: (doesn't seem necessary for this type of issue, just take any long Java file)
* Steps: (doesn't seem necessary for this type of issue, just take any long Java file)

### Expected behaviour

I can read the line numbers.

### Actual behaviour

I can't read the line numbers, as the numbers go out of the left margin of the browser window. Note that this generated Java file has 100K+ lines.

Screenshot:

![image](https://user-images.githubusercontent.com/375606/135903141-7992909a-9350-4548-baae-4bc90181ce31.png)

**Comment by marchof** [comment]
I would accept this as a known limitation.

- When you care about code coverage you should write your code in testable units (a 100K+ source file is definitely not)
- Your snippet seems to be generated. What is the point of white-box testing generated code? Rather test the generator.
