### ISSUE TITLE
[Question]Jacoco cannot cover  classname and function name line

### ISSUE THREAD

**Issue by chen-s-f** [jacoco/jacoco#1236]
I add Jacoco to my project. After ut task finished ,i find  the line ( class name and function name) can not be covered I know the case: if class don't have construct function, system use default construct function,it can not cover the line of class name .
Can you give me any other  case , the problem appears.
     
        Thank you very much !

**Comment by zhaolijunstar** [comment]
关闭了是啥意思

**Comment by zhaolijunstar** [comment]
how to solve this problem？
