### ISSUE TITLE
JaCoCo (Gradle) fails when .zargo files in main / test resources

### ISSUE THREAD

**Issue by thahnen** [jacoco/jacoco#1257]
### Steps to reproduce

* JaCoCo version:  0.8.8
* Operating system: Windows Server 2019
* Tool integration: Gradle 7.2 (which uses Ant underneath - I assume then I am at the right issue tracker)
* Complete executable reproducer: private company repository
* Steps: running *jacocoReport* task after *test* task and prior to *sonarqube* task

### Expected behaviour

JaCoCo works correctly, ignoring the resource file.

### Actual behaviour

JaCoCo fails with exceptions - mainly the one below: "error creating report".
I saw one different message regarding some "unexpected end of file" (this is not the actual error message - i didn't save it sadly).

![InkedJaCoCo-Failure-zargo-files](https://user-images.githubusercontent.com/6588381/142452644-0a94a45a-4de5-4ea0-8283-8539c333cfbb.jpg)

When *.zargo* files are removed / ignored JaCoCo works flawlesly!

**Comment by marchof** [comment]
Can you please provide the full stack trace as indicated in the error message of your screen shot?

**Comment by thahnen** [comment]
Sure, here you go. Everything marked with *\<blacked by thahnen>* was obviously done by me. Project name is simple and path down below does exist. Only left you the information showing that the *.zargo* file is located in $buildDir as a main resource.

[JaCoCo-Stacktrace.txt](https://github.com/jacoco/jacoco/files/7565764/JaCoCo-Stacktrace.txt)

If you need more information - hit me up ;)

**Comment by marchof** [comment]
Here is the problem:

Caused by: java.util.zip.ZipException: invalid entry size (expected 512 but got 515 bytes)
	at org.jacoco.core.analysis.Analyzer.nextEntry(Analyzer.java:273)
	... 169 more

Looks the .zargo is a broken ZIP file. Or it has a ZIP signature but is in fact not a ZIP file. By design JaCoCo uses file signatures to determine content types.

As a workaround please exclude those file types in your build configuration.

**Comment by thahnen** [comment]
Ah - the *.zargo* file is correct (not a ZIP archive) but seems to have such a signature. Din't know this until now 😄 
But thanks for your LIGHTNING FAST help, we'll exclude them from now on.
