### ISSUE TITLE
JaCoCo maven plugin not covering test for spring boot appplication

### ISSUE THREAD

**Issue by ppb1984** [jacoco/jacoco#1260]
I have below method in my springboot application class, which fetch data from DB

```
public void load(){ 
  Optional<List<Employee>> employee = employeeRepository.findEmployee();
  // Some other code with employee data
}
```

I am writing some Junit 4 Test case for this method and also counting coverage with Jacoco plugin.

```
@RunWith(MockitoJUnitRunner.class)
public class EmployeeTest{

  private EmployeeRepository employeeRepository = Mockito.spy(EmployeeRepository.class);

  @Test
  public void shouldLoadDataFromDB(){
    EmployeeService employeeService = new EmployeeService(employeeRepository);
    when(employeeRepository.findEmployee()).thenReturn(buildDataFromDB());
    employeeService.load();
    // Assertions
  }
}
```

For above I am always getting code coverage 0 even though I have covered test for given method,also shows method is not not covered in test.

I have check in jacoco-session.html file, I don't see my classes there. 

Can someone give some idea what am I missing here.

**Comment by marchof** [comment]
With Mockito spy you modify your class under test. This is not supported by JaCoCo.

**Comment by Godin** [comment]
@marchof FYI as far as I know and can see/demonstrate on the following example similar to the above, JaCoCo works fine with Mockito spy - [example.zip](https://github.com/jacoco/jacoco/files/7653984/example.zip)

it contains `src/main/java/org/example/Repository.java`

```
package org.example;

public class Repository {
  public String mocked() {
    return "original mocked";
  }

  public String nonMocked() {
    return "original non mocked";
  }
}
```

`src/main/java/org/example/Service.java`

```
package org.example;

public class Service {
  private Repository repository;

  public Service(Repository repository) {
    this.repository = repository;
  }

  public void load() {
    System.out.println(repository.mocked());
    System.out.println(repository.nonMocked());
  }
}
```

and `src/test/java/org/example/ExampleTest.java`

```
package org.example;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.class)
public class ExampleTest {
  private Repository repository = Mockito.spy(Repository.class);

  @Test
  public void test() {
    Service service = new Service(repository);
    Mockito.doReturn("mocked").when(repository).mocked();
    service.load();
  }
}
```

execution of

```
mvn verify
```

prints

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.example.ExampleTest
mocked
original non mocked
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.63 sec
```

and produces following report

<img width="987" alt="Screenshot 2021-12-04 at 14 01 29" src="https://user-images.githubusercontent.com/138671/144710391-8f1fbc87-d40c-4606-91f4-3d32a9e24a46.png">
<img width="987" alt="Screenshot 2021-12-04 at 14 01 41" src="https://user-images.githubusercontent.com/138671/144710394-0b241072-aab9-4c08-ac91-e0adae396b59.png">

as IMO expected.

Therefore I would say that to investigate this issue complete executable reproducer is missing here, so I'll anyway keep this ticket in closed state.

@ppb1984 can reopen when you'll provide **complete example**.
