### ISSUE TITLE
Method that only throws exception causes method be considered uncovered by the analyser

### ISSUE THREAD

**Issue by mumia** [jacoco/jacoco#1261]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling bug report!

### Steps to reproduce

* JaCoCo version: 0.8.6.202009150832
* Operating system: CentOS Linux release 7.6.1810 (Core) (running in Docker)
* Tool integration: Gradle / Spring boot / API
* Complete executable reproducer: private GitHub repo
* Steps: running the Gradle `check` task

### Expected behaviour
Having this class:
```
package com.company.mediator.adapters.in.requests;

import java.util.regex.Pattern;
import lombok.Getter;

@Getter
public final class RequestedBrand {
  private static final Pattern validationPattern = Pattern.compile("^[a-z\\-_]+$");

  private final String brand;

  public RequestedBrand(String brand) {
    if (brand == null) {
      throwValidationError();
    }

    if (brand.isBlank() || !validationPattern.matcher(brand).find()) {
      throwValidationError();
    }

    this.brand = brand;
  }

  private void throwValidationError() {
    throw new IllegalArgumentException("Invalid brand supplied");
  }
}
```

With these tests:
```
  @ParameterizedTest
  @ValueSource(strings = {"brand", "other-brand", "another_brand"})
  void requestedBrandSuccess(String brandValue) {
    assertThat(new RequestedBrand(brandValue).getBrand()).isEqualTo(brandValue);
  }

  @ParameterizedTest
  @NullAndEmptySource
  @ValueSource(strings = {"  ", "Brand", "brand name", "brand_Name"})
  void requestedBrandFailure(String invalidBrandValue) {
    assertThrows(
        IllegalArgumentException.class,
        () -> {
          new RequestedBrand(invalidBrandValue);
        }
    );
  }
```

We get:
```
> Task :mediator:jacocoTestCoverageVerification FAILED
[ant:jacocoReport] Rule violated for class com.company.mediator.adapters.in.requests.RequestedBrand: lines covered ratio is 0.7, but expected minimum is 0.8
```

### Actual behaviour

Being that the test actually fully test the class I would expect more that 0.8 coverage.
In reality the method calls `throwValidationError();` are shown as not covered in the report.

I did some testing and figured out that is has to do with the fact that the exception is thrown inside the method.

Being that the method's intent is only to abstract the exception, I would expect all calls to it to be considered covered be the analyser.

![Screenshot 2021-12-03 at 17 22 13](https://user-images.githubusercontent.com/1116065/144636743-c9f4b890-f86c-4754-8757-cefdf701ab6c.png)

**Comment by marchof** [comment]
This is a known limitation, please see [FAQ](https://www.jacoco.org/jacoco/trunk/doc/faq.html):

### Source code lines with exceptions show no coverage. Why?

JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding lines of source code are not marked as covered.
