### ISSUE TITLE
Optionally allow ignoring types of classes marked @Deprecated in code coverage

### ISSUE THREAD

**Issue by sroughley** [jacoco/jacoco#1262]
In a similar manner to the ability to ignore types and methods annotated with annotations containing the word `Generated`, an optional filter to allow ignoring types or methods annotated with the `java.lang.@Deprecated` annotation would be extremely helpful

Thanks!

Steve

**Comment by marchof** [comment]
Hi @sroughley, for a couple of reasons we decided not to offer configuration options for filtering:

- More config options makes testing more difficult (consider all combinations)
- It is harder for us to analyze problems reported by users
- We have many 3rd party integrations which needs to be extended & documented for every new option

Given the limited resources we can spent here I hope for your understanding!

My very personal view on your requirement: Deprecated code should also be tested or it should be removed. Running untested code in production is not an option.

**Comment by sroughley** [comment]
Hi @marchof  - yes, that makes sense.

Largely I tend to agree regarded the testing of @Deprecated code, and I think in this case it could _almost certainly_ be removed safely as it has been deprecated for a number of years now.  (As it's in an Eclipse plugin, I guess alternatively if I _really_ dont want to remove it, test it, or report it then I suppose I could push it down into a fragment)  Technical debt...!
