### ISSUE TITLE
Android: Setting testCoverageEnabled to true in library module results in near-empty .exec file for unit tests

### ISSUE THREAD

**Issue by Aidan128** [jacoco/jacoco#1265]
### Issue
If I set testCoverageEnabled to true in the build.gradle for a library module in a multi-module Android project, then the .exec file generated for running unit tests is nearly empty, and any reports generated from it will show 0% code coverage.

Setting testCoverageEnabled to false results in a much larger .exec file that displays the proper coverage in generated reports. (however, testCoverageEnabled is required so that I can use these binaries to gather coverage numbers for on-device instrumentation tests)

### Environment

* JaCoCo version:  0.8.7
* Operating system: MacOS 11.6 (Big Sur)
* Tool integration: Gradle
* Complete executable reproducer: https://github.com/Aidan128/JacocoFailureExample

### Steps
1. Create multi-module Android application
2. In build.gradle for both the application module and a library module, add
```
plugins {
   ...
   id 'jacoco'
}

jacoco {
    toolVersion '0.8.7'
}
```
3.  From the command line, navigate into each module and execute
```
../gradlew clean testDebugUnitTest
```
4. Note that the generated .exec files for each module (`build/jacoco/testDebugUnitTest.exec`) are each ~27k in size.
5. Now add the additional content to each module's build.gradle
```
android {
    ...
    buildTypes {
        debug {
            testCoverageEnabled true
        }
       ...
    }
}
```
6.  Again, from the command line, navigate into each module and execute
```
../gradlew clean testDebugUnitTest
```
7. Note that the generated .exec file for the application module (`build/outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec`) is still ~27k in size, but the generated .exec file for the library module (`build/outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec`) is only 45 bytes long.
8. Finally, in each module's build.gradle, set `testCoverageEnabled` to `false`.
9. From the command line, navigate into each module and execute
```
../gradlew clean testDebugUnitTest
```
10. Note that the generated .exec files for each module (`build/jacoco/testDebugUnitTest.exec`) are again each ~27k in size.

**Comment by Godin** [comment]
Integration with Android is not developed by us, but by developers of Android SDK - https://developer.android.com/studio/report-bugs#build-bugs

**Comment by Aidan128** [comment]
Got it, thanks. Tracked in https://issuetracker.google.com/issues/210500600.
