### ISSUE TITLE
script.jacoco() in groovy code takes all the code even generated one in jenkins

### ISSUE THREAD

**Issue by Sadashiv** [jacoco/jacoco#1268]
script.jacoco() groovy code in pipeline displays code coverage
which contains even for generated code how we can exclude the below class for exclusion
**/generated/** ,**/protobuf/** via script.jacoco()

Please help on this

**Comment by marchof** [comment]
No idea what you're talking about without any context information provided. This are the 3rd party integrations we're aware of. Please contact the respective project.

https://www.jacoco.org/jacoco/trunk/doc/integrations.html
