### ISSUE TITLE
Tcpserver total probe count request

### ISSUE THREAD

**Issue by svdbtno** [jacoco/jacoco#1270]
### Scenario

* Operating system: Ubuntu 20.04
* Tool integration: CLI javaagent
* Description of your use case:
Run the jacoco java agent with the tcpserver to obtain the probes that are being hit. A list with the class id, name and a boolean array is received over the java agent which gives information on which classes and probes as being hit. One important thing to note is that this tcpserver might be setup by a third party, therefore access to the jar file would not be possible.
### Wanted Behaviour
A coverage percentage needs to be given when the application is receiving load. To be able to calculate the coverage percentage the total probe count is needed. Would it be possible to receive this information from the tcpserver?

### Possible Workarounds
-

**Comment by marchof** [comment]
This is not possible. The Java agent only sees the classes which are actually loaded. To create a coverage report you need all classes.
