### ISSUE TITLE
Expose the CLI via the ToolProvider SPI

### ISSUE THREAD

**Issue by bowbahdoe** [jacoco/jacoco#1273]
### Scenario

If I am writing a build script and my usage scenario does not exceed the cases supported by the cli, it would be convenient to use that functionality directly.

### Current Behaviour
Have to either make the cli available on the path outside of my build tool or deal with the direct java api.

### Wanted Behaviour
I can obtain and run an object which provides all the capabilities of the cli via

```java
ToolProvider.findFirst("jacoco").orElseThrow();
```

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/spi/ToolProvider.html

### Possible Workarounds
- Shell out to the CLI
- Use the jacoco classes directly

**Comment by marchof** [comment]
Nice idea! Unfortunately JaCoCo's baseline is currently Java 5. `java.util.spi.ToolProvider` is available since Java 9.

So probably not something we will implement soon. Maybe nice idea for someone to implement a tool provider adapter for users using >= java 9?

**Comment by bowbahdoe** [comment]
You could do it via a multi-release jar

**Comment by marchof** [comment]
Yes, it's theoretically possible... but we have probably no resources to create and maintain a multi-release JAR build.

**Comment by bowbahdoe** [comment]
This might be out of scope for what issues are for, but can you provide some color on what resources are available / who maintains the code base?

I ask because I can help to create the MR jar, but if maintenance afterwards is a concern I can just publish a separate repo.

(The way the CLI is structured right now is 99.99% there for implementing the interface, so all of the work would just be with the build)

**Comment by marchof** [comment]
> what resources are available / who maintains the code base

JaCoCo is a spare time project of @marchof and @Godin, see [contributors](https://github.com/jacoco/jacoco/graphs/contributors).

> if maintenance afterwards is a concern

This is THE main concern. In the meantime we collected too many features to maintain and support them. Therefore we decided to focus on the core coverage engine and hope that tool integrations (Maven, Ant, CLI, ...) will be picked up by other people one day. Especially Maven is so opiniated and at the same time limited for example in the case of integration tests that we have too many exhausting discussions how to do it "right".

> just publish a separate repo

As shown above a CLI tool maintained by a separate project would be my preference.

> all of the work would just be with the build

Just keep in mind that "just the build" currently already is a [matrix](https://dev.azure.com/jacoco-org/JaCoCo/_build/latest?definitionId=1&branchName=master) of 15 different JDK versions.

But please fee free to share ideas or even demonstrate them in a pull request. There are actually other places where it would be nice to use use different API versions.
