### ISSUE TITLE
Jacoco jobs are SKIPPED

### ISSUE THREAD

**Issue by IlyasNN** [jacoco/jacoco#1274]
Mac M1
Gradle JDK: 11

Gitlab project https://gitlab.com/IlyasNN/HarmanWeatherApp

Kotlin Multiplatform Mobile

<img width="717" alt="Screenshot 2022-01-19 at 00 10 09" src="https://user-images.githubusercontent.com/50013971/150021548-565434d7-13e0-47fc-a022-0cd7fbb91571.png">

Gradle file of project:

`import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

val ktorVersion = "1.6.0"
val coroutineVersion = "1.4.3"

plugins {
    kotlin("multiplatform")
    kotlin("native.cocoapods")
    kotlin("plugin.serialization") version "1.6.0"
    id("com.android.library")
    id("io.realm.kotlin") version "0.7.0"
    jacoco
}

jacoco {
    toolVersion = "0.8.6"
}

jacoco {
    toolVersion = "0.8.6"
    reportsDirectory.set(layout.buildDirectory.dir("jacoco"))
}

val jacocoTestReport by tasks.creating(JacocoReport::class.java) {

    val coverageSourceDirs = arrayOf(
        "src/commonMain"
    )
    val classFiles = File("${buildDir}/classes/kotlin/jvm/")
        .walkBottomUp()
        .toSet()
    classDirectories.setFrom(classFiles)
    sourceDirectories.setFrom(files(coverageSourceDirs))

    executionData.setFrom(files("${buildDir}/jacoco/testDebugUnitTests.exec"))
    reports {
        xml.isEnabled = true
        csv.isEnabled = false
        html.isEnabled = true
    }
}

tasks.withType<Test> {
    finalizedBy(testCoverage)
}

val jacocoTestCoverageVerification by tasks.creating(JacocoCoverageVerification::class.java) {
    dependsOn(jacocoTestReport)
    violationRules {
        rule {
            limit {
                minimum = "0.8".toBigDecimal()
            }
        }
    }
}

val testCoverage by tasks.registering {
    group = "verification"
    description = "Runs the unit tests with coverage."

    dependsOn("test", jacocoTestReport, jacocoTestCoverageVerification)
    tasks["jacocoTestReport"].mustRunAfter("test")
    tasks["jacocoTestCoverageVerification"].mustRunAfter("jacocoTestReport")
}

version = "1.0"

kotlin {
    android()

    val iosTarget: (String, KotlinNativeTarget.() -> Unit) -> KotlinNativeTarget = when {
        System.getenv("SDK_NAME")?.startsWith("iphoneos") == true -> ::iosArm64
//        System.getenv("NATIVE_ARCH")?.startsWith("arm") == true -> ::iosSimulatorArm64
        else -> ::iosX64
    }

    iosTarget("ios") {}

    cocoapods {
        summary = "Some description for the Shared Module"
        homepage = "Link to the Shared Module homepage"
        ios.deploymentTarget = "14.1"
        frameworkName = "MultiPlatformLibrary"
        podfile = project.file("../iosApp/Podfile")
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                api("org.jetbrains.kotlin:kotlin-stdlib-common")
                api("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutineVersion-native-mt")
                api("io.ktor:ktor-client-core:$ktorVersion")
                api("io.ktor:ktor-client-logging:$ktorVersion")
                api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.0")
                api("io.realm.kotlin:library-base:0.7.0")

                api("dev.icerock.moko:mvvm-core:0.11.0") // only ViewModel, EventsDispatcher, Dispatchers.UI
                api("dev.icerock.moko:mvvm-livedata:0.11.0") // api mvvm-core, LiveData and extensions
                api("dev.icerock.moko:mvvm-state:0.11.0") // api mvvm-livedata, ResourceState class and extensions
                api("dev.icerock.moko:resources:0.17.2")
                api("dev.icerock.moko:permissions:0.10.2")
                api("dev.icerock.moko:geo:0.4.0")
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
                implementation(kotlin("test-junit"))
                implementation("junit:junit:4.13.2")
                implementation("io.mockk:mockk-common:1.12.1")
                implementation("io.ktor:ktor-client-mock:$ktorVersion")
                implementation("io.ktor:ktor-client-serialization:$ktorVersion")
            }
        }
        val androidMain by getting {
            dependencies {
                api("dev.icerock.moko:mvvm-livedata-material:0.11.0") // api mvvm-livedata, Material library android extensions
                api("dev.icerock.moko:mvvm-livedata-glide:0.11.0") // api mvvm-livedata, Glide library android extensions
                api("dev.icerock.moko:mvvm-livedata-swiperefresh:0.11.0") // api mvvm-livedata, SwipeRefreshLayout library android extensions
                api("dev.icerock.moko:mvvm-databinding:0.11.0") // api mvvm-livedata, DataBinding support for Android
                api("dev.icerock.moko:mvvm-viewbinding:0.11.0") // api mvvm-livedata, ViewBinding support for Android
                api("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutineVersion-native-mt")
                api("io.ktor:ktor-client-android:$ktorVersion")
            }
        }
        val androidTest by getting {
            dependencies {
                implementation(kotlin("test-junit"))
                implementation("junit:junit:4.13.2")
                implementation("io.mockk:mockk:1.12.1")
            }
        }
        val iosMain by getting {
            dependencies {
                implementation("io.ktor:ktor-client-ios:$ktorVersion")
            }
        }
        val iosTest by getting
    }

    kotlin {
        // export correct artifact to use all classes of library directly from Swift
        targets.withType(org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget::class.java)
            .all {
                binaries.withType(org.jetbrains.kotlin.gradle.plugin.mpp.Framework::class.java)
                    .all {
                        export("dev.icerock.moko:mvvm-core:0.11.0")
                        export("dev.icerock.moko:mvvm-livedata:0.11.0")
                        export("dev.icerock.moko:mvvm-state:0.11.0")
                        export("dev.icerock.moko:resources:0.17.2")
                        export("dev.icerock.moko:permissions:0.10.2")
                        export("dev.icerock.moko:geo:0.4.0")
                    }
            }
    }

    kotlin {
        targets.withType<org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget> {
            binaries.all {
                freeCompilerArgs += "-Xadd-light-debug=disable"
            }
        }
    }
}

android {
    compileSdkVersion(31)
    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    defaultConfig {
        minSdkVersion(21)
        targetSdkVersion(31)
    }
}
`
May be problem is internal. If I run tests with default code coverage, I have the next problem
<img width="266" alt="Screenshot 2022-01-19 at 00 38 09" src="https://user-images.githubusercontent.com/50013971/150022747-95edf0f4-ce94-41ba-980a-3bde95b8b2e9.png">

Thank you for the future help)

**Comment by marchof** [comment]
Android and Gradle integration is not developed by the JaCoCo project. Please check with the respective projects.
