### ISSUE TITLE
Make the filtering annotation configurable

### ISSUE THREAD

**Issue by akantek** [jacoco/jacoco#1278]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling feature request!

### Scenario

* JaCoCo version: (from right bottom corner of JaCoCo report): latest
* Operating system: any
* Tool integration: Maven / Ant / CLI / API (for others please report to respective project): any
* Description of your use case: (detailed description or executable reproducer, e.g. GitHub repo): This is just a simple request to make AnnotationGeneratedFilter more flexible (see explanation below).

### Current Behaviour

To exclude code from coverage report, ones need to use any annotation containing the `Generated` string (see 
jacoco/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/AnnotationGeneratedFilter.java).

### Wanted Behaviour

Check for some system.propery (or any other sort of property) where one can define what annotation they want to use to filter code from coverage. I believe this will be a simple change in AnnotationGeneratedFilter, just check if the property is present, if so apply it instead of just checking for annotations containing the string `Generated`.

This feature is important since some teams/codebase may be using Generated for something different.

### Possible Workarounds

If adding a property is too hard, will be possible to check for annotations containing `Generated` or `Exclude` ?

**Comment by marchof** [comment]
Due to the complexity that configuration options add especially in the case of reported "bugs" we decided to not add any configuration options for filtering. I'm sorry but this is a spare time project we we need to limit the scope.

**Comment by akantek** [comment]
And how about just making AnnotationGeneratedFilter to also exclude code annotated with annotations containing `Exclude` ? This will be one line change, I can volunteer to send the patch. The change will be:

`
	private static boolean matches(final String annotation) {
		final String name = annotation
				.substring(Math.max(annotation.lastIndexOf('/'),
						annotation.lastIndexOf('$')) + 1);
		return name.contains("Generated") || name.contains("Exclude");
	}
`
Will that work ?

**Comment by Godin** [comment]
@akantek 

If by

>  some teams/codebase may be using Generated for something different

you're saying that not all annotations containing `Generated` should cause filtering, then

> And how about just making AnnotationGeneratedFilter to also exclude code annotated with annotations containing Exclude ?

this won't help.

If `org.my.company.Generated` is used for something else and you wanna another one to filter-out code from coverage reports, then you already can use for example `org.my.company.CoverageShouldNotBeGenerated`. But this annotation based filtering was developed solely for the purposes of filtering-out really generated code and not human-written. And while you can as shown above, we do not recommend abusing it for manual exclusion of human-written code - see for example reasons in https://github.com/jacoco/jacoco/pull/675#issuecomment-608075757 and https://github.com/jacoco/jacoco/issues/977

So to sum-up - sorry, but no, we don't want to expand current implementation of annotation-based filtering.
