### ISSUE TITLE
Outer IF condition is partially covered.

### ISSUE THREAD

**Issue by Manjiz** [jacoco/jacoco#1280]
### Steps to reproduce

* JaCoCo version:  0.8.6
* Operating system: MacOS
* Tool integration: Maven

### Expected behaviour

No yellow diamond.

### Actual behaviour

![image](https://user-images.githubusercontent.com/13447336/151284529-bb8f2eee-bea2-4413-b000-1195656599a0.png)

**Comment by Godin** [comment]
JaCoCo performs analysis of class files after collection of information about execution of unit tests, hence impossible to reproduce/investigate behaviour shown on screenshot without having your tests and class files - maybe you simply do not have test where `onlineAt.isEqual(beginTime)` evaluates to `true` or `false`.

**Comment by Manjiz** [comment]
> maybe you simply do not have test where onlineAt.isEqual(beginTime) evaluates to true or false

@Godin Both inner IF condition and `return false;` are marked with green color. So the both conditions are tested?

**Comment by Manjiz** [comment]
Oh, I get it! I sincerely appreciate your help.:smile:
