### ISSUE TITLE
How to merge jacoco reports of two different version - 0.7.9 and 0.8.7 of two different maven projects

### ISSUE THREAD

**Issue by mehulparmariitr** [jacoco/jacoco#1281]
I have execs report of two different jacoco plugins from two different projects - 0.7.9 and 0.8.7 version of jacoco. I want to merge and show a single report. Is it possible?

**Comment by mehulparmariitr** [comment]
I used cli with this command but it is throwing this error `no main manifest attribute, in org.jacoco.cli-0.8.7.jar`

command I used java -jar org.jacoco.cli-0.8.5.jar merge ./jacoco7.exec ./jacoco8.exec --destfile ./merged.exec

**Comment by Godin** [comment]
> it is throwing this error no main manifest attribute, in org.jacoco.cli-0.8.7.jar

Because you're using wrong JAR:

in Maven Central repository [correct one has **classifier `nodeps`**](https://repo1.maven.org/maven2/org/jacoco/org.jacoco.cli/0.8.7/org.jacoco.cli-0.8.7-nodeps.jar) - see https://www.jacoco.org/jacoco/trunk/doc/repo.html

exactly the same JAR inside [JaCoCo zip-distribution](https://repo1.maven.org/maven2/org/jacoco/jacoco/0.8.7/jacoco-0.8.7.zip) has name `jacococli.jar`

**Comment by mehulparmariitr** [comment]
I think I missed something here. Exec files alone will not help me in generating merged reports of two different version of jacoco. Class files also need to be merged?

**Comment by Godin** [comment]
Let's say that you have 
`project1/jacoco.exec`
`project2/jacoco.exec`
and following directories
`project1/src` - source files of first project
`project1/classes` - class files of first project
`project2/src` - source files of second project
`project2/classes` - class files of second project

then execution of

```
java -jar jacococli.jar report project1/jacoco.exec project2/jacoco.exec --classfiles project1/classes --classfiles project2/classes --sourcefiles project1/src --sourcefiles project2/src --html report
```

will produce report containing information from exec files, source files and class files of both projects in directory `report`

**Comment by mehulparmariitr** [comment]
Is there any api also to do these operations?

**Comment by Godin** [comment]
> jacoco is backwards compatible

Newer JaCoCo versions can read exec files produced by older versions **only if they are compatible** - the last change of exec file format was in version `0.7.5`, so JaCoCo versions `0.7.6` and greater can't read exec files produced by version `0.7.5` and lower, while for example JaCoCo version `0.8.7` can read exec files produced by versions from `0.7.6` to `0.8.7`. 

> Is there any api also to do these operations?

Please read the documentation - https://www.jacoco.org/jacoco/trunk/doc/ !

**Comment by mehulparmariitr** [comment]
is there any way using which we can merge `0.7.4.201502262128` and the latest `0.8.7 `? Thanks for your help.

**Comment by Godin** [comment]
> is there any way using which we can merge 0.7.4.201502262128 and the latest 0.8.7 ?

No, as I already said earlier - format of exec file was changed in version `0.7.5` in incompatible way.

**Comment by Godin** [comment]
You'd better upgrade projects that still use `0.7.4` to newer version - update is a good practice in general.

**Comment by mehulparmariitr** [comment]
Yes I understand. But there are some older reports which used 0.7.4, for that I was thinking if we could do something to merge them with new reports. Not directly through the cli but through code or through a manual process?

**Comment by marchof** [comment]
@mehulparmariitr Basically the way how we insert probes has been reworked. You can trust @Godin, there is no way to merge incompatible exec files.

You can write your own tooling to merge generated reports, e.g. xml reports. But there is now built-in support for this in JaCoCo.

**Comment by mehulparmariitr** [comment]
@marchof So you are saying jacoco supports merging of XML supports now and that can merge 0.7.4 and 0.8.7 reports? Can you please share the command.

**Comment by marchof** [comment]
@mehulparmariitr Sorry for the typo: I wanted to say there is NO support for this.

**Comment by mehulparmariitr** [comment]
I noticed even 0.7.5 is compatible with latest version.

**Comment by Godin** [comment]
> I noticed even 0.7.5 is compatible with latest version.

That's true - in https://github.com/jacoco/jacoco/issues/1281#issuecomment-1024153424

> the last change of exec file format was in version 0.7.5,

is correct, however made typo after it, here is correction

> so JaCoCo versions ~~`0.7.6`~~ `0.7.5` and greater can't read exec files produced by version ~~`0.7.5`~~ `0.7.4` and lower, while for example JaCoCo version `0.8.7` can read exec files produced by versions from ~~`0.7.6`~~ `0.7.5` to `0.8.7`.

----

> Yes I understand. But there are some older reports which used 0.7.4, for that I was thinking if we could do something to merge them with new reports. Not directly through the cli but through code or through a manual process?

We do not provide such way.

It was not a mere structural change of "format", but an absolutely "incompatible" change of stored data - in exec files of versions `0.7.4` and lower **there is simply not enough data** to feed algorithms of versions `0.7.5` and upper.

So we did not and will not be hacking around this, so **will not consult you on this subject further** than what was already said here.

Please believe me that much simpler to **upgrade JaCoCo version in projects that still use 7 years-old version `0.7.4`**.

> Or if I can know what exactly changed in the format?

Feel free to figure out exact details by yourself - [all the code and changes are publicly available](https://github.com/jacoco/jacoco) in this repository.
