### ISSUE TITLE
Add current version of the jacoco maven plug-in on www.eclemma.org/jacoco/trunk/doc/maven.html

### ISSUE THREAD

**Issue by iachelini** [jacoco/jacoco#1284]
### Scenario
* Operating system: all
* Tool integration: Maven
* Type "jacoco-maven-plugin" on google.com
* https://www.eclemma.org/jacoco/trunk/doc/maven.html should come up and open it
* open page and look for current version

### Current Behaviour
* current release version is nowhere found
* current SNAPSHOT version can be found in "Usage" section

### Wanted Behaviour
* Similar to apache maven plugin documentation pages current release is on top of page

### Possible Workarounds
* Leave page and open https://search.maven.org/search?q=g:org.jacoco%20a:jacoco-maven-plugin

**Comment by marchof** [comment]
Hi @iachelini,

the current version is on the main page: https://www.jacoco.org/jacoco/

Everything under https://www.jacoco.org/jacoco/trunk/ is the latest snapshot build from master. We actually don't have JaCoCo documentation of the latest release(s).

Probably we should publish documentation for releases, too (including a "latest" alias).

**Comment by iachelini** [comment]
I understand. Thanks for taking the time.
