### ISSUE TITLE
Jacoco still reports coverage for child classes where parent class annotated with @Generated

### ISSUE THREAD

**Issue by jazzman1968** [jacoco/jacoco#1286]
Using Jacoco version 0.8.7 I have the following annotation:

@Inherited
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface GeneratedCodeCoverageExclusion {}

I add this to an abstract base class and I can see the annotation is detected through reflection on child classes but Jacoco only skips coverage of the base class, not the child classes

**Comment by marchof** [comment]
This is exactly how JaCoCo works: Classes are analyzed independently from each other. There is no inheritance semantic for code exclusion.
