### ISSUE TITLE
Android "viewModelScope.launch" block not fully covered for Kotlin 1.6.10

### ISSUE THREAD

**Issue by AnneJ17** [jacoco/jacoco#1290]
### Steps to reproduce

* JaCoCo version:  0.8.7
* Operating system: MacOS
* Steps: When using Jacoco tool for reporting code coverage in my Android project with Kotlin version of `1.6.10`, the Jacoco reports for viewModelScope.launch { ... } block is always **NOT fully covered**.

### Expected behaviour
`viewModelScope.launch { ... }` should be marked as fully covered by jacoco for Kotlin 1.6.10.

### Actual behaviour
The report says 2 of 3 branches missed for `viewModelScope.launch { ... }` block.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/48440224/155369389-bb831494-24c4-4ba7-98e3-27041bead6de.png">

**Comment by Godin** [comment]
> with Kotlin version of `1.6.10`

Do you get the same result with other versions? e.g. with `1.4.10` or `1.5.32`?

> JaCoCo version: 0.8.7

Are you sure? How we can verify this?

Because of closed long time ago #1126 and #1123 we have to ask all those questions in the absence of reproducer from you.

And in any case JaCoCo performs analysis of bytecode, so we can't investigate this without looking at your class files - please provide at least them.

**Comment by AnneJ17** [comment]
@Godin I get the same result with `1.4.10` and `1.5.32` using JaCoCo version `0.8.7`. I have attached both class file and the bytecode of the class below. Please let me know if there is any additional information that you may require.

[GoalDetailsViewModel.class.zip](https://github.com/jacoco/jacoco/files/8134953/GoalDetailsViewModel.class.zip)
[bytecode.txt](https://github.com/jacoco/jacoco/files/8134928/bytecode.txt)

**Comment by Godin** [comment]
> I get the same result with 1.4.10 and 1.5.32 using JaCoCo version 0.8.7

Same as before - we can't verify correctness of this statement without complete reproducer / access to your project.

> I have attached both class file and the bytecode of the class below

`{ ... }` in your `viewModelScope.launch { ... }` is lambda, so it's bytecode is not stored in `GoalDetailsViewModel.class` file but in another one next to it, so please provide **all class-files**.

**Comment by AnneJ17** [comment]
@Godin 
[GoalDetailsFragment.class.zip](https://github.com/jacoco/jacoco/files/8135277/GoalDetailsFragment.class.zip)
Sorry about that. In this class is where that function that launches is invoked. This is a huge project, so I will try my best to give you the files that will help you to find the issue. Thank you for your patience and understanding.

**Comment by Godin** [comment]
> [bytecode.txt](https://github.com/jacoco/jacoco/files/8136481/bytecode.txt)
> [GoalDetailsFragment.class.zip](https://github.com/jacoco/jacoco/files/8135277/GoalDetailsFragment.class.zip)
> Sorry about that. In this class is where that function that launches the coroutine is invoked.

No this is not what is needed for investigations and not what was requested.

> This is a huge project, so I will try my best to give you the files that will help you to find the issue. Thank you in advance. Please let me know if this won't work, I can create a sample project mimicking this scenario.

Either simply provide **all class files** as was requested,
or if simpler for you - indeed create a small one from scratch to demonstrate the same problem.

**Comment by Godin** [comment]
> here is the link to the [repo](https://github.com/AnneJ17/jacoco-miss-launch) that reproduces this scenario.

Even not taking into account that you don't provide description of steps to compile this project, it doesn't look like anyone other than you can easily build this project without modifications - here is what I tried

```
git clone https://github.com/AnneJ17/jacoco-miss-launch
cd jacoco-miss-launch

docker run --rm -v `pwd`:/project mingc/android-build-box bash -c 'cd /project; ./gradlew :coroutinelaunch:assembleDebug'
```

and it failed as following

```
* What went wrong:
Execution failed for task ':coroutinelaunch:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':coroutinelaunch:debugCompileClasspath'.
   > Could not resolve androidx.databinding:viewbinding:7.0.4.
     Required by:
         project :coroutinelaunch
      > Could not resolve androidx.databinding:viewbinding:7.0.4.
         > Could not parse POM https://jfrog.info53.com/artifactory/fitb-development-virtual/androidx/databinding/viewbinding/7.0.4/viewbinding-7.0.4.pom
```

So please either make it buildable by others,
or provide all compiled class files - build this project by yourself and simply commit all produced files and reports into the repository.

**Comment by AnneJ17** [comment]
> Even not taking into account that you don't provide description of steps to compile this project, it doesn't look like anyone other than you can easily build this project without modifications - here is what I tried

My sincere apologies. Can you please kindly clone the repo once again? I have also updated the README.md to include the steps to get the Jacoco report.

**Comment by Godin** [comment]
> included the steps

After following your steps

```
git clone https://github.com/AnneJ17/jacoco-miss-launch
cd jacoco-miss-launch
./gradlew ":coroutinelaunch:jacocoDebugTestReport"
open coroutinelaunch/build/reports/jacoco/jacocoDebugTestReport/html/index.html
```

you can see following report

<img width="1607" alt="Screenshot 2022-03-04 at 01 19 56" src="https://user-images.githubusercontent.com/138671/156675309-bec5aacc-da17-4dd9-be65-53ba62f28d44.png">

please pay attention on the JaCoCo version at the right bottom corner of the report,
so as was suspected from the beginning in https://github.com/jacoco/jacoco/issues/1290#issuecomment-1050075689
to generate report you actually use JaCoCo version `0.8.6` and not `0.8.7` as you claimed.

After following modification of your `coroutinelaunch/jacoco.gradle`

```diff
 apply plugin: 'jacoco'
+jacoco.toolVersion = "0.8.7"
```

and execution

```
./gradlew ":coroutinelaunch:jacocoDebugTestReport"
open coroutinelaunch/build/reports/jacoco/jacocoDebugTestReport/html/index.html
```

report is

<img width="1598" alt="Screenshot 2022-03-04 at 01 25 41" src="https://user-images.githubusercontent.com/138671/156675988-0d1c1c48-97f3-476f-8853-0443aa2a7fae.png">

And so btw I highly suspect that statement about Kotlin version

> I get the same result with 1.4.10

was not true also.

**Comment by JEMoralesD** [comment]
I am having the same issue on jacoco 0.8.7 with kotlin 1.6.10.

In my report there are two similar methods with a unit test that does practically the same, the only difference is that one updates a `MutableSharedFlow` while the one that is reported as partially covered is a `MutableStateFlow`

![jacoco](https://user-images.githubusercontent.com/45465347/160886677-328aa0e9-3eb3-4f81-904c-cefaa72ea8c5.jpg)

Btw in my case the dispatchers only provide the default android kotlin dispatchers 
`class DefaultDispatchers: DispatcherProvider
{
    override val main: CoroutineDispatcher
        get() = Dispatchers.Main
    override val io: CoroutineDispatcher
        get() = Dispatchers.IO
    override val default: CoroutineDispatcher
        get() = Dispatchers.Default
}`

And I am using the Turbine package to create the unit tests for this corroutine scopes

**Comment by Godin** [comment]
@JEMoralesD 

> I am having the same issue

**You can't have exactly the same** issue, because from your screenshot seems that you use JaCoCo 0.8.7 whereas issue discussed here was due to use of JaCoCo 0.8.6 instead of 0.8.7. 

So if you believe that something is still not working properly with 0.8.7, then please first create complete executable reproducer that others can try, and then share it with us by creating new ticket.
