### ISSUE TITLE
Whitelist and exclude files while analysing

### ISSUE THREAD

**Issue by kvallish** [jacoco/jacoco#1293]
### Scenario

* JaCoCo version: 0.8.8.202203110758
* Operating system: Ubuntu
* Tool integration: Maven / Ant / CLI / API (for others please report to respective project)
* Description of your use case: (detailed description or executable reproducer, e.g. GitHub repo)
Need a way to whitelist only my organisation's packages for code coverage and exclude some patterns of classes (like DTOs)

### Current Behaviour
Cannot exclude classes and patterns from report. 
### Possible Workarounds
Remove the unwanted classes from the jar file manually before passing it to the report generator.

**Comment by marchof** [comment]
There is a `includes` (whitelist) and `excludes` configuration option for the Ant task and Maven goal, see documentation:

https://www.jacoco.org/jacoco/trunk/doc/report-mojo.html

**Comment by kvallish** [comment]
We need this in the Analyzer class since we have written a service to automatically dump code coverage information and feed the JAR file to the analyzer for analysis.

**Comment by marchof** [comment]
In this case you need to do the filtering yourself and directly feed the classes which match your rules. There is an API to add individual classes to the Analyzer: `analyzeClass(final InputStream input, final String location)`

https://github.com/jacoco/jacoco/blob/v0.8.7/org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java#L149
