### ISSUE TITLE
Execution jacoco-merge of goal org.jacoco:jacoco-maven-plugin:0.8.7:merge failed: Incompatible execution data for class org/dmfs/rfc3986/validation/CharSets with id 65a4721848375d26

### ISSUE THREAD

**Issue by kaoh** [jacoco/jacoco#1294]
Any ideas what can cause this?

### Steps to reproduce

* JaCoCo version:  0.8.7
* Operating system: Linux Ubuntu 20.04
* Tool integration: Maven, Java 11
* Complete executable reproducer: I cannot share the jacoco files, it is closed source.
* Steps: Merging unit with integration tests

### Expected behaviour

Files are merged.

### Actual behaviour

[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.7:merge (jacoco-merge) on project smdp-server: Execution jacoco-merge of goal org.jacoco:jacoco-maven-plugin:0.8.7:merge failed: Incompatible execution data for class org/dmfs/rfc3986/validation/CharSets with id 65a4721848375d26

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  1.223 s
> [INFO] Finished at: 2022-03-22T15:16:51+01:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.7:merge (jacoco-merge) on project foobar: Execution jacoco-merge of goal org.jacoco:jacoco-maven-plugin:0.8.7:merge failed: Incompatible execution data for class org/dmfs/rfc3986/validation/CharSets with id 65a4721848375d26. -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.7:merge (jacoco-merge) on project foobar: Execution jacoco-merge of goal org.jacoco:jacoco-maven-plugin:0.8.7:merge failed: Incompatible execution data for class org/dmfs/rfc3986/validation/CharSets with id 65a4721848375d26.
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:566)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> Caused by: org.apache.maven.plugin.PluginExecutionException: Execution jacoco-merge of goal org.jacoco:jacoco-maven-plugin:0.8.7:merge failed: Incompatible execution data for class org/dmfs/rfc3986/validation/CharSets with id 65a4721848375d26.
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:566)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> Caused by: java.lang.IllegalStateException: Incompatible execution data for class org/dmfs/rfc3986/validation/CharSets with id 65a4721848375d26.
>     at org.jacoco.core.data.ExecutionData.assertCompatibility (ExecutionData.java:197)
>     at org.jacoco.core.data.ExecutionData.merge (ExecutionData.java:160)
>     at org.jacoco.core.data.ExecutionData.merge (ExecutionData.java:133)
>     at org.jacoco.core.data.ExecutionDataStore.put (ExecutionDataStore.java:55)
>     at org.jacoco.core.data.ExecutionDataStore.visitClassExecution (ExecutionDataStore.java:178)
>     at org.jacoco.core.data.ExecutionDataReader.readExecutionData (ExecutionDataReader.java:151)
>     at org.jacoco.core.data.ExecutionDataReader.readBlock (ExecutionDataReader.java:116)
>     at org.jacoco.core.data.ExecutionDataReader.read (ExecutionDataReader.java:93)
>     at org.jacoco.core.tools.ExecFileLoader.load (ExecFileLoader.java:60)
>     at org.jacoco.core.tools.ExecFileLoader.load (ExecFileLoader.java:74)
>     at org.jacoco.maven.MergeMojo.load (MergeMojo.java:101)
>     at org.jacoco.maven.MergeMojo.executeMerge (MergeMojo.java:83)
>     at org.jacoco.maven.MergeMojo.executeMojo (MergeMojo.java:69)
>     at org.jacoco.maven.AbstractJacocoMojo.execute (AbstractJacocoMojo.java:46)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:566)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> [ERROR] 
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by marchof** [comment]
Wow, that is surprising. It basically says we have a hash collision: There are two versions of the class `CharSets` with the same fingerprint but different number of probes.

But it could also mean that there is a corrupted execution data file.

Can this be reproduced when you delete all exec files before you re-run the build?

**Comment by kaoh** [comment]
Deleting the old files did solve this issue.
