### ISSUE TITLE
jacoco tcpclient mode cannot get .exec data is empty

### ISSUE THREAD

**Issue by 17396900506** [jacoco/jacoco#1298]
I'm trying to get live coverage data from jacocoagent.jar using jacoco's official example ExecutionDataServer, and I have enabled
 new RemoteControlWriter(socket.getOutputStream()).visitDumpCommand(true, false); 
but it doesn't work below is the start command and code
`public final class ExecutionDataServer {
    private static final String DESTFILE = "D:\\work\\bc\\code\\collection-center\\jacoco.exec";

    private static final String ADDRESS = "localhost";
    private static final int PORT = 6300;

    /**
     * Start the server as a standalone program.
     *
     * @param args
     * @throws IOException
     */
    public static void main(final String[] args) throws IOException {
        final ExecutionDataWriter fileWriter = new ExecutionDataWriter(new FileOutputStream(DESTFILE));
        final ServerSocket server = new ServerSocket(PORT, 0, InetAddress.getByName(ADDRESS));
        while (true) {
            final Handler handler = new Handler(server.accept(), fileWriter);
            new Thread(handler).start();
        }
    }

    private static class Handler implements Runnable, ISessionInfoVisitor, IExecutionDataVisitor {

        private final Socket socket;

        private final RemoteControlReader reader;

        private final ExecutionDataWriter fileWriter;

        Handler(final Socket socket, final ExecutionDataWriter fileWriter)
                throws IOException {
            this.socket = socket;
            this.fileWriter = fileWriter;

            // Just send a valid header:
            new RemoteControlWriter(socket.getOutputStream()).visitDumpCommand(true, false);

            reader = new RemoteControlReader(socket.getInputStream());
            reader.setSessionInfoVisitor(this);
            reader.setExecutionDataVisitor(this);
        }

        @Override
        public void run() {
            try {
                while (reader.read()) {
                }
                socket.close();
                synchronized (fileWriter) {
                    fileWriter.flush();
                }
            } catch (final IOException e) {
                e.printStackTrace();
            }
        }

        @Override
        public void visitSessionInfo(final SessionInfo info) {
            System.out.printf("Retrieving execution Data for session: %s%n",
                    info.getId());
            synchronized (fileWriter) {
                fileWriter.visitSessionInfo(info);
            }
        }

        @Override
        public void visitClassExecution(final ExecutionData data) {
            synchronized (fileWriter) {
                fileWriter.visitClassExecution(data);
            }
        }
    }

    private ExecutionDataServer() {
    }
}`
`-javaagent:D:\work\jacoco\lib\jacocoagent.jar=includes=*,output=tcpclient,address=127.0.0.1,port=6300,sessionid=test`

**Comment by marchof** [comment]
Also in `tcpclient` mode coverage data is written when the application shuts down properly. Please make sure that the JVM terminates properly.

**Comment by 17396900506** [comment]
> `tcpclient`当应用程序正确关闭时，也会写入模式覆盖数据。请确保 JVM 正确终止。

What I expect is to be able to get coverage information in real time without closing jacocoagent

**Comment by marchof** [comment]
In this case you can modify the server to send a dump command to the client when you need the data. For example the EclEmma Eclipse plug-in works this way. The user can press a button to request coverage data from a running process.

See [JavaDoc](https://www.jacoco.org/jacoco/trunk/doc/api/org/jacoco/core/runtime/RemoteControlWriter.html#visitDumpCommand(boolean,%20boolean))

**Comment by 17396900506** [comment]
> 在这种情况下，您可以修改服务器以在需要数据时向客户端发送转储命令。例如，EclEmma Eclipse 插件就是这样工作的。用户可以按下按钮从正在运行的进程中请求覆盖数据。
> 
> 请参阅[JavaDoc](https://www.jacoco.org/jacoco/trunk/doc/api/org/jacoco/core/runtime/RemoteControlWriter.html#visitDumpCommand(boolean,%20boolean))

Change the running mode of jacocoagent from tcpclient mode to tcpserver mode, yes?
