### ISSUE TITLE
Coverage report is 0% for android library modules

### ISSUE THREAD

**Issue by viveksinha121** [jacoco/jacoco#1301]
I'm trying to use jacoco for my andorid app (Android studio 4.2.1).

classpath "com.android.tools.build:gradle:4.2.1"
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31"
classpath "org.jacoco:org.jacoco.core:0.8.7"

1. Create an android project in android studio.
2. Write some test in app module 
3. Check jacoco coverage -> It is showing proper coverage
4. Create an android library module in same project.
5. Write some test in respective test directory.
6. Generate & check coverage report. -> Not coverage is 0%.
7. In same library module change plugin id from com.android.library to com.android.application. 
8. Run same test & generate coverage. -> Showing proper coverage.

### Expected behaviour
Coverage should be proper in library module also.

### Actual behaviour
Not showing coverage for library module.

**Comment by marchof** [comment]
Hi @viveksinha121, unfortunately I'm not familiar with Android Studio. How do you generate the coverage report? With Android Studio itself or do you run some build (Maven/Gradle)?

**Comment by viveksinha121** [comment]
Hi @marchof, I integrated jacoco in my android project following this: https://medium.com/nerd-for-tech/setup-jacoco-code-coverage-with-your-multimodule-android-app-kotlin-a0f82573a1.
I can also give you a sample project if needed.

**Comment by marchof** [comment]
This is a Android build. Please understand that we're not involved in the JaCoCO Grade integration nor in the Android Studio project. Please contact these projects.

https://www.jacoco.org/jacoco/trunk/doc/integrations.html
