### ISSUE TITLE
Jacoco HTML report not marker green color when the java method has been executed

### ISSUE THREAD

**Issue by hardy1213** [jacoco/jacoco#1306]
### Steps to reproduce

* JaCoCo version:  0.8.5
* Operating system: Linux
* Tool integration: Maven 
* Complete executable reproducer: Gitlab 
* Steps: (what exactly are you doing with the above reproducer?)
![image](https://user-images.githubusercontent.com/16552761/165520150-cfe05476-a8d5-4290-9ffd-3d98915d0ed7.png)

### Expected behaviour
checkCode(value) should be marker green color;

### Actual behaviour
checkCode(value)  marker red color;

(In case of exceptions provide FULL STACKTRACE)

**Comment by marchof** [comment]
If a method throws an exception its invocation cannot be marked as executed. Please see [FAQ](https://www.jacoco.org/jacoco/trunk/doc/faq.html).

> **Source code lines with exceptions show no coverage. Why?**
> 
> JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding lines of source code are not marked as covered.
