### ISSUE TITLE
Ability to capture coverage from child processes

### ISSUE THREAD

**Issue by big-andy-coates** [jacoco/jacoco#1308]
### Scenario

* JaCoCo version: 0.8.7.202105040129
* Operating system: macOS Monterey Version 12.2.1
* Tool integration: Gradle 7.3
* Description of your use case: 

I'm testing a command line tool. The functional / black-box testing spawns the tool under test as a new process and asserts standard output and error streams.  

Example of such blackbox test can be see in this PR: https://github.com/creek-service/creek-json-schema/pull/10

Related old issue: https://github.com/jacoco/eclemma/issues/100

### Current Behaviour

Test coverage reports do not take into account code executed by the child process.

### Wanted Behaviour

Test coverage report to include code executed by the child process.

### Possible Workarounds

None that I can think of.

**update**: workaround found. See [below](https://github.com/jacoco/jacoco/issues/1308#issuecomment-1112185672)

**Comment by big-andy-coates** [comment]
Workaround found!

I've found that the code coverage report correctly includes code executed by the child process if I forward the Jacoco `-javaagent` argument to the child process. Nice.

So... maybe this is just a documentation issue?  (Or I didn't RTFM, but Google searches for "Jacoco coverage child process" and similar didn't point me to any appropriate docs).

FYI, my "fix" here: https://github.com/creek-service/creek-json-schema/pull/11

**Comment by marchof** [comment]
Glad you figured it out! Feel free to propose a FAQ entry.

**Comment by big-andy-coates** [comment]
@OrangeDog you've already got full paths, which is good as that can be an issue.  What's the full command you're running? 
I'd suggest adding the `-javaagent` param as the first parameter of the `java` process.

**Comment by big-andy-coates** [comment]
Sorry James, no sure. I can point you at code that works for me on
Linux/Mac, but not tried windows
