### ISSUE TITLE
Generated report shows 0% for test folder in android using kotlin.

### ISSUE THREAD

**Issue by yennamsanthosh-skyflow** [jacoco/jacoco#1309]
### Steps to reproduce

* JaCoCo usage in android :  classpath 'com.dicedmelon.gradle:jacoco-android:0.1.5'
* Operating system:  ubuntu
* Tool integration: gradle
* Complete executable reproducer: https://github.com/skyflowapi/skyflow-android/pull/93/
* Steps: 

    ```
      added in build.gradle (project level) : 
                  1.   classpath 'com.dicedmelon.gradle:jacoco-android:0.1.5'

      added in build.gradle (module level):

                  1. apply plugin: "com.dicedmelon.gradle.jacoco-android"

                  2.  debug {
                              testCoverageEnabled true
                       }
                  3. buildFeatures {
                              dataBinding = true
                      }

      run command :   ./gradlew jacocoTestReport
     ```
### Expected behaviour

Generated report should show test coverage for the tests present in test folder (unit tests) and androidTest folder (instrumentation tests).

### Actual behaviour
Generated report is showing coverage as 0% for the tests present in test folder (unit tests).
Report is showing as expected for tests in androidTest folder.

**Comment by marchof** [comment]
Neither hradle JaCoCo integration nor the Android JDK is maintained by us. Please report to the respective projects. See:

https://www.jacoco.org/jacoco/trunk/doc/integrations.html
