### ISSUE TITLE
jacoco.exec is empty (0 bytes)

### ISSUE THREAD

**Issue by bluestreak01** [jacoco/jacoco#1310]
### Steps to reproduce

* JaCoCo version:  0.8.7 (tested with 0.8.8 - same problem)
* Operating system: Windows, Linux
* Tool integration: Maven
* Complete executable reproducer: https://github.com/questdb/questdb
* Steps:

```
git clone  --depth=1 https://github.com/questdb/questdb.git
cd questdb/core
mvn  -Dtest.exclude=**/griffin/**,**/cairo/**  -Dout=/log-file.conf -P jacoco clean test
```
You redirect `temp` directory location to somewhere fast, like RAM-disk if on Windows to have tests run faster by adding:
```
-Djava.io.tmpdir=H:/
```

in front of ` -Dout=/log-file.conf`

### Expected behaviour

non-zero `jacoco.exec`

### Actual behaviour

zero-length `jacoco.exec`

**Comment by bluestreak01** [comment]
FYI, we found a PR into our repo, which broke the coverage:

https://github.com/questdb/questdb/pull/2044/files

**Comment by marchof** [comment]
What is the exact Java version you're using to execute the test please? Some older Java versions had an issue which prevented the execution of shutdown hooks (which we use to dump exec files) when the main thread was left in interrupted state. See [JDK-8154017](https://bugs.openjdk.java.net/browse/JDK-8154017)

**Comment by Godin** [comment]
According to https://github.com/questdb/questdb/blob/a18dbcacfa1f123f52f6937e19325dedcb9a4226/core/pom.xml#L662 you are using JUnit `4.13.1` and in https://github.com/questdb/questdb/pull/2044/files used `org.junit.rules.Timeout`, so see https://github.com/junit-team/junit4/issues/1652
