### ISSUE TITLE
Jacoco reports invalid(65535) line entry for Kotlin class

### ISSUE THREAD

**Issue by vvictor10** [jacoco/jacoco#1312]
### Steps to reproduce

* JaCoCo version:  0.8.8
* Operating system: Ubuntu Linux
* Tool integration: CLI(Bitrise)
* Complete executable reproducer: N/A
* Steps: 

Generating coverage report for modules in an android project.  We run our coverage report generation in our CI workflow for unit and android tests. Everything seems ok except for this one issue. Some classes report invalid line entries in their coverage report entry.

### Expected behaviour

Class coverage entries in the report indicate only lines available in the source code.

### Actual behaviour

We see that some of our kotlin classes(android project) are reporting so invalid line(nr) entries in the jacoco coverage report.

Using Jacoco v 0.8.8

For e.g.

The DisableInteraction class contains only 25 lines in the source code. And we see the **65535** entry in the reports. We have about 10 such class entries in the report. All of them are Kotlin classes and they have jetpack compose views(composables) in them.

```
<sourcefile name="DisableInteraction.kt">
	<line nr="15" mi="70" ci="0" mb="18" cb="0"/>
	<line nr="16" mi="2" ci="0" mb="2" cb="0"/>
	<line nr="17" mi="14" ci="0" mb="0" cb="0"/>
	<line nr="18" mi="2" ci="0" mb="0" cb="0"/>
	<line nr="19" mi="2" ci="0" mb="0" cb="0"/>
	<line nr="20" mi="4" ci="0" mb="0" cb="0"/>
	<line nr="21" mi="16" ci="0" mb="0" cb="0"/>
	<line nr="22" mi="16" ci="0" mb="0" cb="0"/>
	<line nr="25" mi="18" ci="0" mb="2" cb="0"/>
	<line nr="65535" mi="6" ci="0" mb="2" cb="0"/>
	<counter type="INSTRUCTION" missed="151" covered="0"/>
	<counter type="BRANCH" missed="24" covered="0"/>
	<counter type="LINE" missed="10" covered="0"/>
	<counter type="COMPLEXITY" missed="14" covered="0"/>
	<counter type="METHOD" missed="2" covered="0"/>
	<counter type="CLASS" missed="2" covered="0"/>
</sourcefile>
```

Something seems off. We have a lot of other kotlin files with composables and they are all fine.

**Comment by Godin** [comment]
> Complete executable reproducer: N/A

JaCoCo performs analysis of bytecode, so please understand that we can't investigate this without looking at your class files, thus please provide a complete reproducer or at least all the class files.

**Comment by vvictor10** [comment]
Hi @Godin Thanks for the super quick update. Please find attached a few class files(zipped, since I could not attach .class files) that all fail with the same error. I got these from the build classes directory on Android Studio. Hope its in the format that you need to analyze them. Please keep me posted. This issue is preventing us from coming to a conclusion with code coverage using SonarCloud. Thanks.

[classes.zip](https://github.com/jacoco/jacoco/files/8631412/classes.zip)

**Comment by vvictor10** [comment]
@Godin I was able to put together a quick test project with which I can reproduce the same issue. I am attaching 3 things with this message:

1. Zipped Android gradle project
2. HTML test reports (can be generated by executing "gradle debugTestCoverage" - assuming you have all the other right tools working for the android gradle project - best to use android studio which should everything you need).
3. XML report which shows the "65535" line entries for the 3 test classes I have in the source code.

You should be able to run the "gradle debugTestCoverage" command after syncing the project with the gradle scripts.

The source code under the "com.skey.jacocotest" package has 3 kotlin classes, all of which are super close to what I have in my project source code and exhibit the same issue with the line entry for "65535" line, which should be non existent on the bytecode.

Hope this helps.
[jacoco-html-reports.zip](https://github.com/jacoco/jacoco/files/8633860/jacoco-html-reports.zip)
[JacocoTest.zip](https://github.com/jacoco/jacoco/files/8633861/JacocoTest.zip)
[jacoco.xml.zip](https://github.com/jacoco/jacoco/files/8633867/jacoco.xml.zip)

**Comment by Godin** [comment]
@vvictor10 thank you for the reproducer.

After its compilation execution of

```
javap -v -p app/build/tmp/kotlin-classes/debug/com/skey/jacocotest/SwipeCardKt\$SwipeCard\$2\$1.class | grep -A 5 "LineNumberTable:"
```

produces

```
      LineNumberTable:
        line 65535: 3
        line 62: 44
        line 65535: 90
        line 70: 97
      LocalVariableTable:
```

i.e. actually bytecode contains line number `65535`. And so this looks like a problem in Jetpack Compose compiler plugin or in Kotlin compiler - please report it to them. Once you do this, please post a link to the report here.

**Comment by vvictor10** [comment]
@Godin Created https://issuetracker.google.com/issues/231616123
