### ISSUE TITLE
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named '$jacocoData' in 'class

### ISSUE THREAD

**Issue by zhangyuan3566** [jacoco/jacoco#1314]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named '$jacocoData' in 'class ... Why it happends ?How can I resolve it? Help!!  jacoco version: 0.8.7

**Comment by Godin** [comment]
Please read FAQ - http://www.jacoco.org/jacoco/trunk/doc/faq.html :

> #### My code uses reflection. Why does it fail when I execute it with JaCoCo?
>
> To collect execution data JaCoCo instruments the classes under test which adds two members to the classes: A private static field $jacocoData and a private static method $jacocoInit(). Both members are marked as synthetic.
>
> Please change your code to ignore synthetic members. This is a good practice anyways as also the Java compiler creates synthetic members in certain situation.
