### ISSUE TITLE
Code Coverage issue in JaCoCo while integrating with jenkins

### ISSUE THREAD

**Issue by seemanagarale** [jacoco/jacoco#1317]
JaCoCo version: 0.8.7
OS : windows 10
Tool integration : IntelliJ with Gradle project(Kotlin)

i used a simple project to get the code coverage using JoCoCo. i am able to get the report in the local as shown below:

![Capture22](https://user-images.githubusercontent.com/61103274/169283040-826e7f55-b216-446f-a64c-6550a9cbe738.PNG)

![image](https://user-images.githubusercontent.com/61103274/169284786-1b2bd63c-0f8b-4f21-8a08-769d716fe030.png)

i tried to integrate with jenkins free style project, selected post build action as jococo report publisher.

### Expected behaviour

it should reflect the same as in local coverage 

### Actual behaviour
 when i build the project i am not able to get the same coverage as i am getting in my local it is showing everything as 100%

i found that its not able to get the exec file:

Collecting JaCoCo coverage data...
[JaCoCo plugin] **/**.exec;**/classes;**/src/main/java; locations are configured
[JaCoCo plugin] Number of found exec files for pattern **/**.exec: 0
[JaCoCo plugin] Saving matched execfiles:  
[JaCoCo plugin] Saving matched class directories for class-pattern: **/classes: 
[JaCoCo plugin] Saving matched source directories for source-pattern: **/src/main/java: 
[JaCoCo plugin] Source Inclusions: **/*.java,**/*.groovy,**/*.kt,**/*.kts
[JaCoCo plugin] Source Exclusions: 
[JaCoCo plugin] Loading inclusions files..
[JaCoCo plugin] inclusions: []
[JaCoCo plugin] exclusions: []
[JaCoCo plugin] Thresholds: JacocoHealthReportThresholds [minClass=0, maxClass=0, minMethod=0, maxMethod=0, minLine=0, maxLine=0, minBranch=0, maxBranch=0, minInstruction=0, maxInstruction=0, minComplexity=0, maxComplexity=0]
[JaCoCo plugin] Publishing the results..
[JaCoCo plugin] Loading packages..
[JaCoCo plugin] Done.
[JaCoCo plugin] Overall coverage: class: 100.0, method: 100.0, line: 100.0, branch: 100.0, instruction: 100.0, complexity: 100.0
Finished: SUCCESS

i tried to give the full path of the exec file but still facing the issue. Kindly help!

**Comment by marchof** [comment]
Jenkins plugin is not maintained by us. Please see https://www.jacoco.org/jacoco/trunk/doc/integrations.html
