### ISSUE TITLE
OpenApi generated code not showing up as being covered

### ISSUE THREAD

**Issue by zabiullakhan123** [jacoco/jacoco#1318]
We are using JaCoCo 0.8.5 for our AT run.

At the moment, we're having a problem with code that generated via OpenAPI tool. JaCoCo reports as not being covered for generated code from OpenAPI tool but there clearly is a test and executes it. Hand written code is executing and showing in the JaCoCo report but not generated code is not showing in JaCoCo report.
 

Steps to reproduce
JaCoCo version: (from right bottom corner of JaCoCo report) -> 0.8.5
Operating system: Linux, but issue reproducible across all platform
Tool integration: Gradle 6.8.3
Complete executable reproducer: Please see below POM
Steps: Generate OpenApi  Vo/ Pojo and code related to execution and Call that API from test suit/postman.

### Actual behaviour

(In case of exceptions provide FULL STACKTRACE)

**Comment by marchof** [comment]
Please provide  a executable reproducer, preferably a Github repository.

**Comment by marchof** [comment]
No reproducer, so nothing we can invetigate.
