### ISSUE TITLE
the goal `check` does not always work

### ISSUE THREAD

**Issue by BruceZu** [jacoco/jacoco#1325]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling bug report!

### Steps to reproduce
report-aggregate is configured to verify phrase
```xml
 <executions>
          <execution>
            <id>report-aggregate</id>
            <phase>verify</phase>
            <goals>
              <goal>report-aggregate</goal>
            </goals>
          </execution>
        </executions>
```
the check goal
```xml
<groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.8</version>
        <executions>
          <execution>
            <id>check</id>
            <goals>
              <goal>check</goal>
            </goals>
            <configuration>
              <haltOnFailure>true</haltOnFailure>
              <rules>
                <rule>
                  <element>BUNDLE</element>
                  <limits>
                    <limit>
                      <counter>INSTRUCTION</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>0.25</minimum>
                    </limit>
                    <limit >
                      <counter>BRANCH</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>0.09</minimum>
                    </limit>
                  </limits>
                  <excludes>
                    <!--  <exclude>com.test.ExampleExclusion</exclude> -->
                  </excludes>
                </rule>
              </rules>
            </configuration>
          </execution>
        </executions>
```

* JaCoCo version:  (from right bottom corner of JaCoCo report)
0.8.8
* Operating system:
macOS
* Tool integration: Maven / Ant / CLI / API (for others please report to respective project)
Maven
* Complete executable reproducer: (e.g. GitHub Repo)
I do not it is caused by the java class
* Steps: (what exactly are you doing with the above reproducer?)

Currently, I use these commands. They can make goal `check` work 
```
coco="org.jacoco:jacoco-maven-plugin:0.8.8"
mvn clean
mvn clean ${coco}:prepare-agent verify ${coco}:report-aggregate  
```
Note here; the `clean` in the second line does not clean anything
but without  the `clean` in the second line, the `check` goal will not work

this  command can also make `check` goal work
```
mvn clean ${coco}:prepare-agent verify
```

But, All the following commands  CAN NOT make `check` goal work

```
mvn clean  ${coco}:prepare-agent && \
       mvn clean  verify &&
       mvn ${coco}:report-aggregate
```
or 
```
mvn verify
```
or 
```
mvn clean verify
```
or 
```
mvn clean  ${coco}:report-aggregate
```
I think 
is there a clear document on how to use JaCoCo goal `check` and `repot-aggregate` together

### Expected behaviour
the JaCoCo goal `check` always work

### Actual behaviour
not stable or does not work 

(In case of exceptions provide FULL STACKTRACE)

**Comment by marchof** [comment]
Please specify what exactly means „does not work“

Also if you expect us to investigate this issue please provide a **executable reproducer** that we can execute on our side. This means **all** files included e.g. in a Github repository to show the problem. You don‘t have to share your proprietary code. You can extract an example which demonstrates the problem. Without this we must close this bug as invalid.

**Comment by BruceZu** [comment]
@marchof 
Thank you for shedding light here! 
The 'does not work' means the `check` goal did not report the error.  
E.g.  the `check` goal finds the actually calculated minimum of INSTRUCTION of a submodule is 0.20, and it is less than the configured number 0.25. then `check` goal should output failed information. 
```xml
<element>BUNDLE</element>
                  <limits>
                    <limit>
                      <counter>INSTRUCTION</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>0.25</minimum>
                    </limit>
```

does not work means the result always is the success of the submodule
does work means the result show expected failure information like 
![image](https://user-images.githubusercontent.com/648550/172784195-514b51f4-d26c-4d7a-8059-cf114b21cad6.png)

I want to provide an executable reproducer if I know which class is the root reason. 
Thousands of classes are there. it is really hard for me and I do not think it is caused by some java file. 
I guess it is related to how to use the JaCoCo goal `check` and `repot-aggregate` together or separately via  right maven commands

**Comment by marchof** [comment]
As noted in #1326 coverage figures in `check` and `report-aggregate` cannot be compared.

Without a reproducer we can use to debug this there is nothing we can do for you here, sorry.

**Comment by BruceZu** [comment]
@marchof 
The issue here is not comparing numbers here. I think you mixed the current issue with the issue https://github.com/jacoco/jacoco/issues/1326

The current issue is how to use the maven command to call the `check`  goal rightly to let it work together with the goal `repot-aggregate`
I have listed 2 groups of maven commands.  The first group works, but the second group actually does not call the `check` goal from the effect result.

**Comment by Godin** [comment]
> I think you mixed

No - @marchof didn't mixed anything - `check` goal works on exactly the same numbers and data as `report` goal, there is no such thing as `check-aggregate` that works on the same numbers and data as `report-aggregate`.

> The current issue is how to use the maven command to call the check goal rightly to let it work together with the goal repot-aggregate

Please see https://github.com/jacoco/jacoco/issues/902

**Comment by BruceZu** [comment]
@Godin 
I did not say `check-aggregate` on this page. right? 
please move the focus away from numbers and data in this issue. 
to be short 
if I use command 
```bash
coco="org.jacoco:jacoco-maven-plugin:0.8.8"
mvn clean # the clean in the following line does not clean anything, so I have to add this line. 
mvn clean ${coco}:prepare-agent verify ${coco}:report-aggregate 
``` 
or command 
```bash
coco="org.jacoco:jacoco-maven-plugin:0.8.8"
mvn clean ${coco}:prepare-agent verify
```
The result will show the result in the picture I provided above. This is the expected result.  
But if I remove the `clean` the result will show all are 'success'
why? Must I use `clean` in the `mvn` command to make the `check` goal work? 

The following command should invoke the `check` goal and show the output as the provided picture 
but the outputs are all `success`
Don't you think it is crazy? 
```bash
mvn clean  ${coco}:prepare-agent && \
       mvn clean  verify &&
       mvn ${coco}:report-aggregate
```
or

```mvn verify```
or
```mvn clean verify```
or
```mvn clean  ${coco}:report-aggregate```

**Comment by Godin** [comment]
> I did not say check-aggregate on this page. right?

You multiple times repeated

>  goal check and repot-aggregate together

(in https://github.com/jacoco/jacoco/issues/1325#issue-1265147302 and in https://github.com/jacoco/jacoco/issues/1325#issuecomment-1151212417)

Our with @marchof answers were about this above sentence to the best of how we can understand it and your other descriptions. And please notice that seems that I and @marchof understand it the same way.

As was already said here in https://github.com/jacoco/jacoco/issues/1325#issuecomment-1150706965 and in other tickets created by you, the best way to avoid misunderstandings - is to provide a complete executable reproducer.

----

> But if I remove the clean the result will show all are 'success'
> why?

This puzzles you while you have access to all your code and even to the open-source code of JaCoCo, so can debug every piece. We don't have access to your code - do you expect us to be able to blindly guess? Once again - the information that you provide is not enough to reproduce your issue.

**Comment by BruceZu** [comment]
`repot-aggregate` is a typo, sorry it should be `report-aggregate`. But I did not write `check-aggregate` and did not ask to double-check the number or data in the current issue. 
Please focus on the maven command. 
The only thing I want to know is the right maven command to invoke JaCoCo maven goal `check` and `report-aggregate` together. I have provided detailed cases of commands. Do you have a document about that? 
No idea why you guys always want the code. I do not think it is related to the code as no exception.
