### ISSUE TITLE
Some ration number in the report  is not right. 

### ISSUE THREAD

**Issue by BruceZu** [jacoco/jacoco#1326]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling bug report!

### Steps to reproduce

* JaCoCo version:  (from right bottom corner of JaCoCo report)
0.8.8
* Operating system:
macOS
* Tool integration: Maven / Ant / CLI / API (for others please report to respective project)
Maven
* Complete executable reproducer: (e.g. GitHub Repo)
No idea which class(s) cause the issue

* Steps: (what exactly are you doing with the above reproducer?)

Please see https://imgur.com/a/x7lpnra
We have applied `check` goal on 4 submodules, according to the JaCoCo report.
But only one submodule trigger-core report ratio is not right, the other 3 submodules are correct
From the report link, it shows the 
Submodule |          Instructions |  Branches
---------------------------------------------
trigger-core	         39%	 	 15% ( shown on the report page)
trigger-core	         25%	 	 9% (`check` goal actually use these calculated number to compare with my configuration)

### Expected behaviour
All the ratio number calculated by JaCoCo's` check` goal and those shown in the report should be the same. 

### Actual behaviour
some are not in consistent.

(In case of exceptions provide FULL STACKTRACE)
No exception

**Comment by marchof** [comment]
Again you do not provide a reproducer so just wild guessing:

The report on your screenshot is created with report-aggregate. This goal collects execution data from all modules before calculating coverage for every module. Therefore tests from module A will contribute to coverage of module B if B is used by A.

The check goal works separately on every module, so typically has less coverage in a poorly tested multi-module project. If you want to see the same figures please use the report goal.

**Comment by BruceZu** [comment]
@marchof  Thank you! your feedback resolved my confusion. 
The submodule trigger-core which has the unexpected number is just the one that other modules depend on it.
