### ISSUE TITLE
The number showed on report-aggregate page is less than the number showed by goal check output

### ISSUE THREAD

**Issue by BruceZu** [jacoco/jacoco#1330]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling bug report!

### Steps to reproduce

* JaCoCo version:  (from right bottom corner of JaCoCo report)
0.8.8
* Operating system:
MacOS
* Tool integration: Maven / Ant / CLI / API (for others please report to respective project)
Maven
* Complete executable reproducer: (e.g. GitHub Repo)
* Steps: (what exactly are you doing with the above reproducer?)

### Expected behaviour
the number shown on the report-aggregate page should be >= the number shown by the goal check output.

### Actual behaviour
 The new added test cases do not take effect in the aggregate report page
![image](https://user-images.githubusercontent.com/648550/173991615-ba9b1273-62e1-4aa9-b502-8bf31e7c0518.png)
I want to know if there is some cached result somewhere. I want to clean them. `mvn clean` does not work.
Because I find some method has been tested in the newly added test cases, but the report-aggregate page shows the newly added test cases did not take effect in the report. For example, these lines actually have been tested in the newly added test cases. But these lines are still in red color.
 
![image](https://user-images.githubusercontent.com/648550/173993006-a93ca060-d231-4f6c-83a5-3766405b4917.png)

(In case of exceptions provide FULL STACKTRACE)
No exception

**Comment by marchof** [comment]
@BruceZu Please stop wasting the time of volunteers with your screenshots. If you want someone to look into your setup provide a example we can actually debug.

**Comment by BruceZu** [comment]
@marchof It is not easy to prepare the example, because there is no exception and I do not know which java file triggers this bug from thousands of java files and which one I should pick out. 
I am sure this is a bug. 
You guys should do nothing without providing an example code.  As you are the developer, know how it works.  You should know something helpful. 
As you guys open-source the JaCoCo, I assume you want others to use it and report any issues, and you are glad to support users.

**Comment by marchof** [comment]
> It is not easy to prepare the example

And you expect us to do this work for free for you???

> As you guys open-source the JaCoCo, I assume you want others to use it and report any issues, and you are glad to support users.

Looks like you have a complete misunderstanding of open source.

**Comment by BruceZu** [comment]
Do you want me to pay you?

**Comment by marchof** [comment]
This is a plain side project and we do not offer commercial support.

**Comment by BruceZu** [comment]
As you think  I have a complete misunderstanding of open source, so I want to know how you understand the open-source, at least why you guys open-source the JaCoCo. What do you expect from the end-user?  I do not think no-commercial support give your guys a reason to treat end user in such a way.

**Comment by BruceZu** [comment]
To be honest, you guys are so rude. I am thinking to drop JaCoCo next month.

**Comment by marchof** [comment]
For full transparency: After a fruitless discussion here and on multiple previous issues we decided to block user @BruceZu here.
