### ISSUE TITLE
Could not create task :app:jacocoTestReport

### ISSUE THREAD

**Issue by aleksandravojinovic-htec** [jacoco/jacoco#1331]
Android studio `.\gradlew tasks` is failing with the following error:

```
Could not create task :app:jacocoTestReportDevelopmentDebug
 org.jetbrains.kotlin.gradle.tasks.KotlinCompile.getDestinationDir()Ljava/io/File;
```

**Current versions:**
version.org.jacoco..org.jacoco.core=0.8.8
gradle plugin.android=7.2.1
gradle wrapper gradle-7.4.2-all.zip

**Previously working with versions:**
version.org.jacoco..org.jacoco.core=0.8.8
gradle plugin.android=7.1.2
gradle wrapper gradle-7.4.1-bin.zip

**Comment by marchof** [comment]
Please check with the Android or Gradle project.

**Comment by filipkowicz** [comment]
issue is with kotlin 1.7

**Comment by moskaland** [comment]
@aleksandravojinovic-htec were you able to fix this issue?

**Comment by tonywmk** [comment]
I just encountered this problem, I'm also interested in the answer.

**Comment by filipkowicz** [comment]
@marchof unfortunately it's jacoco issue - you are using method `getDestinationDir` of KotlinCompile task which was removed recently - [here](https://github.com/JetBrains/kotlin/commit/4aa6d984fc27ac747d0d44ff742e90b21994afed#diff-3e4eb07a214aa32b2a50470441cb356a616c29edaa4344d7c24ff00b27dc293d) you need to change to `destinationDirectory.get().asFile`

**Comment by marchof** [comment]
Gradle plugin is not developed by us and we're not involved. Please check with them.

**Comment by filipkowicz** [comment]
Yeah but they won't bring this method back what makes your tool incompatible

**Comment by marchof** [comment]
We (the JaCoCo project) are not calling this method.

**Comment by manuelkrtc** [comment]
@aleksandravojinovic-htec I have the same problem with the same kotlin and gradle version.

can you please show me what versions you have for other libraries in the project?
