### ISSUE TITLE
Lambdas inside code block should be considered in code coverage for Kotlin v1.6.20

### ISSUE THREAD

**Issue by CyborgRahil** [jacoco/jacoco#1333]
### Steps to reproduce
* JaCoCo version:  0.8.8
* Operating system: MacOS
* Tool integration: Gradle/Kotlin
* Complete executable reproducer:
Attached as a zip
[jacocoReproducer.zip](https://github.com/jacoco/jacoco/files/8927617/jacocoReproducer.zip)
#### Steps: (what exactly are you doing with the above reproducer?)
To generate the test reports execute
` ./gradlew kotlinjacocoTestReport`
in the above reproducer.
Same can be run after changing the kotlin version in build.gradle file's plugin section
`id 'org.jetbrains.kotlin.jvm' version '1.6.20'`
### Expected behaviour
Due to change in structure during code generation there is an impact of code coverage. Coverage should be same for both Kotlin v1.4.32 and kotlin v1.6.20
### Actual behaviour
Using lambda function in Kotlin 1.4.32 generates as a class in the coverage report.
<img width="1504" alt="Screenshot 2022-06-17 at 6 45 40 PM" src="https://user-images.githubusercontent.com/16253416/174305692-8193eaf7-c375-4c50-b5f5-e01f02bdbd16.png">

Using lambda function in Kotlin 1.6.20 generates as a function in a class as a part of the coverage report.

<img width="914" alt="Screenshot 2022-06-17 at 6 14 04 PM" src="https://user-images.githubusercontent.com/16253416/174305277-eadd4744-58d5-4eee-93aa-cbd528e30cdd.png">
<img width="910" alt="Screenshot 2022-06-17 at 6 13 29 PM" src="https://user-images.githubusercontent.com/16253416/174305303-82c1259b-175f-488c-8eff-b3b49097368e.png">

Code coverage for 1.6 is :
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/16253416/174306593-a6e4ef44-6943-4fa7-8df7-f93e3d29b6d8.png">

**Comment by Godin** [comment]
> Due to change in structure during code generation there is an impact of code coverage. Coverage should be same for both Kotlin v1.4.32 and kotlin v1.6.20

Yes - different versions of the compiler generate different bytecode.
JaCoCo doesn't analyse source code - JaCoCo performs analysis of bytecode, and so the resulting reports for different versions of the compiler can be different.

**Comment by CyborgRahil** [comment]
@Godin 
Agreed, different version of the compiler generate diff bytecode.

Due to change in compiler, it does not impact the code coverage, we are seeing upto 20% variation in most of the module. 
Any flags or any workaround for this where we can handle this type of changes?
Cater details from the modules will take some time, because there is no any change in codebase?
