### ISSUE TITLE
Branch and Instruction Line Coverage for Violations Checker Ant task

### ISSUE THREAD

**Issue by kingargyle** [jacoco/jacoco#1340]
### Scenario

* JaCoCo version: 0.8.8
* Operating system:  any
* Tool integration: Ant / Gradle / Maven

Description:

Currently for Bundle coverage we only have to ability to represent Branch, Instructions, Methods, Class, etc levels of coverage for the violation rules.   In order to help match up with the way Sonar reports code coverage, as documented at the following link:

https://community.sonarsource.com/t/sonarqube-and-code-coverage/4725#how-to-calculate-code-coverage-4

It would be nice to have another option for the combined calculation of Branch and Instruction/Line Coverage.    This would help closer align what the developer sees and what sonar itself is reporting.   Or if there was a way to configure the Violation rules to take the aggregrate of several coverge metrics that would be even better and more flexible.

### Current Behaviour

No way to combine Instruction and Branch coverage for an overall coverage

### Wanted Behaviour

Ability to specify multiple metrics to consider as a whole.

### Possible Workarounds

None

**Comment by marchof** [comment]
JaCoCo uses [standard definitions](https://www.jacoco.org/jacoco/trunk/doc/counters.html) widely adopted in the industry.

We will not incorporate additional proprietary definitions of other tools. Based on our XML reports you can create tooling to calculate any metrics. Or you use SonarQube directly if you want to see their metrics

**Comment by kingargyle** [comment]
Thanks.  I figured it was a long shot.   I should be able to create a gradle task based on the xml data to possibly meet our internal needs.

**Comment by marchof** [comment]
JaCoCo is has an public API and is released as Maven artifacts. You could even use that.
