### ISSUE TITLE
Coverage Report is showing 0%

### ISSUE THREAD

**Issue by SEBASIAO** [jacoco/jacoco#1347]
I have and android studio project where i have only unit test, using the android studio tool for code coverage it says that i have 12% of code coverage as i only have two view models tested, now i need a report of this coverage for that i am trying to use jacoco but the generated report by jacoco is showing 0%.

`Source file "com/xxx/xxx/xx/xx/xx/xx.kt" was not found during generation of report.`

![Captura de Pantalla 2022-07-29 a la(s) 11 40 23 a m](https://user-images.githubusercontent.com/50461957/181805747-37dee278-374a-4f0f-b278-b56aa5848125.png)

`plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'jacoco'
}

android {
    compileSdk 32

    defaultConfig {
        minSdk 21
        targetSdk 32

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        debug {
            testCoverageEnabled true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    testOptions {
        animationsDisabled true

        unitTests {
            includeAndroidResources = true
        }
    }

    android.sourceSets.all {
        kotlin.srcDir("src/$name/kotlin")
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}`

Gradle Plugin Version : 7.2.0
Gradle Version : 7.5

### Steps to reproduce

* JaCoCo version:  0.8.7
* Operating system: MacOs
* Tool integration: Maven / Ant / CLI / API (for others please report to respective project)
* Complete executable reproducer: (e.g. GitHub Repo)
* Steps: (what exactly are you doing with the above reproducer?)

### Expected behaviour
Generate report with 12% of coverage

### Actual behaviour
Generate Report with 0% of coverage

(In case of exceptions provide FULL STACKTRACE)

**Comment by marchof** [comment]
Neither android studio nor JaCoCo plugin for Gradle is developer by us. Please check with the [respecive projects](https://www.jacoco.org/jacoco/trunk/doc/integrations.html).
