### ISSUE TITLE
CoroutineScope.launch reported as partially covered

### ISSUE THREAD

**Issue by joshfriend** [jacoco/jacoco#1353]
### Steps to reproduce

* JaCoCo version:  0.8.8.202204050719
* Operating system: macOS 12.5
* Tool integration: Gradle
* Kotlin version: 1.7.10
* Complete executable reproducer: [CoroutineLaunchPartialCoverage.zip](https://github.com/jacoco/jacoco/files/9353797/CoroutineLaunchPartialCoverage.zip)

Steps: (what exactly are you doing with the above reproducer?)

1. Run `./gradlew jacocoTestReportDebug` in the provided sample, or just open the jacoco report that should already be included from when I ran it `app/build/reports/jacoco/debug/com.example.coroutinelaunch/ExampleRepository.kt.html`

### Expected behaviour

`ExampleRepository.kt` should have 100% coverage.

### Actual behaviour

The call to `CoroutineScope.launch` is marked partially covered, I believe from the _theoretically_ possible case where the coroutine somehow doesn't get launched.

`ExampleRepository.doSomething.new Function2() {...}` `invokeSuspend(Object)` is what I see marked as not covered.

I believe this to be a barebones reproducible version of #1290 which was closed for not having a sample. It is my understanding that 0.8.7 release should have fixed this this issue with the inclusion of #1149.

See also this issue from the kotlin coroutines repo: https://github.com/Kotlin/kotlinx.coroutines/issues/2351

**Comment by Godin** [comment]
In your case JaCoCo report

<img width="617" alt="Screenshot 2022-10-13 at 15 05 58" src="https://user-images.githubusercontent.com/138671/195606460-156d6f16-456f-4468-9d34-2874c6a5b8e9.png">

correctly shows that the end of suspending lambda after the suspension point `delay(100)` is never reached.

The addition of debug output before and after the suspension point demonstrates this

<img width="617" alt="Screenshot 2022-10-13 at 15 12 12" src="https://user-images.githubusercontent.com/138671/195606429-e214df90-3fa3-4cb3-a11d-80715afd13c2.png">

<img width="734" alt="Screenshot 2022-10-13 at 15 12 52" src="https://user-images.githubusercontent.com/138671/195606405-6714cbe1-6275-460f-bd88-402671075bf8.png">

And if you'll modify your test to wait a bit after the execution of `doSomething()`

```diff
    fun `demonstrate missed launch coroutine coverage`() = runTest {
         val repo = ExampleRepository()
         repo.doSomething()
+        Thread.sleep(1000)
    }
```

then you'll see that the end of suspending lambda is reached

<img width="601" alt="Screenshot 2022-10-13 at 15 25 34" src="https://user-images.githubusercontent.com/138671/195609381-dd6b11aa-6493-400c-ae9b-ea3274e3b1f6.png">

<img width="1045" alt="Screenshot 2022-10-13 at 15 27 27" src="https://user-images.githubusercontent.com/138671/195609615-6f56e08d-5092-4a0c-bf22-f056b0f17912.png">

<img width="734" alt="Screenshot 2022-10-13 at 15 25 07" src="https://user-images.githubusercontent.com/138671/195609407-6abead79-2995-4d15-8aa5-e4d98e751307.png">
