### ISSUE TITLE
Automatic (smarter) code exclusions

### ISSUE THREAD

**Issue by toorap** [jacoco/jacoco#1354]
### Scenario

* JaCoCo version: since 0.6.1
* Operating system: All
* Tool integration: All
* Description of your use case: Currently we hand-craft exclusions to identify code that we don't want covered. I propose that we provide a mechanism to automatically decide which code should be covered based on smart criteria such as cyclomatic complexity and/or machine learning. This will save time by avoiding the need to craft exclusions and will improve the value of coverage by focussing on business logic. 

### Current Behaviour
DEVs manually identify what code should or should not be covered through configuration or annotations.

### Wanted Behaviour
Jacoco to automatically decide what code should or should not be covered. 
This can be triggered by a configuration flag. 
Combine this with the existing exclusions mechanism as an override to handle cases such as legacy code that will not change.

### Possible Workarounds
Continue with the current approach

**Comment by marchof** [comment]
> Jacoco to automatically decide what code should or should not be covered.

How should this be done??

**Comment by toorap** [comment]
You could start with focussing on areas of code that have non-trivial cyclomatic complexity. Also, I believe there are ML algos that can predict complexity.

**Comment by marchof** [comment]
Ok, I think this is beyond our capabilities here. JaCoCo has an documented, public API. Maybe somebody else wants to start al ML project.
