### ISSUE TITLE
Jacoco exec size file not incrementing in JDK17 whereas with JDK11 it was working fine

### ISSUE THREAD

**Issue by NavdeepKaur0404** [jacoco/jacoco#1358]
I am providing below command in Conf file and starting tomcat service. With this, jacoco.exec file generating with 0 KB.
**_set CATALINA_OPTS="-javaagent:C:\jacoco\jacocoagent.jar=address=*,port=36320,destfile=C:\Devproject\jacoco\jacoco-it.exec,output=file,append=true"_**

Once application is up, I am doing some activities on the application and then stopped tomcat service. Jacoco.exec file still remains 0 Kb and does not show any code coverage percent or size increase.

It was working fine with JDK11. In both scenarios I am using **jacoco-0.8.8 jar** file.

**Comment by marchof** [comment]
Writing coverage data requires a proper JVM shutdown. Please check with the tomcat project how to shutdown the JVM properly
