### ISSUE TITLE
Line Calling Method which Throws Exception Incorrectly Reported as not Covered

### ISSUE THREAD

**Issue by iadcode** [jacoco/jacoco#1360]
### Steps to reproduce

* JaCoCo version: 0.8.8.202204050719
* Operating system: Windows 10 64-bit
* Tool integration: Maven (plugin version 0.8.8)
* Complete executable reproducer: https://github.com/iadcode/jacocoTest
* Steps: `mvn clean verify`

### Expected behaviour
All methods in [Example.java](https://github.com/iadcode/jacocoTest/blob/main/src/main/java/Example.java) should be covered.

### Actual behaviour
jacoco reports [this line](https://github.com/iadcode/jacocoTest/blob/9fcebd2a986aa01e48f3fd8d9bc21d49b6111e6f/src/main/java/Example.java#L6) as not covered.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/18545429/190028855-782b76cf-d193-47fa-b041-0c96fd190533.png)

### Further information
* The line reported as uncovered calls a method that throws an exception.
* If the callee does not throw an exception, the caller will be reported correctly as covered (see [`coveredMethodOne`](https://github.com/iadcode/jacocoTest/blob/9fcebd2a986aa01e48f3fd8d9bc21d49b6111e6f/src/main/java/Example.java#L10))
* If the line throw the exception directly, it will be reported correctly as covered (see [`coveredMethodTwo`](https://github.com/iadcode/jacocoTest/blob/9fcebd2a986aa01e48f3fd8d9bc21d49b6111e6f/src/main/java/Example.java#L14))
* The callee is also reported as covered while the only caller (the line in question) is reported not covered. (see [`calleeThrowsException`](https://github.com/iadcode/jacocoTest/blob/9fcebd2a986aa01e48f3fd8d9bc21d49b6111e6f/src/main/java/Example.java#L21))

**Comment by marchof** [comment]
Hi @iadcode, thanks for this very clear and detailed bug report! Unfortunately you discovered a known limitation. Please see [FAQ](https://www.jacoco.org/jacoco/trunk/doc/faq.html):

> # Source code lines with exceptions show no coverage. Why?
> 
> JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding lines of source code are not marked as covered.
