### ISSUE TITLE
Does not support Chinese file path?

### ISSUE THREAD

**Issue by wamdy** [jacoco/jacoco#1363]
* JaCoCo version:  
* Operating system: Windows 11
* Tool integration: Maven
* Complete executable reproducer: https://github.com/wamdy/simplecode
* Steps: mvn clean test

Two maven project basic same, the difference is that the folder name is a Chinese ，Another one is English, cause the jacoco. Exec file cannot be generated when Chinese.

### Expected behaviour
![image](https://user-images.githubusercontent.com/2725226/190607161-57293768-1e7d-42c1-93c7-9bd360e1d96e.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/2725226/190607090-6910b1c6-473c-402b-b91b-5194d2f2d328.png)

Hope your response, Thanks.

**Comment by wamdy** [comment]
Sample like I missed some parameter to assign charset encode.

**Comment by marchof** [comment]
Can you please share what was the configuration to make ist workß
