### ISSUE TITLE
Coverage not effective！

### ISSUE THREAD

**Issue by r498647365** [jacoco/jacoco#1376]
### Steps to reproduce

* JaCoCo version:  0.85
* Operating system: windows
* Tool integration: API
* Steps: 
The interface calls the service method，All interface methods are covered，But the service method has no coverage，
The same server

1、Interface screenshot
![IMG20221015112955](https://user-images.githubusercontent.com/24275317/195967063-31536b6b-ee3b-4f79-a3ac-c9a495d1efc2.png)
2、Interface coverage
![SDSDSD](https://user-images.githubusercontent.com/24275317/195967135-b696b6c0-0f2a-4843-8a06-f43bef57d875.png)
3、Service method coverage
![FGFG](https://user-images.githubusercontent.com/24275317/195967202-eb4803c0-c86c-4dae-9544-b34bc8bb080c.png)

**Comment by marchof** [comment]
Hi @r498647365, unfortunatelly I have no idea what your screenshots show and what the code is. Please provide an executable reproducer (preferably a GitHub repository) where we can analyze the problem

**Comment by r498647365** [comment]
This is our company's business code，
I can't give it to you，
the truth is that，
Why is the code colored green,
All the called methods are red

**Comment by marchof** [comment]
I really can't tell you from the screenshots. You don't have to share you're companies code. You can craft a minimal example which demonstrates your problem.
