### ISSUE TITLE
JaCoCo report counts on class level do not aggregate lambda counts

### ISSUE THREAD

**Issue by uhafner** [jacoco/jacoco#1380]
### Steps to reproduce

* JaCoCo version:  0.8.8.202204050719
* Operating system: MacOS
* Tool integration: Maven
* Complete executable reproducer: https://github.com/jenkinsci/analysis-model
* Steps: `mvn verify`

### Expected behaviour

The counter for lines on the class level should be the sum of the counters of the containing elements. However, the counter is only the sum of the method counters, lambdas are ignored. See sample report snippet below. Full report can be obtained by building the example project above.
 
### Actual behaviour

The following snippet of the JaCoCo report shows the problem:
```
    <class name="edu/hm/hafner/analysis/parser/pvsstudio/AnalyzerType" sourcefilename="AnalyzerType.java">
      <method name="fromErrorCode"
              desc="(Ljava/lang/String;)Ledu/hm/hafner/analysis/parser/pvsstudio/AnalyzerType$AnalysisType;" line="113">
        <counter type="INSTRUCTION" missed="4" covered="23"/>
        <counter type="BRANCH" missed="1" covered="1"/>
        <counter type="LINE" missed="1" covered="7"/>
        <counter type="COMPLEXITY" missed="1" covered="1"/>
        <counter type="METHOD" missed="0" covered="1"/>
      </method>
      <method name="lambda$fromErrorCode$1" desc="(Ljava/util/Optional;)Ljava/util/stream/Stream;" line="122">
        <counter type="INSTRUCTION" missed="0" covered="7"/>
        <counter type="LINE" missed="0" covered="1"/>
        <counter type="COMPLEXITY" missed="0" covered="1"/>
        <counter type="METHOD" missed="0" covered="1"/>
      </method>
      <method name="lambda$fromErrorCode$0"
              desc="(ILedu/hm/hafner/analysis/parser/pvsstudio/AnalyzerType$AnalysisType;)Ljava/util/Optional;"
              line="121">
        <counter type="INSTRUCTION" missed="0" covered="4"/>
        <counter type="LINE" missed="0" covered="1"/>
        <counter type="COMPLEXITY" missed="0" covered="1"/>
        <counter type="METHOD" missed="0" covered="1"/>
      </method>
      <method name="&lt;clinit&gt;" desc="()V" line="109">
        <counter type="INSTRUCTION" missed="0" covered="34"/>
        <counter type="LINE" missed="0" covered="1"/>
        <counter type="COMPLEXITY" missed="0" covered="1"/>
        <counter type="METHOD" missed="0" covered="1"/>
      </method>
      <counter type="INSTRUCTION" missed="4" covered="68"/>
      <counter type="BRANCH" missed="1" covered="1"/>
      <counter type="LINE" missed="1" covered="8"/>
      <counter type="COMPLEXITY" missed="1" covered="4"/>
      <counter type="METHOD" missed="0" covered="4"/>
      <counter type="CLASS" missed="0" covered="1"/>
    </class>
```

**Comment by marchof** [comment]
> The counter for lines on the class level should be the sum of the counters of the containing elements.

Unfortunately this is not this easy: The total on class level is the total number of *unique* lines. See for example this line:

    .map(type -> type.create(errorCode))

The `map()` method called from `fromErrorCode()` and the lambda body are in the same line. Therefore it is only counted as a single line of source.

**Comment by uhafner** [comment]
Hmm, why is then the lambda not a child of the containing method node? That would make more sense and would produce a concise model. Now we have two nodes that can overlap. This is hard to distinguish for tools that use the XML as input. Are all lambdas part of a method, or is it possible to have them outside of a method? Or is there an easy way to detect such overlapping methods? It would be helpful for consumers if this decision can be somehow written to the XML.

**Comment by marchof** [comment]
JaCoCo is based on Java bytecode and basically shows the structure of classfiles:

Lambda bodies are compiled into separate methods in the same class. Methods cannot be nested into methods.

As source files can be compiled into many classes and methods I recommend to primarily use the sourcefile node for presenting results to the user.

**Comment by uhafner** [comment]
> As source files can be compiled into many classes and methods I recommend to primarily use the sourcefile node for presenting results to the user.

Ok, thanks for the clarification. I'm not sure if using sourcefiles nodes will be sufficient for users of a coverage reporter (users will loose the information about the coverage of individual methods and classes) but we will see if this works out.

> Lambda bodies are compiled into separate methods in the same class. Methods cannot be nested into methods.

When lambdas are always compiled as separate methods then I would have assumed that the code (and counters) would be separate from the method that defines and uses them (or that the line counter is 0 as it is already included in the method). But this seems to be a matter of taste. At least it would be helpful if you can mark such elements in the XML file somehow (I can guess that by filtering by the name `lambda$*`, but I am not sure if that is always true).

**Comment by marchof** [comment]
> When lambdas are always compiled as separate methods then I would have assumed that the code (and counters) would be separate from the method that defines and uses them (or that the line counter is 0 as it is already included in the method)

As shown in the example above: With lambdas a single source line typically produces code in two methods (the lambda body AND the method consuming the lambda). With anonymous inner classes you can even have two classes in the same line of code. The report simply reflects what's in the class files.

> At least it would be helpful if you can mark such elements in the XML file somehow (I can guess that by filtering by the name lambda$*, but I am not sure if that is always true).

There are many more situations where the compiler creates auxiliary methods which is also highly language specific (Java, Scala, Kotlin). What this would mean having a coverage model for the specific source language and trying to map bytecode coverage to the AST of the respective model. We have no plans or capacity to implement this.

**Comment by uhafner** [comment]
> > When lambdas are always compiled as separate methods then I would have assumed that the code (and counters) would be separate from the method that defines and uses them (or that the line counter is 0 as it is already included in the method)
> 
> As shown in the example above: With lambdas a single source line typically produces code in two methods (the lambda body AND the method consuming the lambda). With anonymous inner classes you can even have two classes in the same line of code. The report simply reflects what's in the class files.
> 
> > At least it would be helpful if you can mark such elements in the XML file somehow (I can guess that by filtering by the name lambda$*, but I am not sure if that is always true).
> 
> There are many more situations where the compiler creates auxiliary methods which is also highly language specific (Java, Scala, Kotlin). What this would mean having a coverage model for the specific source language and trying to map bytecode coverage to the AST of the respective model. We have no plans or capacity to implement this.

I see, this makes sense on the byte code level. It seems that I made too many wrong assumptions in my model (that reads the XML and shows a report). I will adapt my model so that the coverage counters will be stored on all model levels, this should fix these problems in my reports.

**Comment by marchof** [comment]
BTW, here is a detailed explanation of JaCoCo's coverage counters: https://www.jacoco.org/jacoco/trunk/doc/counters.html
