### ISSUE TITLE
java.io.InvalidClassException because of an issue with serialVersionUID generation

### ISSUE THREAD

**Issue by maximethebault** [jacoco/jacoco#1384]
Posting here for reference.

I think I've met an issue with ASM, an underlying library JaCoCo is using.

Issue can be encountered when using a library that relies on Java Serialization and serialVersionUID auto-generated by the JVM.
In that case, ASM will generate a serialVersionUID that might be different than what the JVM would generate, that can cause the following exception:
```
Caused by: java.io.InvalidClassException: java.class.XXX; local class incompatible: stream classdesc serialVersionUID = 5893177478437626661, local class serialVersionUID = -2099619866804728723
	at java.base/java.io.ObjectStreamClass.initNonProxy(Unknown Source)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)

```

More details here: https://gitlab.ow2.org/asm/asm/-/issues/317987

Can you confirm JaCoCo is relying on serialver generated by ASM and this issue is plausible?

Thanks

**Comment by marchof** [comment]
@maximethebault JaCoCo does not use ASM's `SerialVersionUIDAdder`. In any case JaCoCo add new members during instrumentation which means the default serialVersionUID changes. Therefore original and instrumented classes are not compatible in serialization. I don't think this is specific to Java.

**Comment by maximethebault** [comment]
Good to know, couldn't find much resource about that while investigating.

Thanks for your help.
