### ISSUE TITLE
Loss of coverage after adding a new unit test

### ISSUE THREAD

**Issue by nbauma109** [jacoco/jacoco#1387]
After adding a new unit test, the code coverage is expected to be greater or equal.

### Steps to reproduce

* JaCoCo version:  0.8.8
* Operating system: ubuntu
* Tool integration: Maven
* Complete executable reproducer: [Pull request](https://github.com/nbauma109/jd-core-v0/pull/65)
* Steps: (what exactly are you doing with the above reproducer?)
- Create a new branch from master
- Commit and push a new unit test to the new branch
- Create a new pull request
- Read codecov report

### Expected behaviour
- Global code coverage increases or remains the same
- None of the classes may have decreased coverage
### Actual behaviour
- a loss of coverage is observed but that might be due to wrong initial coverage

**Comment by marchof** [comment]
@nbauma109 Can you please show the native JaCoCo code coverage report (screenshots of summary) before and after the change?

**Comment by nbauma109** [comment]
Before:

![before](https://user-images.githubusercontent.com/9403560/208401707-7b81a043-8b5e-4fe8-8b45-673640338230.png)


After:

![after](https://user-images.githubusercontent.com/9403560/208401739-75f8e87f-f2e1-40b9-a7c3-fd61a9f6ac0e.png)

**Comment by nbauma109** [comment]
I can't see the coverage loss in the jacoco reports generated locally (the version before also has the same uncovered pieces). I think the issue might be on codecov side.

**Comment by marchof** [comment]
Then please report to codecov, thx!
