### ISSUE TITLE
Upgrade maven-repository-metadata to the latest version

### ISSUE THREAD

**Issue by bigbird023** [jacoco/jacoco#1390]
* JaCoCo version: 0.8.8
* Operating system: all
* Tool integration: Maven 
* Description of your use case: The company I work for fails builds with any library or dependent library that is "stale", or 10 years since the last commit to that version.  maven-repository-metadata version 2.0.2 is in that window, but has newer versions released.

**Comment by marchof** [comment]
Can you please point to the exact Maven artifact you're referring to? JaCoCo 0.8.8 was released last year (2022/04/05):

https://www.jacoco.org/jacoco/index.html

**Comment by bigbird023** [comment]
I dug into this, and it seems it might be a little more complicated to upgrade just that one library, and there might be multiple libraries with staleness of over 10 years w/o a new version built.  But to answer your question, the following is what I've done so far.

We are using version 0.8.8

 <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.8</version>

I have cloned the jacoco repository and ran the following maven command 
 mvn dependency:tree | grep maven-repository-metadata -B 8
 
 with it returning 3 results for that library
 
[INFO] +- org.apache.maven.shared:file-management:jar:1.2.1:compile
[INFO] |  +- org.apache.maven.shared:maven-shared-io:jar:1.1:compile
[INFO] |  |  +- org.apache.maven:maven-artifact:jar:3.0:compile
[INFO] |  |  +- org.apache.maven:maven-artifact-manager:jar:2.0.2:compile
[INFO] |  |  |  \- org.apache.maven:maven-repository-metadata:jar:3.0:compile

[INFO] +- org.jacoco:org.jacoco.examples.test:jar:0.8.9-SNAPSHOT:test
[INFO] +- org.jacoco:jacoco-maven-plugin:jar:0.8.9-SNAPSHOT:compile
[INFO] |  +- org.codehaus.plexus:plexus-utils:jar:3.0.22:compile
[INFO] |  +- org.apache.maven.shared:file-management:jar:1.2.1:compile
[INFO] |  |  +- org.apache.maven:maven-plugin-api:jar:2.0.6:compile
[INFO] |  |  +- org.apache.maven.shared:maven-shared-io:jar:1.1:compile
[INFO] |  |  |  +- org.apache.maven:maven-artifact:jar:2.0.2:compile
[INFO] |  |  |  +- org.apache.maven:maven-artifact-manager:jar:2.0.2:compile
[INFO] |  |  |  |  \- org.apache.maven:maven-repository-metadata:jar:2.0.2:compile

[INFO]    +- org.jacoco:org.jacoco.examples:jar:0.8.9-SNAPSHOT:compile
[INFO]    \- org.jacoco:jacoco-maven-plugin:jar:0.8.9-SNAPSHOT:compile
[INFO]       +- org.codehaus.plexus:plexus-utils:jar:3.0.22:compile
[INFO]       +- org.apache.maven.shared:file-management:jar:1.2.1:compile
[INFO]       |  +- org.apache.maven:maven-plugin-api:jar:2.0.6:compile
[INFO]       |  +- org.apache.maven.shared:maven-shared-io:jar:1.1:compile
[INFO]       |  |  +- org.apache.maven:maven-artifact:jar:2.0.2:compile
[INFO]       |  |  +- org.apache.maven:maven-artifact-manager:jar:2.0.2:compile
[INFO]       |  |  |  \- org.apache.maven:maven-repository-metadata:jar:2.0.2:compile

**Comment by marchof** [comment]
Ok, now I see your problem. You can forget about the examples, they are not part of the maven plugin. The Maven plugin is still compatible with Maven 2.0 therefore we cannot simply update dependencies.

If this is a problem for your you can update the library in your POM under build / pluginManagement/ plugins / plugin / dependencies (if a newer version is compatible).
