### ISSUE TITLE
JaCoCo has coverage issues with Android API level 33

### ISSUE THREAD

**Issue by rameshphilips** [jacoco/jacoco#1391]
### Steps to reproduce

* JaCoCo version:  0.8.8
* Operating system: Ubuntu 
* Tool integration: CLI - Jenkins
* Complete executable reproducer: (e.g. GitHub Repo)
* Steps: We have migrated to the latest Android SDK version 33 along with JaCoCo version 0.8.8. We could only see the 0% in the report. Test cases were passed and an exec file was also created.
* AGP Version- com.android.tools.build:gradle:7.3.1
* Gradle version - gradle-7.4-bin.zip

### Expected behaviour
We would like to see the right coverage

### Actual behaviour
Coverage was 0% by default.

**Comment by marchof** [comment]
Please note that neither Gradle nor Android SDK integration of JaCoCO is developed by us. Please check with the respective projects. Thx!
