### ISSUE TITLE
Maven Integration ReportSet is going directly for target/classes

### ISSUE THREAD

**Issue by cstamas** [jacoco/jacoco#1394]
### Steps to reproduce

* JaCoCo version: 0.8.8 (currently latest, but seems all affected)
* Operating system: Linux, Fedora 37 WS, but does not matter
* Tool integration: Maven
* Complete executable reproducer: (e.g. GitHub Repo): https://github.com/eclipse/sisu.inject/pull/72
* Steps: (what exactly are you doing with the above reproducer?) try to build id, `mvn clean install`

### Expected behaviour

Jacoco be able to do it's job.

### Actual behaviour

jacoco emits warnings:
```
[INFO] --- jacoco-maven-plugin:0.8.8:report-aggregate (jacoco-report) @ org.eclipse.sisu.inject.tests ---
[INFO] Loading execution data file /home/cstamas/Worx/eclipse/sisu.inject/org.eclipse.sisu.inject.tests/target/jacoco.exec
[INFO] Analyzed bundle 'org.eclipse.sisu.inject' with 207 classes
[WARNING] Classes in bundle 'org.eclipse.sisu.inject' do not match with execution data. For report generation the same class files must be used as at runtime.
[WARNING] Execution data for class org/eclipse/sisu/space/SpaceScanner does not match.
[WARNING] Execution data for class org/eclipse/sisu/wire/DynamicGlue does not match.
[WARNING] Execution data for class org/eclipse/sisu/space/SpaceScanner$1 does not match.
```

These three classes contains references to shaded ASM in 1st module. The reason for this warning is that Jacoco Mojo goes for "wrong source" when it builds report. To example, the refd project consist of two modules:
1. sisu: compiles, and shades and relocates in ASM using maven-shade-plugin, but this happens in "packaging" phase (hence, 1st module target/classes contains unshaded/unrelocated classes). Still, the main artifact of reactor project provided correct classes.
2. tests: compiles, uses 1st module as dep and runs tests w/ Jacoco. Jacoco reports error that "classes does not match".

Reason: 2nd module will use for test artifact built by 1st module (so the JAR that has shaded and relocated ASM). But the ReportSupport class goes for target/classes directly https://github.com/jacoco/jacoco/blob/master/jacoco-maven-plugin/src/org/jacoco/maven/ReportSupport.java#L158-L159 (hence, warning is right, classes in target/classes and in shaded/relocated JAR are really not the same).

How to fix: the ReportSupport should get the main artifact of the processed project (a JAR) and process that one, and not the (potentially intermediate output) of target/classes.

**Comment by marchof** [comment]
Hi @cstamas, the JaCoCo Maven plug-in relies on the standard Maven project layout and is only configurable to a certain degree. If you want to fully customize the report generation we recommend to embed an [Ant script](https://www.jacoco.org/jacoco/trunk/doc/ant.html) where you can specify arbitrary locations for exec files, class files and source files.

**Comment by cstamas** [comment]
Howdy @marchof Sorry, but I cannot grasp what "JaCoCo Maven plug-in relies on the standard Maven project layout" should mean, given my issue reports exactly the opposite: JaCoCo Maven plugin does NOT rely on standard Maven project layout, given we are past package phase of module 1 (tests are run in module 2, we are past 1st module package phase), so main artifact is not target/classes anymore (it is just after the compilation), but the packaged JAR is. Still, jacoco maven plugin insists on "target/classes", that is wrong. Again, tests are running in 2nd module that, declare dependency on 1st module, so Maven will (correctly) hand over the packaged (and shaded) JAR as dependency, while JaCoCo will go for "compiled only" (but lacking any packaging/transformation/post-processing) target/classes.

This is not about customization at all, this is more about correctness of the plugin, as currently plugin does is wrong from Maven aspect: it should go for project main artifact, not the compiler output. Hence, this issue also means that ANY kind of processed classes/JAR (ie. AOP) will end up with "WARN" as well...
