### ISSUE TITLE
Gradle 8 breaks with failure to get output directory

### ISSUE THREAD

**Issue by thejeff77** [jacoco/jacoco#1402]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filing a useful bug report!

### Steps to reproduce

1. Update to gradle 8. 
2. Build your project.
3. Observe the following error:

```
Execution failed for task ':jacocoLogAggregatedCoverage'.
> 'org.gradle.api.provider.Provider org.gradle.api.reporting.Report.getOutputLocation()'
```

* JaCoCo version:  (from right bottom corner of JaCoCo report) 0.8.8
* Operating system: Ubuntu Latest (As of 2/15/23)
* Tool integration: Maven / Ant / CLI / API (for others please report to respective project) Gradle 8
* Complete executable reproducer: (e.g. GitHub Repo)
* Steps: (what exactly are you doing with the above reproducer?)

### Expected behaviour
Build succeeds

### Actual behaviour
Fails with error:

```
Execution failed for task ':jacocoLogAggregatedCoverage'.
> 'org.gradle.api.provider.Provider org.gradle.api.reporting.Report.getOutputLocation()'
```

(In case of exceptions provide FULL STACKTRACE)

**Comment by Godin** [comment]
The Gradle integration is maintained by the Gradle Project, not by the JaCoCo project - see https://www.jacoco.org/jacoco/trunk/doc/integrations.html and https://github.com/gradle/gradle/blob/v8.0.0/subprojects/jacoco/build.gradle.kts#L5
So please contact the Gradle project for questions/issues.
