### ISSUE TITLE
ArrayIndexOutOfBoundsExceptions with jmockit & jacocoagent

### ISSUE THREAD

**Issue by abhijitbude** [jacoco/jacoco#1419]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filing a useful bug report!

While generating the code coverage for unit tests using jmockit (v1.49) using the org.jacoco.agent-0.8.8-runtime.jar, I am getting exception as 
    _[junit] Index 3073 out of bounds for length 849
    [junit] java.lang.ArrayIndexOutOfBoundsException: Index 3073 out of bounds for length 849_

* JaCoCo version:  0.8.8
* Operating system: Linux - CentOS7
* Tool integration: Ant
* Complete executable reproducer: (e.g. GitHub Repo)
* Steps: (what exactly are you doing with the above reproducer?)

### Expected behaviour
The testcases should run successfully with classes instrumented for code coverage.

### Actual behaviour
Getting following exception:
    [junit] Testcase: com.test.MyTest.AppendStringAlgorithmTest:	Caused an ERROR
    [junit] Index 3073 out of bounds for length 849
    [junit] java.lang.ArrayIndexOutOfBoundsException: Index 3073 out of bounds for length 849
    [junit] 	at com.test.MyTest.AppendStringAlgorithmTest$1.<init>(AppendStringAlgorithmTest.java:32)
    [junit] 	at com.test.MyTest.AppendStringAlgorithmTest.setUpMocks(AppendStringAlgorithmTest.java:32)

If I replace the org.jacoco.agent-0.8.8-runtime.jar to older version like org.jacoco.agent-0.8.3-runtime.jar, the issue does not occur but the older version is not compatible with Java 17.

**Comment by Godin** [comment]
Quoting https://github.com/jmockit/jmockit1/issues/615#issuecomment-501009439

> JMockit should be fixed to properly handle condy (https://openjdk.java.net/jeps/309).
