### ISSUE TITLE
Project gets 0% coverage after switching from jacoco 0.8.7 to jacoco 0.8.10

### ISSUE THREAD

**Issue by steinarb** [jacoco/jacoco#1496]
I have several maven projects that follows more or less the same structure and inherit the same parent pom.

One of these maven projects went from 100% test coverage (it's a small project) to 0% coverage when I upgraded jacoco from 0.8.7 to 0.8.10

The other projects with the same parent and the same basic structure, still have the same coverage with jacoco 0.8.10 as they had with jacoco 0.8.7. I haven't been able to spot what's different in this project.

### Steps to reproduce

* JaCoCo version:  0.8.10
* Operating system: debian 12 "bookworm" on amd64
* Tool integration: maven 3.8.7, openjdk 17.0.7
* Complete executable reproducer: https://github.com/steinarb/osgi-service
* Steps:

  1. [Download sonarqube community edition](https://www.sonarsource.com/products/sonarqube/downloads/) unpack it and start it locally on the devmachine
  2. Clone and build the project with sonar reporting
      ```
      git clone https://github.com/steinarb/osgi-service.git
      mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dmaven.test.failure.ignore=false -Dsonar.host.url=http://localhost:9000 -Dsonar.login=admin -Dsonar.password=amdin
      ```
      (use the admin password you ended up setting in the sonarqube instance)

### Expected behaviour

Test coverage for the project in sonarqube is 100%

### Actual behaviour

Test coverage for the project in sonarqube is 0%

#### Additional information:

This project lost code coverage when moving from jacoco 0.8.7 to 0.8..10 https://github.com/steinarb/osgi-service

The jacoco-maven-plugin version is inherited from the pluginManagement of the parent: https://github.com/steinarb/bang-bompom/blob/master/bang-pom/pom.xml#L167

As far as I can tell this hasn't happened to any of my other projects that have gone through the same upgrades.

And I have many projects that have the same parent and follows more or less the same structure.

As far as I can tell, the jacoco.xml file containing the coverage information is the exact same file in the exact same place when using jacoco 0.8.10 as when using 0.8.10 (I use the multi-module project approach from a blog post I wrote: [How to get test coverage back in sonarcloud maven builds](https://steinar.bang.priv.no/2020/03/30/how-to-get-test-coverage-back-in-sonarcloud-maven-builds/)).

There are no extra error messages that I can see when building with jacoco 0.8.10. It's just that the coverage goes AWOL.

Interestingly the covereage is lost in both [sonarcloud](https://sonarcloud.io/summary/overall?id=steinarb_osgi-service)/sonarqube and on [coveralls.io](https://coveralls.io/github/steinarb/osgi-service)

**Comment by marchof** [comment]
Hi @steinarb, please understand that we cannot provide support for other products like Sonar here.

Can you please create JaCoCo html reports and check the coverage in these reports? Thx

**Comment by Godin** [comment]
> This project lost code coverage when moving from jacoco 0.8.7 to 0.8..10 https://github.com/steinarb/osgi-service

This doesn't seem to be related to the update of JaCoCo version, because

after checkout of your project at commit bfc0f8944250ae3a61dd41a6f8c98e4c2abe108f
and the following change (i.e. downgrade of parent pom version and update of JaCoCo version to `0.8.10`)

```diff
@@ -17,7 +17,7 @@
     <parent>
         <groupId>no.priv.bang.pom</groupId>
         <artifactId>bang-pom</artifactId>
-        <version>1.1.33</version>
+        <version>1.1.30</version>
     </parent>
     <groupId>no.priv.bang.osgiservice</groupId>
     <artifactId>osgiservice-parent</artifactId>
@@ -41,6 +41,15 @@
     </properties>

     <build>
+      <pluginManagement>
+        <plugins>
+            <plugin>
+                <groupId>org.jacoco</groupId>
+                <artifactId>jacoco-maven-plugin</artifactId>
+                <version>0.8.10</version>
+            </plugin>
+        </plugins>
+      </pluginManagement>
         <plugins>
             <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
```

execution of

```
mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify
```

produces the following JaCoCo HTML report

<img width="1143" alt="Screenshot 2023-07-17 at 10 58 50" src="https://github.com/jacoco/jacoco/assets/138671/c39a6cc6-a941-40dd-b76d-4f778c1f84ed">

Whereas the same command with the following modification (i.e. without downgrade of parent pom version and with JaCoCo version 0.8.7)

```diff
@@ -41,6 +41,15 @@
     </properties>

     <build>
+      <pluginManagement>
+        <plugins>
+            <plugin>
+                <groupId>org.jacoco</groupId>
+                <artifactId>jacoco-maven-plugin</artifactId>
+                <version>0.8.7</version>
+            </plugin>
+        </plugins>
+      </pluginManagement>
         <plugins>
             <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
```

produces the following report

<img width="1147" alt="Screenshot 2023-07-17 at 10 51 01" src="https://github.com/jacoco/jacoco/assets/138671/b18a85f3-a5cc-445d-8e4b-29c1ad27b791">

Therefore look at what else (besides JaCoCo version) changed in the parent pom.

**Comment by Godin** [comment]
The culprit is the following change - https://github.com/steinarb/bang-bompom/commit/b0bf04d503057301247234c2a366b1f89b54b94b
i.e. the same command after checkout of your project at commit bfc0f8944250ae3a61dd41a6f8c98e4c2abe108f
and the following change

```diff
@@ -41,6 +41,18 @@
     </properties>

     <build>
+      <pluginManagement>
+        <plugins>
+            <plugin>
+                    <groupId>org.apache.maven.plugins</groupId>
+                    <artifactId>maven-surefire-plugin</artifactId>
+                    <version>2.22.2</version>
+                    <configuration>
+                        <useSystemClassLoader>false</useSystemClassLoader>
+                    </configuration>
+                </plugin>
+        </plugins>
+      </pluginManagement>
         <plugins>
             <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
```

produces expected report.

**Comment by Godin** [comment]
`maven-surefire-plugin` version `3.0.0-M4` produces expected report, whereas `3.0.0-M5` does not

**Comment by Godin** [comment]
Before https://github.com/steinarb/osgi-service/commit/879553ebd9c94531c4d52565a87b3d946363a768
(i.e. before `maven-surefire-plugin` version update)

you had

```
[INFO] --- surefire:2.22.2:test (default-test) @ osgiservice.users ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running no.priv.bang.osgiservice.users.UserRolesTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 s - in no.priv.bang.osgiservice.users.UserRolesTest
[INFO] Running no.priv.bang.osgiservice.users.RoleTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in no.priv.bang.osgiservice.users.RoleTest
[INFO] Running no.priv.bang.osgiservice.users.UserManagementServiceTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.716 s - in no.priv.bang.osgiservice.users.UserManagementServiceTest
[INFO] Running no.priv.bang.osgiservice.users.UsersExceptionTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in no.priv.bang.osgiservice.users.UsersExceptionTest
[INFO] Running no.priv.bang.osgiservice.users.UserTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in no.priv.bang.osgiservice.users.UserTest
[INFO] Running no.priv.bang.osgiservice.users.PermissionTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in no.priv.bang.osgiservice.users.PermissionTest
[INFO] Running no.priv.bang.osgiservice.users.UsersPasswordsNotIdenticalExceptionTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in no.priv.bang.osgiservice.users.UsersPasswordsNotIdenticalExceptionTest
[INFO] Running no.priv.bang.osgiservice.users.UserAndPasswordsTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in no.priv.bang.osgiservice.users.UserAndPasswordsTest
[INFO] Running no.priv.bang.osgiservice.users.RolePermissionsTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in no.priv.bang.osgiservice.users.RolePermissionsTest
[INFO] Running no.priv.bang.osgiservice.users.UsersPasswordEmptyExceptionTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in no.priv.bang.osgiservice.users.UsersPasswordEmptyExceptionTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0
```

whereas after

```
[INFO] --- surefire:3.1.2:test (default-test) @ osgiservice.users ---
[INFO] Using auto detected provider org.apache.maven.surefire.junit4.JUnit4Provider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

no tests were executed, so no coverage as expected.
And why `maven-surefire-plugin` after upgrade does not execute your tests is clearly not a question to JaCoCo.

**Comment by Godin** [comment]
Tests are executed and the expected report is generated after the removal of `junit-platform-launcher` and `junit-platform-runner` from `test` dependencies - https://github.com/steinarb/osgi-service/pull/2
