### ISSUE TITLE
Jacoco agent not reading classes (0 coverage, 0 entries on sessions page) with tomcat .. but generates .exec file on tomcat bootup 

### ISSUE THREAD

**Issue by hjain25** [jacoco/jacoco#1498]
### No questions answered here

- [X] I understand that no quesions will be answered on this issue tracker

**Comment by hjain25** [comment]
I have a multi-module project whose build (.war file) is deployed in standalone tomcat. I have a set of integration test cases that gets fired from a different server. To get code coverage I am using jacoco agent attached with tomcat i.e. 

`-javaagent:/mypath/jacoco/jacocoagent.jar=destfile=/mypath/jacoco/coverage_dev.exec,output=file,append=true,includes=com.myapp*,dumponexit=true,classdumpdir=/mypath/jacoco/jacoco_classes/`

When I start tomcat the jacoco generates .exec file. After firing test case when I shutdown tomcat the .exec file remains empty. Also, no classes from triggered test cass are listed on sessions page. 

I have tried multiple workarounds to make it work like 

1. Make sure same JDK is being used to compile and run tomcat. 
2. Check debug info in class files by using javap. 
3. Using classDumpDir so that if tomcat is also intrumenting classes then jacoco uses only separate file and calculates coverage
4. Using jacoco as only java agent i.e. being the first java agent. 
5. Forcefully trying to dump the data with jacoco cli. 

But nothing seems to be working. Jacoco.exec file remains empty and the sessions page does not show any classes. 

Grateful for any hint or help here. 

-

**Comment by asthinasthi** [comment]
Can you try with `<includes>**`</includes>` and see if anything changes? We can narrow it down later
