### ISSUE TITLE
Need Actaul Branch coverage report as output

### ISSUE THREAD

**Issue by visu-suganya** [jacoco/jacoco#1504]
Normally C1 refers to Branch coverage

**What is Branch coverage?**
As per [this](https://en.wikipedia.org/wiki/Code_coverage) page , branch coverage covers only the overall outcome from a branch

**Example: - Branches:**
- if statements
- switch
- while
- for

**Example: Not Branches**
- boolean exp in return
- boolean assignments
these are not branches, because branches decides the flow of a program

Jacoco currently outputs conditions as branches in the report. This will be difficult for developers to fix all the conditions to improve the coverage
example: 
```
if(cond1 && cond2) {
  print "something"
}
```

In branch coverage, it should have only 2 branches
```
cond1 && cond2 = true
cond1 && cond2 = false
```
But Jacoco provides output as 4 branches:
<img width="714" alt="image" src="https://github.com/jacoco/jacoco/assets/122344105/322f88aa-76c1-4a57-aa74-8f3d6e58c2d0">

It will be baby step to achieve condition coverage(C2) without any burden.

**Comment by marchof** [comment]
In Java `&&` is the *conditional-and operator* (see [JLS](https://docs.oracle.com/javase/specs/jls/se17/html/jls-15.html#jls-15.23)) which means 

    if (cond1 && cond2) {
      print "something"
    }

is effectively compiled to

    if (cond1) {
        if (cond2) {
          print "something"
        }
    }

This is 2 x 2 branches = 4.

JaCoCo is based on Java bytecode and shows what the Java compiler actually generates.

**Comment by marchof** [comment]
@visu-suganya BTW if you use the *logical and operator* `&` you will see only two branches. We use the following integration test to verify that JaCoCo correctly reflects the JLS:

https://github.com/jacoco/jacoco/blob/master/org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/targets/BooleanExpressionsTarget.java

**Comment by visu-suganya** [comment]
Hi @marchof Thanks for the explanation about byte code working.
But take this example: condition assigned to a boolean variable
```test.java
boolean s = x > 0 || y > 0 ;
```
The jacoco result will be shown as 4 branches for line 7 and 8
Line 7 is not a branch in this case. It is statement.
<img width="731" alt="image" src="https://github.com/jacoco/jacoco/assets/122344105/08202221-3915-477b-bd97-70bdc66102e4">

Im having concern in the cases like this(condition assignemnt, condition in return statements)

**Comment by marchof** [comment]
Exactly the same same situation with the *conditional-and operator* which by specification requires lazy evaluation of the second branch.

As said above JaCoCo simply reflects how Java source code is compiled to bytecode. If you have questions or concerns about the Java language specification you may discuss this with the Java/OpenJDK project. But in this specific case I don't think they will change language fundamentals which have been in Java (and many other languages) since the the very beginning.

If you don't like the behaviour of conditional-and you can instead use `&` in your code.
