### ISSUE TITLE
Publish version 0.8.11

### ISSUE THREAD

**Issue by mbert** [jacoco/jacoco#1516]
People want to use the new switch syntax introduced by Java 11. Support for this has been built into Jacoco, but no release exists yet, that has this feature included. 

In some productive environments using snapshots is technically not possible or not an option, even if it is only for plugins. 

That's why I'd like to make a point for releasing 0.8.11, so that this rather important functionality is made available to users.

**Comment by marchof** [comment]
Please see FAQ: https://www.jacoco.org/jacoco/trunk/doc/faq.html

There will be a release soon. But please understand that we do not commit to any dates.
