### ISSUE TITLE
Reports contain invalid line="0" when using flatMapLatest() and combine() Kotlin coroutines functions

### ISSUE THREAD

**Issue by dzirbel** [jacoco/jacoco#1521]
### Steps to reproduce

* JaCoCo version:  0.8.9, 0.8.10 (not present in 0.8.8 and before)
* Operating system: Linux
* Tool integration: Gradle / Kotlin 1.9.10/1.8.22, Coroutines 1.7.3/1.6.4/1.5.2/1.4.3
* Complete executable reproducer: https://github.com/dzirbel/compose-playground/tree/jacoco
* Steps: run `./gradlew ./gradlew jacocoTestReport` and inspect `build/reports/jacoco/test/jacocoTestReport.xml` which contains elements with `line="0"` when using JaCoCo 0.8.9 or 0.8.10 (but not 0.8.8 or earlier)

### Expected behaviour

JaCoCo reports should not contain coverage with `line="0"`. I'm not personally familiar enough with JaCoCo reports to say whether there is a valid case for zero-indexed lines, but this does cause errors with Codecov's processing of my project's coverage reports (see https://github.com/codecov/feedback/issues/72). If Codecov's parser considers this invalid, others might as well. The change in behavior in 0.8.9 also suggests that this might be incorrect behavior.

See also my report to the Coroutines team: https://github.com/Kotlin/kotlinx.coroutines/issues/3911; I'm reporting it here as well since the behavior is tied specifically to a JaCoCo version change, but the root cause may be in Coroutines code generation, the Kotlin compiler, etc.

### Actual behaviour

JaCoCo generates reports with `line="0"` when using functions `flatMapLatest()` and `combine()` from Kotlin coroutines. These functions are somewhat unusual in that they are `inline` with lambda parameters marked both `crossinline` and `suspend`; these are the function signatures:
```
public inline fun <T, R> Flow<T>.flatMapLatest(@BuilderInference crossinline transform: suspend (value: T) -> Flow<R>): Flow<R>

public inline fun <reified T, R> combine(flows: Iterable<Flow<T>>, crossinline transform: suspend (Array<T>) -> R): Flow<R>
```

This branch of my sample project https://github.com/dzirbel/compose-playground/tree/jacoco demonstrates this issue on these very simple snippets:

```
import kotlinx.coroutines.flow.emptyFlow
import kotlinx.coroutines.flow.flatMapLatest

fun flatMapLatest() {
    emptyFlow<Unit>().flatMapLatest { emptyFlow<Unit>() }
}
```

which produces this in the JaCoCo report:

```
<class name="FlatMapLatestKt$foo$$inlined$flatMapLatest$1" sourcefilename="Merge.kt">
	<method desc="(Ljava/lang/Object;)Ljava/lang/Object;" line="0" name="invokeSuspend">
		<counter covered="0" missed="28" type="INSTRUCTION"/>
		<counter covered="0" missed="2" type="LINE"/>
		<counter covered="0" missed="1" type="COMPLEXITY"/>
		<counter covered="0" missed="1" type="METHOD"/>
	</method>
	<counter covered="0" missed="28" type="INSTRUCTION"/>
	<counter covered="0" missed="2" type="LINE"/>
	<counter covered="0" missed="1" type="COMPLEXITY"/>
	<counter covered="0" missed="1" type="METHOD"/>
	<counter covered="0" missed="1" type="CLASS"/>
</class>
```

and

```
import kotlinx.coroutines.flow.combine

fun combine() {
    combine<Unit, Unit>(emptyList()) { }
}
```

which produces:

```
<class name="CombineKt$bar$$inlined$combine$1$3" sourcefilename="Zip.kt">
	<method desc="(Ljava/lang/Object;)Ljava/lang/Object;" line="0" name="invokeSuspend">
		<counter covered="0" missed="29" type="INSTRUCTION"/>
		<counter covered="0" missed="2" type="LINE"/>
		<counter covered="0" missed="1" type="COMPLEXITY"/>
		<counter covered="0" missed="1" type="METHOD"/>
	</method>
	<counter covered="0" missed="29" type="INSTRUCTION"/>
	<counter covered="0" missed="2" type="LINE"/>
	<counter covered="0" missed="1" type="COMPLEXITY"/>
	<counter covered="0" missed="1" type="METHOD"/>
	<counter covered="0" missed="1" type="CLASS"/>
</class>
```

Using JaCoCo 0.8.8 marks these lines as 193 and 292, respectively. While those line numbers don't make much sense to me either they will at least be processed correctly downstream.

**Comment by marchof** [comment]
Hi @dzirbel, thanks for the detailed bug report!

JaCoCo runs on Java classfiles and uses the contained debug information to extract line numbers. The line numbers are inserted by the respective compiler. It is a known issue that the Kotlin compiler sometimes emits line number 0. Please report this to the Kotlin project.

So why don't you see line number 0 in older versions? Because this was a bug in ASM (https://gitlab.ow2.org/asm/asm/-/issues/317989) which has been fixed.

**Comment by dzirbel** [comment]
I see, thanks for the response! For future reference, I think https://github.com/Kotlin/kotlinx.coroutines/issues/3911 will be the main report going forward.

**Comment by Godin** [comment]
For the record: some time ago I did bisection of changes in Kotlin compiler (see https://github.com/jacoco/jacoco/issues/1471#issuecomment-1634317975), which unfortunately revealed change in the coroutines library (JetBrains/kotlin@a1b04a7) and not in the compiler. Unfortunately wasn't able to craft reproducer that doesn't rely on coroutines library. And unfortunately did not managed to bisect changes in the coroutines library, because was unable to build its older versions due to massive rework of external dependencies and repositories.

CC @qwwdfsad

**Comment by Godin** [comment]
🎉 here is reproducer that doesn't require coroutines library

`src/a/A.kt`
```
package a;

@Suppress("UNUSED_PARAMETER")
public fun a0(p: suspend () -> Unit) {
}

public inline fun a(crossinline p: suspend () -> Unit) = a0 { p() }
```

`src/b/B.kt`
```
package b;

fun b() {
  a.a { }
}
```

their separate compilation

```
kotlin-compiler-1.9.10/bin/kotlinc -d classes src/a
kotlin-compiler-1.9.10/bin/kotlinc -d classes -cp classes src/b
find . -name "*.class" -print0 | xargs -0 javap -v -p | grep "line 0"
```

leads to zero line numbers

```
        line 0: 3
        line 0: 44
```

**Comment by Godin** [comment]
And to me seems that this is a compiler bug that was introduced during a switch to IR-based back-end:
support for crossinline suspend lambdas was added in Kotlin compiler version `1.4.0` - see https://github.com/JetBrains/kotlin/commit/a1448ebb371e18532732980333fd51a1a945f0af
and for the above reproducer https://github.com/JetBrains/kotlin/releases/tag/v1.4-M1 produces zero line numbers only with `-Xuse-ir` option

**Comment by Godin** [comment]
FWIW the same still happens with Kotlin `2.0.0` compiler.
CC @qwwdfsad

**Comment by qwwdfsad** [comment]
This is indeed a bug that slipped into our BE.
The self-contained reproducer is really appreciated, thanks!

The issue to keep track of: https://youtrack.jetbrains.com/issue/KT-69283/Incorrect-synthetic-line-numbers-when-inlining-suspend-funs
