### ISSUE TITLE
Option to inline CSS and JS code into HTML code coverage reports

### ISSUE THREAD

**Issue by alzimmermsft** [jacoco/jacoco#1522]
### Scenario

* JaCoCo version: 0.8.9
* Operating system: All
* Tool integration: Maven
* Description of your use case: Scenarios where relative CSS and JS links don't work

### Current Behaviour

JaCoCo generates HTML code coverage reports using relative links to CSS and JS files contained in the `jacoco-resources` folder. When displaying reports in locations where relative links won't work the coverage report details (viewing the code file and visually seeing which lines are covered) doesn't work and it effectively just shows your code.

### Wanted Behaviour

A configuration, or command (either will work), where the code coverage HTML files are generated with the CSS and JS code inlined into the HTML file so they can be viewed anywhere or shared without needing to include the `jacoco-resources` folder.

I believe this will also resolve https://github.com/jacoco/jacoco/issues/1061 and similar cases.

### Possible Workarounds

A possible workaround is writing an external script to inline the CSS and JS files into each HTML code coverage result.

**Comment by marchof** [comment]
Hi @alzimmermsft, if you can't resolve relative links the report cannot be navigated at all, because everything is based on relative links. So I think I don't understand the use case here. Can you please explain how you would use the report?

CSS, Javascript and Icons are shared by design to keep the individual pages as small es possible (depending on the projects there can be hundreds of thousands of pages).

**Comment by alzimmermsft** [comment]
I dug a bit further and I was slightly off on relatively links not working. The environment is using a sandboxed iframe to present the code coverage report, but before showing the report it appears to strip out `<links>` and `<scripts>` based on viewing the web page source. It does appear to retain `<style>` tags.

**Comment by marchof** [comment]
In this case please report to the tool breaking the HTML report. Please understand that we cannot maintain workarounds other products. Thx.
