### ISSUE TITLE
A documentation is missing explaining how to create an aggregated maven site report

### ISSUE THREAD

**Issue by bgranier** [jacoco/jacoco#1527]
In the case of a multi modules maven project, there is a documentation explaining how to create a coverage report in each module, but there is no documentation explaining how to create an aggregated report and this is missing.

**Comment by marchof** [comment]
Here is the documentation: https://www.jacoco.org/jacoco/trunk/doc/report-aggregate-mojo.html

**Comment by bgranier** [comment]
@marchof a great thanks for your answer. 

That's right that the documentation that you provide explains how to create an aggregated coverage report in the build element. But my question is about to have an aggregated report in maven site - in the reporting element.

The documentation explains how to generate a coverage report for each module but not how to generate an aggregated maven site report.

Sincerly,

Bernard

**Comment by marchof** [comment]
@bgranier Thanks for the clarification! Do you have an example what you mean by Maven site? Probably we don't support what you expect.

**Comment by bgranier** [comment]
Hi,

Of course :) I have some example.

I opened a question on stackoverflow , you will see a configuration for some reports. [see](https://stackoverflow.com/questions/77303276/how-to-integrate-a-test-coverage-reports-in-maven-site-for-a-multi-modules-proje?noredirect=1#comment136280915_77303276).

There is the maven site documentation [see](https://maven.apache.org/plugins/maven-site-plugin/). For a multi modules project, two commands have to be executed: mvn site:site AND mvn site:stage.

There is Jacoco documentation [see](https://www.jacoco.org/jacoco/trunk/doc/maven.html). The documentation says "select non-aggregate reports". It would be great to have the aggregated report also.

Uncompressed the attached file, open index.html, on the top left, there is a grey box with a link "Project reports", click on the link and you will see some reports: javadoc, tests javadoc, dependencies check, unit tests reports thank to the maven-surefire-report-plugin. It would be great to have a coverage report also.

I will be happy to provide all needed informations.
[maven-site.zip](https://github.com/jacoco/jacoco/files/12935375/maven-site.zip)

**Comment by marchof** [comment]
So you mean that the report is linked in the site menu on the left? I don't think this is currently supported.

**Comment by bgranier** [comment]
Indeed the goal or the expected result or what I would like is to access to the coverage report from the site menu.

The rational is to access to keys project information from the index page and that all audit reports are available from the home page.

The website of the surfire plugin ([see](https://maven.apache.org/surefire/maven-surefire-plugin/project-reports.html)) provides an example of reports available from the home page.

Maybe this issue could be changed in feature request ?

Anyway thanks for all of your answers.
