### ISSUE TITLE
Branch coverage calculation error！！！！

### ISSUE THREAD

**Issue by SunYonge** [jacoco/jacoco#1537]
I don't understand why the branch coverage for this code is 0.33333. This is not a valid number. The code is as follows:
```
if (!isScrollAnimCompleted) {
      if (mCallerContext != null &&
          mCallerContext.sharedCallerContext.mISlideSceneAdAdapter != null &&
          mCallerContext.sharedCallerContext.slidePlayDataFetcher != null)
}
```
The branch coverage for
` if (!isScrollAnimCompleted) `
being 0.5 seems reasonable. However, the branch coverage for 
`if (mCallerContext != null && mCallerContext.sharedCallerContext.mISlideSceneAdAdapter != null &&           mCallerContext.sharedCallerContext.slidePlayDataFetcher != null) `
being 0.3333 is unusual.

I don't understand why the branch coverage for this code is 0.166666. 
```
 if (mSlipViewModel != null && currentPhoto != null && currentPhoto.isAd()) {
        isADOpen = mSlipViewModel.mSlideMode == SlideMode.SIDE_SLIP;
      }
```

How was this calculated?
we used org.jacoco:org.jacoco.core:0.8.7

**Comment by marchof** [comment]
In general code coverage depends on your tests. Without seeing the tests or better having a executable reproducer we cannot answer this question. Please use the Mailing list for questions.
