### ISSUE TITLE
Aspect method invoking chain doesn't have right coverage data

### ISSUE THREAD

**Issue by sanmuqingliang** [jacoco/jacoco#1543]
### Steps to reproduce

* JaCoCo version:  v0.8.10
* Operating system: Linux X86 64bit
* Tool integration: we use on-the-fly instrumenting class and Jacoco java agent
* Complete executable reproducer: sorry, there is't
* Steps: 
As shown in picture 1, the api method has an aspect(which is an around aspect),  and from picture 2, we see the aspect method invoke the next method ”getLegInstIds“, which is in picture 3.
From the api method's coverage data which is all green in picture 1 , and the aspect method coverage data which is green and yellow in picture 2,  the "getLegInstIds" method should have been invoked,  but in picture 3, we see the "getLegInstIds" method doesn't have coverage data.  
It isn't a problem with report generating, I checked the exec file's data, and found the "getLegInstIds" method probes were  false. I found this issue https://github.com/jacoco/jacoco/issues/1360,  but seems it isn't the same.  Because the whole api method is all green,  it means it doesn't throw an exception.  
Is this a known issue of Jacoco? Or Have I investigate the problem further?

picture 1:
![step1](https://github.com/jacoco/jacoco/assets/56817843/33328acf-4084-4853-88d2-11e6dd350223)

picture 2:
![step2](https://github.com/jacoco/jacoco/assets/56817843/e23bf902-89c8-4237-aa7d-187ba4c8772d)

picture 3:
![step3](https://github.com/jacoco/jacoco/assets/56817843/1f86942e-3b27-443f-ae68-c910f4ac4374)

**Comment by marchof** [comment]
Hi @sanmuqingliang This really depends on the aspect system you're using and how this is integrated with JaCoCo. Maybe the aspect code is inlined?

If you want to have someone look into this please provide an minimal, executable reproducer.

**Comment by sanmuqingliang** [comment]
> Hi @sanmuqingliang This really depends on the aspect system you're using and how this is integrated with JaCoCo. Maybe the aspect code is inlined?
> 
> If you want to have someone look into this please provide an minimal, executable reproducer.

Hi  @marchof  Thx for the advice. Because that is our product code, providing an executable reproducer is somewhat difficult. As I checked the code, the aspect was using Spring AOP.  We used on-the-fly jacoco agent,  I got and decompiled the byte code from the JVM instance which has been changed by Jacoco, and I also checked the probes' value from the exec file, I didn't find anything strange and didn't know how to find the root cause by myself. Could you help to give me some instructions on how to investigate this problem further?

**Comment by marchof** [comment]
Having literally no experience with the toolstack you're using there is really no advice I can give you. As said before: If you want someone to spend some time on this issue you have to spend your time for an isolated reproducer first. Also creating a minimal reproducer often helps to understand a problem.

**Comment by marchof** [comment]
We can't analyze this with the provided information in without a reproducer, sorry.
