### ISSUE TITLE
Partial branch coverage being shown on exhaustive switch statements

### ISSUE THREAD

**Issue by rishabharoraa** [jacoco/jacoco#1551]
Steps to reproduce

- JaCoCo version: 0.8.11
- Java version: 21.0.1
- Operating system: MacOS Ventura Version 13.5
- Tool integration: CLI

File I used `SwitchStatementTarget.java`
```java
public class SwitchStatementTarget {

	private enum E {
	        ZERO, ONE;
	}

	private static int target(E e) {
                int a = -1;
		switch (e) {
			case ZERO -> a = 0;
			case ONE -> a = 1;
		};
                return a;
	}

	public static void main(String[] args) {
		target(E.ZERO);
		target(E.ONE);
	}

}
```

By doing:
```
$ java -version
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM (build 21.0.1+12-LTS, mixed mode, sharing)

$ javac SwitchStatementTarget.java

$ java -javaagent:jacoco-0.8.11/lib/jacocoagent.jar SwitchStatementTarget 

$ java -jar ./jacoco-0.8.11/lib/jacococli.jar report jacoco.exec --classfiles SwitchStatementTarget.class --sourcefiles . --html report
```

### Expected behaviour
The report must show full coverage

### Actual behaviour
The report shows 1 missed branch

<img width="542" alt="image" src="https://github.com/jacoco/jacoco/assets/43946451/ffea5eba-4d21-4bf7-a183-534902688a96">

**Comment by Godin** [comment]
Duplicates #1531

**Comment by rishabharoraa** [comment]
@Godin this is for switch statements, not switch expressions

**Comment by Godin** [comment]
@rishabharoraa
Java compiler doesn't allow you to omit `a = -1` prior to your switch, because this switch isn't considered exhaustive by compiler

see also https://docs.oracle.com/en/java/javase/17/language/switch-expressions.html
> **Unlike switch statements**, the cases of switch expressions must be exhaustive

**Comment by ancap-kun** [comment]
The problem is nothing to do with switch expessions, the problem is in phantom branch, that is in fact doesn't exist and will never execute. Maybe drop branches from code coverage counter that guaranteed will be never executed?
