### ISSUE TITLE
Jacoco requires coverage threshold lower than generated coverage

### ISSUE THREAD

**Issue by jimshowalter** [jacoco/jacoco#1552]
The Jacoco report in Jenkins shows 95%:

![Screenshot 2023-12-11 at 9 58 12 AM](https://github.com/jacoco/jacoco/assets/211780/f80f1884-18b1-47bb-8e2b-075b44bd0692)

but we have to set the threshold lower or the build fails:

build.gradle:

`def static analysisExcludes() {
    return [
        ...
    ]
}

def execData() {
    return files(fileTree(buildDir).include("jacoco/*.exec"))
}

apply plugin: "jacoco"

jacoco {
    toolVersion = "${jacocoVersion}"
}

jacocoTestReport {
    getExecutionData().setFrom(execData())
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: analysisExcludes())
        }))
    }
}

jacocoTestCoverageVerification {
    getExecutionData().setFrom(execData());
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: analysisExcludes())
        }))
    }
    violationRules {
        rule {
            limit {
                minimum = new BigDecimal("${coverageMinimum}")
            }
        }
    }
}

task codeCoverageReport(type: JacocoReport) {
    executionData execData()
    sourceSets sourceSets.main
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: analysisExcludes())
        }))
    }
    reports {
        xml.required = true
        html.required = true
    }
}`

gradle.properties:

`jacocoVersion=0.8.10
googleJavaFormatVersion=0.9
googleJavaFormatToolVersion=1.18.1

# We actually have 95%, which you can see in Jenkins in the coverage report, but for some reason Jacoco doesn't
# see things that way. We've seen this in modules in other repos, and have never found a fix, or even an explanation.
coverageMinimum=0.92`

### Steps to reproduce

* JaCoCo version:  (from right bottom corner of JaCoCo report)
* jacocoVersion=0.8.10
googleJavaFormatVersion=0.9
googleJavaFormatToolVersion=1.18.1
* Operating system: RHEL8

* Steps: (what exactly are you doing with the above reproducer?)

We run coverage tests in Jenkins, it generates a Jacoco report that shows 95% coverage, but the above coverage check says coverage is only 92%, and fails the build.

### Expected behaviour

The 95% coverage and 95% coverageThreshold would match and the build wouldn't fail.

### Actual behaviour

The build fails and we have to lower coverageThreshold to 92%.

**Comment by marchof** [comment]
@jimshowalter Hard to tell what is going on here without knowing your build structure. My guess would be that the "jacocoTestCoverageVerification" has a different scope (for example single modules) while your snippet shows the overall coverage.

Anyways, the Gradle implementation is not maintained by us, I can't tell you how these gradle tasks collect coverage stats. Please check with Gradle project.
