### ISSUE TITLE
Jacoco merge/generate: Execution data for class does not match

### ISSUE THREAD

**Issue by p00j4** [jacoco/jacoco#1558]
### Expected behaviour
Should be able to generate and merge coverage results from class files and execution data priorly stored.

### Actual behaviour
Coverage generation/merging is failing with `Execution data for class does not match` for many of the files (working for some)

### Steps to reproduce
* JaCoCo version:  0.8.8 
* Operating system:  Linux 5.15.0-1050-azure amd64 Java: openjdk 17.0.9 2023-10-17 JVM: 1.8.0_382
* Tool integration: Gradle (which is calling Ant inside)
* Gradle 7.5 
* Kotlin: 1.6.21 
* Groovy: 3.0.10 Ant: Apache Ant(TM) version 1.10.11 compiled on July 10 2021

<img src="https://github.com/jacoco/jacoco/assets/6470509/eb520e60-99da-432b-9c16-96f0dc73121f" width="400" height="200">

![image](https://github.com/jacoco/jacoco/assets/6470509/85b919f8-77ca-4d53-98c8-9a43ceeefc1c)
I have plugged in Jacoco to capture coverage from my instrumented tests. 
While it's generating coverage for most of the files, at the same time for many files, it's failing with "Execution data for class <my_classes> does not match"

**Steps I followed:**

Step 1: with jacoco enabled, build  (jacocoDevDebug executed during the run)
Step 2: Save all the ".class" files to refer later
Step 3: Run tests with coverage on and saved the coverage ".ec" files 
Step 4: Download both (.ec and .class files)
Step 5: Given their path to  jacoco task to publish the coverage 
  
```
task jacocoInstrumentationReport(type: JacocoReport){
       group "Coverage"
       description "Generate XML, HTML, CSV code coverage reports coverage.ec"
        
       reports {
          csv.enabled true
          csv.destination file("${rootProject.buildDir}/jacoco/coverage-report.csv")
          xml.enabled true
          xml.destination file("${rootProject.buildDir}/jacoco/coverage-report.xml")
          html.enabled true
          html.destination file("${rootProject.buildDir}/jacoco/html-report")
        }
        def javaClasses = []
        def kotlinClasses = []
        def javaSrc = []
        def kotlinSrc = []
        def javaPath = "intermediates/javac"
        def kotlinPath = "tmp/kotlin-classes"
        
        javaSrc << "$proj.projectDir/src/main/java"
        kotlinSrc << "$proj.projectDir/src/main/kotlin"
        javaClasses << fileTree(dir: "<my_path>/build/${javaPath}/devDebug", excludes: fileFilter)
        kotlinClasses << fileTree(dir: "<my_path>/build/${kotlinPath}/devDebug", excludes: fileFilter)
        
        sourceDirectories.from = files([javaSrc, kotlinSrc])
        classDirectories.from = files([javaClasses, kotlinClasses])
        
        getExecutionData().setFrom(
        fileTree(dir: "code_coverage", includes: ['**/*.ec']))
       doLast {
         println("Generated Jacoco coverage report at ${rootProject.buildDir}/jacoco")
      }
}

```

What step maybe changing the .class files to make it feel different and marking as "does not match"?
Debug build setting has 
  - Minify false
  - Shrink false 

### Suspect:
Since we "assemble" (build) with one gradle task and trigger tests with other gradle task, and jacoco task without another gradle task. Is this the root cause? Does Jacoco needs same gradle task to execute tests and coverage generation? 
Eg. jacocoInstrumentationReport is not depending on the test task. 
If so, what alternative I can have to shard my tests? 
I distribute tests on different machines and on one machine, a few (say 3) emulators run the tests in parallel. Hence I need to wait for al shards (different machines) and all tests in each shard to compelte all the tests and then run the jacoco coverage generation task. 

**Note:** Originally posted on relatively right place [forum](https://groups.google.com/g/jacoco/c/2zcSu-Bngqg/m/dJ6KXCLEAQAJ), however still blocked on this hence posting it again here.
Highly appreciate if anyone can guide or help me

**Comment by marchof** [comment]
@p00j4 The only chance that we can investigate this is to have a reproducer. Please provide an standalone example as a GitHub repository that we can run and that shows the problem. Thx.

**Comment by bangoo1** [comment]
It was running fine on Gradle 7.0, but after upgrading to 7.4, I got the same issue. Any progress on this?

**Comment by marchof** [comment]
@bangoo1 As we don't have an reproducer we cannot analyze this.

**Comment by marchof** [comment]
Also note that if depends on your Gradle version this is probably related to Grade, which is not maintained by us. Please see https://www.jacoco.org/jacoco/trunk/doc/integrations.html

**Comment by p00j4** [comment]
In my case, the mini repro wasn't helping. 
However meanwhile I have found that it had to do with a transformation happening "Intune MAM Gradle plugin". 
Closing this for now. Will come back with reproducer if it still repeats after disabling MAM.
