### ISSUE TITLE
Using instrumented code for coverage

### ISSUE THREAD

**Issue by JTK79** [jacoco/jacoco#1562]
### No questions answered here

- [X] I understand that no quesions will be answered on this issue tracker

**Comment by JTK79** [comment]
We have a different situation, but I doubt it is unique.
Our code is over 25 years old and we want to produce code coverage.   We have automated tests but they are not junit.   The run in a "home grown runner".     We produce a server-type app that contains many different JARs, so what I tried to do is instrument the JARs and run our tests against these JARs to produce code coverage.   Also a caveat in our server is that java processes can created and destroyed,   So when a new java process starts or stops does that destroy previous coverage?   Also, I don't specify and jacoco properties - is there a default file location that the EXEC files are written?

**Comment by marchof** [comment]
Default location is `jacoco.exec` in current working directory. See documentation: https://www.jacoco.org/jacoco/trunk/doc/agent.html
