### ISSUE TITLE
Jacoco stopped reporting android unit test coverage

### ISSUE THREAD

**Issue by lukas1** [jacoco/jacoco#1563]
### Steps to reproduce

* JaCoCo version:  0.8.9~0.8.11
* Operating system: OSX
* Tool integration: Gradle 8.5
* Complete executable reproducer: 
[jacoco-unit-test-problem.zip](https://github.com/jacoco/jacoco/files/13935717/jacoco-unit-test-problem.zip)
* Steps: (what exactly are you doing with the above reproducer?)
Execute `./gradlew jacocoTestReport`

### Expected behaviour
Class `StringProvider` would be reported as 100% covered in Jacoco report

### Actual behaviour
Class `StringProvider` shows 0% coverage.

This worked with version 0.8.8, but stopped working with 0.8.9 and the issue persists in 0.8.11.

The reproducer is not configured to show it, but interestingly connected android tests do provide test coverage. It seems that the `.exec` file is ignored.

**Comment by marchof** [comment]
@lukas1 Thanks for the repoducer! Unfortunately I don't have an Android setup or experience and it looks like this involves some fiddling around with manual SDK installation. In GitHub codespaces I tried:

```bash
sudo apt update && sudo apt install -y android-sdk

wget https://github.com/jacoco/jacoco/files/13935717/jacoco-unit-test-problem.zip
unzip jacoco-unit-test-problem.zip
cd jacoco-unit-test-problem

echo "sdk.dir=/usr/lib/android-sdk" > local.properties
./gradlew jacocoTestReport
```

I end up with this error:

```
Checking the license for package Android SDK Build-Tools 34 in /usr/lib/android-sdk/licenses
Warning: License for package Android SDK Build-Tools 34 not accepted.
Checking the license for package Android SDK Platform 34 in /usr/lib/android-sdk/licenses
Warning: License for package Android SDK Platform 34 not accepted.

FAILURE: Build failed with an exception.
```


So I added a "Help Wanted", maybe someone with time and Android experience can have a look.

**Comment by lukas1** [comment]
I don't know how to work with Github Codespaces, I have never tried it, but based on the error message it seems you need to run this command before the actual build:

`yes | /usr/lib/android-sdk/tools/bin/sdkmanager --licenses`

**Comment by marchof** [comment]
@lukas1 Exactly. Except that the binary `sdkmanager` is not getting installed via package manager :(

You can simply start a code space from any of your repositories or a detached one from the GitHub menu. It will launch a VS Code UI in your browser and has a Ubuntu VM in the backend. This is my preferred way to execute reproducers without messing around with my notebook.

![image](https://github.com/jacoco/jacoco/assets/1936262/90830352-b3c0-4b20-9ac8-57e88fa00f6c)

**Comment by marchof** [comment]
Finally was able to get your reproducer running:

https://github.com/marchof/sketchbook/tree/jacoco-1563-android-unit-test-coverage

**Comment by marchof** [comment]
Ok, looks like a known Android SDK issue: If you set JaCoCo > 0.8.8 in `build.gradle` (e.g. 0.8.9) the tests run with both jacoco runtimes, 0.8.8 and 0.8.9 which is not supported by JaCoCo. You can only use one runtime at a time.

Please check with the Android project how to properly upgrade JaCoCo.
