### ISSUE TITLE
exhaustive switch expression is not fully covered

### ISSUE THREAD

**Issue by eortega-pjr** [jacoco/jacoco#1571]
I apologize if the terminology is incorrect. I wasn't getting full coverage on our fully-defined and exercised switch-expressions after upgrading to jacoco-8.11.0. 

I extended the original example here: https://github.com/jacoco/jacoco/pull/1472

---

* JaCoCo version: 0.8.11.202310140853
* Operating system: Linux
* Tool integration: none/javac
```
java version "21.0.1" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)
```

* Complete executable reproducer:
```java
enum Example {
    A, B;

    static void example(Example e) {
        switch (e) {
            case A -> {
                int i = 4;
            }
            case B -> {
                int i = 4;
            }
        }
    }

    public static void main(String[] args) {
        example(A);
        example(B);
    }
}
```
* Steps: (what exactly are you doing with the above reproducer?)
```
javac Example.java -d classes
java -javaagent:jacocoagent.jar -cp classes Example
java -jar jacococli.jar report jacoco.exec --classfiles classes --sourcefiles . --html report
```

### Expected behaviour
Full branch coverage

### Actual behaviour
![2024-01-24-163922_565x578_scrot](https://github.com/jacoco/jacoco/assets/87546380/6bad37c0-7831-43a2-8cf9-418b9d35acff)

Thanks.

**Comment by Godin** [comment]
This

```
switch (e) {
	 case A -> {
	 	 int i = 4;
	}
	 case B -> {
	 	 int i = 4;
	}
}
```

is **switch statement** and not switch expression. As proof - try to add a new constant to enum and you'll see that the compiler doesn't complain that switch is not exhaustive.

Duplicates #1531

**Comment by eortega-pjr** [comment]
oh wow

Thanks for the quick response @Godin!
