### ISSUE TITLE
It is laways good to show the in he horrizontal bar, gree <covered code lines %> first then red <how much still to be covered>

### ISSUE THREAD

**Issue by nagkumar** [jacoco/jacoco#1577]
https://www.jacoco.org/jacoco/trunk/coverage/

<img width="761" alt="image" src="https://github.com/jacoco/jacoco/assets/332234/3b42b5fd-2385-43d3-a7f0-a4be18d74cd7">

Currently uncovered % is shown first.. bit non intuitive

**Comment by nagkumar** [comment]
Every other report related to junit does follow green first and red later.. e.g PIT test report

<img width="1139" alt="image" src="https://github.com/jacoco/jacoco/assets/332234/eef9b9ea-c25c-4410-88d0-8c2c357d79e0">

**Comment by marchof** [comment]
This is by design because we encourage user to focus on the **uncovered** code. Also the bar does not show the percentage, but the total amount of uncovered code within the group -- which is also the default sorting.
