### ISSUE TITLE
report-aggregate for multi-module site does not produce correct reports

### ISSUE THREAD

**Issue by SiKing** [jacoco/jacoco#1592]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filing a useful bug report!

### Steps to reproduce

* JaCoCo version: 0.8.11
* Operating system: all
* Tool integration: Maven
* Complete executable reproducer: (e.g. GitHub Repo)
* Steps: (what exactly are you doing with the above reproducer?)

1. I have a multi-module Maven project. All my configurations are in the parent pom. Relevant portions of this pom are attached.
2. When I run `mvn clean test site` I get the expected jacoco reports: one in each of my modules.
3. If I change the report type to `report-aggregate`, only the last module (as per the Maven reactor order) report is correct. All the others are generated with 0% coverage.

[pom.txt](https://github.com/jacoco/jacoco/files/14608730/pom.txt)

### Expected behaviour

All reports should be generated: one for each module, and one aggregate of all the modules.

### Actual behaviour

Only the last module report is generated. All others have only zeroes
![Screenshot 2024-03-14 at 4 06 38 PM](https://github.com/jacoco/jacoco/assets/5496738/d6c090ec-fdaa-4c5b-abc0-bb12506d3bca)

**Comment by marchof** [comment]
Report aggregate requires a separate module. You cannot use it in the parent pom. See documentation:

https://www.jacoco.org/jacoco/trunk/doc/report-aggregate-mojo.html

**Comment by SiKing** [comment]
@marchof Could this be changed to a feature request?

I have bunch of other reports generated as -aggregate from my parent pom, and they work just fine. Would be nice if jacoco had the same behaviour?

**Comment by marchof** [comment]
@SiKing We wish this would be possible, too. We tried hard but the Maven lifecycle model does not support this. I noted some background information: https://github.com/jacoco/jacoco/wiki/MavenMultiModule
