### ISSUE TITLE
JaCoCo fails to build from sources for Fedora 40.

### ISSUE THREAD

**Issue by noloader** [jacoco/jacoco#1593]
Fedora is preparing for the Fedora 40 release. JaCoCo is failing to build from sources (FTBFS). The error is shown below from `build.log`:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project jacoco-maven-plugin: Compilation failure
[ERROR] /builddir/build/BUILD/jacoco-0.8.10/jacoco-maven-plugin/src/org/jacoco/maven/MergeMojo.java:[89,80] incompatible types: org.apache.maven.plugin.logging.Log cannot be converted to org.slf4j.Logger
```

Also see <https://bugzilla.redhat.com/show_bug.cgi?id=2261256>. It is the Fedora bug report, and it includes the build logs.

(I'm sorry I don't have more info. I wanted to report the issue in case the JaCoCo can lend a hand at getting through the issue)

**Comment by Godin** [comment]
Seems that you are trying to build JaCoCo version 0.8.10 with some modifications

> MergeMojo.java:[89,80] incompatible types: org.apache.maven.plugin.logging.Log cannot be converted to org.slf4j.Logger

here is line 89 in JaCoCo version 0.8.10

https://github.com/jacoco/jacoco/blob/8ea9668fa0272a6649e031f580c04ede04a7f17c/jacoco-maven-plugin/src/org/jacoco/maven/MergeMojo.java#L89

`FileSetManager` is from `org.apache.maven.shared:file-management` and its constructor starting from version `3.1.0` indeed accepts `org.slf4j.Logger` - see https://github.com/apache/maven-file-management/commit/c7153b197a9124ff8189310589adaf9e9534990a

However, JaCoCo version 0.8.10 did not depend on this version, but depended on
https://github.com/jacoco/jacoco/blob/8ea9668fa0272a6649e031f580c04ede04a7f17c/jacoco-maven-plugin/pom.xml#L53-L57

`org.apache.maven.shared:file-management` version `1.2.1` and its constructor accepts `org.apache.maven.plugin.logging.Log` - see https://github.com/apache/maven-file-management/blob/file-management-1.2.1/src/main/java/org/apache/maven/shared/model/fileset/util/FileSetManager.java

And BTW here is how the version of this dependency was updated in JaCoCo version 0.8.11 - https://github.com/jacoco/jacoco/commit/e0d9d0442e9d6caa98362db034ad76db819a8cc9

So this doesn't look to me as a bug on our side, but rather a problem on your side - please use the correct combination of JaCoCo sources and dependencies.
