### ISSUE TITLE
Excluding Generated annotation does not work if function has other annotations

### ISSUE THREAD

**Issue by szczepanski-k** [jacoco/jacoco#1630]
### Steps to reproduce

* JaCoCo version:  0.8.12
* Operating system: Mac OS
* Tool integration: Gradle
* Complete executable reproducer: ?
* Steps: 

Excluding Generated annotation does not work if function has other annotations:

```
@Retention(AnnotationRetention.RUNTIME)
@Target(
    AnnotationTarget.CLASS,
    AnnotationTarget.FUNCTION,
    AnnotationTarget.PROPERTY_GETTER,
    AnnotationTarget.PROPERTY_SETTER,
    AnnotationTarget.CONSTRUCTOR
)
annotation class ExcludeGenerated

@Preview
@Composable
@ExcludeGenerated
fun LayoutPreview_NotExcluded() {
        println("Some")
}

@ExcludeGenerated
fun LayoutPreview_Excluded() {
        println("Some")
}
```

### Expected behaviour

Function LayoutPreview_NotExcluded should be excluded same as LayoutPreview_Excluded

### Actual behaviour

Function LayoutPreview_NotExcluded is not excluded from the report

**Comment by szczepanski-k** [comment]
I'm closing this issue as invalid - I've double checked that the behavior is not in fact caused by additional annotations but by the composable function inside, so my example above was incorrect:

@Preview
@Composable
@ExcludeGenerated
fun LayoutPreview_Excluded() {
        println("test") // This is excluded
}

@Preview
@Composable
@ExcludeGenerated
fun LayoutPreview_NotExcluded() {
        Box {   // This is not excluded 
            ... rest of composable layout
        }
}

**Comment by Godin** [comment]
@szczepanski-k see https://github.com/jacoco/jacoco/issues/977 and https://github.com/jacoco/jacoco/issues/1208#issuecomment-1684133090
