### ISSUE TITLE
Jacoco version issue 

### ISSUE THREAD

**Issue by simhadri-git** [jacoco/jacoco#1636]
### Steps to reproduce

* JaCoCo version:  0.8.3 , Java version : Amazon corretto 17.0.7..7 (Open JDK)
* Operating system: windows
* Tool integration: Ant (ivy)
* Complete executable reproducer: vsts-Azure
* Steps: When running our tests thru Azure piplelines in the logs we are seeing the below errors. We tried to upgrade the jacoco version to latest but when we upgrade that some of the tests are failing due to Array Index out of bound exception.

Error Message when using jacoco version 0.8.3 👍 
--------------------------------------------------------------------------------------------------------------------------------------
[jacoco:coverage] Enhancing junit with coverage
    [junit] java.lang.instrument.IllegalClassFormatException: Error while instrumenting sun/util/resources/cldr/provider/CLDRLocaleDataMetaInfo.
    [junit] 	at org.jacoco.agent.rt.internal_43f5073.CoverageTransformer.transform(CoverageTransformer.java:94)
    [junit] 	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
    [junit] 	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    [junit] 	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
----------------------------------------------------------------------------------------------------------------------------------------

[junit] Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
    [junit] 	at org.jacoco.agent.rt.internal_43f5073.asm.ClassReader.<init>(ClassReader.java:195)
    [junit] 	at org.jacoco.agent.rt.internal_43f5073.asm.ClassReader.<init>(ClassReader.java:176)
    [junit] 	at org.jacoco.agent.rt.internal_43f5073.asm.ClassReader.<init>(ClassReader.java:162)

-----------------------------------------------------------------------------------------------------------------------------------------
    [junit] Tests run: 42, Failures: 1, Errors: 43, Skipped: 0, Time elapsed: 55.614 sec
    [junit] Exception in thread "main" com.lxnx.fab.eden.test.FunctionalTestExitException: Application has exited with exitStatus=2
    [junit] 	at com.lxnx.fab.eden.test.EdenTestHarness$FunctionalTestSecurityManager.checkExit(EdenTestHarness.java:128)
    [junit] 	at java.base/java.lang.Runtime.exit(Runtime.java:113)
    [junit] 	at java.base/java.lang.System.exit(System.java:1860)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1046)
--------------------------------------------------------------------------------------------------------------------------------------
[jacoco:coverage] Exception in thread "OkHttp TaskRunner" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Ref$IntRef
[jacoco:coverage] 	at okhttp3.internal.http2.Http2Connection.shutdown(Http2Connection.kt:419)
[jacoco:coverage] 	at okhttp3.internal.http2.Http2Connection.close$okhttp(Http2Connection.kt:449)
[jacoco:coverage] 	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:627

***********************************************************************************************************************************
Error Message  when I upgrade to latest version of Jacoco 0.8.12 👍 

Index 52570 out of bounds for length 12141

java.lang.ArrayIndexOutOfBoundsException: Index 52570 out of bounds for length 12141

**Comment by marchof** [comment]
JaCoCo 0.8.3 is from 2019 and does not support Java 17 which was released in 2021. If you encounter a problem with the latest version please file a bug report with the information requested in our form. Thanks!
