### ISSUE TITLE
Java Version Issue -0.8.12

### ISSUE THREAD

**Issue by simhadri-git** [jacoco/jacoco#1637]
Error Message when I upgrade to latest version of Jacoco 0.8.12 👍 with Open JDK 17

Windows - OS

Ant Configuration

Index 52570 out of bounds for length 12141

Error message when using jacoco 0.8.12:

java.lang.ArrayIndexOutOfBoundsException: Index 52570 out of bounds for length 12141

**Comment by marchof** [comment]
@simhadri-git Please provide the full stack trace, thanks!

**Comment by simhadri-git** [comment]
Error message
Index 52570 out of bounds for length 12141



Stack trace
java.lang.ArrayIndexOutOfBoundsException: Index 52570 out of bounds for length 12141
at com.lxnx.fab.eden.test.fakes.db.FakeDriverManager.<init>(FakeDriverManager.java:105)
at com.lxnx.fab.eden.test.fakes.db.FakeDriverManager.createFakeDriverManager(FakeDriverManager.java:55)
at com.lxnx.fab.eden.processing.conformancechecks.MNCRConformanceChecks_FunctionalTests.setUpFakes(MNCRConformanceChecks_FunctionalTests.java:67)
at com.lxnx.fab.eden.test.EdenTestHarness.setUp(EdenTestHarness.java:244)

**Comment by marchof** [comment]
@simhadri-git Is this the *full stacktrace? Isn't there any more nested stack traces below starting with "caused by"?

**Comment by simhadri-git** [comment]
That's all we have

**Comment by simhadri-git** [comment]
Can you please provide an update Asap.

**Comment by marchof** [comment]
@simhadri-git With this limited information we there is nothing we can do.

If you want us to analyze the problem please provide a executable reproducer (preferably a GitHub repo) where we can analyze your problem.

**Comment by marchof** [comment]
We don't have enough information to analyze this.
