### ISSUE TITLE
Coverage Report 0%

### ISSUE THREAD

**Issue by HamzahNaseer** [jacoco/jacoco#1638]
Steps to reproduce

* JaCoCo version:  0.8.12
* AGP Version 8.4.2
* Firebase performance SDK 'com.google.firebase:firebase-bom:33.1.0'

I am trying to make coverage report and i am also using firebase performance SDK because of which it shows 0 coverage. It shows coverage if i remove the firebase performance SDK.

Expected Behaviour:
It should show some coverage.

Actual Behaviour:
 It shows 0 coverage.

Logs:

> Task :app:testDevDebugUnitTestCoverage                                                                                                                                                
[ant:jacocoReport] Classes in bundle 'app' do not match with execution data. For report generation the same class files must be used as at runtime.                                     
[ant:jacocoReport] Execution data for class com/app/cm/persivia/viewmodels/AppViewModel$uploadFile$1 does not match.
[ant:jacocoReport] Execution data for class com/app/cm/persivia/viewmodels/TelehealthV2ViewModel$loginTelehealthUser$1$1 does not match.
[ant:jacocoReport] Execution data for class com/app/cm/persivia/viewmodels/TelehealthV2ViewModel$updateParticipantState$1 does not match.
[ant:jacocoReport] Execution data for class com/app/cm/persivia/viewmodels/TaskViewModel$getCampaignsBySoapNote$1 does not match.                                                       
[ant:jacocoReport] Execution data for class com/app/cm/persivia/viewmodels/EnterpriseViewModel$getSoapNoteSettings$1$1$1 does not match.                                                
[ant:jacocoReport] Execution data for class com/app/cm/persivia/viewmodels/DocumentsViewModel$getAllPatientsList$1 does not match.

**Comment by HamzahNaseer** [comment]
It shows coverage if i remove the firebase performance SDK

**Comment by marchof** [comment]
Then it looks line the "firebase performance SDK" somehow modifies the class files. This is not supported by JaCoCo. See documentation for background information:

https://www.jacoco.org/jacoco/trunk/doc/classids.html
