### ISSUE TITLE
Support excluding classes from reporting on CLI

### ISSUE THREAD

**Issue by ttho** [jacoco/jacoco#1639]
### Scenario

* JaCoCo version: 0.8.12
* Operating system: all
* Tool integration: CLI
* Description of your use case: Support excluding some classes from report generation on CLI as it is possible for ant (maybe also maven - did not check). 

Implementation is ready. See PR.

### Current Behaviour
With CLI it is not possible to exclude some classes from the report.

### Wanted Behaviour
CLI should allow pattern-based black-listing classes.

### Possible Workarounds
List classes to include one-by-one instead of providing directories.

**Comment by marchof** [comment]
See discussion at #1640
