### ISSUE TITLE
[Android Studio] UnitTest and Instrumentation testcases are passing 100% but in report Test Coverage is shown as 0%

### ISSUE THREAD

**Issue by pritamghosh0** [jacoco/jacoco#1641]
I'm using Jacoco to generate Unit test and Instrumentation test report. All of my testcases are running fine and the test report is generating fine as well in ```/app/build/reports/tests/testStagingUnitTest```. But in coverage report the coverage is showing as 0%. This is the stacktrace:
```
[ant:jacocoReport] Classes in bundle 'app' do not match with execution data. 
For report generation the same class files must be used as at runtime.
[ant:jacocoReport] Execution data for class {classPath} does not match.
```

**Environment information** 
Following are the version I'm using:
- Jacoco version: 0.8.11
- Android Gradle Plugin version: 7.3.0
- Jdk version: OpenJdk-11
- Android studio gradle Jdk version: OpenJdk-11
- Kotlin version: 1.7.10
- Kotlin Jvm target: 11
- Compile version: Java-11

I have also disabled code obfuscation using the following
```
            postprocessing {
                removeUnusedCode true
                removeUnusedResources true
                obfuscate false
                optimizeCode true
            }
```
I can't find any reason for Jacoco to not able to match the execution data with the original classes.

**Comment by ArunPaleti407** [comment]
I am also facing same issue, any resolution so far?

**Comment by marchof** [comment]
Note that we're neither working on Android Studio nor on Gradle. The Grade integration of JaCoCo is also done by the Gradle project. Please report this issue to the respective projects. Thanks!

**Comment by Godin** [comment]
In addition to what @marchof said, you @pritamghosh0 can also try to completely remove any `postprocessing`.

**Comment by pritamghosh0** [comment]
thanks @marchof and @Godin I was able solve this issue by removing firebase performance plugin. I'm not sure if the issue is related to jacoco or firebase performance plugin.

**Comment by dikshahike** [comment]
@pritamghosh0 , did you get any way where we use performance plugin with jacoco
