### ISSUE TITLE
Error while instrumenting - ClassTooLargeException

### ISSUE THREAD

**Issue by eldcn** [jacoco/jacoco#1653]
* JaCoCo version:  JaCoCo 0.8.11.202310140853/f33756c

### Steps to reproduce
We are using a dependency in our project that contains a [large class](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/formats/JsonParser.java) (over 80k lines of code). When instrumenting this class for our androidTest coverage, jacoco [Instrumentor](https://github.com/jacoco/jacoco/blob/master/org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java) fails the whole task with ClassToLargeException. Please find the full stacktrace below. Excluding the file from `coverageExclusions` below also does not help. This is how we setup jacoco for each module of our project:

```kotlin
// project build.gradle.kts

subprojects {
    ...
    ...
    setupJacoco()
}

fun Project.setupJacoco() {
    apply(plugin = "jacoco")
    val buildDir = layout.buildDirectory.get()
    val coverageExclusions = listOf(
        // Android
        "**/R.class",
        "**/R\$*.class",
        "**/BuildConfig.*",
        "**/Manifest*.*",
        "**/*_Hilt*.class",
        "**/Hilt_*.class",
        "**/*Activity.class",
        "**/*Application.class",
        "**/di/*Module.*",
    )
    val reportTask = tasks.register("jacocoCoverageReport", JacocoReport::class.java) {
        classDirectories.setFrom(
            fileTree("$buildDir/intermediates/classes/debug") {
                exclude(coverageExclusions)
            } + fileTree("$buildDir/tmp/kotlin-classes/debug") {
                exclude(coverageExclusions)
            }
        )
        reports {
            html.required.set(true)
            xml.required.set(true)
        }
        sourceDirectories.setFrom(files("$projectDir/src/main"))

        executionData.setFrom(
            files(
                "$buildDir/outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec"
            )
        )
        doLast {
            println("Jacoco report generated in: ${reports.html.outputLocation.get()}")
        }
    }

    tasks.withType<Test>().configureEach {
        configure<JacocoTaskExtension> {
            isIncludeNoLocationClasses = true
            excludes = listOf("jdk.internal.*")
        }
        finalizedBy(reportTask)
    }
}

```

We are not explicitly doing any setup for android tests coverage, it runs and generates the android tests report via the built in gradle task `createDebugAndroidTestCoverageReport`.

Do you have any hint how to overcome this issue via some configuration? Would it be possible to just catch the error in Instrumentor and ignore the file? Thanks in advance

FULL STACKTRACE:
[ClassTooLargeException.txt](https://github.com/user-attachments/files/16353236/ClassTooLargeException.txt)

**Comment by okostyuk** [comment]
Looks like it is not a Jacoco issue. 
Android Gradle Plugin calls the method org.jacoco.core.instr.Instrumenter.instrument(byte[] buffer, String name). 
And this method just throws an exception. 
I think it is a bug in the Android Gradle Plugin. They should use the Jacoco other way

**Comment by marchof** [comment]
JaCoCo collects coverage data by inserting additional code ("probes"). For very large classes the resulting class may exceed the technical limits of the Java specification. As a workaround you may split the class in smaller classes.

**Comment by marchof** [comment]
Re configuration of exclusions please contact the Gradle project (we don't work on this plugin).
