### ISSUE TITLE
Regular expression with non-literal value on jacoco report

### ISSUE THREAD

**Issue by JocheRDevelopment** [jacoco/jacoco#1654]
Description
The RegExp constructor was called with a non-literal value. If an adversary were able to supply a malicious regex, they could cause a Regular Expression Denial of Service (ReDoS) against the application. In Node applications, this could cause the entire application to no longer be responsive to other users' requests.

To remediate this issue, never allow user-supplied regular expressions. Instead, the regular expression should be hardcoded. If this is not possible, consider using an alternative regular expression engine such as node-re2. RE2 is a safe alternative that does not support backtracking, which is what leads to ReDoS.

Example using re2 which does not support backtracking (Note: it is still recommended to never use user-supplied input):

// Import the re2 module
const RE2 = require('re2');

function match(userSuppliedRegex, userInput) {
    // Create a RE2 object with the user supplied regex, this is relatively safe
    // due to RE2 not supporting backtracking which can be abused to cause long running
    // queries
    var re = new RE2(userSuppliedRegex);
    // Execute the regular expression against some userInput
    var result = re.exec(userInput);
    // Work with the result
}
For more information on Regular Expression DoS see:

https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS
Status: 
Needs triage
Severity:  Medium

* JaCoCo version:  (from right bottom corner of JaCoCo report)
* Operating system:
* Tool integration: Maven / Ant / CLI / API (for others please report to respective project)
* Complete executable reproducer: (e.g. GitHub Repo)
* Steps: (what exactly are you doing with the above reproducer?)

### Expected behaviour
vulnerability is not detected in my SAST scan.
### Actual behaviour
vulnerability is detected and suggested changes are to stop using Regular Expression with REG library
(In case of exceptions provide FULL STACKTRACE)

**Comment by Godin** [comment]
> non-literal value

does not mean 

> user-supplied regular expressions

and does not mean that

> adversary

will be

> able to supply a malicious regex

Moreover JaCoCo reports are not

> Node applications

**Comment by JocheRDevelopment** [comment]
I know this is not a Node application, but this comes from jacoco generated files on the reports

**Comment by Godin** [comment]
> non-literal value

does not mean

> user-supplied regular expressions

and does not mean that

> adversary

will be

> able to supply a malicious regex

**Comment by garysheppardjr** [comment]
@JocheRDevelopment is correct. This is a finding in JaCoCo's generated report, and it needs to be fixed.

It should be simple to fix by using an `RE2` object from the `re2` package instead of `RegExp` when the regular expression is a dynamic value.
