### ISSUE TITLE
Unabled to read report because tilde is attached to the extension

### ISSUE THREAD

**Issue by zooucat** [jacoco/jacoco#1656]
* JaCoCo version:  0.8.12
* Operating system: MacOS
* Tool integration: Maven

I generated HTML reports using the jacoco plugin. However, since the strings that make up the java file name are not included in the [`legal`](https://github.com/jacoco/jacoco/blob/master/org.jacoco.report/src/org/jacoco/report/internal/NormalizedFileNames.java#L42), it is generated with the name "_________Service.html". To make matters worse, even though it's actually a different java file name, since it gets replaced to `_`, so the HTML file name is duplicated and  and generated as "_________Service.html~1". Eventually, it will be downloaded by clicking the link connected to that file.

### Expected behaviour

- expect a unique string(`~idx`) to be present before the extension to ensure uniqueness

**Comment by Godin** [comment]
Steps to reproduce:

given `src/α.java`

```
public class α {}
```

and `src/β.java`

```
public class β {}
```

execution of

```
mkdir classes
javac -d classes src/α.java src/β.java
java -jar jacoco-0.8.12/lib/jacococli.jar report --classfiles classes --sourcefiles src --html report
ls -1 report/default/
```

produces

```
_.html
_.html~1
_.java.html
_.java.html~1
index.html
index.source.html
```
