### ISSUE TITLE
getting 0 coverage and only missed branch coming in jacoco report when in java 17

### ISSUE THREAD

**Issue by dikshahike** [jacoco/jacoco#1743]
### Steps to reproduce

* JaCoCo version:  0.8.12
* Operating system:
* Tool integration: Gradle
* Complete executable reproducer: (e.g. GitHub Repo)
* Steps: (what exactly are you doing with the above reproducer?)

**Comment by marchof** [comment]
@dikshahike We run integration tests for Java 5 to Java 24. JaCoCo definitely works with Java 17. The problem seems to be related to your environment. If you want us to look at it please provide an executable reproducer (preferable as a GitHub repository) which demonstrates the problem. Otherwise we cannot help here.

**Comment by dikshahike** [comment]
Hi mac, i can't share the working repo, but today I found one another view that after upgrade Android gradle plugin 7.1.0  to 7.2.0 i am getting same problem in java 11. let me know if any specific code can help you.

**Comment by dikshahike** [comment]
jacoco: 0.8.8 , AGP: 7.2.0, gradle: 7.6: Java 11: getting 0% coverage and missed branch 
jacoco: 0.8.8 , AGP: 7.1.0, gradle: 7.6: Java 11: Getting coverage more than 0

**Comment by marchof** [comment]
@dikshahike Without a reproducer there is nothing we can do here. Here are your options:

* Extract an minimal reproducer that you can share
* Neither the JaCoCo nor the Android Grade plugin is developed by us. You probably find better support at those projects.

**Comment by dikshahike** [comment]
could you please share some GitHub repo (for an example )where you find out the coverage on  latest Android Gradle plugin?

**Comment by Godin** [comment]
@dikshahike as @marchof already said in https://github.com/jacoco/jacoco/issues/1743#issuecomment-2407143089 - Android Gradle Plugin is not developed by us.
