### ISSUE TITLE
Ant Test CoverageTaskTest.testSecurityManager fails since JEP 486

### ISSUE THREAD

**Issue by marchof** [jacoco/jacoco#1779]
Since integration of [JEP 486](https://openjdk.org/jeps/486) in https://github.com/openjdk/jdk/commit/db85090553ab14a84c3ed0a2604dd56c5b6e6982 the Ant test CoverageTaskTest.testSecurityManager fails:

    testSecurityManager:
    [jacoco:coverage] Enhancing java with coverage
         [java] Error occurred during initialization of VM
         [java] java.lang.Error: A command line option has attempted to allow or enable the Security Manager. Enabling a Security Manager is not supported.
         [java] 	at java.lang.System.initPhase3(java.base@24-internal/System.java:2071)
         [java] 

I see two options to address this:

1. Remove this test
2. Execute this test only for JDK < 24, for example with JUnit assumptions

**Comment by marchof** [comment]
@Godin If you agree I would separate the security manager test into its own test suite and run is with < 24 only.

**Comment by Godin** [comment]
@marchof I definitely agree 👍  given that wide adoption of Java 24 will take some time, we should not remove the test completely. Thanks! ❤️
