### ISSUE TITLE
Coverage is missing a class that was in fact tested

### ISSUE THREAD

**Issue by sigurdknippenberg** [jacoco/jacoco#193]
I ran into a strange scenario today. We're using 0.6.1.201212231917, but I've reproduced the problem on 0.6.4.201312101107 as well.

When we run the build with coverage checks it is failing because one class was missed (message for 0.6.4.201312101107 was: Rule violated for bundle xxxx: classes missed count is 1, but expected maximum is 0).

But... the class is used by a number of test cases. I added System.out.println() statements to its constructor and it is being printed a number of times during test case execution, yet Jacoco shows no coverage for it.

I made a copy of the class and its test case with a new name, and they are picked up by Jacoco. I then removed the original class and test case and renamed the copies back to the original name and it is not picked up by Jacoco anymore. It almost seems like the class has a magic name that causes it to not be picked up.

Any ideas on what I should check to figure this out?

**Comment by marchof** [comment]
@sigurdknippenberg Are the any updates on this issue? Did you find a solution to your problem?

**Comment by jmaister** [comment]
I am getting the same problem. The JPA model classes are not added to the coverage results:

I get this messages from the execution for each model class:

    [ant:jacocoReport] Execution data for class com/[...]/model/AppData does not match.

The JPA provider used is OpenJPA that has an java-agent that has some Java class enhancement. Could this be the problem that the .class files do not match ?

**Comment by sigurdknippenberg** [comment]
@marchof - no. We just lowered the expected class coverage for this particular project from 100% to 90% to stop the build from failing.

**Comment by deepaksubu** [comment]
I have the same issue and I am using Jmockit to mock my classes

**Comment by marchof** [comment]
Known limitation.

**Comment by manoharyes** [comment]
Is there any workaround for this issue? With gradle we always have many classes skipped because of this issue. We started using powermock, but now its too late to get rid of powermock.

Desparately in need for a fix or workaround for this.

**Comment by Godin** [comment]
@manoharyes this thread seems unrelated to PowerMock, but answering your question: known workaround for PowerMock - is to use its latest version and JaCoCo Offline instrumentation ( see https://github.com/jacoco/jacoco/issues/51#issuecomment-257235159 from PowerMock maintainer )

In future instead of commenting on random issues please use our mailing list for questions - https://groups.google.com/forum/#!forum/jacoco

Thank you for your understanding.

**Comment by theangrydev** [comment]
For future readers, this issue also occurs with Mockito 2 final class mocking

**Comment by Godin** [comment]
@theangrydev 
> this issue also occurs with Mockito 2 final class mocking

This is supposed to be fixed in latest version of Mockito 2 - see https://github.com/mockito/mockito/issues/757 If you experience some problems, then please post minimalistic reproducer in our mailing list instead of commenting on random tickets. Thank you for your understanding.

**Comment by theangrydev** [comment]
@Godin Great, thanks for the information, I tried 2.2.28 and it worked fine. I was commenting here because it was one of the top hits when I was searching for my issue and so I figured it could help other people in the future that made their way here too.
