### ISSUE TITLE
Revoke support for Maven 2.2.*

### ISSUE THREAD

**Issue by mfriedenhagen** [jacoco/jacoco#194]
As decided on the Maven developer list, Maven 2.2.\* has reached [end-of-life](http://mail-archives.apache.org/mod_mbox/maven-dev/201402.mbox/%3CCA%2BnPnMzPNhkBqbj-Uz045Gt4j8%3DCiXBFCwnNGB0NZ38j-X%2BUvA%40mail.gmail.com%3E).

We may choose between 2 strategies:
1. Just do not fix any Maven 2.2.\* related issues and do not test jacoco-maven-plugin with this version anymore.
2. Go forward and make Maven 3.\* a prerequisite for building jacoco _and_ running the `jacoco-maven-plugin` _and_ remove any workarounds and documentation for running jacoco with Maven 2.2.*

@Godin, @marchof: your oppinions?

**Comment by marchof** [comment]
Should be asked on the mailing list whether there are any objections.
If we keep Maven 2.x we should least run integration tests.

**Comment by Godin** [comment]
Should be noted that support of Maven 2.x has been removed in SonarQube 5.0.

**Comment by Godin** [comment]
Another note is that Apache Maven Plugins are massively start to require 3.0 - http://mail-archives.apache.org/mod_mbox/maven-dev/201503.mbox/%3C20150320213920.6AE4B17423@minotaur.apache.org%3E

**Comment by khmarbaise** [comment]
Sorry to say that, but this is not true. See here: https://builds.apache.org/view/All/job/dist-tool-plugin/site/dist-tool-prerequisites.html. At the moment only  two plugins (maven-shade-plugin, maven-scm-publish-plugin) need Maven 3.X...and two plugins need Java 1.6 instead of Java 1.5 (maven-checkstyle-plugin, maven-pmd-plugin). (if you need Maven 2.2.1 support take a look here: http://maven.apache.org/maven-2.x-eol.html). What you are referencing is the plan we have...

**Comment by khmarbaise** [comment]
I would vote for leaving Maven 2 behind but would suggest to make a version dump for example to 1.0.0 to make clear something important has happened (Maven 3.X requirement).

**Comment by Godin** [comment]
Indeed, I was referring to plan:
> The next step on our roadmap is to lift all plugin versions to 3.0.0 to make clear those plugins will only work with Maven 3.0+ furthermore the Java minimum requirement will be lifted to JDK 1.6 as well.

to make our own plan ;) but thanks for correction @khmarbaise

And strictly speaking we don't need Maven 2 for builds/releases as they already on Maven 3 for a long time.

**Comment by Godin** [comment]
@marchof I executed integration tests manually with Maven 2.2.1 and unfortunately (but not really surprisingly) test for MergeMojo fails:
```
[INFO] Failed to configure plugin parameters for: org.jacoco:jacoco-maven-plugin:0.7.6-SNAPSHOT
Cause: Class 'java.util.List' cannot be instantiated
```
This is regression, which was introduced in version 0.7.1 (91e51b560798dd0927a21344b12c1de5a26049f7). Problem is well-known and was fixed immediately after initial implementation of mojo (0dbd9687afce808c115bd843ae596d3c10db9ac5).
I'm wondering why this wasn't catched by our users earlier? :wink:

**Comment by Godin** [comment]
@marchof finally I posted question in mailing list - https://groups.google.com/d/msg/jacoco/iqd_AP0Mq8o/z8fvcJIro4IJ

But in any case I feel that testing of only one Maven version might be not enough, so as a note to myself - seems that http://takari.io/book/70-testing.html might help in testing of many different versions in one shot without headaches.
