### ISSUE TITLE
Include M2E ignore file in jacoco-maven-plugin

### ISSUE THREAD

**Issue by ansell** [jacoco/jacoco#203]
Could jacoco include a file like the following with each of the goals that should not be run by M2E in the list of goals so that M2E users do not need to manually ignore it? The file needs to be in the plugin jar file at META-INF/m2e/lifecycle-mapping-metadata.xml

More documentation can be found at: http://wiki.eclipse.org/M2E_compatible_maven_plugins

    <lifecycleMappingMetadata>
      <pluginExecutions>
        <pluginExecution>
          <pluginExecutionFilter>
            <goals>
              <goal>some-goal</goal>
            </goals>
          </pluginExecutionFilter>
          <action>
            <ignore />
          </action>
        </pluginExecution>
      </pluginExecutions>
    </lifecycleMappingMetadata>

**Comment by rtack** [comment]
can this be closed? has it been released?

**Comment by Godin** [comment]
@rtack lifecycle mapping was added into Eclemma Eclipse plugin ( see jacoco/eclemma@d89be2834d4a98a8cd087024caa9d26a35276686 ), whereas this ticket is about addition directly into jacoco-maven-plugin, which wasn't done yet.

**Comment by rtack** [comment]
would a PR help solving this?

**Comment by ansell** [comment]
Yes, a PR would help. I am still a little confused by the build system here and where a resource would be added, as it doesn't look like it would be src/main/resources/META-INF/ as usual for maven.

**Comment by Godin** [comment]
@rtack @ansell could you please build plugin from PR #299 and check that all fine with M2E? And if so, it will be merged into master and available in next release.

**Comment by ansell** [comment]
I get a compilation error when I compile from the git repository using oracle jdk 8:

[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ org.jacoco.core.test ---
[INFO] Compiling 105 source files to /home/peter/gitrepos/jacoco/org.jacoco.core.test/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/peter/gitrepos/jacoco/org.jacoco.core.test/src/org/jacoco/core/test/validation/java8/LambdaExpressionsTarget.java:[26,10] error: lambda expressions are not supported in -source 1.5
[ERROR]   (use -source 8 or higher to enable lambda expressions)
/home/peter/gitrepos/jacoco/org.jacoco.core.test/src/org/jacoco/core/test/validation/java8/InterfaceDefaultMethodsTarget.java:[23,1] error: default methods are not supported in -source 1.5
[INFO] 2 errors 

Looking at the pom.xml file there is a profile that I could select to disable the compilation of those classes, but it isn't clear why the compilation should work for java-8 users, given that the source and target for the maven-compiler-plugin are both inherited from the maven.compiler.source and maven.compiler.target properties defined in the org.jacoco.build pom, with or without the profile being active.

My environment is Oracle JDK 8 on Ubuntu 14.04:
$ mvn -version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-12T06:58:10+10:00)
Maven home: /opt/apache-maven-3.2.3
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-46-generic", arch: "amd64", family: "unix"

After compiling using "mvn -Pno-java8-validation clean install", it seems to work.

I verified that the M2E error appears with 0.7.4.201502262128 but does not appear when I changed that to 0.7.5-SNAPSHOT to use my locally compiled version.

Thanks!

**Comment by Godin** [comment]
@ansell let's don't mix subjects - I created #300 to address difficulties with build. In the meantime #299 has been merged. Thank you for testing.

**Comment by ansell** [comment]
Sorry, didn't mean to confuse the issue, just describing what happened when I did the testing.

**Comment by Godin** [comment]
@ansell no pb.
