### ISSUE TITLE
java.lang.IllegalStateException: Class ... is already instrumented.

### ISSUE THREAD

**Issue by remmin** [jacoco/jacoco#208]
Hi,

I'm using the following jacoco  version

[ivy:resolve] 	found org.jacoco#org.jacoco.ant;0.7.0.201403182114 in public
[ivy:resolve] 	[0.7.0.201403182114] org.jacoco#org.jacoco.ant;latest.integration
[ivy:resolve] 	found org.jacoco#org.jacoco.core;0.7.0.201403182114 in public
[ivy:resolve] 	found org.ow2.asm#asm-debug-all;5.0 in public
[ivy:resolve] 	found org.jacoco#org.jacoco.report;0.7.0.201403182114 in public
[ivy:resolve] 	found org.jacoco#org.jacoco.agent;0.7.0.201403182114 in public
[ivy:resolve] 	found com.googlecode.jmockit#jmockit;1.7 in public
[ivy:resolve] 	[1.7] com.googlecode.jmockit#jmockit;latest.integration

together with jmockit. In one Unit Test I get this error here when running from junit with jacoco

    [junit] java.lang.instrument.IllegalClassFormatException: Error while instrumenting class com/mycompany/myproduct/DataPool.
    [junit] 	at org.jacoco.agent.rt.internal_38bf6f6.CoverageTransformer.transform(CoverageTransformer.java:89)
    [junit] 	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    [junit] 	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
    [junit] 	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
    [junit] 	at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:170)
    [junit] 	at mockit.internal.startup.Startup.redefineMethods(Startup.java:260)
    [junit] 	at mockit.internal.startup.Startup.redefineMethods(Startup.java:252)
    [junit] 	at mockit.internal.mockups.MockClassSetup.applyClassModifications(MockClassSetup.java:144)
    [junit] 	at mockit.internal.mockups.MockClassSetup.redefineMethodsInClassHierarchy(MockClassSetup.java:101)
    [junit] 	at mockit.internal.mockups.MockClassSetup.redefineMethods(MockClassSetup.java:87)
    [junit] 	at mockit.MockUp.redefineMethods(MockUp.java:117)
    [junit] 	at mockit.MockUp.redefineClassOrImplementInterface(MockUp.java:111)
    [junit] 	at mockit.MockUp.<init>(MockUp.java:74)
    [junit] 	at com.mycompany.testing.myproduct.TransitQueueTest$1.<init>(TransitQueueTest.java:92)
    [junit] 	at com.mycompany.testing.myproduct.TransitQueueTest.testMessageNotInTransitQueueWrongCorrId(TransitQueueTest.java:92)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:606)
    [junit] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    [junit] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    [junit] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    [junit] 	at mockit.integration.junit4.internal.JUnit4TestRunnerDecorator.executeTestMethod(JUnit4TestRunnerDecorator.java:134)
    [junit] 	at mockit.integration.junit4.internal.JUnit4TestRunnerDecorator.invokeExplosively(JUnit4TestRunnerDecorator.java:73)
    [junit] 	at mockit.integration.junit4.internal.MockFrameworkMethod.invokeExplosively(MockFrameworkMethod.java:32)
    [junit] 	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:606)
    [junit] 	at mockit.internal.util.MethodReflection.invokeWithCheckedThrows(MethodReflection.java:106)
    [junit] 	at mockit.internal.mockups.MockMethodBridge.callMock(MockMethodBridge.java:85)
    [junit] 	at mockit.internal.mockups.MockMethodBridge.invoke(MockMethodBridge.java:44)
    [junit] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java)
    [junit] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    [junit] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    [junit] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    [junit] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    [junit] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    [junit] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    [junit] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    [junit] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    [junit] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    [junit] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    [junit] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:532)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1165)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:988)
    [junit] Caused by: java.io.IOException: Error while instrumenting class com/myproduct/mycompany/DataPool.
    [junit] 	at org.jacoco.agent.rt.internal_38bf6f6.core.instr.Instrumenter.instrumentError(Instrumenter.java:164)
    [junit] 	at org.jacoco.agent.rt.internal_38bf6f6.core.instr.Instrumenter.instrument(Instrumenter.java:115)
    [junit] 	at org.jacoco.agent.rt.internal_38bf6f6.CoverageTransformer.transform(CoverageTransformer.java:87)
    [junit] 	... 47 more
    [junit] Caused by: java.lang.IllegalStateException: Class com/mycompany/myproduct/DataPool is already instrumented.
    [junit] 	at org.jacoco.agent.rt.internal_38bf6f6.core.internal.instr.InstrSupport.assertNotInstrumented(InstrSupport.java:81)
    [junit] 	at org.jacoco.agent.rt.internal_38bf6f6.core.internal.instr.ClassInstrumenter.visitField(ClassInstrumenter.java:79)
    [junit] 	at org.jacoco.agent.rt.internal_38bf6f6.asm.ClassVisitor.visitField(ClassVisitor.java:272)
    [junit] 	at org.jacoco.agent.rt.internal_38bf6f6.asm.ClassReader.readField(ClassReader.java:768)
    [junit] 	at org.jacoco.agent.rt.internal_38bf6f6.asm.ClassReader.accept(ClassReader.java:689)
    [junit] 	at org.jacoco.agent.rt.internal_38bf6f6.asm.ClassReader.accept(ClassReader.java:506)
    [junit] 	at org.jacoco.agent.rt.internal_38bf6f6.core.instr.Instrumenter.instrument(Instrumenter.java:95)
    [junit] 	at org.jacoco.agent.rt.internal_38bf6f6.core.instr.Instrumenter.instrument(Instrumenter.java:113)
    [junit] 	... 48 more

The unit test class uses jmockit  like this:

			 new MockUp<DataPool>() {
			        @Mock
			        public Message getMessageWithServiceSatzId(final Invocation inv, final String satzId) {

			        	Throwable t = new Throwable();
			        	for (int i = 0; i < t.getStackTrace().length; i++) {

			        		if (t.getStackTrace()[i].getMethodName().contains("sendAntwortMessageToMessageStore")) {
			        			LOGGER.warn("I'm faking");
			        			return null;
			        		}
			        	}
			        	return inv.proceed(satzId);
			        }
			    };

The idea of the mocked method is to return null only if has been called from a certain method. Not sure if this is the best way do it. Also I don't know if this triggers my exception above. The unit test itself (without jacoco) works fine.

What can I do to get rid of this exception ? 

Thanks for your help

**Comment by Godin** [comment]
@marchof quite an old report... do you need help with investigations of received files?

**Comment by marchof** [comment]
@Godin Forwarded the original email to you. I simply haven't found any time to investigate. Especially as we don't have a reproducer.

**Comment by andreicristianpetcu** [comment]
@marchof Did you say you cannot reporduce? I have this issue on my server. I think it's the same issue. What info do you need in order to fix it?

**Comment by Godin** [comment]
@andreicristianpetcu it will be very helpful, if you can share example of project which reproduces this and which we'll be able to build/execute easily in order to investigate in live what's going on.

**Comment by andreicristianpetcu** [comment]
@Godin I will try to provide a runnable project hopefully tomorrow :) Thank you for looking into this bug!

**Comment by andreicristianpetcu** [comment]
@Godin I made a small [project](https://github.com/andreicristianpetcu/jacoco-bug-208) that reproduces this bug. There is something strange happening at GitHub so if I refresh the project page once it shows it then it does not so I made a mirror in [GitLab](https://gitlab.com/andreicristianpetcu/jacoco-bug208). You can use which one is more useful for you :)

**Comment by Godin** [comment]
@andreicristianpetcu thx, I'll have a look

**Comment by Godin** [comment]
@andreicristianpetcu with @marchof we were discussing inability to reproduce case of deadlock which was faced by @remmin

In your case - it is wrong configuration. Duplicating here for the record my comment from https://github.com/andreicristianpetcu/jacoco-bug-208/pull/1 :

Do not mix offline instrumentation with online. Either use one or another. Otherwise online instrumentation will be trying to instrument classes, which already instrumented in offline, resulting in llegalStateException "Class ... is already instrumented".

It is possible to mix them, but classes instrumented in offline should be explicitly excluded from online instrumentation.

See http://eclemma.org/jacoco/trunk/doc/offline.html for more details

**Comment by andreicristianpetcu** [comment]
Thank you! Sorry for the noise on this thread. I thought I had the same issue :) Thank you for the information about the instrumentation.

**Comment by Godin** [comment]
@marchof @remmin I looked on stack dump and don't think that information in it sufficient to understand the problem. So I'm proposing to close this ticket, unless there is more information to understand/reproduce problem.

**Comment by marchof** [comment]
@Godin Agreed -> closed.
