### ISSUE TITLE
Includes in jacoco:report Maven Task Cause Blank Report

### ISSUE THREAD

**Issue by hborders** [jacoco/jacoco#221]
When I have an `<includes>` tag in my `jacoco:report` configuration, jacoco generates a blank report.

My entire project is very small [1], please check it out and see the effect for yourself. I've isolated the problem to this branch [2].

Relevant `pom.xml` section:

```
<execution>
    <id>post-unit-test</id>
    <phase>test</phase>
    <goals>
        <goal>report</goal>
    </goals>
    <configuration>
        <!-- Sets the path to the file which contains the 
        <dataFile>${project.build.directory}/coverage-reports/
        <includes>
            <include>com.example.Foo</include>
        </includes>
        <!-- Sets the output directory for the code coverage 
        <outputDirectory>${project.reporting.outputDirectory}/
    </configuration>
</execution>
```

[1] https://github.com/hborders/jacoco-coverage-example
[2] https://github.com/hborders/jacoco-coverage-example/tree/jacoco_report_includes_broken

**Comment by leochanus** [comment]
hborders, you said it works for you but it doesn't for me. Can you provide an example of your includes syntax?
