### ISSUE TITLE
Compatibility issue with android-maven-plugin 3.9.x or higher

### ISSUE THREAD

**Issue by kingargyle** [jacoco/jacoco#229]
I've reported this issue on the android-maven-plugins project as well.

https://github.com/jayway/maven-android-plugin/issues/421

Since upgrading to 3.9.x of that plugin, I get roughly half of the code coverage I get if I use their 3.7.0 version of the plugin.  With 3.7.0 and the latest Jacoco maven plugin, I get roughly 88% code coverage being reported.   With 3.9.x (any of the release candidates), I'm getting roughly 35% coverage reported.

I also get items like the following in the log which leads me to expect some classpath issues somewhere.

 Analyzed bundle 'Plexapp Android Client' with 745 classes
[WARNING] Classes in bundle 'Plexapp Android Client' do no match with execution data. For report generation the same class files must be used as at runtime.
[WARNING] Execution data for class android/support/v7/app/ActionBarImplJBMR2 does not match.
[WARNING] Execution data for class android/support/v7/app/ActionBarActivityDelegateICS does not match.
[WARNING] Execution data for class android/support/v7/app/ActionBarImplJB does not match.

Not sure where the issue lies as all I did was change the version number of the androind-maven-plugin.  They suggested it might be an issue here, so I'm covering the bases and reporting the issue against both projects.

**Comment by marchof** [comment]
@kingargyle ping... any updates on this?

**Comment by kingargyle** [comment]
No, I'll go ahead and close this until I have time to retest with the new 4.0 release.

**Comment by kingargyle** [comment]
This seems to be working with the latest 4.x releases.  I'm not seeing the issues that I was seeing with the 3.8 - 3.9 releases.  So I think we can close this issue.

**Comment by marchof** [comment]
Ok, thanks for the update!
