### ISSUE TITLE
"peer not authenticated" when publishing artifacts

### ISSUE THREAD

**Issue by marchof** [jacoco/jacoco#269]
Most of our snapshot builds do now [fail](https://jacoco.ci.cloudbees.com/job/jacoco-deploy/) because artifacts cannot be uploaded.

It is always the same SSL exception "peer not authenticated". The strange thing here is that a different number of uploads do work before a random upload fails.

It seems to be a [known issue](https://issues.sonatype.org/browse/OSSRH-8111) which can be resolved with adding

    -Dhttps.protocols="TLSv1"

to MAVEN_OPTS.

@Godin Do you have any chance to have a look into this and e.g. apply the TLS setting?

**Comment by Godin** [comment]
@marchof I'll check asap.

**Comment by Godin** [comment]
@marchof One of the problems is that in order to do atomic deployment we use Jenkins and not Maven.

**Comment by Godin** [comment]
@marchof I've updated Maven Integration Plugin in Jenkins - let's see if this will help. In the meantime I'll search for a way to do atomic deployment using just Maven, so that we'll be able to fully control configuration, e.g. force usage of TLSv1. If I won't find, then we can switch on non-atomic deployments.

**Comment by marchof** [comment]
@Godin Can't we open a ticket at CloudBees? This should be a quite common problem for them.

**Comment by Godin** [comment]
@marchof Indeed - it is an option. They already have page https://wiki.cloudbees.com/bin/view/DEV/SSLv3 , but there is nothing about Maven Integration Plugin. I'll contact them.

**Comment by marchof** [comment]
@Godin Did you get any response? Most of the builds are still failing due to the SSL problem.

**Comment by Godin** [comment]
@marchof Good news! We don't rely on Jenkins for deployment anymore (which is a good on its own), I've used latest version of maven-deploy-plugin instead, which allows to deploy at the end of build (see http://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#deployAtEnd). Before this change 1 build out of 2 sequential was failing, and after change - last three sequential builds are successful. So I'll close this ticket after commit with update for plugin version to avoid declaration of version in Jenkins.

**Comment by marchof** [comment]
@Godin Thx!
