### ISSUE TITLE
jacoco 0.7.1 - unable to get coverage for jnlp client launched using java ws

### ISSUE THREAD

**Issue by Harissh77** [jacoco/jacoco#274]
Am trying to get a coverage for a client functionality launched using java web start..

jacocoagent -  is of version 0.7.1 
Java - 1.8.0_25-b18

command used:
C:\harish>javaws -J-javaagent:C:\HG\jacocoagent.jar=destfile=C:\HG\jacoco.exec,jmx=true C:\jnlp.jnlp

however with the above command the client is launched and no coverage is found to be recorded into jacoco.exec and no error message too..

**Comment by marchof** [comment]
Is the jacoco.exec file created? What is its size?

**Comment by Harissh77** [comment]
The jacoco.exec file size is 0
anything i do on my app is not covered in the jacoco.exec

**Comment by Harissh77** [comment]
note : i got the coverage after i change my jdk version to 1.8.0_05 from 1.8.0_25

**Comment by marchof** [comment]
The coverage data is written when the JVM properly shuts down. If the JVM is killed (or CTRL+C on windows CMD) not coverage data can be written.

**Comment by Harissh77** [comment]
here in my case what happens is as soon as i pass the command C:\harish\>javaws  C:\jnlp.jnlp the jacoco.exec has been generated with 0 file size.. (even before the application is launched).. so do you mean the JVM instance is not running or it is killed as soon as my app is launched..

**Comment by marchof** [comment]
JaCoCo creates a empty exec file when the JVM starts and writes execution data to it when the JVM terminates (this is typically after when also your app terminates).

How do you terminate your application?

**Comment by Harissh77** [comment]
usually i terminate my application by clicking on the close button or by the menu option File > Exit.
as soon as i launch my app from command Prompt, my command prompt comes back

**Comment by Harissh77** [comment]
C:\>javaws C:/jacoco/jnlp.jnlp

C:\>

**Comment by Harissh77** [comment]
Hi marchof, 

  i saw a notification email from build hive, does that mean .. i need to download the latest javaagent and give a try.. please confirm...

-HG

**Comment by marchof** [comment]
No, this change set was not related. I have no idea why coverage dump doesn't work for you. I see two ways to make it working:

* Test with a simple hello world program (which terminates on its own) and see whether execution data is written. Then step by step test what the difference to your app is.
* Enable JMX for the JaCoCo agent and trigger a dump manually with JConsole before you terminate your application.

**Comment by marchof** [comment]
Can you please run your application with the JaCoCo agent from the following build? It creates system.out debug statements which should help to narrow down the issue.

http://download.eclipselab.org/jacoco/preview/jacoco-0.7.3.201501250606.zip

Can you please provide the system outout produced by the agent?

**Comment by marchof** [comment]
@Harissh77 Any updates on this? Could you run your scenario with the agent provided above with additional logging?

**Comment by simjeet** [comment]
where will it show the log information?

**Comment by marchof** [comment]
To the console with System.out

**Comment by simjeet** [comment]
One possible solution in case of jnlp applications is try using jars certified and verified by any authority or organisation.

**Comment by marchof** [comment]
No feedback --> Closed
