### ISSUE TITLE
ant task to generate PDF report 

### ISSUE THREAD

**Issue by sham-marol** [jacoco/jacoco#275]
Hi,

I am aware that by-default jacoco ant does provides an option to generate pdf report other than html, xml and csv. But was wondering if with minor tweaks to the ant script, whether I would be able to generate the pdf report on the fly instead of writing another program to convert from xml/html/csv to pdf.

**Comment by marchof** [comment]
JaCoCo does not support PDF reports. You might have a look at SonarQube which has a plug-in to create PDF reports for JaCoCo code coverage along with other project metrics.
