### ISSUE TITLE
Instrumentation of third-party code

### ISSUE THREAD

**Issue by henri-tremblay** [jacoco/jacoco#276]
It might not be a bug but I was a bit surprised. I had an issue with spring-batch. A clash on the jacocoData field as usual. The bug is in Spring. It shouldn't consider static fields in this case.

However, I was surprised that this class, a class in the Spring-batch-core jar, was instrumented. Why? I only want code coverage for my own classes so why do third party libraries getting instrumentation?

**Comment by marchof** [comment]
The JaCoCo agent sees and instruments all classes loaded into the JVM. It has no clue what "my own classes" are.

You can narrow the scope by defining the agent's includes property to e.g. com.mycompany.*

**Comment by henri-tremblay** [comment]
Thanks for the explanation.

Can an "instrumentLocalCodeOnly" option be useful? Filtering with something as dull as 
getClass().getProtectionDomain().getCodeSource().getLocation().toString().endsWith("/") or using the source directories from maven (with the maven plugin)

**Comment by marchof** [comment]
The JaCoCo agent works independent of Maven and does not make any assumptions on physical class file locations. That's why it also works with container like J2EE servers or OSGi containers.
