### ISSUE TITLE
no server side coverage when output=file and jacoco agent version > 0.6.1

### ISSUE THREAD

**Issue by plaxmijyothi** [jacoco/jacoco#278]
We are trying get code coverage for our integration tests. The server jvm includes the following argument:
`-javaagent:/Users/lakshmi/.m2/repository/org/jacoco/org.jacoco.agent/0.7.1.201405082137/org.jacoco.agent-0.7.1.201405082137-runtime.jar=destfile=/Users/lakshmi/git/my-test/my-api-ws-test/target/server-jacoco.exec,output=file,append=true,dumponexit=true`

With version > 0.6.1 (like the one mentioned in the example above), server-jacoco.exec is created with a size of 0B. The dump never happens. I verified that the server jvm shuts down gracefully.

Now, if I change the version of jacoco agent to 0.6.1 and leave everything else the same, I get all the coverage data as expected. With versions > 0.6.1 the output modes that have worked for me are tcpserver/tcpclient modes; output=file never worked.

Has anyone else experienced the same issue? (Searching through the mailing list archives, I do see some similar issues mentioned but none of them have a proper closure/follow up). Why does it work with 0.6.1 and not with later versions? Am I missing something?

Many thanks!

**Comment by marchof** [comment]
With 0.6.2 we basically changed the exec file creation behavior with issue #52: 
* A empty exec file is created a startup to ensure the configured location is writable and closed again
* At shutdown the same file is opened again and execution data is written to.
* In any case a file lock is acquired to avoid parallel writes

**Comment by marchof** [comment]
@plaxmijyothi Would it be possible for you to test a different jacocoagent.jar which I provide to you? In this case I would create a temp branch with detailed logging to System.out

**Comment by plaxmijyothi** [comment]
@marchof Definitely! I'd highly appreciate it, thanks! I'll test it as soon as I have it.

**Comment by marchof** [comment]
@plaxmijyothi Here is a special build that produces extra system.out logs during shutdown. You find the jacoco agent in the lib folder: http://download.eclipselab.org/jacoco/preview/jacoco-0.7.3.201501250606.zip

This is the corresponding branch: https://github.com/jacoco/jacoco/tree/agent-debug-logging

Can you please provide the system.out log?

**Comment by plaxmijyothi** [comment]
@marchof Thanks, will try this and get back to you in a week.

**Comment by marchof** [comment]
@plaxmijyothi Any updates on this issue?

**Comment by plaxmijyothi** [comment]
@marchof Sorry, I didn't get a chance to try it all these days. I'll give it a try today and will keep you posted. Thanks.

**Comment by plaxmijyothi** [comment]
@marchof I've attached an excerpt of the system.out log generated after using the custom jacoco agent for an IT test project (have to strip out all internal log statements).

It looks like the server side jacoco agent is shutting down right after unit tests. Looking at the strings in jacoco.exec also indicates the same thing, as there are several surefire classes being instrumented.

```
[INFO] --- maven-surefire-plugin:2.12:test (default-test) @ xxxxx-test ---
[INFO] Surefire report directory: /Users/lakshmi/git/xxxxx-test/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
[JaCoCo Agent] Starting agent with options destfile=/Users/lakshmi/git/xxxxx-test/target/jacoco.exec
[JaCoCo Agent] Opening file /Users/lakshmi/git/xxxxx-test/target/jacoco.exec
[JaCoCo Agent] Akquiring lock on file /Users/lakshmi/git/xxxxx-test/target/jacoco.exec
[JaCoCo Agent] Got lock on file /Users/lakshmi/git/xxxxx-test/target/jacoco.exec


[JaCoCo Agent] Shutting down agent
[JaCoCo Agent] Opening file /Users/lakshmi/git/xxxxx-test/target/jacoco.exec
[JaCoCo Agent] Akquiring lock on file /Users/lakshmi/git/xxxxx-test/target/jacoco.exec
[JaCoCo Agent] Got lock on file /Users/lakshmi/git/xxxxx-test/target/jacoco.exec
[JaCoCo Agent] Writing data to file /Users/lakshmi/git/xxxxx-test/target/jacoco.exec
[JaCoCo Agent] Execution data written


[INFO] --- maven-failsafe-plugin:2.16:integration-test (it) @ xxxxx-test ---
[INFO] Failsafe report directory: /Users/lakshmi/git/xxxxx-test/target/failsafe-reports
[INFO] Using configured provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
[INFO] parallel='none', perCoreThreadCount=true, threadCount=0, useUnlimitedThreads=false, threadCountSuites=0, threadCountClasses=0, threadCountMethods=0

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
[JaCoCo Agent] Starting agent with options destfile=/Users/lakshmi/git/xxxxx-test/target/headless-jacoco.exec
[JaCoCo Agent] Opening file /Users/lakshmi/git/xxxxx-test/target/headless-jacoco.exec
[JaCoCo Agent] Akquiring lock on file /Users/lakshmi/git/xxxxx-test/target/headless-jacoco.exec
[JaCoCo Agent] Got lock on file /Users/lakshmi/git/xxxxx-test/target/headless-jacoco.exec



[JaCoCo Agent] Shutting down agent
[JaCoCo Agent] Opening file /Users/lakshmi/git/xxxxx-test/target/headless-jacoco.exec
[JaCoCo Agent] Akquiring lock on file /Users/lakshmi/git/xxxxx-test/target/headless-jacoco.exec
[JaCoCo Agent] Got lock on file /Users/lakshmi/git/xxxxx-test/target/headless-jacoco.exec
[JaCoCo Agent] Writing data to file /Users/lakshmi/git/xxxxx-test/target/headless-jacoco.exec
[JaCoCo Agent] Execution data written
```

Should I be setting some property on the server side? Thanks for your help!

**Comment by marchof** [comment]
And the following files still have 0 bytes?

* /Users/lakshmi/git/xxxxx-test/target/jacoco.exec
* /Users/lakshmi/git/xxxxx-test/target/headless-jacoco.exec

This is strange. Maybe another faulty configuration overwrites them afterwards?

**Comment by plaxmijyothi** [comment]
These files have data:
* jacoco.exec 77K
* headless-jacoco.exec 90K

I looked into my configurations but I didn't find anything that overwrites them. As a workaround, when I configured the agent with output=tcpserver I get coverage for server-side classes.

**Comment by Godin** [comment]
@plaxmijyothi For me statement

> It looks like the server side jacoco agent is shutting down right after unit tests.

looks a bit ambiguous. From log there is two sets of tests - unit tests with maven-surefire-plugin and integration tests with maven-failsafe-plugin. If "server side" relates to integration tests, then this statement means that you see shutdown of JaCoCo agent before the end of integration tests? So could you please clarify?

And connected question - is it possible that something in your tests, triggers execution of JVM Shutdown Hooks before termination of all tests?

What will happen, if you'll disable all tests, except one? Will you receive coverage for this one in "output=file" mode? If not, then maybe you can reduce further and provide us a minimalistic example of project, which reproduces problem and doesn't contain internal/confidential details of your application?

Also: do you use "redirectTestOutputToFile"? If so then maybe some error messages during startup/work of JaCoCo in "output=file" mode were redirected to files and thus overlooked?

@marchof BTW this is and interesting question - why exceptions during startup are not fatal? see
https://github.com/jacoco/jacoco/blob/master/org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/Agent.java#L127

**Comment by plaxmijyothi** [comment]
Okay, I spent some time today to gather as much info as I can, and looks like I might have jumped on the gun a bit yesterday and overlooked a few things.

@Godin:
> If "server side" relates to integration tests, then this statement means that you see shutdown of JaCoCo agent before the end of integration tests? So could you please clarify?

No, the server is not started until failsafe plugin starts running IT tests. It is started as part of setup in IT tests.

> And connected question - is it possible that something in your tests, triggers execution of JVM Shutdown Hooks before termination of all tests?

I have checked again. Nothing of that sort seems to be happening. At the end of all tests, the server is shutdown as part of a 'teardown it test'.

> What will happen, if you'll disable all tests, except one? Will you receive coverage for this one in "output=file" mode?

Yeah, I've been running only one IT test that way, but I still cannot see the output.

> Also: do you use "redirectTestOutputToFile"? If so then maybe some error messages during startup/work of JaCoCo in "output=file" mode were redirected to files and thus overlooked?

Actually, this gave me a hint, so, thanks! I looked through all logs, and interestingly enough, in the server log, I see:

```
[JaCoCo Agent] Starting agent with options destfile=/Users/lakshmi/git/xxxxx-test/target/jacoco.exec
[JaCoCo Agent] Opening file /Users/lakshmi/git/xxxxx-test/target/jacoco.exec
[JaCoCo Agent] Akquiring lock on file /Users/lakshmi/git/xxxxx-test/target/jacoco.exec
[JaCoCo Agent] Got lock on file /Users/lakshmi/git/xxxxx-test/target/jacoco.exec
```
but no shutdown related statements. I looked at our scripts, and it seems like the server is not shutdown gracefully at times.

@marchof Sorry I was wrong about the file sizes, jacoco.exec is indeed 0B.

So it looks like it could be due to the server jvm not shutting down gracefully.However, when I change the version to 0.6.1.xxx, the coverage magically appears (jacoco.exec > 0B), and surprisingly even when the server was not shutdown gracefully. What changed from 0.6.1 that made the jacoco agent not write the execution (regardless of whether the shutdown was graceful or not)?

many thanks for your time and sorry for the confusion.

**Comment by marchof** [comment]
@plaxmijyothi The important change to 0.6.2 was that

1) A empty exec file is created a startup to ensure the specified location is writable
2) For every write operation to the exec file a file lock is akquired to avoid corrupted files due to concurrent writes.

See: http://www.eclemma.org/jacoco/trunk/doc/changes.html

**Comment by marchof** [comment]
@Godin Good question, I'll dig in history why it is implemented this way.

**Comment by Godin** [comment]
@marchof If for some reasons we can't have fail-fast approach always by default, then we can introduce switch - or to switch off strict mode with fail-fast, or to switch on.

**Comment by Godin** [comment]
@marchof And we can use this approach not only for errors during startup, but for all errors.

**Comment by Godin** [comment]
@marchof BTW I don't see how this change in 0.6.2 leads to change of behavior in case of non-graceful shutdown, i.e. I don't see how 0.6.1 could gather coverage - they both use same mechanism of shutdown hook. What I miss?

**Comment by marchof** [comment]
@Godin Same here. Maybe the additional steps like locking the file do not work out any more during shutdown. That's why I created the snapshot build with additional debug information. But somehow I don't understand how @plaxmijyothi 's debug output and empty exec filed go together.

**Comment by Godin** [comment]
@marchof Another thing which I can't correlate - how you can have non-graceful shutdown of JVM without complains from maven-failsafe-plugin. The only option, which comes to my mind - another JVM is spawned during integration tests with same options including agent, and exactly this JVM isn't terminated correctly, but not the one which executes tests. @plaxmijyothi is it the case? And anyway - would be really nice to receive reproducer from you.

**Comment by Godin** [comment]
@marchof Oh, I've re-read message from @plaxmijyothi and indeed seems that "server" is a
spawned process! This answers my question. Regarding zero size - maybe it is consequence of the fact that spawned process terminates exactly at the moment of writing?
If there is no other affecting factors (like version of JVM, operating system, type of file-system or whatever else), then creation of reproducer should be straightforward. And I'll try to do it to check difference between 0.6.1 and 0.6.2.

**Comment by marchof** [comment]
Actually @plaxmijyothi writes that on the server side the log entry

    [JaCoCo Agent] Execution data written

is missing
