### ISSUE TITLE
Exceptions cause surrounding area to be counted as uncovered

### ISSUE THREAD

**Issue by col6y** [jacoco/jacoco#279]
With the following self-contained example, I get output and code coverage results that disagree.

Notice that the line that prints `"I'm here!"` is highlighted in red, but the output still shows up. (This example may seem arbitrary, but I was running into this with a real codebase and the `wait()` method in an interrupted thread.) I'm pretty sure that this isn't a issue with my code, though I'm not certain.

I would expect the output and the coverage results to agree on what code got executed and what didn't get executed.

(I'm using jacoco-0.7.3-20150122.155523-39)

    public class SCD {
        public static void main(String[] args) throws Exception {
            try {
                System.out.println("I'm here!");
                error();
            } catch (Exception ex) {
                System.out.println("Oops...");
            }
        }
        private static void error() throws Exception {
            throw new Exception();
        }
    }

![jacoco](https://cloud.githubusercontent.com/assets/5056099/5886119/0b09b31a-a33f-11e4-9c9f-efbbc6041300.png)

Output:

    Buildfile: C:\Users\[...]\tests.xml
    run-tests:
       [delete] Deleting directory C:\Users\[...]\coverage-report
       [delete] Deleting: C:\Users\[...]\jacoco.exec
    [jacoco:coverage] Enhancing java with coverage
         [java] I'm here!
         [java] Oops...
    [jacoco:report] Loading execution data file C:\Users\[...]\jacoco.exec
    [jacoco:report] Writing bundle '[...]' with 305 classes
    BUILD SUCCESSFUL
    Total time: 7 seconds

**Comment by marchof** [comment]
This is a known limitation of JaCoCo. Please see [FAQ](http://www.eclemma.org/jacoco/trunk/doc/faq.html). Basically it is a tradeoff between coverage in case of exceptions and runtime performance. 

### Code with exceptions shows no coverage. Why?

JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and not marked as executed.
