### ISSUE TITLE
[v0.7.2] Coverage not being build for catch clauses which are rethrowing exceptions

### ISSUE THREAD

**Issue by hirthwork** [jacoco/jacoco#281]
I have a pretty simple class with four member functions: a(), b(), c() and d():
main() calls d(), d() calls b() inside try-catch block, b() calls a() and a() throws an Exception.
Inside catch block of d(), message is being printed to System.out, then c() will be called and exception will be rethrown.
Here the complete example (except package name, which was erased for compatibility): http://ideone.com/QlsIvB
After program execution I see that message was printed to stdout, but when I build the coverage I see that call to System.out.println wasn't counted as executed: http://dump.bitcheese.net/images/egyceza/jacoco.png

How I can workaround such behaviour?

**Comment by marchof** [comment]
his is a known limitation of JaCoCo. Please see [FAQ](http://www.eclemma.org/jacoco/trunk/doc/faq.html). Basically it is a tradeoff between coverage in case of exceptions and runtime performance. 

### Code with exceptions shows no coverage. Why?

JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and not marked as executed.

**Comment by hirthwork** [comment]
Thank you for prompt response,
Let's assume I don't care about runtime performance during unit-testing, but wish to have fair code coverage report for error handling scenarios. What pieces of code should I change to have probes set for all [flow edges](http://www.eclemma.org/jacoco/trunk/doc/flow.html)?

**Comment by andrioli** [comment]
@hirthwork note that every instructions in a try-catch block have a "virtual" edge to the exception handler. So basically, for the most precise coverage you will need a probe per instruction.

obviously, not all instructions throws an exception. But there a set of JVM instructions that you need to care about.

**Comment by hirthwork** [comment]
I perfectly understand that precise coverage measurement will require probes after each instruction and I ready for performance penalties. I just need some hint on entry point in JaCoCo source code to start investigation.

**Comment by marchof** [comment]
There is some discussion about this topic in PR #261 The idea is to add additional probes at least for method invocations.

It would partly solve @hirthwork 's issue: At the lease the "System.out" line would be green. The methods throwing exceptions would still be red.
