### ISSUE TITLE
code coverage report not generated for jnlp based  applications

### ISSUE THREAD

**Issue by simjeet** [jacoco/jacoco#283]
Hi I am trying to generate a code coverage report for my jnlp application.
Report is getting generated with build jacoco-0.6.1.201212231917 of jacocoagent but not for jacoco-0.7.2.201409121644 version. hooking the java agent with 'set JAVA_TOOL_OPTIONS=-javaagent:C:\project\code\jacocoagent.jar' command and running my application using 'javaws https:myweb/TestJnlp.jnlp' command
File is created but no coverage report written into it.
Thanks .

**Comment by marchof** [comment]
Same problem here: #274 

Can you please try the JaCoCo build with additional debug information as referenced in the other issue?

**Comment by simjeet** [comment]
i did the it. The thing that is creating problem is locking the file .
