### ISSUE TITLE
ArrayIndexOutOfBoundsException in combination of Agent 0.7.3 and Analyzer 0.7.1

### ISSUE THREAD

**Issue by Godin** [jacoco/jacoco#285]
Can be reproduced using following code:
```
public class Example {
  boolean method(Object param) {
    if (param == null) {
      return false;
    } else {
      try {
        return true;
      } catch (Exception e) {
      }
    }
    return true;
  }
}
```
Seems that this relates to changes for #265.

**Comment by marchof** [comment]
From the exec files are different numbers of probes for the Example class:
* 0.7.1: 5 probes
* 0.7.2: 5 probes
* 0.7.3: 4 probes

**Comment by Godin** [comment]
@marchof I confirm that #286 also fixes this issue.
