### ISSUE TITLE
JSR-045 SourceDebugExtension HowTo

### ISSUE THREAD

**Issue by melvinma** [jacoco/jacoco#293]
This is actually not an issue. However, since no response on my posting in StackOverflow. I thought I will try my luck here. I will really appreciate any help!

http://stackoverflow.com/questions/28844652/jacoco-coverage-report-of-dsl

---- here is a summary:
I am writing a customer Jacoco coverage report of my DSL file. Here is what I did -

1> get analyzing data (similar to http://www.eclemma.org/jacoco/trunk/doc/examples/java/CoreTutorial.java)

2> generate the report (similar to http://www.eclemma.org/jacoco/trunk/doc/examples/java/ReportGenerator.java).

Now, the differences are: I created SMAP file (following JSR-045) and attached the file to the class file as SourceDebugExtention. I could not independently verify this step is successful - except that, on the Eclipse debugger, it looks differently and looks like working. However, the debugger could not load my text file and I could not really tell if it is successful.

Now, I am expecting that after analyzing, I get a report of DSL coverage. What I found is, if I merge the data with Java file, it looks perfectly matching. But if I merge the data with DSL file, it does not match at all. It seems the "SourceDebugExtension" is not turned on. How should I enable it? 

Looking at the code, the problem seems org.jacoco.core.analysis.Analyzer class -

public void analyzeClass(final ClassReader reader) {
    final ClassVisitor visitor = createAnalyzingVisitor(
            CRC64.checksum(reader.b), reader.getClassName());
    reader.accept(visitor, 0);
}
It seems I should change "reader.accept" line to add Attribute. I created an Attribute with type as SourceDebugExtension but that did not help at all.

**Comment by marchof** [comment]
This is the JaCoCo project bug tracker. Maybe try our mailing list to get some audience.
