### ISSUE TITLE
on HTML and XML resports request, generated only HTML

### ISSUE THREAD

**Issue by OleksandrKucherenko** [jacoco/jacoco#295]
I catch a strange behavior, I request two reports generation at the same time, but produced only HTML version of it.

Any idea how to trace what can be wrong? any deep logging of Jacoco Report Ant/Gradle task supported?

**Comment by marchof** [comment]
https://gradle.org/docs/current/userguide/jacoco_plugin.html

The Gradle tasks are provided by the Gradle project. Please report the issue there.
