### ISSUE TITLE
Jacoco reports coverage for empty private constructors

### ISSUE THREAD

**Issue by veita** [jacoco/jacoco#298]
However, empty private constructors are quite common to prevent classes from being instantiated.

As a result in such cases Jacoco reports code coverage worse than it actually is.

It would be nice to have a mechanism to handle this case, e.g. with an annotation or whitelist.

**Comment by marchof** [comment]
Such a feature would be part of the filtering story #15. The case is on the list:

https://github.com/jacoco/jacoco/wiki/FilteringOptions
