### ISSUE TITLE
JaCoCo should shade the ASM dependency to not interfere with other versions of ASM used by projects under test

### ISSUE THREAD

**Issue by centic9** [jacoco/jacoco#304]
We have a set of projects which still require older versions of ASM due to some 3rd party dependencies. Now when I try to add JaCoCo support to the Gradle build via the JaCoCo plugin of Gradle, I get strange exceptions being thrown because ASM changed classes from interfaces to abstract classes between one of the major version upgrades.

In order to reduce the effect of such dependencies of the JaCoCo agent to a bare minimum, it would be good to shade the asm dependency into a custom package-namespace, similar to what e.g. the javaagent from kohsuke/file-leak-detector does, see the [pom.xml](https://github.com/kohsuke/file-leak-detector/blob/master/pom.xml) at https://github.com/kohsuke/file-leak-detector for how it is done there

**Comment by Godin** [comment]
@centic9 dependencies of agent already shaded, maybe you are looking on wrong jar? check content of 
http://search.maven.org/remotecontent?filepath=org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128-runtime.jar

**Comment by Godin** [comment]
@centic9 also as you mention Gradle plugin - this might be an issue with it, in this case issue should be reported to maintainers of this plugin

**Comment by centic9** [comment]
Ah, I didn't thing the plugin would interfere so much here, so maybe we can tell Gradle to keep the Eclipse classpath clean. Thanks for the info, this one is a non-issue here, I will take it somewhere else then.

**Comment by afaucogney** [comment]
Any news on this topic @Godin. I got the issue.

**Comment by Godin** [comment]
@afaucogney please read the thread carefully - if you face same issue with gradle, then please talk to them as issue is not on JaCoCo side and there is nothing to expect from us.
