### ISSUE TITLE
NaN returned as a Covered Ratio value

### ISSUE THREAD

**Issue by dawrut** [jacoco/jacoco#305]
Coverage Ratio returns NaN when there are no branches in a method.

As an example code:

class Foo {
  def bar = {}
}

After invocation of a bar method of the instrumented Foo class version the method:
org.jacoco.core.internal.analysis.CounterImpl#getCoveredRatio
can result in a NaN value.

Shouldn't it return a 1.0 as there is only one flow of a method and has been executed?

Attached debug screenshot below of variables values:

![screen shot 2015-05-09 at 19 10 34](https://cloud.githubusercontent.com/assets/1149384/7551172/1940020c-f67f-11e4-9c01-e92bf08c7190.png)

**Comment by marchof** [comment]
If the total number of branches is 0 the coverage ratio by plain mathematical definition is:

    coverage ratio = covered branches / total branches = 0 / 0 = NaN

Or in other words: If a particular total count does not exist at all (like number of branches) you can't calculate a coverage ratio for it.

Please see documentation for definition of coverage counters: http://www.eclemma.org/jacoco/trunk/doc/counters.html
