### ISSUE TITLE
Suggestion: Decompiler as a ant task within jacocoant.jar

### ISSUE THREAD

**Issue by simjeet** [jacoco/jacoco#306]
Pardon its just a suggestion. Can you create a ant task which decompiles the jar to generate source code level coverage report.

**Comment by marchof** [comment]
Sorry, creating a decompiler is out of scope for the JaCoCo project.

**Comment by simjeet** [comment]
we can use any opensource library to do so.
it will remove our dependency to provide path of source code.
and will even generate source code level coverage reports for other imported libraries or dependencies.

**Comment by marchof** [comment]
I don't think there is a usable open source library whoch works with latest Java versions. Also the library would need to emit source files with identical line numbers as the original source.

Even if such a library exists as a first step you could easily recreate the source files before you run the JaCoCo coverage report.

From a methodical point of view code coverage reports on source level granularity are meant to be studies by the developers of the source code. So they should better see the original code.

**Comment by simjeet** [comment]
You are right the source code produced by decompiler doesn't produce identical line numbers as original source code.Eventually generating wrong reports.
