### ISSUE TITLE
Misleading result

### ISSUE THREAD

**Issue by Godin** [jacoco/jacoco#307]
Same code, but different coverage results with different versions of javac.

JDK 7u75:

![jdk7u75](https://cloud.githubusercontent.com/assets/138671/7577926/64bbde56-f84e-11e4-93e4-6c103b7bac13.png)

JDK 7u80:

![jdk7u80](https://cloud.githubusercontent.com/assets/138671/7577925/622dc410-f84e-11e4-843e-4e06f869b9b3.png)

JDK 8u45:

![jdk8u45](https://cloud.githubusercontent.com/assets/138671/7577924/5f0a8868-f84e-11e4-848a-f6e875f62fed.png)

For all cases function is called with parameter "0", so that first and third results are misleading.

And for all JDK versions listed above after removal of declaration of local variable inside of switch-case:

![ok](https://cloud.githubusercontent.com/assets/138671/7577930/6a9ece8c-f84e-11e4-8af1-9517f4f93fb6.png)

so this might be related to https://bugs.openjdk.java.net/browse/JDK-8065674

**Comment by Godin** [comment]
@marchof do you think that JDK-8065674 can be root cause of this? Also I'm wondering, whether JaCoCo should deal with this or not?

**Comment by marchof** [comment]
@Godin The issue seems to fix the mapping from local variables to line numbers (LVT). JaCoCo uses the line number attribute, which maps code offsets to line numbers.

Can you please send the 3 class files? I'll have a look what the issue is.

**Comment by Godin** [comment]
@marchof sent into Dev ML.

**Comment by Godin** [comment]
@marchof btw, even if issue is about mapping for local variables, for me it looks suspicious that removal of local variable removes problem. If you think that would be valuable, I can do bisection of JDK forest to find commit which changes bytecode.

**Comment by marchof** [comment]
The decompiled class files are here: https://gist.github.com/marchof/a0e181e983a1354f7625
Only JDK 7u75 and 8u45 use the following control flow for the while loop:

         8: aload_2       
         9: ifnull        44
        12: iload_1       
        13: lookupswitch  { // 1
                       0: 32
                 default: 39
            }
        32: aconst_null   
        33: astore_3      
        34: aconst_null   
        35: astore_2      
        36: goto          41
        39: aconst_null   
        40: astore_2      
        41: goto          8

The first break results in the goto at offset 36 which jumps to offset 41. The line number table assigns offset 41 to line 13. That's why line 13 seems so be covered even if only the first break statement executed.

For the other JDKs the same block reads:

         8: aload_2       
         9: ifnull        44
        12: iload_1       
        13: lookupswitch  { // 1
                       0: 32
                 default: 39
            }
        32: aconst_null   
        33: astore_3      
        34: aconst_null   
        35: astore_2      
        36: goto          8
        39: aconst_null   
        40: astore_2      
        41: goto          8

Here the first break correctly results in a goto directly back to the loop beginning (36: goto 8) not causing any extra coverage.

**Comment by marchof** [comment]
@Godin For JaCoCo I would close this as invalid. As it seems to be fixed in JDK 8u60 and JDK 9 I wonder whether we should report this to the JDK project?

**Comment by Godin** [comment]
@marchof I bisected jdk8u-dev forest and first commit, which changes behavior is http://hg.openjdk.java.net/jdk8u/jdk8u-dev/langtools/rev/dca7f60e618d , so associated ticket is https://bugs.openjdk.java.net/browse/JDK-8064857 , which is for my understanding has nothing to do with gotos, but again only about LVT. And I agree with you that this is quite strange.
Regarding jdk7 - unfortunately it uses old build and I didn't managed to do it locally, so can't bisect jdk7u-dev forest, but still have strict feeling that only https://bugs.openjdk.java.net/browse/JDK-8065674 and so http://hg.openjdk.java.net/jdk7u/jdk7u-dev/langtools/rev/979f55cda0e2 can cause this.
Thus I'll talk to OpenJDK guys about this behavior change.

**Comment by marchof** [comment]
@Godin Looks like some unwanted side effects on the control flow.

**Comment by Godin** [comment]
Ticket created on OpenJDK side - https://bugs.openjdk.java.net/browse/JDK-8080555

**Comment by Godin** [comment]
@marchof found another difference between JDK7u80 and JDK8u45 on chains of method invocations, which again improves our reports in such case, and what seems to be consequence of change http://hg.openjdk.java.net/jdk8/jdk8/langtools/rev/02b8381781ab for https://bugs.openjdk.java.net/browse/JDK-7024096
And IMO this one a really good candidate for inclusion into set of our tests - #287

**Comment by marchof** [comment]
@Godin #287 is about exec file compatibility on the same class files. We actually have nice integration tests for the cycle source -> compiler -> coverage:
https://github.com/jacoco/jacoco/tree/master/org.jacoco.core.test/src/org/jacoco/core/test/validation
Except for Java 8 we currently do not test for compiler vendor/version specific features.

**Comment by marchof** [comment]
@Godin Can this issue be closed?

**Comment by Godin** [comment]
@marchof in fact I'm thinking - maybe we should add test case for this, since now we are constantly testing EA builds of JDKs and so in case of regressions will be able to catch and report this back quickly?

**Comment by marchof** [comment]
@Godin Tricky, as the behaviour has changed with different JDK versions: So what should we assert for? We also have subtile differences between JDC and ECJ (here I decided to not test for).

But anyways I clearly consider the behaviour in JDK 8u45 as a bug and wonder why the JDK issues has been closed? Or has this been fixed in later versions?

**Comment by Godin** [comment]
@marchof about what you are talking? The behavior of JDK8u45 and JDK7u75 was proven to be correct by issue JDK-8080555, which also means (and explicitly says) that behavior of earlier versions is a bug. Moreover - I though that we already agreed that this change is positive for JaCoCo.

If you talk about JDK-7024096 , then description is also explicit enough.

**Comment by marchof** [comment]
@Godin From the users point of view I cannot understand why the behavior should be correct: How can the second break statement be executed if the line before was not?

**Comment by Godin** [comment]
@marchof oh, sorry my bad (wrote too fast) - in fact JDK-8080555 says that fix in JDK8**u60** and in JDK 7**u80** is correct, which give result expected by user.

**Comment by Godin** [comment]
@marchof we catched this difference during testing of Early Access of 8u60.

**Comment by marchof** [comment]
@Godin So we could add a new >=java7-only verification suite once 7u80 and 8u60 is released and we upgraded our CI servers.

**Comment by Godin** [comment]
@marchof 7u80 already available for a quite some time. And current suite already conditional because of Java 8, so maybe it can have conditions for minors? Execution against Early Access versions locally in addition to released already the case for me. In fact maybe we can even have them in Jenkins.

**Comment by marchof** [comment]
@Godin Hm, somehow I think JaCoCo tests itself should only test against the Java specifications, not against specific implementations and update releases.

Maybe it would be more useful to create a separate test project with a couple of exectuted test classes where we compare all coverage details between different JRE update versions (not just the once we explicitely assert for).

**Comment by Godin** [comment]
@marchof ok, fine, so we can close this ticket.

As a playground for possible preparation of such kind of tests I created https://github.com/Godin/jacoco-tests-playground , which currently contains only source code for this case to not lose it.
