### ISSUE TITLE
Example progarm ReportGenerator not working

### ISSUE THREAD

**Issue by simjeet** [jacoco/jacoco#308]
Throwing exception:Exception in thread "main" java.lang.IncompatibleClassChangeError: class org.jacoco.core.internal.flow.ClassProbesVisitor has interface org.objectweb.asm.ClassVisitor as super class

**Comment by marchof** [comment]
Please use correct ASM version as declared in the dependencies. The current version used by JaCoCo is ASM 5.0.1

**Comment by simjeet** [comment]
using  asm  5.0.1 version still not working

**Comment by marchof** [comment]
Double check you class path. In ASM 5.0 ClassVisitor definitely is an abstract class, not an interface:

http://asm.ow2.org/asm50/javadoc/user/org/objectweb/asm/ClassVisitor.html

It used to be an interface ASM 3.x:

http://asm.ow2.org/asm33/javadoc/user/org/objectweb/asm/ClassVisitor.html

**Comment by simjeet** [comment]
i have build the core and report library with asm 5.0.1. still the same problem. Anyways found another workaround. Thanks for active responses.
