### ISSUE TITLE
Use standard Maven layout?

### ISSUE THREAD

**Issue by marchof** [jacoco/jacoco#312]
Investigate whether can use a standard Maven layout, especially joining main and test into a single project. There might be issues with running JaCoCo tests with code coverage.

**Comment by Godin** [comment]
This indeed doesn't seem to be possible since will be impossible to use JaCoCo which is result of the build itself - chicken and egg problem...

**Comment by Godin** [comment]
Also current layout is not that "non standard", actually not uncommon.
