### ISSUE TITLE
Invalid graph scalling algorithm

### ISSUE THREAD

**Issue by mrorat** [jacoco/jacoco#316]
Scalling of the graph data is quite bad.
Examples of two projects:

![fireshot screen capture 047 - jenkins](https://cloud.githubusercontent.com/assets/6039858/7831880/a8345626-0452-11e5-8f07-c962ae049333.png)
![fireshot screen capture 048](https://cloud.githubusercontent.com/assets/6039858/7831881/ab2f1b5e-0452-11e5-804d-6af342b55fc9.png)

There is a nice algorithm described on stackoverflow: http://stackoverflow.com/a/326746/2240408

If somebody will be kind enough to point me in the right direction I can try to fix this issue myself.

Cheers,
Michal

**Comment by Godin** [comment]
@mrorat Looks like you're talking about Jenkins plugin for JaCoCo, which is another project (see https://wiki.jenkins-ci.org/display/JENKINS/JaCoCo+Plugin ), so instead please contact maintainers of it. Thanks.

**Comment by mrorat** [comment]
Thanks!
