### ISSUE TITLE
How to distinguish the same class in different jar?

### ISSUE THREAD

**Issue by stevenscn** [jacoco/jacoco#320]
Hi All,
We get class' coverage from application server that has deployed many packages(jar/war).
There are some classes whose full name and content is identical but in different jar.
For the same class in different jar, it return an identical coverage. 
We expect that it can get different coverage for each class in different jar.
Any suggestion ? 
Thanks.

**Comment by marchof** [comment]
As the JaCoCo agent is framework and classloader agnostic it does not consider the source of a class. The identity of a class is constructed from its definition only (hash over the binary class file representation).
