### ISSUE TITLE
Accounting of assert statements

### ISSUE THREAD

**Issue by Dridi** [jacoco/jacoco#324]
I'm using jacoco with @SonarSource's sonarqube and one thing that bothers me is the actual accounting of `assert` statements in coverage reports.

They basically get a 100% line coverage, and 50% branch coverage.

Both metrics don't make sense since assert are not supposed to have any side effect, and thus do anything useful. You also don't want a 100% branch coverage, since it means corrupted state. And of course you can disable them at run time.

They should not be treated as code instructions.

Other than that, jacoco rocks!

**Comment by marchof** [comment]
Hi, thanks for your feedback! This is a known issue and needs to be solved with filters one day (Issue #15). I added it to the list of use cases here: https://github.com/jacoco/jacoco/wiki/FilteringOptions

**Comment by Dridi** [comment]
Sorry for the duplicate, it didn't show up when I searched open issues for "assert".

I will subscribe to #15 :)

**Comment by marchof** [comment]
No problem -- it actually wasn't on the use case list for filtering till your your report.
