### ISSUE TITLE
jacoco:check goal does not respect jacoco.skip=true property

### ISSUE THREAD

**Issue by chrishenzie** [jacoco/jacoco#325]
If you invoke ```mvn jacoco:check -Djacoco.skip=true``` on the following pom (does not have any rules configured) jacoco returns the following:
```
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.7.5.201505241946:check (default-cli) on project artifactId: The parameters 'rules' for goal org.jacoco:jacoco-maven-plugin:0.7.5.201505241946:check are missing or invalid -> [Help 1]
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>some.groupId</groupId>
  <artifactId>artifactId</artifactId>
  <version>0.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.7.5.201505241946</version>
      </plugin>
    </plugins>
  </build>

</project>
```
I understand that you should have rules configured but I think the ```jacoco.skip=true``` property should be respected regardless.

**Comment by Godin** [comment]
@chrishenzie The fact is that check of "required" parameters (such as "rules") is performed by Maven Core far before our Mojo makes a decision based on value of property "jacoco.skip". You can see this in full stack trace of an error:
```
Caused by: org.apache.maven.plugin.PluginParameterException: The parameters 'rules' for goal org.jacoco:jacoco-maven-plugin:0.7.5.201505241946:check are missing or invalid
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:586)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:539)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:119)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
```

Of course as a workaround we can mark parameter "rules" as not "required" and then after "jacoco.skip" verify that "rules" are not empty. But I'm wondering about ROI - could you specify a use-case for ``mvn jacoco:check -Djacoco.skip`` without "rules"?

**Comment by chrishenzie** [comment]
@Godin Ah got it. No I don't think I can to be honest lol, I just threw JaCoCo in my personal project but the "verify" phase was failing because it was invoking jacoco:check but I hadn't bothered to setup any rules yet. Thank you though, I'll close the issue.
