### ISSUE TITLE
java.io.IOException: invalid execution data file

### ISSUE THREAD

**Issue by w1807710180** [jacoco/jacoco#332]
I want to statistics code coverage of the Web project dynamically via jacocoagent.jar. And I add "set JAVA_OPTS=-javaagent:E:/apache-tomcat-7.0.63/lib/jacocoagent.jar=includes=*,output=tcpserver,port=10001,address=127.0.0.1" in catalina.bat. After I operated my project, when I visited "http://127.0.0.1:10001" , there is nothing. And Tomcat show "java.io.IOException: invalid execution data file". I don't know why. Please help me. Thanks.

**Comment by Godin** [comment]
This is issue tracker and not a forum. Forum located at https://groups.google.com/forum/#!forum/jacoco
