### ISSUE TITLE
Jacoco coverage is affected by AspectJ

### ISSUE THREAD

**Issue by shizhz** [jacoco/jacoco#335]
Hi,

We're using AspectJ in our project and also Jacoco for test coverage report, currently we're facing an issue that due to AspectJ changed the byte code during compiling phase, which makes the code coverage report not correct. One example is due to AspectJ adds extra if-else statement, then the branch  coverage shows something like 1/4 but actually there's no condition branch in the source code.  Is there some good way to tell Jacoco to ignore all code generated by AspectJ?

Thanks a lot.

**Comment by marchof** [comment]
This is a issue tracker, will answer your question on the mailing list.

**Comment by shizhz** [comment]
Thanks @marchof , I'll close this.
