### ISSUE TITLE
classdumpdir

### ISSUE THREAD

**Issue by youdidut** [jacoco/jacoco#337]
Hi!

I am using gradle+jacoco, and my current goal is to get some of the loaded class files with jacocoagent.jar and "classdumpdir" option. 

However, I could only get few of the loaded classes in classdumpdir, after I added "-javaagent:/home/d/test11/jacoco-example/lib/jacocoagent.jar=classdumpdir=/home/d/test11/jacoco-example/dump" to the JVM configuration in gradlew. I also add "org.gradle.jvmargs=-javaagent:/home/d/test11/jacoco-example/lib/jacocoagent.jar=classdumpdir=/home/d/test11/jacoco-example/dump" to "gradle.properties" for daemon processes.

I believe the reason has something to do with the fact I have 4 projects under the main directory. Each of them seems to automatically download their own jacocoagent.jar and use it to generate its .exec file. What can I do to gather all the instrumented class files listed in sessions.html?

Your help would be much appreciated! 
@marchof

**Comment by Godin** [comment]
@youdidut Gralde Plugin for JaCoCo is maintained by Gradle developers and not here, so please contact them about your issue. Thank you for understanding.
