### ISSUE TITLE
Jacoco coverage < cobertura

### ISSUE THREAD

**Issue by damianszczepanik** [jacoco/jacoco#340]
I've compared code coverage jacoco vs cobertura because they show different results. So let's talk about exxample:
http://damianszczepanik.github.io/jacoco/jacoco/pl.szczepanik.silencio.core/ProcessorStateMachine.java.html
vs 
http://damianszczepanik.github.io/jacoco/cobertura/pl.szczepanik.silencio.core.ProcessorStateMachine.html
from
https://github.com/damianszczepanik/silencio

As you see cobertura shows 100% while jacoco displays two uncovered invocation of `reportViolation()` What is interesting `reportViolation()` is private method accessible only from this class or via reflection. This method is covered so if I don't reflect this class the only way is to use mentioned invocation that jacoco says are not used at all. This case is covered by following test case https://github.com/damianszczepanik/silencio/blob/d0d1f060f1964daf42e17a1f6013d6170dbd1a9e/src/test/java/pl/szczepanik/silencio/core/ProcessorStateMachineTest.java#L14

**Comment by marchof** [comment]
This is a known limitation of JaCoCo, see [FAQ](http://www.eclemma.org/jacoco/trunk/doc/faq.html):

Source code lines with exceptions show no coverage. Why?

JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding line of source code is not marked as covered.

**Comment by damianszczepanik** [comment]
Thanks,

Is it possible to rewrite code so the jacoco shows correctly coverage?

**Comment by marchof** [comment]
Absolutely, just inline reportViolation(). The executed throw statement will get green.

**Comment by damianszczepanik** [comment]
Works fine now https://github.com/damianszczepanik/silencio/pull/19 - thank you!
