### ISSUE TITLE
Coverage for Java 8 lambdas

### ISSUE THREAD

**Issue by DmitriyKartashov** [jacoco/jacoco#345]
Hi all,

Java 8 and lambdas brought new style of coding where branches are hidden inside the framework.
For example, this code:
```java
    public String findLongestStringStartsWithA(List<String> stringList)
    {
        return stringList.stream()
            .filter(s -> s.startsWith("a"))
            .max((s1, s2) -> s1.length() - s2.length())
            .orElse("no match");
    }
```
has two logical branches:
 - something filtered in or filtered out for processing
 - result may or may not be found in the given list

And with this test:
```java
    @Test
    public void shouldTestHappyPass() {
        //given
        List<String> list = Arrays.asList("aa", "acc", "a");

        //when
        String foundValue = lambdaExample.findLongestStringStartsWithA(list);

        //then
        assertEquals("acc", foundValue);
    }
```
Jacoco reports 100% code coverage.

For Java 7 code that is doing the same:
```java
    public String findLongestStringStartsWithA(List<String> stringList)
    {
        String longest = "";
        for (String s : stringList)
        {
            if (s.startsWith("a"))
            {
                if (s.length() > longest.length())
                {
                    longest = s;
                }
            }
        }
        return longest.isEmpty() ? "no match" : longest;
    }
```
And with the same test Jacoco reports 94% code coverage and 75% branch coverage because not all the branches in ```if (s.startsWith("a"))``` and in ```longest.isEmpty()``` are covered.
You can check the code here:
https://github.com/DmitriyKartashov/lambdas_example

Can Jacoco be improved to detect such logical branches like "filter", "orElse", "ifPresent" and check their coverage?

**Comment by marchof** [comment]
JaCoCo works on the plain control flow seen in the class files. It is completely API or framework agnostic and does not make any assumptions about the functionality particular APIs. Also it it only records the control flow and does not consider the data flow.

To implement the functionality you requested JaCoCo would need to

1. understand the semantic of the Optional API
2. analyze data flow to see differentiate the behavior of orElse() depending on the state of the Optional instance.

Unfortunately both is far beyond the current scope (and capability) of the JaCoCo project.
