### ISSUE TITLE
Differences in coverage reports depending on how I test an application?

### ISSUE THREAD

**Issue by DavidKuo** [jacoco/jacoco#346]
I am running tests on our project through 2 methods:
1) the source code (as an Eclipse application, using the RCP Testing Tool plugin) 
2) A compiled and built executable (as an AUT, using the RCP Testing Tool plugin).

I am able to get identical coverage in most areas of my code. However, I am getting 0% coverage in certain classes when running the tests through the executable while the test using the source code would get actual numbers such as 40-50% coverage

Is there any reason for this? I am unsure of what the cause could be for the differences.

My JAVA_HOME is set to 1.8, and I am using Eclipse 4.4.2

**Comment by marchof** [comment]
This is a issue tracker, please use our forum for general questions: https://groups.google.com/d/forum/jacoco

Your problem sounds like a FAQ entry (http://eclemma.org/jacoco/trunk/doc/faq.html):

> Why does a class show as not covered although it has been executed?
> 
> First make sure execution data has been collected. For this select the Sessions link on the top right
> corner of the HTML report and check whether the class in question is listed. If it is listed but not linked > the class at execution time is a different class file. Make sure you're using the exact same class file at 
> runtime as for report generation. Note that some tools (e.g. EJB containers, mocking frameworks) 
> might modify your class files at runtime. Please see the chapter about class ids for a detailed
> discussion.
