### ISSUE TITLE
Skipping JaCoCo execution due to missing execution data (missing jacoco-it.exe

### ISSUE THREAD

**Issue by zizigooloo** [jacoco/jacoco#348]
Hi 
i used last pom.xml file from this address:
http://eclemma.org/jacoco/trunk/doc/examples/build/pom-it.xml

and maven result:

 --- jacoco-maven-plugin:0.7.6-SNAPSHOT:prepare-agent-integration (default-prepare-agent-integration) @ Test ---
argLine set to -javaagent:/home/sina/.m2/repository/org/jacoco/org.jacoco.agent/0.7.6-SNAPSHOT/org.jacoco.agent-0.7.6-SNAPSHOT-runtime.jar=destfile=/home/sina/Test/target/jacoco-it.exec

 --- jacoco-maven-plugin:0.7.6-SNAPSHOT:report-integration (default-report-integration) @ Test ---
Skipping JaCoCo execution due to missing execution data file:/home/sina/Test/target/jacoco-it.exec

thx

**Comment by marchof** [comment]
@Godin Can you have a look whether our example is actually broken?

**Comment by Godin** [comment]
@marchof We have integration test - https://github.com/jacoco/jacoco/blob/master/org.jacoco.examples.test/src/test/resources/verify-it.groovy

And I have strong feeling that it is not about our example, but about its modified/extracted/... version.
But I double-checked manually to be sure:
```
$ wget "http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.5.201505241946/jacoco-0.7.5.201505241946.zip" -O jacoco-0.7.5.zip
$ unzip jacoco-0.7.5.zip
$ cd doc/examples/build
$ mvn -V clean verify -f pom-it.xml
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /usr/share/maven-bin-3.3
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /home/godin/.java-select/versions/jdk1.7.0_80/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.0.5-gentoo", arch: "amd64", family: "unix"
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JaCoCo Maven plug-in example 0.7.5.201505241946
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ org.jacoco.examples.maven ---
[INFO] Deleting /tmp/jj/doc/examples/build/target
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (default-prepare-agent) @ org.jacoco.examples.maven ---
[INFO] argLine set to -javaagent:/home/godin/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/tmp/jj/doc/examples/build/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ org.jacoco.examples.maven ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /tmp/jj/doc/examples/build/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ org.jacoco.examples.maven ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 8 source files to /tmp/jj/doc/examples/build/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ org.jacoco.examples.maven ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /tmp/jj/doc/examples/build/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ org.jacoco.examples.maven ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 2 source files to /tmp/jj/doc/examples/build/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ org.jacoco.examples.maven ---
[INFO] Surefire report directory: /tmp/jj/doc/examples/build/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jacoco.examples.parser.ExpressionParserTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.092 sec - in org.jacoco.examples.parser.ExpressionParserTest

Results :

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ org.jacoco.examples.maven ---
[INFO] Building jar: /tmp/jj/doc/examples/build/target/org.jacoco.examples.maven-0.7.5.201505241946.jar
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent-integration (default-prepare-agent-integration) @ org.jacoco.examples.maven ---
[INFO] argLine set to -javaagent:/home/godin/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/tmp/jj/doc/examples/build/target/jacoco-it.exec
[INFO] 
[INFO] --- maven-failsafe-plugin:2.16:integration-test (default-integration-test) @ org.jacoco.examples.maven ---
[INFO] Failsafe report directory: /tmp/jj/doc/examples/build/target/failsafe-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jacoco.examples.parser.ExpressionParserIT
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.093 sec - in org.jacoco.examples.parser.ExpressionParserIT

Results :

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:report (default-report) @ org.jacoco.examples.maven ---
[INFO] Analyzed bundle 'JaCoCo Maven plug-in example' with 7 classes
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:report-integration (default-report-integration) @ org.jacoco.examples.maven ---
[INFO] Analyzed bundle 'JaCoCo Maven plug-in example' with 7 classes
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:check (default-check) @ org.jacoco.examples.maven ---
[INFO] Analyzed bundle 'JaCoCo Maven plug-in example' with 7 classes
[INFO] All coverage checks have been met.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.988 s
[INFO] Finished at: 2015-09-30T11:12:44+02:00
[INFO] Final Memory: 18M/239M
[INFO] ------------------------------------------------------------------------
```

**Comment by zizigooloo** [comment]
when i checked it with only  prepare-agent then everything is ok that jacoco.exec generated with 
argLine set to -javaagent:/home/sina/.m2/repository/org/jacoco/org.jacoco.agent/0.7.6-SNAPSHOT/org.jacoco.agent-0.7.6-SNAPSHOT-runtime.jar=destfile=/home/sina/Test/target/jacoco.exec.

 but when used prepare-agent-integration then 
argLine set to -javaagent:/home/sina/.m2/repository/org/jacoco/org.jacoco.agent/0.7.6-SNAPSHOT/org.jacoco.agent-0.7.6-SNAPSHOT-runtime.jar=destfile=/home/sina/Test/target/jacoco-it.exec dosen't generate jacoco-it.exec file.

i changed this properties in the pom.xml file of example site:


maven.compiler.source 1.5
maven.compiler.target 1.5

to 

maven.compiler.source 1.8 
maven.compiler.target 1.8


Note: i use this tools:
 java compiler : jdk1.8.0_45 
 maven 3.3
 IntelliJ 14.1.4


thx

**Comment by Godin** [comment]
@zizigooloo sorry, but for me completely unclear what you did and what you expect without concrete example, so could you please provide it, so that we'll be able to have a look and try locally - this will be much simpler.

Couple of notes:
- the differences between "prepare-agent" (http://eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html) and "prepare-agent-integration" (http://eclemma.org/jacoco/trunk/doc/prepare-agent-integration-mojo.html) - are default phase and destFile location, as described in documentation
- the differences between "report" (http://eclemma.org/jacoco/trunk/doc/report-mojo.html) and "report-integration" (http://eclemma.org/jacoco/trunk/doc/report-integration-mojo.html) are the same
- due to those differences "prepare-agent" is intended to be used in a pair with "report", while "prepare-agent-integration" in a pair with "report-integration"

**Comment by zizigooloo** [comment]
Godin thanks a lots for help me.

i find the problem. The problem wasn't with my profile and it was with naming test file. 
your told is truth and jacoco example pom file is correct.

i mistake in writting test file for integration test.

thx

**Comment by holiday-sunrise** [comment]
Hi Godin, i have some problem with jacoco and multi module projekts.

My Projekt looks like

parent
    moduleA  with source and test source
    moduleB  with source and test source  Depends A
moduleB

**Comment by Godin** [comment]
@holiday-sunrise this is issue tracker, please use our mailing list for questions - https://groups.google.com/forum/#!forum/jacoco Moreover it already contains answers on similar questions - for example https://groups.google.com/d/msg/jacoco/c02zAEkLULQ/q5ojtn8lBgAJ
