### ISSUE TITLE
Ignore classes without source code

### ISSUE THREAD

**Issue by pmwmedia** [jacoco/jacoco#350]
If there are dynamic generated classes without any underlying source code, JaCoCo throws a UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields).

JMockit example:

```java
public final class InterfaceMockTest {

    @Test
    public void test() throws SQLException {
        MockUp<PreparedStatement> mock = new MockUp<PreparedStatement>() {
            @Mock
            public void setString(int parameterIndex, String x) {
                System.out.println(x);
            }
        };

        mock.getMockInstance().setString(1, "example");
    }

}
```

Code coverage without any existing source code doesn't make any sense. I propose to ignore all these classes (getClass().getProtectionDomain().getCodeSource().getLocation() == null) out of the box.

**Comment by Godin** [comment]
@pmwmedia such classes already ignored - see https://github.com/jacoco/jacoco/blob/73e36a107c1e9c8480e117ea769be34b8be957dd/org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/CoverageTransformer.java#L83

**Comment by pmwmedia** [comment]
Thanks for your quick answer! So there is another reason for the exception.

**Comment by pmwmedia** [comment]
Is fixed by pull #272, which is unfortunately not yet part of the current EclEmma version 2.3.2.

**Comment by marchof** [comment]
You can install the latest trunk build of EclEmma from this update site URL:

http://download.eclipselab.org/eclemma/trunk/update

**Comment by pmwmedia** [comment]
Thanks, it's working :-)
