### ISSUE TITLE
Generated coverage for Kotlin contains invalid lines

### ISSUE THREAD

**Issue by jkcclemens** [jacoco/jacoco#353]
When using jacoco on [Kotlin](http://kotlinlang.org/)-generated jars, it will produce reports with invalid lines, as can be seen [here](https://github.com/jkcclemens/khttp/pull/1).

Specifically, [here](https://travis-ci.org/jkcclemens/khttp/builds/87444126#L1110) is an examination of the report, a [JSON representation](https://codecov.io/api/github/jkcclemens/khttp/src/main/kotlin/me/kyleclemens/khttp/structures/cookie/CookieJar.kt?ref=c9879cc9ce24cd4e215e49518617c1dcb5803835), and the [file in question](https://codecov.io/github/jkcclemens/khttp/src/main/kotlin/me/kyleclemens/khttp/structures/cookie/CookieJar.kt?ref=c9879cc9ce24cd4e215e49518617c1dcb5803835).

Note that the report includes lines above 37, the end of the file.

**Comment by Godin** [comment]
@jkcclemens Could you please provide decompiled bytecode with linenumbers (with help of "javap -l") for a class file in question? I have feeling that this might be Kotlin compiler, which generates incorrect linenumbers table.

**Comment by jkcclemens** [comment]
@Godin [Here](https://gist.github.com/jkcclemens/ad77c66028fb54104506) you go. Yeah, I can see some invalid line numbers listed in there.

**Comment by Godin** [comment]
@jkcclemens so if you see invalid linenumbers, I'm closing this ticket - it is not responsibility of JaCoCo to workaround/tolerate compiler bugs.
