### ISSUE TITLE
Strange interaction with GSON and jacoco

### ISSUE THREAD

**Issue by gionn** [jacoco/jacoco#354]
Hi,

while using jclouds 1.9.1, that internally use GSON 2.3, I am getting an exception from GSON only when running integration tests with jacoco agent 0.7.5.201505241946 enabled.

These are the logs used when reporting to jclouds ML before discovering that the culprit was jacoco https://gist.github.com/gionn/e2eb0bae94369ec8ca7c

Suggestions?

**Comment by Godin** [comment]
@gionn Hi, I have strong feeling that you face case, which is described in our FAQ as "My code uses reflection. Why does it fail when I execute it with JaCoCo?" ( http://eclemma.org/jacoco/trunk/doc/faq.html ), i.e. somehow "synthetic" field injected by JaCoCo not ignored. I can dig deeper, but for this I need a simple reproducer to play with. As a workaround you can try to exclude classes (processed by Gson) from JaCoCo instrumentation.

**Comment by gionn** [comment]
Hi @Godin, jclouds guys are helping me investigating the issue, updates will be tracked here:

https://github.com/jclouds/jclouds/pull/873

Thanks.
