### ISSUE TITLE
Unable to run MavenEmbedder in Project which has jacoco maven dependency

### ISSUE THREAD

**Issue by tariq1890** [jacoco/jacoco#355]
Hey Guys,

This may not be a Jacoco issue. I get the NoSuchMethodError  for the DefaultPlexusContainer constructor when i run MavenEmbedder in my project
```
Exception in thread "main" java.lang.NoSuchMethodError: org.codehaus.plexus.DefaultPlexusContainer.<init>(Lorg/codehaus/plexus/ContainerConfiguration;[Lcom/google/inject/Module;)V
	at org.apache.maven.cli.MavenCli.container(MavenCli.java:542)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:279)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:241)
```
On doing a root cause analysis I found out that the NoSuchMethodError is due to a dependency conflict with jacoco maven plugin, The jacoco plugin has the following "dependency plexus-container-default-1.0-alpha-9-stable-1" where there are no paramterized constructors for DefaultPlexusContainer. Whereas Maven Embedded refers to the DefaultPlexusContainer class from jar org.eclipse.sisu.plexus .Since the package names and class names are the same for both the jars, the older DefaultPlexusContainer overrides and I get the NoSuchMethodError as a result

I would like your advice on this. Thanks

**Comment by Godin** [comment]
@tariq1890 Hi, do you have a simple reproducer, which we'll be able to try?

**Comment by tariq1890** [comment]
@Godin , Let me try create one

**Comment by tariq1890** [comment]
Done .https://github.com/tariq1890/JacocoMavenEmbed

**Comment by Godin** [comment]
@tariq1890 and what is the reason to have "jacoco-maven-plugin" as a dependency?

**Comment by tariq1890** [comment]
We are using that to generate the .exec file for java projects. We are using the coverage data for analyses :).

**Comment by Godin** [comment]
@tariq1890 Still it is not clear how exactly it is used, e.g. removal of this dependency won't break compilation of provided example. I'm asking all this in order to understand use case better, because we are not considering jacoco-maven-plugin to be used other than as maven plugin with all the consequences - it doesn't provide an API in a sense of usual Java APIs.

But coming back to NoSuchMethodError.
There is probably a typo in your example:
```
System.setProperty("-Dmaven.multiModuleProjectDirectory", projectPath);
```
"-D" should be removed.
Then place dependency on "jacoco-maven-plugin" after others ( order of dependencies matters in Maven - see https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html ) and exception will disappear.

**Comment by tariq1890** [comment]
Thanks . Changing the order of dependencies worked .

**Comment by Godin** [comment]
You didn't answer my question. But anyway glad that your issue solved.

**Comment by tariq1890** [comment]
Hi Godin,

Sorry to have missed your question. 

We are using the prepare-agent goal of jacoco maven plugin to generate the exec file.

We are also using the Jacoco classes like ILine, CounterImpl, HTMLFormatter, IAgent in our project.

Due to this we are using the jacoco maven plugin in our dependencies

**Comment by Godin** [comment]
@tariq1890 Correct me, if I'm wrong, but usage of goal "prepare-agent" doesn't require declaration of jacoco-maven-plugin as dependency. And for usage of JaCoCo classes better to depend on "org.jacoco.core" directly. To sum up IMO dependency on "jacoco-maven-plugin" not needed, and moreover - misleading.

Also could be noted that "CounterImpl" resides in "internal" package, i.e. not part of public API.

**Comment by tariq1890** [comment]
Hi @Godin ,

Thanks for the suggestion. I am currently trying it out . I am not able to find the maven dependecy fot the classes in this loocation

https://github.com/jacoco/jacoco/tree/master/org.jacoco.agent.rt

Regards,
Tariq

**Comment by tariq1890** [comment]
I have also tried importing the full jacoco package using the following dependency

<dependency>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco</artifactId>
            <version>0.7.5.201505241946</version>
        </dependency>

I am able to Access org.jacoco.agent.rt  classes with this.However the maven install failis for the project

```
[ERROR] Failed to execute goal on project tacoco: Could not resolve dependencies for project org.spideruci.tacoco:tacoco:jar:0.1: The following artifacts could not be resolved: org.jacoco:jacoco:jar:0.7.5.201505241946, org.jacoco:org.jacoco.examples:zip:0.7.5.201505241946, org.jacoco:org.jacoco.doc:jar:javadoc:0.7.5.201505241946: Could not find artifact org.jacoco:jacoco:jar:0.7.5.201505241946 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by Godin** [comment]
@tariq1890 check your settings, all is in central repository - http://search.maven.org/#search%7Cga%7C1%7Corg.jacoco

**Comment by Godin** [comment]
@tariq1890 don't import root POM, dependency is
```
<dependency>
    <groupId>org.jacoco</groupId>
    <artifactId>org.jacoco.core</artifactId>
    <version>0.7.5.201505241946</version>
</dependency>
```

**Comment by tariq1890** [comment]
I also also use the following artifacts

org.jacoco.report
org.jacoco.agent.rt

If I import the below jar (which is there in the central mvn repo )

<dependency>
    <groupId>org.jacoco</groupId>
    <artifactId>org.jacoco.agent</artifactId>
    <version>0.7.5.201505241946</version>
</dependency>

It has only AgentJar.java class

I need to access the classes
IAgent.java and RT.java . They are located in package org.jacoco.agent.rt

**Comment by Godin** [comment]
@tariq1890 they are in jar with classifier "runtime":
```
<dependency>
    <groupId>org.jacoco</groupId>
    <artifactId>org.jacoco.agent</artifactId>
    <version>0.7.5.201505241946</version>
    <classifier>runtime</classifier>
</dependency>
```

**Comment by tariq1890** [comment]
Thanks a lot @Godin  . I really appreciate the help. Next time I face an issue , I'll send a mail to the mailing list. Sorry for creating an Issue ticket.
