### ISSUE TITLE
Missed branch not found

### ISSUE THREAD

**Issue by piotrkot** [jacoco/jacoco#356]
Welcome,

After running report on my [project](https://github.com/piotrkot/simple-cli) it is found one [missed branch](https://github.com/piotrkot/simple-cli/blob/master/src/main/java/com/github/piotrkot/cli/Option.java#L128). This is a correct finding. However, another [missed branch](https://github.com/piotrkot/simple-cli/blob/master/src/main/java/com/github/piotrkot/cli/Option.java#L126) is not found. And this I think is a bug.

**Comment by marchof** [comment]
@piotrkot Can you please provide a screen shot of the coverage report with the "missed branch"? Hard to tell what's going wrong without seeing the tests. Better you provide a isolated reproducer.

**Comment by piotrkot** [comment]
@marchof I was thinking that providing you the whole project, would be already isolated reproducer. Anyway, when you fork/clone the [simple-cli](https://github.com/piotrkot/simple-cli) and run
`mvn clean test jacoco:report -Pqulice` you should be able to find everything you need in `target/site/jacoco`. There are jacoco reports with missing branches in Option.java:value()

**Comment by marchof** [comment]
Hi,

a quick look at the OptionTest reveals that there is no test case, where the value() method is called AND the params list contains a value with a '=' character. That's why the branch is missed.

![image](https://cloud.githubusercontent.com/assets/1936262/10944253/a06f471c-8318-11e5-85f7-12beec92b60b.png)

**Comment by piotrkot** [comment]
@marchof I am afraid you misunderstood. After running jacoco report as described above, you should find file in `target/site/jacoco/com.piotrkot.cli/Option.java.html` with screen shot
![screenshotoptionjava](https://cloud.githubusercontent.com/assets/9504395/10948898/62f94a78-8330-11e5-8466-ea14cbaba7dc.png)
The screen shot (and the report) shows there is only one missed branch on line 128. This is correctly recognized missed branch - no question about it. However, there is also another missed branch on line 126 which is **not found** in your report (and screen shot). This, I believe, is a bug.
Regarding your screen shot, I do not quite understand how you got it with these colors.

**Comment by marchof** [comment]
Ok, your original request was referring to line 126. So let's have a look at the if statement in line 128.

As the body is covered the case (par.split(EQ).length == 2) == false is missed. Every string which contains '=' (which is enforced by the surrounding condition) will always split in at least two substrings. The only way to test this condition false is to  have more that two substrings, e.g. with a par value like "a=b=c". Probably you missed that case.

**Comment by piotrkot** [comment]
@marchof @Godin The case (line 128) `(par.split(EQ).length == 2)` == false is missed. This is correctly found by the library. However, the case (line 126) `(par.contains(EQ))` == false is also missed and this is not found by the library. Which means you have a bug.

**Comment by marchof** [comment]
@piotrkot I don't think so. Your test case [returnEmptyValue()](https://github.com/piotrkot/simple-cli/blob/master/src/test/java/com/github/piotrkot/cli/OptionTest.java#L133) exercises exactly this case:

    new Option("", Collections.singletonList("arg")).value().isEmpty()

Again: Please provide a isolated reproducer if you still think there is a bug.

**Comment by piotrkot** [comment]
@marchof An isolated reproducer would be to replace line 126 `if (par.contains(EQ)) {` with `if (true) {` and run `mvn clean test`. If a test fails means branch false is covered. But I tell you, I run that already and all tests pass.

**Comment by marchof** [comment]
@piotrkot Whether a branch is covered or not related whether tests do fail or not. Actually JaCoCo does not depend on a test framework like JUnit and has no idea about the semantics of test cases. It is a plain coverage tool that works on any Java code executed in a JVM.

Your test cases excercise both situations: Parameters with = and without =. That's why both branches in this statement are covered:

    if (par.contains(EQ)) {

By isolated test case I mean a minimal program or test case (single class), so you can easily understand what your code actually does.

**Comment by piotrkot** [comment]
@marchof Also I do not think you should be dependent on a test framework or classes' semantics. To my understanding test coverage actually is very closely related to tests' failure or success. And then I, perhaps mistakenly, assumed this can be proven with extra tests.

As we prove application running expectedly with tests. And prove tests running expectedly with test covering tools. We should also be able to prove test covering tools running expectedly with simple adjustments to source code and their immediate feedback of tests' failure or success.

This, however, may be conceptually closer to mutation testing, instead. Because how I understood you analyze the source code to check if statements are covered.

That's why we have a bit misunderstanding. Anyway, thank you for help.
