### ISSUE TITLE
Run in coverage mode always, in Eclipse's standard JUnit runner

### ISSUE THREAD

**Issue by willhains** [jacoco/jacoco#357]
Eclemma is easily fast enough to be always-on, i.e. not a separate run mode, but just rolled into Eclipse's standard JUnit runner. Is this possible?

One motivation I have for this is that I use other plugins that run JUnit tests (e.g. [MoreUnit][]), so when they run, I don't get coverage scores.

[MoreUnit]: https://github.com/MoreUnit/MoreUnit-Eclipse

**Comment by marchof** [comment]
This would be an https://github.com/jacoco/eclemma issue.

Anyways, "always on" is not enough. For each launch type (e.g. MoreUnit) we need a specific configuration how to inject the VM arg in this case. Also the Eclipse launch/debug framework does not provide generic as do define a launch mode for all launch types.
