### ISSUE TITLE
Missing line coverage after an exception is thrown in a try block

### ISSUE THREAD

**Issue by havasd** [jacoco/jacoco#362]
Hi!

With the following sample I would like to demonstrate an issue with line coverage in case of exception is thrown in a called method: https://gist.github.com/havasd/64e90baf560820f85bfd

In my opinion if an exception is thrown in a method the caller methods should be covered also and the and also the try block should be covered until that function call which caused the exception.

In case you put directly the "throw new Exception();" in the try block than it works properly.

**Comment by marchof** [comment]
This is a limitation due to the design of JaCoCo, see FAQ: http://eclemma.org/jacoco/trunk/doc/faq.html

Anyways, for your specific case we improved JaCoCo to properly report the lines before the exception occurs as covered.
