### ISSUE TITLE
Add the coverage in the "check" mojo success message

### ISSUE THREAD

**Issue by tmortagne** [jacoco/jacoco#369]
Something like "All coverage checks have been met (0.41)".

That way I could directly see the current status when building and can update the setup if I added some tests recently.

**Comment by marchof** [comment]
@tmortagne What exactly is the meaning of 41?

**Comment by tmortagne** [comment]
Sorry I meant 0.41, I fixed it in the description (I was thinking about 41%).

**Comment by marchof** [comment]
There can be many rules. So you expect a message for every rule? Is the number the actual value or the limit?

**Comment by tmortagne** [comment]
Indeed I totally forgot that this number was only for a specific rule (configured it a long time ago and only change the number now). Here is more detail on my use case:

* I have a Maven property which is used the following way in jacoco setup (in a parent pom)

            <configuration>
              <rules>
                <rule>
                  <limits>
                    <limit>
                      <counter>INSTRUCTION</counter>
                      <minimum>${xwiki.jacoco.instructionRatio}</minimum>
                    </limit>
                  </limits>
                </rule>
              </rules>
            </configuration>

* jacoco:check is enabled by default for any module having this pom as parent (so all the pom in my project)

* in my project I set the property to the number coverage I want my module to never go under as a rule

-> what I would like is to directly see in jacoco:check execution result log if I can increase this number (because I just added some test or move some code else where).

**Comment by marchof** [comment]
Hm, that might become tricky: If the rule is specified for a smaller element (like classes) you would get hundreds of messages, one for every class. What you probably need is the minimum and maximum value encountered for every rule.

BTW, why can't you use the numbers from the coverage report?

**Comment by tmortagne** [comment]
Basically what I want the same value I get when jacoco:check fail which is a unique value.

**Comment by marchof** [comment]
If you have many violation (multiple rules, multiple elements) you will also get many messages. Only in the case that you have a single rule with checks on level BUNDLE you get a unique value.

**Comment by tmortagne** [comment]
Ok now I understand what you mean, I tough it was related to my use case but indeed I never used jacoco with a different setup so I always tough about it as a unique value.

**Comment by marchof** [comment]
@tmortagne Any idea how this request can be generalized? Otherwise I'm tempted to close this as WONTFIX.

**Comment by marchof** [comment]
Also see PR #237.

**Comment by tmortagne** [comment]
#237 indeed looks a lot like what I need, that would do for me I think.

**Comment by marchof** [comment]
#237 will print the following line for every rule and element:

    Rule conforms for CLASS Foo2: instructions covered ratio is 0.0

**Comment by tmortagne** [comment]
I would get only one line in my case, right ?

    <configuration>
      <rules>
        <rule>
          <limits>
            <limit>
              <counter>INSTRUCTION</counter>
              <minimum>${xwiki.jacoco.instructionRatio}</minimum>
            </limit>
          </limits>
        </rule>
      </rules>
    </configuration>

**Comment by marchof** [comment]
Right, one rule only and the default element is BUNDLE.

**Comment by marchof** [comment]
So I close this as duplicate to PR #237.

**Comment by tmortagne** [comment]
Thanks for all the time you spent my not detailed enough feature request :)
