### ISSUE TITLE
How to get min code coverage check only for entire project and not for individual modules

### ISSUE THREAD

**Issue by rajuec2005** [jacoco/jacoco#372]
the current implementation for min code coverage check works only for single module project.I have a multimodule project , so this check is for individual project. I want to set min code coverage check for entire project and not for individual project. it is fine if some module has 30% and some 90% but i want my build to fail only if overall code coverage is < 80% and not check for individual project.
How do we do this using Jacoco.

**Comment by marchof** [comment]
Crosspost from user forum.
