### ISSUE TITLE
Exclude at the method level for generated methods

### ISSUE THREAD

**Issue by cpesarchick-home** [jacoco/jacoco#373]
Need a way exclude at the method level of a class.  It would be nice to have something like **/*.toString.

When using lombok (@Data) it will generate setters/getters, equals, hashcode, and toString methods.  Need a way to exclude these generated methods.  It can be very confusing in Sonar because the code coverage will be low, but the views will not show any code that shows what is not being covered.  When you exclude the class then any methods that were written are not part of the coverage report.

**Comment by marchof** [comment]
We have an container Issue for all Filtering issues #15.

Added LOMBOK.DATA as a new use case: https://github.com/jacoco/jacoco/wiki/FilteringOptions
