### ISSUE TITLE
Trying to  Implement code coverage aggregator in sonar qube for Multimodel project

### ISSUE THREAD

**Issue by vivekkumar71** [jacoco/jacoco#375]
Here I have done  following changes as per my in  pom.xml file 

I am also getting this error :1234: 

JaCoCoSensor: JaCoCo report not found : /var/lib/jenkins/workspace/BuildBreaker-Debug/target/jacoco.exec
[INFO] JaCoCoItSensor: JaCoCo IT report not found: /var/lib/jenkins/workspace/BuildBreaker-Debug/target/jacoco-it.exec
[INFO] JaCoCoOverallSensor: JaCoCo reports not found.

<plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>cobertura-maven-plugin</artifactId>
            <version>2.7</version>
                        
                <goals>
            <goal>cobertura</goal>
                        <goal>cobertura-integration-test</goal>
        </goals>
            <configuration>
                <check>
                    <haltOnFailure>true</haltOnFailure>
                    <branchRate>0</branchRate>
                    <lineRate>0</lineRate>
                    <totalBranchRate>0</totalBranchRate>
                    <totalLineRate>0</totalLineRate>
                    <packageLineRate>0</packageLineRate>
                    <packageBranchRate>0</packageBranchRate>
                </check>
                <aggregate>true</aggregate>
                <formats>
                    <format>xml</format>
                    <format>html</format>
                </formats>
                <instrumentation>
                    <excludes>
                        <exclude>generated-classes/**/*.class</exclude>
                        <exclude>**/*IntegrationTest.class</exclude>
                    </excludes>
                </instrumentation>
            </configuration>
        </plugin>

Also tried with this approach as per this link https://github.com/jacoco/jacoco/pull/97  I tried executing this targets 

clean org.codehaus.mojo:cobertura-maven-plugin:2.7:check -Daggregate=true 

This didn't worked then I also tried by another approach - I made again changes to pom.xml file  with following chanfes in pom.xml file 

plugin>
            <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.7.4.201502262128</version>
                        
                <goals>
            <goal>aggregate-report</goal>
                        <goal>check</goal>
        </goals>
            <configuration>
                <check>
                    <haltOnFailure>true</haltOnFailure>
                    <branchRate>0</branchRate>
                    <lineRate>0</lineRate>
                    <totalBranchRate>0</totalBranchRate>
                    <totalLineRate>0</totalLineRate>
                    <packageLineRate>0</packageLineRate>
                    <packageBranchRate>0</packageBranchRate>
                </check>
                <aggregate>true</aggregate>
                <formats>
                    <format>xml</format>
                    <format>html</format>
                </formats>
                <instrumentation>
                    <excludes>
                        <exclude>generated-classes/**/*.class</exclude>
                        <exclude>**/*IntegrationTest.class</exclude>
                    </excludes>
                </instrumentation>
            </configuration>
        </plugin>
   </plugins>

This is also failing.  

can you please help me out to how can I invoke the aggregator while running my builds.

What goals I can use.

In this below sample can you tell us where we have to include the aggregator tag
  ```

  <groupId>org.jacoco</groupId>
      <artifactId>jacoco-maven-plugin</artifactId>
      <version>0.7.4.201502262128</version>
      <executions>
        <execution>
          <id>pre-unit-test</id>
          <goals>
            <goal>prepare-agent</goal>
          </goals>
          <configuration>
          <!-- Sets the path to the file which contains the execution data. -->
             <destFile>${project.build.directory}/jacoco-ut.exec</destFile>
             <!-- Sets the name of the property containing the settings	for JaCoCo runtime agent.-->
             <propertyName>surefireArgLine</propertyName>
          </configuration>
        </execution>
        <!--Ensures that the code coverage report for unit tests is created after unit tests have been run.-->
        <execution>
          <id>post-unit-test</id>
          <phase>test</phase>
          <goals>
            <goal>report</goal>
          </goals>
          <configuration>
          <!-- Sets the path to the file which contains the execution data. -->
          <dataFile>${project.build.directory}/jacoco-ut.exec</dataFile>
          <!-- Sets the output directory for the code coverage report. -->
          <outputDirectory>${project.reporting.outputDirectory}/jacoco-ut</outputDirectory>
          </configuration>
</execution></executions>
    </plugin><plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-surefire-plugin</artifactId>
   <version>2.12.4</version>
   <configuration>
     <!-- Sets the VM argument line used when unit tests are run. -->
     <argLine>${surefireArgLine}</argLine>
     <!-- Skips unit tests if the value of skip.unit.tests property is true -->
     <skipTests>${skip.unit.tests}</skipTests>
     <!-- Excludes integration tests when unit tests are run. -->
     <excludes>
       <exclude>**/IT*.java</exclude>
     </excludes>
   </configuration>
  </plugin></plugins>
```
mvn org.jacoco:jacoco-maven-plugin:$(version):prepare-agent -Daggregate=true

**Comment by Godin** [comment]
Hi,

First of all - this is issue tracker, but not a support forum. There is mailing list for general questions - https://groups.google.com/forum/?fromgroups=#!forum/jacoco However: there is no aggregation in released version of jacoco-maven-plugin for the time being - #97 is still open. And if you face issue with SonarQube (not clear from your message), then - http://www.sonarqube.org/get-support/

**Comment by vivekkumar71** [comment]
Trying to Implement code coverage aggregator in sonar qube for Multimodel project 

groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.7.4.201502262128</version>
                        

When we are trying to run it is not creating the jacoco.exec even for individual project.

Also please can you let us know what will be the tag and goals for aggregator plugin.
