### ISSUE TITLE
reported coverage in Catch-Branch missed sometimes

### ISSUE THREAD

**Issue by frankstolle** [jacoco/jacoco#378]
I have a problem with reported coverage in the following first catch-branch (InvocationTargetException):
```java
 public void foo(String methodName) {
    try {
      Logic logic = Logic.class.getConstructor(int.class).newInstance(i);
      Method method = Logic.class.getDeclaredMethod(methodName);
      method.invoke(logic);
    } catch (InvocationTargetException e) {
      if (e.getTargetException() instanceof AssertionError)
        throw (AssertionError) e.getTargetException();
      throw new AssertionError(e.getTargetException());
    } catch (InstantiationException | IllegalAccessException | NoSuchMethodException e) {
      throw new AssertionError(e);
    }
}
```

The first throw is never reported als covered. I have built a example-project (https://github.com/frankstolle/jacocotest).

**Comment by marchof** [comment]
This is probably because your example method Logic.bar() actually never throws an AssertionError. It only throws RuntimeException (which wraps an AssertError). Maybe a debugger helps to understand what the code actually does.

**Comment by frankstolle** [comment]
Thank you for your help. Yes you're right, I oversee something and it was my mistake. The measured coverage is right!
