### ISSUE TITLE
spurious missing instruction warning on private constructors

### ISSUE THREAD

**Issue by mcandre** [jacoco/jacoco#379]
JaCoCo erroneously reports warnings for unreachable private constructors. They're *intended* to be unreachable.

Example project:

https://github.com/mcandre/hello-thrift

**Comment by Godin** [comment]
Quoting #298:
> Such a feature would be part of the filtering story #15. The case is on the list:
> https://github.com/jacoco/jacoco/wiki/FilteringOptions
