### ISSUE TITLE
[Z cannot be cast to [Ljava.lang.Object

### ISSUE THREAD

**Issue by Jerry0226** [jacoco/jacoco#384]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.eclemma.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

public String toString()
  {
    StringBuffer localStringBuffer = new StringBuffer();
    Field[] arrayOfField1 = getClass().getDeclaredFields();
    if (arrayOfField1 != null) {
      localStringBuffer.append("Object Value List :").append(System.getProperty("line.separator"));
      for (Field localField : arrayOfField1) {
        if (!localField.isAccessible()) {
          localField.setAccessible(true);
        }localStringBuffer.append(localField.getName()).append(":[");
        String str;
        try { str = StringUtil.toString(localField.get(this));
        } catch (IllegalArgumentException localIllegalArgumentException)
        {
          str = "";
        }
        catch (IllegalAccessException localIllegalAccessException) {
          str = "";
        }
        localStringBuffer.append(str).append("]").append(System.getProperty("line.separator"));
      }
    }
    return localStringBuffer.toString();
  }

<modelVersion>4.0.0</modelVersion>

  <groupId>org.jacoco</groupId>
  <artifactId>root</artifactId>
  <version>0.7.7-SNAPSHOT</version>

JaCoCo version:
Operating system:
Tool integration: Maven/Ant/API/Other

### Actual behaviour
Caused by: java.lang.ClassCastException: [Z cannot be cast to [Ljava.lang.Object;

**Comment by marchof** [comment]
Can you please add the full stack trace?

**Comment by Jerry0226** [comment]
java.lang.ClassCastException: [Z cannot be cast to [Ljava.lang.Object;
	at com.ztesoft.zmart.test.StringUtil.toString(StringUtil.java:159)
	at com.ztesoft.zmart.test.TestCaseException.toString(TestCaseException.java:21)
	at com.ztesoft.zmart.test.Test.main(Test.java:22)


source java:

package com.ztesoft.zmart.test;

import java.lang.reflect.Field;

public class TestCaseException {
	public String toString()
	  {
	    StringBuffer localStringBuffer = new StringBuffer();
	    Field[] arrayOfField1 = getClass().getDeclaredFields();
	    if (arrayOfField1 != null) {
	      localStringBuffer.append("Object Value List :").append(System.getProperty("line.separator"));
	      for (Field localField : arrayOfField1) {
	    	  System.out.println("test========== " + localField.getName() + " -- " + localField.getType())  ;
//	    	  if (localField.getName().equals("$jacocoData")) {
//	    		  continue;
//	    	  }
	        if (!localField.isAccessible()) {
	          localField.setAccessible(true);
	        }localStringBuffer.append(localField.getName()).append(":[");
	        String str;
	        try { str = StringUtil.toString(localField.get(this));
	        } catch (IllegalArgumentException localIllegalArgumentException)
	        {
	          str = "";
	        }
	        catch (IllegalAccessException localIllegalAccessException) {
	          str = "";
	        }
	        localStringBuffer.append(str).append("]").append(System.getProperty("line.separator"));
	      }
	    }
	    return localStringBuffer.toString();
	  }
}

**Comment by marchof** [comment]
Ok, so the interesting method to look at is StringUtil.toString(). How does this code look like?

**Comment by Jerry0226** [comment]
sorry!!!,there may be problems with our own logic,

StringUtil.toString() code :
public static String toString(Object paramObject)
  {
    if (paramObject == null) {
      return "";
    }
    if (paramObject.getClass().isArray()) {
      return arrayToString((Object[])(Object[])paramObject);   ----There was a mistake
    }

    if ((paramObject instanceof List)) {
      return listToString((List)paramObject, null);
    }
    return paramObject.toString();
  }

because,Probe is boolean[] , boolean[]  -> Object[] ,here Forced type conversion error

if (paramObject.getClass().isArray()) {
      return arrayToString((Object[])(Object[])paramObject);   ----There was a mistake
    } 

I will revise this method in the future

Thanks so much!!!!!
