### ISSUE TITLE
Some throw exception defined by myself is not collected

### ISSUE THREAD

**Issue by AtuGao** [jacoco/jacoco#385]
[demo_maven_junit.zip](https://github.com/jacoco/jacoco/files/179013/demo_maven_junit.zip)

version: 0.7.4.201502262128
from Unit test log, Demo.java:22 is executed, so Demo.java:23 is surely to be executed. the branch a==2 is excuted.
Unittest log is
`-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.atugao.coverageDemo.DemoUnitTest
Demo.java:25
Demo.java:19
Demo.java:16
Demo.java:19
Demo.java:16
Demo.java:22 a==2`

but, in the coverage data, Demo.java:22-23 and the branch a==2 has not been executed.
The problem can be located from the following test , itoccurs in Demo.java:23. when I mask Demo.java:23 and re-run the unit test, everything is correct.

when i use version:0.7.5.201505241946 to do the test, in the coverage data, Demo.java:22 is excuted .And Demo.java:23 should be shown in the executed record, but not ...
when i use version:0.7.6.201602180812, it's the lastest , it showed the same result as version:0.7.5.201505241946

**Comment by marchof** [comment]
Implicit exceptions causing missed branches is a known issue: #321
