### ISSUE TITLE
0 code coverage for class in includes

### ISSUE THREAD

**Issue by jmart1** [jacoco/jacoco#391]
I was noticing that when I put a class in the configuration includes list then it shows up in the report with 0 code coverage and fails code coverage.

### Steps to reproduce

Created a Maven project with multiple packages and classes.  Created tests.  Added JaCoCo maven plugin, with code coverage rule, and verify that code coverage report looks accurate and code coverage rules are passed.  Then reconfigured JaCoCo configuration to have `<includes>` with one `<include>` entry to the full path of 1 class.  The report is created but the class shows up with 0 code coverage and code coverage rule fails.

If I use the package path with a suffix of `**`, then the classes in that package show up correctly in the JaCoCo report.  Please note that when the problem is reproduced, the class in question shows up in the report and all its code is there, is just that the coverage is 0.  Basically any `<include>` entry that has the full path of the class, or even if it has `**/MyClass.class`, will cause the problem.  If I do the full path but replace the `.class` with `**`, then the problem does not happen.

So replacing .class with ** is a workaround.

JaCoCo version:  0.7.6.201602180812
Operating system:  Windows 7 and Jenkins running on Linux RH
Tool integration: Maven

### Expected behaviour
Expect code coverage to be the same.

### Actual behaviour
Code coverage goes to 0 when .class is used as suffix.

**Comment by marchof** [comment]
Unfortunatelly the includes and excludes parameters have slightly different semantics for the prepare-agent and report goal:

* prepare-agent: Java VM class names (e.g. com/example/MyClass)
* report: Java class file name (e.g. com/example/MyClass.class)

If you can't find a expression which satisfies both names, you might configure the goals separately. Also typically it should be enough to configure the report goal only to limit the scope of your coverage report.

See #34.

**Comment by jmart1** [comment]
Thank you for the clarification.
