### ISSUE TITLE
Ability to show difference between 2 coverage reports

### ISSUE THREAD

**Issue by AAverin** [jacoco/jacoco#392]
Jacoco needs an ability to not only merge, but also diff 2 reports - that will allow to keep statistics and report increase or decrease in coverage if necessary

**Comment by marchof** [comment]
@AAverin We recommend using a tools like SonarQube for this.

**Comment by marchof** [comment]
While this is not supported by the tools shipped with JaCoCo there's an API for this:

ExecutionDataStore.subtract(ExecutionDataStore)

**Comment by AAverin** [comment]
Unfortunately, SonarQube doesn't support Kotlin yet.
Also, it takes time to run CI, build, calculate coverage, pass to SonarQube and developer has to go to some page to see if coverage got better or not.

I'll take a look into `subtract`. The idea is that PR should get a comment with some coverage result prompting developer to improve tests quality
