### ISSUE TITLE
Calculate coverage for list of sources, not only list of directories

### ISSUE THREAD

**Issue by AAverin** [jacoco/jacoco#393]
Ability to calculate coverage for list of sources will allow to calculate coverage for a pull request diff by passing all classes that were modified in a PR to Jacoco. This will be very helpful when trying to understand if all newly written and changed code is properly covered with tests

**Comment by marchof** [comment]
This not supported by our existing integrations (Ant, Maven), but can be done with the core APIs. You can select the relevant coverage data from  IPackageCoverage.getSourceFiles().

**Comment by AAverin** [comment]
@marchof I need the ability to pass in list of exact source classes for coverage - that will help pin exact lines that were not properly covered in current pull request.
This is usually a problem - developers forgetting to cover some small new method or a small class.

We are using Gradle plugin for Android development.

**Comment by marchof** [comment]
What format will be the "list of exact source classes"? Who will provide that? Do you have an example?

**Comment by AAverin** [comment]
Format could be just a classpath array.

A developer works in a new branch, adds and modifies classes and creates a pull request.
CI grabs that pull request hash, using git makes a list of classes that were affected in a PR.
Jacoco accepts a list of classes and calculates coverage on them.
Having such report, CI can report back on PR in a comment, that some of the classes in PR were not properly covered, and let developer write better tests

**Comment by marchof** [comment]
Are you talking about Java classes or source files? There are differences...

**Comment by AAverin** [comment]
Sorry, probably my wording mixed up.
Git PR has a list of paths to source files, so would be nice to handle those in Jacoco.
Jacoco at the moment accepts source folders, why not add the ability to filter those by exact list of files?

**Comment by marchof** [comment]
Coverage analysis in JaCoCo is based on **class** files only. You can specify the scope by filtering the **class** files you feed into the report generator.

Providing **source** files is optional and only used for source highlighting the the reports.

**Comment by AAverin** [comment]
I see. Filtering at the moment only supports excluding classes, as far as I recall.
Do you plan to have option of excluding all, including some?

**Comment by marchof** [comment]
As of today you can use arbitrary includes and excludes lists to filter **class** files to specify the scope of the report.

**Comment by AAverin** [comment]
Thanks, made it working with includes
