### ISSUE TITLE
Shutdown hook not executed due to race condition in JDK

### ISSUE THREAD

**Issue by johannburkard** [jacoco/jacoco#394]
I have [a project that uses jacoco](/johannburkard/eproxy) where jacoco only randomly works. I think this is due to the JVM spawned by the surefire plugin exiting without jacoco closing its files.

When you clone the project above, do something like `seq 1 25 | while read num; do mvn clean test | tee log >/dev/null; ll target; done` and you'll see

```
-rw-rw-r-- 1 johann johann 41499 Apr  9 00:33 jacoco.exec
```
or
```
-rw-rw-r-- 1 johann johann    0 Apr  9 00:33 jacoco.exec
```

pretty randomly. In the first case, jacoco worked, in the second, it didn't. One thing I did that may have helped is to call `System.runFinalizersOnExit(true);` in a unit test.

Can you change writing to the destination file? Maybe by fsync'ing after every write?

### Steps to reproduce

JaCoCo version: 0.7.6.201602180812
Operating system: Linux
Tool integration: Maven 3.3.3

### Expected behaviour

Coverage is generated for unit tests every time `mvn test` is run.

### Actual behaviour

Coverage isn't written at least half the time.

**Comment by marchof** [comment]
exec files are written at shutdown using the JVM's Runtime.addShutdownHook() API. Also exec files are always closed after writing so they should be synced. Maybe build logs or surefire logs give some hints what's going on at shutdown?

**Comment by Godin** [comment]
@marchof it seems that IOException happens during agent shutdown - 
[log.txt](https://github.com/jacoco/jacoco/files/212501/log.txt)

**Comment by marchof** [comment]
@Godin It looks like the jacocoagent.jar is somehow corrupted (i.e. cropped). What could be the cause for this especially as it does not happen every time?

**Comment by Godin** [comment]
@marchof I don't think that this relates to corruption of JAR. Exception differs from run to run - 
[log.txt](https://github.com/jacoco/jacoco/files/212577/log.txt)

**Comment by Godin** [comment]
No exceptions for 10 runs when `System.runFinalizersOnExit(true);` commented-out in `src/test/java/com/eaio/eproxy/DummyTest.java`, but file `jacoco.exec` sometimes is indeed empty in this case :confused: From here I have feeling that something messes up JVM shutdown hooks.

**Comment by marchof** [comment]
* parallel execution?
* two JaCoCo agents?

**Comment by marchof** [comment]
@Godin Is there a tool to log all files system access during build?

**Comment by Godin** [comment]
@marchof  I don't think that this relates to parallelism: I force Maven to use only one forked JVM for test execution and @johannburkard seems that `AsyncMemcacheServiceHttpCacheStorageTest` messes up shutdown hooks - all fine, if this test ignored

**Comment by Godin** [comment]
More precisely - test-case `InterruptedException should interrupt the thread` in it, code of which looks very suspicious:
```
assertThat(Thread.currentThread().isInterrupted(), is(true))
```

**Comment by marchof** [comment]
This is actually a known issue: https://github.com/jacoco/eclemma/issues/64

**Comment by Godin** [comment]
@marchof and jacoco/eclemma#64 was classified by you as a bug on our side. I added some debug output and in such scenario shutdown hook either not executed at all, either terminated in the middle, thus not sure that this is fixable on our side.

**Comment by marchof** [comment]
@Godin I still want to understand what's going on here exactly. With this simple reproducer I cannot reproduce the problem: https://gist.github.com/marchof/9e439d5b766311276016cadcca23cefc

Maybe it's an additional timing issue or it is related to blocking I/O operations.

**Comment by Godin** [comment]
@marchof after addition of "System.exit(0)" to the end of your example, I don't see execution of hook:
```
public class Main {
  public static void main(String[] args) throws InterruptedException {
    Runtime.getRuntime().addShutdownHook(new Thread() {
      @Override
      public void run() {
        System.out.println("Shutdown Hook");
      }
    });
    Thread.currentThread().interrupt();
    System.exit(0);
  }
}
```

**Comment by marchof** [comment]
@Godin I can confirm, but only with Java 8 JDK. 6 & 7 seems work on my side.
Should we discuss this with OpenJDK?

**Comment by Godin** [comment]
@marchof For me this happens with JDK 1.7.0_80 and in fact sometimes (very rare) I see the execution.

**Comment by Godin** [comment]
@marchof I'm not sure that this example is valid for reporting to OpenJDK, because hook will be executed, if just before `System.exit` interrupted status is cleared as `System.out.println(Thread.interrupted());` (note that `Thread.currentThread().isInterrupted()` doesn't clear interrupted status).

**Comment by Godin** [comment]
@marchof and here is another example, where I always see "start", but rare "run":
```
public class Main {
  public static void main(String[] args) throws InterruptedException {
    Runtime.getRuntime().addShutdownHook(new Thread() {
      @Override
      public synchronized void start() {
        System.out.println("start");
        super.start();
      }

      public void run() {
        System.out.println("run");
      }
    });
    Thread.currentThread().interrupt();
    System.exit(0);
  }
}
```

**Comment by marchof** [comment]
@Godin And it seems to be specific to the main thread. Can't reproduce with this snippet:

```
public class Shutdown {

	public static void main(String[] args) throws InterruptedException {
		Runtime.getRuntime().addShutdownHook(new Thread() {
			@Override
			public void run() {
				System.out.println("Shutdown Hook");
			}
		});
		new Thread() {
			public void run() {
				System.out.println("Stopping...");
				Thread.currentThread().interrupt();
				System.exit(0);
			};
		}.start();
	}

}
```

**Comment by marchof** [comment]
@Godin I haven't found any documented behavior about interrupted threads, System.exit() and shutdown hooks. So it might be worth reporting this to OpenJDK.

**Comment by Godin** [comment]
@marchof I was asking myself earlier - why JUnit by default executes tests in "main" thread. Maybe this could be a workaround for the original report - ask surefire to parallelize tests in forked JVM, so that JUnit will use non-main threads.

**Comment by marchof** [comment]
@Godin Might work for this case. But I always advocate JaCoCo as a framework agnostic tool. It should work for any application running on the JVM.

**Comment by Godin** [comment]
@marchof this doesn't happen with JDK 9b111 and I'm currently in chat with Aleksey Shipilëv, checking what's going on with JDK 8u, will sum-up here, when we'll finish, but this indeed looks like a bug in JVM

**Comment by marchof** [comment]
@Godin Another "jacoco-found" ;-)))

**Comment by Godin** [comment]
Thanks to Aleksey - confirmed race condition in `java.lang.ApplicationShutdownHooks` when main thread is interrupted. And in fact all JDKs from 1.5 up to 1.9 (even 9b111) affected, reproducer in bug report - https://bugs.openjdk.java.net/browse/JDK-8154017

**Comment by marchof** [comment]
@johannburkard So not so much we can do for you here. Please adjust your tests to not leave the main thread in an interrupted status.

**Comment by johannburkard** [comment]
Thanks guys, you did some amazing detective work here.

**Comment by Godin** [comment]
Fixed in JDK 9 EA b125.

**Comment by Godin** [comment]
For the record:
fix was backported to JDK 8u172 - https://bugs.openjdk.java.net/browse/JDK-8191289
