### ISSUE TITLE
Filtering options using manual tags

### ISSUE THREAD

**Issue by fluidjeel** [jacoco/jacoco#396]
I know there is an open request to enhance filters for coverage analysis. But as a short term fix can I use any manual tags to achieve the same.
https://github.com/jacoco/jacoco/wiki/FilteringOptions

} catch (SomeException e) {
  dohandle(e); // $COVERAGE-IGNORE$
}

If manual tagging is an option, can you please list the steps I need to follow to achieve the same.

Thanks,
Manny

**Comment by marchof** [comment]
Such feature feature is not yet available in JaCoCo. Duplicate #15.
