### ISSUE TITLE
Not executed methods with branches results in NaN branch coverage ratio.

### ISSUE THREAD

**Issue by dawrut** [jacoco/jacoco#419]
I would like to measure branch coverage for a class that is only instantiated with no methods executed.
Branch coverage ratio is NaN instead of 0.0. The ratio is calculated as following:
covered / (missed + covered)

Both missed and coverage values are equal to 0. Why missed is 0 instead of number of the branches?

### Steps to reproduce
I've created a git repo with code example: https://github.com/dawrut/jacoco_issue_report_reproduction
Run: main of research.CoreTutorial class

Code is almost a clone of http://eclemma.org/jacoco/trunk/doc/examples/java/CoreTutorial.java

JaCoCo version: 0.7.6
Operating system: MacOS
Tool integration: Java API

### Expected behaviour
A class that has branches in methods that is only instantiated should have branch coverage ratio equal to 0.

### Actual behaviour
NaN

**Comment by marchof** [comment]
Can you please show the full output of your test program?

**Comment by Godin** [comment]
@dawrut @marchof 
```
method01
method02
method03
Coverage of class research/NoBranchesClassTest
instructions: 1.0
branches: NaN
lines: 1.0
methods: 1.0
complexity: 1.0
Coverage of class research/WithBranchesClassTest
instructions: 1.0
branches: NaN
lines: 1.0
methods: 1.0
complexity: 1.0
```

and indeed - there is no branches in https://github.com/dawrut/jacoco_issue_report_reproduction/blob/68ed545126cb3ead2b3d1299bec4e9650936c917/src/main/java/research/WithBranchesClassTest.java and in https://github.com/dawrut/jacoco_issue_report_reproduction/blob/68ed545126cb3ead2b3d1299bec4e9650936c917/src/main/java/research/NoBranchesClassTest.java

I have strong feeling that reproducer is invalid.

**Comment by marchof** [comment]
@Godin @dawrut Same feeling here: The `CoreTutorial` works for single classes only. It does not include any dependent classes in to the report. The output looks ok for the *Test classes.

**Comment by dawrut** [comment]
Yes, this is true. Thanks!
