### ISSUE TITLE
Availability of "includes" and "excludes" properties in descriptions of "dump", "merge" and "restore-instrumented-classes" mojos is misleading

### ISSUE THREAD

**Issue by Godin** [jacoco/jacoco#424]
![selection_002](https://cloud.githubusercontent.com/assets/138671/15988490/2daa760a-3053-11e6-9c00-be2913a7abc9.png)

![selection_003](https://cloud.githubusercontent.com/assets/138671/15988491/2db512c2-3053-11e6-81ab-f7798b507c9e.png)

![selection_004](https://cloud.githubusercontent.com/assets/138671/15988495/81686874-3053-11e6-934f-e0d61871957f.png)

**Comment by marchof** [comment]
Just a side note: There are more issues with includes/excludes semantics, see: #34
