### ISSUE TITLE
Incorrect coverage for synchronized blocks

### ISSUE THREAD

**Issue by marcbrouwertue** [jacoco/jacoco#431]
JaCoCo version: 0.7.5
Operating system: Windows 7
Tool integration: NetBeans JaCoCoverage plugin

Unless I'm doing something wrong, I think there might be an issue with the coverage of synchronized blocks. Below I have attached examples of a simple getter. In the first 2 cases the methods coverage is 67% instead of 100%. The last image as an example where the value is returned outside of the synchronized block, yet the coverage is 72% while I'd expect 100%.

Example 1:
![jaco](https://cloud.githubusercontent.com/assets/11163337/16565581/94846a1c-420e-11e6-9b40-18d7b85142a1.PNG)
Example 2:
![jaco2](https://cloud.githubusercontent.com/assets/11163337/16565711/6bc505a4-420f-11e6-8860-e139cfb44a1a.PNG)
Example 3:
![jaco3](https://cloud.githubusercontent.com/assets/11163337/16566037/bd74e3ae-4211-11e6-93d2-194156e813e6.PNG)

**Comment by Godin** [comment]
@marcbrouwertue Hi, please see https://github.com/jacoco/jacoco/issues/245#issuecomment-58939096  which describes exactly this known limitation.
