### ISSUE TITLE
jacoco  in wildfly 8.2 running with java 8 - throws Caused by: org.jboss.classfilewriter.InvalidBytecodeException: Cannot  load variable at 0. Local Variables: Local Variables: []  at 

### ISSUE THREAD

**Issue by samkyatham** [jacoco/jacoco#436]
This looks like wildfly issue but appears only when jacoco is enabled. 
It seems jacoco instrumention code(when ejb3 with local interfaces) creates this issue. Please confirm the defect.

>  Caused by: org.jboss.classfilewriter.InvalidBytecodeException: Cannot
> load variable at 0. Local Variables: Local Variables: []  at
> org.jboss.classfilewriter.code.CodeAttribute.aload(CodeAttribute.java:185)
>   at
> org.jboss.invocation.proxy.ProxyFactory$ProxyMethodBodyCreator.overrideMethod(ProxyFactory.java:86)
>   at
> org.jboss.invocation.proxy.AbstractSubclassFactory.overrideMethod(AbstractSubclassFactory.java:106)
>   at
> org.jboss.invocation.proxy.AbstractSubclassFactory.addInterface(AbstractSubclassFactory.java:363)
>   at
> org.jboss.invocation.proxy.ProxyFactory.generateClass(ProxyFactory.java:286)
>   at
> org.jboss.invocation.proxy.AbstractClassFactory.buildClassDefinition(AbstractClassFactory.java:207)
>   at
> org.jboss.invocation.proxy.AbstractClassFactory.defineClass(AbstractClassFactory.java:160)
>   at
> org.jboss.invocation.proxy.AbstractProxyFactory.getCachedMethods(AbstractProxyFactory.java:150)
>   at
> org.jboss.as.ejb3.component.stateless.StatelessComponentDescription$3.configure(StatelessComponentDescription.java:150)
>   at
> org.jboss.as.ee.component.DefaultComponentViewConfigurator.configure(DefaultComponentViewConfigurator.java:68)
>   at
> org.jboss.as.ee.component.deployers.EEModuleConfigurationProcessor.deploy(EEModuleConfigurationProcessor.java:81)
>   ... 6 more

This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.eclemma.org/jacoco/trunk/doc/faq.html

### Steps to reproduce
Ear should contain ejb3 with local interfaces
Use java8 to compile and run wildfly 8.2.0. 
 Deployment fails if jacoco is configured, works okay if jacoco is removed.

Works very well with java7.

JaCoCo version: 0.7.7.201606060606
Operating system: Linux
Tool integration: Maven/Ant/API/Other: Ant

### Expected behaviour
Ear deployment should be successful with jacoco java agent.

### Actual behaviour
Deployment fails with Invalid Bytecode exception

**Comment by Godin** [comment]
@samkyatham Could you please specify **exact** version of JaCoCo or make sure that you are using latest release - 0.7.7, because there were fixes for Java 8 in various releases of 0.7.x series.

And if you are already using latest released, then could you please share with us an example of project, with which we can play to reproduce this?

**Comment by samkyatham** [comment]
@Godin Here is the exact version: jacoco-0.7.7.201606060606

**Comment by marchof** [comment]
According to the stack trace the problem seems to be with the JBoss class file generator. Due to our extensive integration tests I'm pretty sure JaCoCo creates valid class files. I recommend reporting this issue to JBoss or excluding affected classes from JaCoCo code coverage.

**Comment by samkyatham** [comment]
@marchof does jacoco use lambdas if java 8 is used? (seems like wildfly 8 face issues with lambdas)

Could you help how specific classes(or package) can be excluded as part of jacoco configuration.

**Comment by marchof** [comment]
@samkyatham No, JaCoCo itself is compiled with Java 5 only.

No idea what classes causes the problem. Ask JBoss for a more detailed error message.

**Comment by Godin** [comment]
@samkyatham I'm pretty sure that you can find an answer about how to configure exclusions in our documentation - http://www.eclemma.org/jacoco/trunk/doc/
