### ISSUE TITLE
Current status of Multi Module support for Jacoco

### ISSUE THREAD

**Issue by nigurr** [jacoco/jacoco#437]
Hi,

This [wiki link](https://github.com/jacoco/jacoco/wiki/MavenMultiModule) shows that it's not supported yet.
But this PR: https://github.com/jacoco/jacoco/pull/388 gives information that it's implemented.

Can anyone give the correct status? if supported, any test-case/example?

**Comment by Godin** [comment]
@nigurr first of all: this is issue tracker, so next time please use our forum for questions - https://groups.google.com/forum/#!forum/jacoco

Answering your question:
as stated in changelog ( http://www.eclemma.org/jacoco/trunk/doc/changes.html )

>  Maven goal report-aggregate to create reports for multi-module projects (GitHub #388)

has been added in version 0.7.7.
As usual documentation for it available on our site - http://www.eclemma.org/jacoco/trunk/doc/report-aggregate-mojo.html
An integration test for it can be found in https://github.com/jacoco/jacoco/tree/v0.7.7/jacoco-maven-plugin.test/it/it-report-aggregate

Hope this helps.
