### ISSUE TITLE
Java 9: IllegalAccessError on CLDRLocaleDataMetaInfo.$jacocoData

### ISSUE THREAD

**Issue by don-vip** [jacoco/jacoco#439]
### Steps to reproduce

Run JOSM Junit test from Ant build file, using current JDK9-ea build.

JaCoCo version: jacoco-0.7.8-20160724.185238-10
Operating system: Linux Ubuntu 16.04.1
Tool integration: Ant 1.9.7

### Expected behaviour

Test run ok.

### Actual behaviour

    [echo] Running unit tests with JUnit
    [jacoco:coverage] Enhancing junit with coverage
    [junit] Exception in thread "main" java.util.ServiceConfigurationError: sun.util.locale.provider.LocaleDataMetaInfo: Provider sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo could not be instantiated
    [junit] 	at java.util.ServiceLoader.fail(java.base@9-ea/ServiceLoader.java:379)
    [junit] 	at java.util.ServiceLoader.access$800(java.base@9-ea/ServiceLoader.java:218)
    [junit] 	at java.util.ServiceLoader$ModuleServicesIterator.nextService(java.base@9-ea/ServiceLoader.java:741)
    [junit] 	at java.util.ServiceLoader$RestrictedIterator.next(java.base@9-ea/ServiceLoader.java:538)
    [junit] 	at java.util.ServiceLoader$2.next(java.base@9-ea/ServiceLoader.java:921)
    [junit] 	at sun.util.cldr.CLDRLocaleProviderAdapter$1.run(java.base@9-ea/CLDRLocaleProviderAdapter.java:76)
    [junit] 	at sun.util.cldr.CLDRLocaleProviderAdapter$1.run(java.base@9-ea/CLDRLocaleProviderAdapter.java:73)
    [junit] 	at java.security.AccessController.doPrivileged(java.base@9-ea/Native Method)
    [junit] 	at sun.util.cldr.CLDRLocaleProviderAdapter.<init>(java.base@9-ea/CLDRLocaleProviderAdapter.java:73)
    [junit] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-ea/Native Method)
    [junit] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@9-ea/NativeConstructorAccessorImpl.java:62)
    [junit] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@9-ea/DelegatingConstructorAccessorImpl.java:45)
    [junit] 	at java.lang.reflect.Constructor.newInstance(java.base@9-ea/Constructor.java:453)
    [junit] 	at java.lang.Class.newInstance(java.base@9-ea/Class.java:565)
    [junit] 	at sun.util.locale.provider.LocaleProviderAdapter.forType(java.base@9-ea/LocaleProviderAdapter.java:175)
    [junit] 	at sun.util.locale.provider.LocaleProviderAdapter.findAdapter(java.base@9-ea/LocaleProviderAdapter.java:278)
    [junit] 	at sun.util.locale.provider.LocaleProviderAdapter.getAdapter(java.base@9-ea/LocaleProviderAdapter.java:249)
    [junit] 	at java.text.NumberFormat.getInstance(java.base@9-ea/NumberFormat.java:859)
    [junit] 	at java.text.NumberFormat.getInstance(java.base@9-ea/NumberFormat.java:429)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.SummaryJUnitResultFormatter.<init>(SummaryJUnitResultFormatter.java:44)
    [junit] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-ea/Native Method)
    [junit] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@9-ea/NativeConstructorAccessorImpl.java:62)
    [junit] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@9-ea/DelegatingConstructorAccessorImpl.java:45)
    [junit] 	at java.lang.reflect.Constructor.newInstance(java.base@9-ea/Constructor.java:453)
    [junit] 	at java.lang.Class.newInstance(java.base@9-ea/Class.java:565)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.FormatterElement.createFormatter(FormatterElement.java:301)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.FormatterElement.createFormatter(FormatterElement.java:257)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.transferFormatters(JUnitTestRunner.java:1085)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1180)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1004)
    [junit] Caused by: java.lang.IllegalAccessError: Update to static final field sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo.$jacocoData attempted from a different method ($jacocoInit) than the initializer method <clinit> 
    [junit] 	at sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo.$jacocoInit(jdk.localedata@9-ea/CLDRLocaleDataMetaInfo.java)
    [junit] 	at sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo.<clinit>(jdk.localedata@9-ea/CLDRLocaleDataMetaInfo.java)
    [junit] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-ea/Native Method)
    [junit] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@9-ea/NativeConstructorAccessorImpl.java:62)
    [junit] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@9-ea/DelegatingConstructorAccessorImpl.java:45)
    [junit] 	at java.lang.reflect.Constructor.newInstance(java.base@9-ea/Constructor.java:453)
    [junit] 	at java.util.ServiceLoader$ModuleServicesIterator.nextService(java.base@9-ea/ServiceLoader.java:737)
    [junit] 	... 27 more
    [junit] Running org.openstreetmap.josm.tools.template_engine.Batch-With-Multiple-Tests
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] Tests FAILED (crashed)

**Comment by Godin** [comment]
See #434

**Comment by don-vip** [comment]
Thanks for the link, I looked for a similar problem in issues, but forgot to check in PRs :+1: I see the PR is almost complete, do you know when the code review will be done?

**Comment by Godin** [comment]
@don-vip I do not know ETA as I don't know about availability of time for @marchof , but not sure that there is need for rush given the fact that for earlier JDKs and earlier builds of JDK 9 it works and later is still in EA state and things may change ( still need to come back to hotspot-dev to verify whether this new check will be enabled by default or only in case of Java 9 bytecode, what however will not change  the need of fix on our side ).

However what you can do instead of waiting - is to test this PR and give us your feedback.

**Comment by don-vip** [comment]
Sure! I will try it tonight :)
