### ISSUE TITLE
jacoco maven plugin should not fail the build when some tests have failed

### ISSUE THREAD

**Issue by vmassol** [jacoco/jacoco#444]
Right now we have this problem on XWiki's CI (http://ci.xwiki.org):
- We don't fail the build when a test fails - So that the CI reports all tests failing
- However jacoco is configured to fail the build when a threshold is not met
- Thus when a test fails, this reduces the test coverage and our CI reports a jacoco build failure when the issue is actually a test failure.

I don't know how easy or how hard this would be for the jacoco maven plugin to check if some tests have failed. And maybe offer a configuration option to not fail the build if some tests have failed.

**Comment by marchof** [comment]
JaCoCo is independent of the test framework used.

-1 for creating a dependency on JUnit/Failsafe

Maybe there is a plain Maven solution which can be used to configure you're scenario?

**Comment by vmassol** [comment]
Hi Mark,

I was afraid you'd say something along those lines :)

I was thinking that maybe there's a maven property set (independent of the test framework) when a test fails and that can be checked or some generic way of knowing that a test has failed. 

I agree that jacoco shouldn't have a dep on junit or any specific test framework

**Comment by marchof** [comment]
@vmassol But I also have to admit that I don't get your case or your priorities: You accept failed tests but you break the build if you don't meet a certain coverage threshold? So what is the value of your tests except creating coverage? ;-)

**Comment by vmassol** [comment]
@marchof The maven build you execute on your local machine does fail immediately whenever a test fails. However the build, when executed in Jenkins, behaves a bit differently; it does fail but only at the end (that's a very typical setup for CI and that's how Jenkins works by default). The reason is that this allows you to see all failing tests. However Jenkins doesn't do the same for, say, Jacoco, and I don't think it can be configured. I agree that, using the same strategy for jacoco would be the best; i.e. jenkins should continue the job running and not fail it when jacoco finds an error and only report all jacoco threshold failures at the end. Would be a nice feature.

I guess I could find a hackish way of simulating this somehow. I'd need to add a jenkins profile in our POM to override the jacoco property for not failing the the build and activate it when executed inside jenkins, i.e. when a specific property it set (which is easy to do since we add a system property on the command line that starts maven inside Jenkins). However Jenkins will not aggregate all jacoco failures and report them in the UI which means that we won't see the jacoco failures...

... Unless someone develops a jacoco plugin for jenkins to do this....

I've just checked https://wiki.jenkins-ci.org/display/JENKINS/JaCoCo+Plugin and it doesn't seem to support this.

Anyway, don't bother too much, I agree that this is an edge use case for the jacoco project and I don't know of a generic way for a maven plugin to know if some tests have failed. 

Thanks for listening and maybe this will give some ideas to someone to develop this feature :)
