### ISSUE TITLE
Using @Spy causes jacoco to ignore that class

### ISSUE THREAD

**Issue by mattinger** [jacoco/jacoco#447]
### Steps to reproduce

1.  Create a basic JUnit test using the Mockito Framework to test an android Activity instance.
2.  Add an @Spy annotation to your class under test

`
@RunWith(PowerMockRunner.class)
public class MyActivityTest {
    @Spy
    private MyActivity myActivity = new MyActivity();

    @Test
    public void test1() {
        myActivity.method1();
    }
}
`

3.  Run jacoco from gradle:  ./gradlew jacocoTestReport

JaCoCo version: 0.7.7.201606060606
Operating system: MacOS 10.11.x
Tool integration: Gradle

### Expected behaviour

MyClass code coverage is reported

### Actual behaviour

MyClass code coverage is ignored

I realize this is not a simple problem, as @Spy causes runtime code generation, however, the code coverage runner embedded in Android Studio is capable of producing the coverage numbers correctly when running a test like this, so it can be done somehow.

I've explored alternate routes, but they are not feasible for me, due to the design of android's Activity class.  Specifically, i cannot override the Activity.setResult methods as they are final, and they part of my verification.

I also realize that testing Activity instances with junit tests is a little odd, but we're using android databinding, and we interact mostly with the ViewModel, which makes it relatively easy for us to write most tests, except when we're calling into the activity lifecycle like this.

**Comment by Godin** [comment]
@mattinger I'm pretty sure that you can use [JaCoCo offline instrumentation](http://www.eclemma.org/jacoco/trunk/doc/offline.html) as a workaround for this.
