### ISSUE TITLE
Gradle/Androdd/Jacoco/Robolectric/mockito IllegalClassFormatException / IllegalStateException Class is already instrumented 

### ISSUE THREAD

**Issue by ahtokca** [jacoco/jacoco#451]
I've got a multi modules gradle project which builds an android application. I'd like to have jacoco to produce a coverage report. However I get "IllegalClassFormatException / IllegalStateException Class is already instrumented."
I saw couple issues reported under the same exception however they seemed to be caused by another problem. Could please advice how to workaround or get rid of the exception?

Thank you in advance

### Steps to reproduce

JaCoCo version: 0.7.7.201606060606
Operating system: Win7
Tool integration: gradle 2.14.1, android plugin 2.2, robolectirc 3.1.1, mockito 1.9.0
see attached file of how jacoco is wired up
[jacoco.gradle.txt](https://github.com/jacoco/jacoco/files/486855/jacoco.gradle.txt)

### Expected behaviour
report is generated

### Actual behaviour
IllegalClassFormatException followed by IllegalStateException Class is already instrumented 

```
Starting process 'Gradle Test Executor 1'. Working directory: D:\G\project\module Command: D:\java\jdk_8u51\bin\java.exe
 -Djava.awt.headless=true -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -javaagent:target/tmp/expandedArchives/org.jacoco.agent-0.7.7.201606060606.jar_156yqgrthaq4l5119au92060g/jacocoagent.jar=destfile=target/jacoco/testReleaseUnitTest.exec,append=true,inclnolocationclasses=true,dumponexit=true,output=file,jmx=false -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp D:\gradle\caches\2.14.1\workerMain\gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1'
Successfully started process 'Gradle Test Executor 1'
Gradle Test Executor 1 started executing tests.

........MyTest STANDARD_ERROR
    java.lang.instrument.IllegalClassFormatException: Error while instrumenting class ../../../../...Testcase.
        at org.jacoco.agent.rt.internal_6da5971.CoverageTransformer.transform(CoverageTransformer.java:93)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
-------------cut--------------

```

see attach for the whole stacktrace
[exception.txt](https://github.com/jacoco/jacoco/files/486870/exception.txt)

**Comment by Godin** [comment]
First of all - for questions please use our mailing list ( https://groups.google.com/forum/#!forum/jacoco ) in future.

I have feeling that you're mixing "offline instrumentation" with "on-the-fly instrumentation", so either switch on usage of only one mode, either quoting page http://www.eclemma.org/jacoco/trunk/doc/offline.html :
> The agent must be configured in a way that pre-instrumented classes are excluded

**Comment by ahtokca** [comment]
Thank you for the quick reply. I did check the link you provided. I wish I know how to mix offline and online. The only thing I do is wiring up jacoco gradle plugin. How can I make sure which of modes is used?

**Comment by Godin** [comment]
@ahtokca Gradle JaCoCo Plugin is not developed by us. We can't provide question-answer here for tons of tools that integrate JaCoCo library. So better to ask Gradle JaCoCo Plugin developers, or its active users via their communication channels. Or that's why it is preferable to go thru our mailing list, because some of them are reading it, whereas don't check this issue tracker. Thank you for your understanding.

**Comment by ahtokca** [comment]
of course, sure, thanks
