### ISSUE TITLE
JaCoCoSensor: JaCoCo report not found sonar+jaccoo using maven

### ISSUE THREAD

**Issue by nareshvatsal39** [jacoco/jacoco#455]
[INFO] Sensor SurefireSensor
[INFO] parsing C:\Users\naresh.vatsal\xiFolio\target\surefire-reports
[INFO] Sensor SurefireSensor (done) | time=368ms
[INFO] Sensor JaCoCoSensor
[INFO] JaCoCoSensor: JaCoCo report not found : C:\Users\naresh.vatsal\xiFolio\target\surefire-reports\jacoco.exec
[INFO] Sensor JaCoCoSensor (done) | time=16ms
[INFO] Sensor JaCoCoItSensor
[INFO] JaCoCoItSensor: JaCoCo IT report not found: C:\Users\naresh.vatsal\xiFolio\target\surefire-reports\jacoco-it.exec
[INFO] Sensor JaCoCoItSensor (done) | time=15ms
[INFO] Sensor JaCoCoOverallSensor
[INFO] Sensor JaCoCoOverallSensor (done) | time=16ms
[INFO] Sensor XmlFileSensor

**Comment by Godin** [comment]
Since this is solely about SonarQube, please use their support channels http://www.sonarqube.org/get-support/
