### ISSUE TITLE
Can we push the data to server after several hours using the current tcpclient mode

### ISSUE THREAD

**Issue by bastenf** [jacoco/jacoco#456]
The problem for our environment is the network very unstable, alwasy lost connection after one hour.

As you know, for tcpclient mode, the socket between jacoco agent and the server is always connected.

Why we do not use the tcpserver mode? since we do not know how many machines installed jacoco agent, we need use the tcpclient mode to automatically connect to the server, then we can know.
If we use tcpserver mode, any idea for jacoco agent to send online request to some application?

any unclear, please let me know.

**Comment by marchof** [comment]
> any unclear, please let me know.

Yes. Why do you think it's a good idea to post your question to our **issue** tracker AND our mailing list?
