### ISSUE TITLE
Problem with multimodule maven project and site report.

### ISSUE THREAD

**Issue by oldzitterhand** [jacoco/jacoco#464]
**Steps to reproduce:**
JaCoCo version: 0.7.7.201606060606
Operating system: Windows 7 (64Bit)
Tool integration: Maven

**Expected behaviour:**
It should be possible to switch off 'report-aggregate' in a multimodule projects.

**Actual behaviour:**
Not able to switch it off in my setting:

project root - (pom.xml with modules section)
|
|_ parent (pom.xml with all the plugins, etc - including JaCoCo)
|_ sub-module A
|_ sub-module B
|_ sub-module C
|_ sub-module D

I manage to create JaCoCo reports with surefire for each of the sub-modules.
But the report of a sub-module will not be linked within its individual site-report (HTML report).
This is because I am not setting the JaCoCo plugin the report-section. If I set it I get a strange behavior.
I will end up with aggregate reports of some sub-modules in the individual site-reports.
That is having aggregates of A and B in C, aggregate of A and C in D (I don't see a pattern here). Also the aggregate of the individual sub-module will not show up (so no aggregate for D in D). 

I just want a site-report for each sub-module with its JaCoCo report linked in.
I do not want one report for the whole project! I guess this is what the goal report-aggregate was intended for.

Here is my setup (trying to skip the execution in the plugin section and having the plugin in the report section):

Build section in parent pom.xml
```
<build>
   <plugins>
      <!-- build-report related plugins --> 
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
               <argLine>${surefire.argLine} -Xss1024k -Xms256m -Xmx1280m -XX:MaxMetaspaceSize=256m</argLine>
               <excludes>
                  <!-- Excludes as defined by active profile. -->
                  <exclude>${testExclusionPattern}</exclude> 
               </excludes>
            </configuration>
         </plugin>
         <plugin>
           <groupId>org.jacoco</groupId>
           <artifactId>jacoco-maven-plugin</artifactId>
              <version>${comara.ext.jacoco.version}</version><!--$NO-MVN-MAN-VER$-->
              <executions>
                  <execution>
                     <id>pre-unit-test</id>
                     <goals>
                        <goal>prepare-agent</goal>
                     </goals>
                     <configuration>
                           <destFile>${jacoco.ut.execution.data.file}</destFile>
                           <propertyName>surefire.argLine</propertyName>
                      </configuration>
                   </execution>
                   <execution>
                   <id>post-unit-test</id>
                      <phase>test</phase>
                      <goals>
                         <goal>report</goal>
                      </goals>
                      <configuration>
                         <dataFile>${jacoco.ut.execution.data.file}</dataFile>
                         <outputDirectory>${project.reporting.outputDirectory}/jacoco-ut</outputDirectory>
                      </configuration>
                   </execution>
                   <execution>
                      <id>report-aggregate</id>
                      <phase>verify</phase>
                      <goals>
                         <goal>report-aggregate</goal>
                      </goals>
                      <configuration>
                         <skip>true</skip>
                      </configuration>
                   </execution>
                </executions>
             </plugin>
          </plugins>
<build>
```
Report section in parent pom.xml
```	<!-- Setting up the plugins for the site-report -->
	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-report-plugin</artifactId>
				<configuration>
					<reportSets>
						<reportSet>
							<reports>
								<report>report-only</report>
							</reports>
						</reportSet>
					</reportSets>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>${comara.ext.jacoco.version}</version>
			</plugin>
```
The plugin setting for JaCoCo in the report section will execute report-aggregation and I am not able to switch this off. I have tried different approaches including https://github.com/jacoco/jacoco/issues/409
As I said: Deleting the plugin from the report section will lead to non-linked report within the site-report.

Is there any workaround or solution for this available?

Cheers
Patrick

**Comment by Godin** [comment]
> I do not want one report for the whole project! I guess this is what the goal report-aggregate was intended for.

A bit unclear what you mean here: `report-aggregate` was developed for scenarios, where people want to aggregate coverage across modules, in particular - one report for the while project. If you don't want this, then don't use `report-aggregate`.

> The plugin setting for JaCoCo in the report section will execute report-aggregation and I am not able to switch this off.

As an answer to this let me quote https://maven.apache.org/plugins/maven-site-plugin/examples/configuring-reports.html :
> By default, when you add a plugin in reporting section, every reporting goal available in the plugin is rendered once.
> If you want to choose only some reports from a plugin ... you need to configure report sets ...

There is nothing what we can do, since this behavior is dictated by the Maven site-plugin.
And this is also described in our documentation - http://www.eclemma.org/jacoco/trunk/doc/maven.html

If this doesn't help, then please provide minimalistic, but complete example (instead of separate pieces, especially in case of multi-module configurations) to reproduce your issue.

Also note that for questions better to use our mailing list - https://groups.google.com/forum/#!forum/jacoco

Thank you for your understanding.

**Comment by oldzitterhand** [comment]
Hi again,

thank you for your quick answer.  I guess an cannot provide the whole structure and all the pom.xml files of the project as I would have to remove everything that points to the company I am working for and this would render the files useless I guess. Also I am afraid to miss something and hints will stay in the files. Besides from that, I hoped that by describing the project structure and giving the part of the file pom.xml which is responsible for generation of reports would be enough.

From your answer I now fully aware that I understood the purpose of `report-aggregate` correctly (and do not want/need it).
What I don't understand, is why the maven site-report does not contain a link to the jacoco-report when setting up the report section like this:

```
<reporting>
   <plugins>
      <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-surefire-report-plugin</artifactId>
         <configuration>
            <reportSets>
               <reportSet>
                  <reports>
                     <report>report-only</report>
                  </reports>
               </reportSet>
            </reportSets>
         </configuration>
      </plugin>
      <plugin>
         <groupId>org.jacoco</groupId>
         <artifactId>jacoco-maven-plugin</artifactId>
         <version>${comara.ext.jacoco.version}</version>
         <reportSets>
            <reportSet>
               <reports>
                  <report>report</report>
               </reports>
            </reportSet>
         </reportSets>
      </plugin>
      .
      .
      .
   </plugins>
</reporting>
```

However the report itself is generated. I just does not get linked within the site-report. Therefor it's the same behavior as not putting jacoco in the report section at all.

**Comment by oldzitterhand** [comment]
Oh... just discovered a working solution:
```
<reporting>
   <plugins>
      <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-surefire-report-plugin</artifactId>
         <configuration>
            <reportSets>
               <reportSet>
                  <reports>
                     <report>report-only</report>
                  </reports>
               </reportSet>
            </reportSets>
         </configuration>
      </plugin>
      <plugin>
         <groupId>org.jacoco</groupId>
         <artifactId>jacoco-maven-plugin</artifactId>
         <version>${comara.ext.jacoco.version}</version>
         <reportSets>
            <reportSet>
               <reports>
                  <report>report</report>
               </reports>
            </reportSet>
         </reportSets>
         <configuration>
            <!-- Sets the path to the file which contains the execution data. -->
            <dataFile>${jacoco.ut.execution.data.file}</dataFile>
            <!-- Sets the output directory for the code coverage report. -->
            <outputDirectory>${project.reporting.outputDirectory}/jacoco-ut</outputDirectory>
         </configuration>
      </plugin>
      .
      .
      .
   </plugins>
</reporting>
```
In addition to the plugin configuration I am setting the dataFile and outputDirectory again in the report section. That seems to give me the desired result (the link in the site-report).
Still confused why I have to do the configuration twice (see execution section in my first post).

**Comment by Godin** [comment]
Quoting https://maven.apache.org/pom.html#Reporting 
> build plugin configuration does not affect a reporting

By declaring `report` in both `build` and `reporting` sections you are getting two executions - if execution during `test` phase is undesired, then simply remove it.

**Comment by oldzitterhand** [comment]
Awesome! Thank you very much!
