### ISSUE TITLE
Publish new Jacoco release

### ISSUE THREAD

**Issue by TimvdLippe** [jacoco/jacoco#467]
The latest Jacoco release is almost 6 months old and master has since then merged a significant number of pullrequests (https://github.com/jacoco/jacoco/compare/v0.7.7...master). Could you publish a new release so we can use the fixes merged into master?

**Comment by Godin** [comment]
Hi @TimvdLippe , most of the changes is about JDK 9 (not counting documentation), which is itself not yet released and hence might potentially require more changes, as it was with JaCoCo version 0.7.7 that started to provide JDK 9 support.

IMO the only important change affecting usage of JaCoCo with lower JDK versions is #441.

So may I ask which changes are of particular interest for you?

**Comment by TimvdLippe** [comment]
At Mockito we are preparing the library for JDK9. However Jacoco is one of our few dependencies which also needs to work for JDK9 for us to build the test suite on JDK9. Therefore we need a version of Jacoco, as our builds currently randomly fail because snapshots are removed.

**Comment by Godin** [comment]
@TimvdLippe first of all excuse me for the delay with reply - I'm currently on vacation and traveling. And thank you for explanations. That's makes sense, so let's us sort out few questions and we'll roll out release. Hopefully by the end of this week.

**Comment by TimvdLippe** [comment]
Thanks a lot for the swift responses and looking forward to the new release!

**Comment by Godin** [comment]
For the record - thread about final preparations for release: https://groups.google.com/d/msg/jacoco-dev/HNWPzop4ZI4/pvmfWsSSCAAJ

**Comment by bric3** [comment]
Cool thanks @Godin

**Comment by Godin** [comment]
Please excuse us that it took longer than expected.
0.7.8 was finally released and available in Maven Central. Be aware that with this release we simplified numbering of versions for artifacts in Maven Central repository, i.e. you should simply use "0.7.8".

**Comment by Godin** [comment]
@TimvdLippe FYI while doing latest tests, we came across some difficulties in execution of Groovy scripts with latest JDK 9 EA b148 - see https://twitter.com/CedricChampeau/status/807285853580103684 and as starting point about workarounds see `--add-opens` in https://groups.google.com/d/msg/jacoco-dev/g9P4xeXDx8A/9yClieKwCQAJ I think that this might be of interest for you, because of usage of Gradle in Mockito.

**Comment by TimvdLippe** [comment]
@Godin Thanks a lot! We will be upgrading soon and run our test suite. Will report back if we encounter issues 😄

**Comment by Godin** [comment]
@TimvdLippe more than welcome, but I expect that you'll have more difficulties on ByteBuddy side than with JaCoCo :wink:

**Comment by Godin** [comment]
@TimvdLippe I guess this is already in your plan, but one more remark: we've uncovered more surprises with JDK 9, when really started to compile into 9 bytecode, usage as runtime wasn't enought - see #434 . It is still in my todo-list to come back to OpenJDK with discussion about enabling such verification for lower bytecode versions.

**Comment by TimvdLippe** [comment]
CC @raphw for above ^^
