### ISSUE TITLE
About read jacoco source code problem

### ISSUE THREAD

**Issue by cryingDream94** [jacoco/jacoco#469]
Is there any wiki about the source code of the introduction？When looking at the source code, no way to start。
Thanks, good luckO(∩_∩)O~~

**Comment by marchof** [comment]
Documentation of the latest JaCoCo release can be found here (not in the wiki):

http://www.jacoco.org/jacoco/trunk/doc/

If you would heave read the template text when creating this issue, you would know about our mailing list for general questions: https://groups.google.com/forum/?fromgroups=#!forum/jacoco
