### ISSUE TITLE
coverage data is mistake ?

### ISSUE THREAD

**Issue by Jerry0226** [jacoco/jacoco#479]
![jacoco](https://cloud.githubusercontent.com/assets/6658130/21758961/6f05039e-d67b-11e6-91bb-cf222f881059.png)

class coverage data ， 3 methods，first：11 lines, second：13 lines , third: 5 ,  total: 27 lines why???

**Comment by Godin** [comment]
@Jerry0226 Which answer do you expect in absence of reproducer??? A good bug report requires clear reproducer, so that others can consistently reproduce it. It could be a small project which others will be able to build. Or in this particular case - at least class files of a package where you observe this discrepancy.

**Comment by marchof** [comment]
@Jerry0226 From the screenshot I can only guess that inner classes are involved here: Those come from the same source file where code of different classes can overlap. Therefore the total can be less than sum of lines of the individual classes.

**Comment by Jerry0226** [comment]
@Godin @marchof  Thanks very much，At first I thought the problem was a common phenomenon, sorry.
jacoco is forked at 2016-02-24 01:33:32, As marchof  said， class has innerclass，but different execution results are different, first 27 and next is 29, class file and source file are same. I carefully observed, the difference in the data on the internal class coverage. 
![27](https://cloud.githubusercontent.com/assets/6658130/21790350/8d1d3130-d716-11e6-89fe-f4fd12082214.png)
![27innerclass_1](https://cloud.githubusercontent.com/assets/6658130/21790351/8d5344dc-d716-11e6-8f47-9e167af4f958.png)
![27innerclass_2](https://cloud.githubusercontent.com/assets/6658130/21790353/8d8b2988-d716-11e6-9b53-ed057e67e91e.png)
![29](https://cloud.githubusercontent.com/assets/6658130/21790354/8dc2bede-d716-11e6-9c11-22f962203d07.png)
![29innerclass_1](https://cloud.githubusercontent.com/assets/6658130/21790355/8e051c70-d716-11e6-8efe-f78bf7399a0e.png)
![29innerclass_2](https://cloud.githubusercontent.com/assets/6658130/21790356/8e3c3d04-d716-11e6-9cbf-adcd7e59ab9c.png)

[111.zip](https://github.com/jacoco/jacoco/files/695064/111.zip)

**Comment by marchof** [comment]
@Jerry0226 What exactly is the difference in the in the setup of the two reports?

**Comment by Jerry0226** [comment]
@marchof Report settings are the same

**Comment by Jerry0226** [comment]
@marchof ant task ，Every time is the same

<target name="jacocoReport"> 
    <jacoco:report> 
      <executiondata> 
          
        <file file="${jacoco.dir}/jacoco.exec"/> 
      </executiondata>  
      <structure name="JaCoCo Ant"> 
        <group name="contact">
          <classfiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/contact/bin"/>
          </classfiles>
          <sourcefiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/contact/src"/>
          </sourcefiles>
        </group>
        <group name="profile">
          <classfiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/profile/bin"/>
          </classfiles>
          <sourcefiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/profile/src"/>
          </sourcefiles>
        </group>
        <group name="public">
          <classfiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/public/bin"/>
          </classfiles>
          <sourcefiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/public/src"/>
          </sourcefiles>
        </group>
        <group name="account">
          <classfiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/account/bin"/>
          </classfiles>
          <sourcefiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/account/src"/>
          </sourcefiles>
        </group>
        <group name="order">
          <classfiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/order/bin"/>
          </classfiles>
          <sourcefiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/order/src"/>
          </sourcefiles>
        </group>
      </structure>  
      <html destdir="${report.dir}/html/"/>  
      <xml destfile="${report.dir}/xml/report.xml"/> 
    </jacoco:report>

**Comment by Jerry0226** [comment]
ant task detail
`<target name="jacocoReport"> 
    <jacoco:report> 
      <executiondata> 
          
        <file file="${jacoco.dir}/jacoco.exec"/> 
      </executiondata>  
      <structure name="JaCoCo Ant"> 
        <group name="contact">
          <classfiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/contact/bin"/>
          </classfiles>
          <sourcefiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/contact/src"/>
          </sourcefiles>
        </group>
        <group name="profile">
          <classfiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/profile/bin"/>
          </classfiles>
          <sourcefiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/profile/src"/>
          </sourcefiles>
        </group>
        <group name="public">
          <classfiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/public/bin"/>
          </classfiles>
          <sourcefiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/public/src"/>
          </sourcefiles>
        </group>
        <group name="account">
          <classfiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/account/bin"/>
          </classfiles>
          <sourcefiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/account/src"/>
          </sourcefiles>
        </group>
        <group name="order">
          <classfiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/order/bin"/>
          </classfiles>
          <sourcefiles>
            <fileset dir="d:/zcip/workpath/2536/code/web/java/code/bss/order/src"/>
          </sourcefiles>
        </group>
      </structure>  
      <html destdir="${report.dir}/html/"/>  
      <xml destfile="${report.dir}/xml/report.xml"/> 
    </jacoco:report> `
