### ISSUE TITLE
app/build/reports/coverage/debug/index.xml

### ISSUE THREAD

**Issue by missmisslonely** [jacoco/jacoco#482]
Java logic unit test coverage is always 0.
About android studio ide.

**Comment by missmisslonely** [comment]
Java logic unit test coverage is always 0

**Comment by marchof** [comment]
@missmisslonely Please use aour mailing list for questions:

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Try to provide some useful context information if you expect answers. We tried to help you and provided an issue template -- which you obviously just deleted :-(
