### ISSUE TITLE
jacoco lost some coverage

### ISSUE THREAD

**Issue by felix1982** [jacoco/jacoco#483]
### Steps to reproduce

JaCoCo version:0.7.8
Operating system:linux
Tool integration: Maven+jacoco agent

I use jacoco agent to dump exec file,then use maven-plugin generate report

![image](https://cloud.githubusercontent.com/assets/17865984/22232068/1bde5ad2-e222-11e6-91d5-771cbed73de0.png)

In this class,   TaskBusiness.getCTaskTreeType(request) is covered ,but TaskBusiness's coverage is 0%.

![image](https://cloud.githubusercontent.com/assets/17865984/22232099/4aeed0ae-e222-11e6-9df1-8f74a6f2b614.png)

**Comment by marchof** [comment]
Cross-post from mailing list: 
 
https://groups.google.com/d/msgid/jacoco/7df5cd4b-14a1-4b55-a3cb-0c08812a3684%40googlegroups.com
