### ISSUE TITLE
JavaNCSS got an error while parsing the java file

### ISSUE THREAD

**Issue by wu-sheng** [jacoco/jacoco#484]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce
Tool integration: Maven

### Actual behaviour
I got several warnings, when I run coverage in travis-ci.

```
[WARN] JavaNCSS got an error while parsing the java file /home/travis/build/wu-sheng/sky-walking/skywalking-webui/src/main/java/com/a/eye/skywalking/web/client/routing/RoutingServerWatcher.java
ParseException in STDIN
Last useful checkpoint: "com.a.eye.skywalking.web.client.routing.RoutingServerWatcher.notify(List<RegistryNode>)"
Encountered " ">" "> "" at line 29, column 43.
Was expecting one of:
    "assert" ...
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "enum" ...
    "false" ...
    "float" ...
    "int" ...
    "long" ...
    "new" ...
    "null" ...
    "short" ...
    "super" ...
    "this" ...
    "true" ...
    "void" ...
    <INTEGER_LITERAL> ...
    <FLOATING_POINT_LITERAL> ...
    <CHARACTER_LITERAL> ...
    <STRING_LITERAL> ...
    <IDENTIFIER> ...
    "(" ...
    "!" ...
    "~" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
```

pom.xml
```xml
             <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>cobertura-maven-plugin</artifactId>
                <version>2.7</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <aggregate>true</aggregate>
                    <formats>
                        <format>xml</format>
                        <format>html</format>
                    </formats>
                    <instrumentation>
                    </instrumentation>
                </configuration>
            </plugin>
```

Why have this warning? Does it affect the coverage report?

You can find my log in here:
https://api.travis-ci.org/jobs/194402786/log.txt?deansi=true
Or
https://travis-ci.org/wu-sheng/sky-walking/builds/194402785

I was recommended by @andrioli from `coveralls-maven-plugin`, to submit this issue here. Ref https://github.com/trautonen/coveralls-maven-plugin/issues/105

**Comment by marchof** [comment]
@wu-sheng You're using Cobertura. Please report the issue to the Cobertura project: https://github.com/cobertura/cobertura/

**Comment by Godin** [comment]
@wu-sheng Cobertura and JaCoCo are two different tools. As far as I can see - @andriolli has recommended you to migrate on JaCoCo, but not to report Cobertura problem here :wink:
