### ISSUE TITLE
jacoco html coverage report seems uncorrect

### ISSUE THREAD

**Issue by liangbindai** [jacoco/jacoco#489]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### background
1.My application is java web application ，and it based on spring boot，and the application is jar file.
the config for applicaion  is 
![image](https://cloud.githubusercontent.com/assets/25740542/23149992/d19b0b18-f82a-11e6-8647-cfbe32b0e81f.png)
2. used jacoco with ant ,and the build.xml is as flow
`<project xmlns:ns0="antlib:org.jacoco.ant" default="rebuild" name="hslist">

	<description>
	  Example Ant build file that demonstrates how a JaCoCo coverage report
	  can be itegrated into an existing build in three simple steps.
	</description>

	<property location="/jacoco" name="result.dir" />
	<property location="${result.dir}/target" name="result.report.dir" />
	<property location="/jacoco/server.exec" name="result.exec.file" />
        <property location="/jacoco/source/credit-card-account/api/src/main/java" name="src.dir" />
	<property location="/jacoco/classes" name="result.classes.dir" />

	<taskdef resource="org/jacoco/ant/antlib.xml" uri="antlib:org.jacoco.ant">
		<classpath path="/jacoco/jacocoant.jar" />
	</taskdef>

	<target name="clean">
		<delete dir="${result.dir}" />
	</target>

	<target name="dump">
	        <ns0:dump address="127.0.0.1" append="true" destfile="${result.exec.file}" port="10002" reset="false" />
	</target>

	<target name="report">

		<ns0:report>

			<executiondata>
				<file file="${result.exec.file}" />
			</executiondata>

			<structure name="server">
				<classfiles>
					 <zipfileset src="${result.classes.dir}/server-3.1.6-SNAPSHOT.jar">
						<exclude name="**/JsonAutoDetect*.*" />
						<exclude name="**/lib/bcprov-jdk16-1.46.jar" />
						<exclude name="**/lib/ehcache-2.10.0.jar" />
						<exclude name="**/lib/jcl-over-slf4j-1.7.13.jar"/>
						<exclude name="**/lib/joda-time-2.8.2.jar"/>
						<exclude name="**/lib/junit-4.12.jar"/>
						<exclude name="**/lib/lombok-1.16.4.jar"/>
						<exclude name="**/lib/tomcat-embed-core-8.0.28.jar"/>
						<exclude name="**/lib/**"/>
					</zipfileset>
					
                                </classfiles>
				<sourcefiles  encoding="UTF-8">
                                        <fileset dir="${src.dir}" />
                                </sourcefiles>
			</structure>

			<html destdir="${result.report.dir}" />
			<csv destfile="${result.report.dir}/report.csv" />
			<xml destfile="${result.report.dir}/report.xml" />
		</ns0:report>
	</target>

	<target depends="clean,report" name="rebuild" />

</project>
`
3.I hava confirmed the jar file is same with source code

### Steps to reproduce
1.use command ：ant dump，get the .exec file
2.user command:ant report,get the html report

JaCoCo version:0.7.8.201606240924
Operating system:Red Hat 4.4.7-16（Linux version 2.6.32-573.12.1.el6.x86_64 ）
Tool integration: Ant ant version 1.9.7

### Expected behaviour
the html report should like this:continues red or  continues green or yellow

### Actual behaviour
the html report seems uncorect,I cannot unserstand why the 85th line code uncovered,and the 86th has no coverage(no covered ,no uncovered ,no half covered),and the getBanks() method has no exception, from the html report  ,the 85th line code executed but the 86th line code unexecuted，I debug the applicaion found the 85th line code and 86th line code executed as well. why the report is like this???
![image](https://cloud.githubusercontent.com/assets/25740542/23150130/1af958d6-f82c-11e6-8b54-fa1f118ab564.png)

**Comment by Godin** [comment]
@liangbindai could you please provide complete example of project that reproduces this issue, so to allow us to reproduce it and investigate?

**Comment by liangbindai** [comment]
I am sorry,I cannot git you the source code of the project ,bacause of company policy。but I can give you .exec file. or else is there another way to solve the problem?

**Comment by Godin** [comment]
@liangbindai then please at least provide exec file and class file corresponding to the source file where you observe problem.

**Comment by liangbindai** [comment]
I am sorry for so long time ,recently I thin maybe I have get the reason:
I found the code with without the @Loggable annotation the report will be correct ,and the annotation is from 
<dependencies>
  <dependency>
    <groupId>com.jcabi</groupId>
    <artifactId>jcabi-aspects</artifactId>
    <version>0.22.6</version>
  </dependency>
</dependencies>
I search the jcabi ,and found the homepage:http://aspects.jcabi.com/
and I found (from http://aspects.jcabi.com/example-weaving.html)
![image](https://cloud.githubusercontent.com/assets/25740542/23348443/1f81b17e-fce5-11e6-9998-0655e090ff16.png) I guess it is the reason why the report is not correct.
is it meas that I cannot use jacoco and the jacbi at the same time ,or I can use them at the same time by channging some settings.

**Comment by marchof** [comment]
@liangbindai Looks like jcabi and/or AspectJ messes up source line numbers in class files, which are essential for JaCoCo to work. You might report a bug to them.

**Comment by liangbindai** [comment]
whose bug？ jcabi ？

**Comment by marchof** [comment]
@liangbindai Not sure. But looks like there are some known issues with AspectJ, see e.g. https://bugs.eclipse.org/449797

**Comment by liangbindai** [comment]
ok Thank you
