### ISSUE TITLE
Jacoco should not generate an aggregate report if there are no tests.

### ISSUE THREAD

**Issue by trajano** [jacoco/jacoco#499]
### Steps to reproduce

JaCoCo-maven-plugin version: 0.7.9
Operating system: Unix, Windows
Tool integration: Maven

When generating a Maven site that is POM only, but still include `jacoco-maven-plugin` in the `reporting`/`plugins` section as this is an organizational POM which will be used by others to set up common reports but have no modules themselves.  see https://github.com/trajano/trajano/blob/master/pom.xml#L489 for an example

The logic should be as follows:

If the project is not a "java" project (or is just a POM project that has no non-POM modules) then the JaCoCo report should not be attempted.

### Expected behaviour

The generated site https://site.trajano.net/trajano/project-reports.html should not have a JaCoCo report link.

### Actual behaviour

https://site.trajano.net/trajano/project-reports.html has a JaCoCo aggregate report with no data.

**Comment by Godin** [comment]
Please read http://www.jacoco.org/jacoco/trunk/doc/maven.html and related documentation about Maven : 

> Usage of plugin together with maven-site-plugin without [explicit selection of reports](https://maven.apache.org/plugins/maven-site-plugin/examples/configuring-reports.html#Selecting_Reports_from_a_Plugin:_Configuring_Report_Sets) might lead to generation of redundant aggregate reports. Specify reportSets explicitly to avoid this

**Comment by trajano** [comment]
I think the logic should also be in the plugin as well, because maven-Javadoc-plugin does not require any extra configuration from what i can surmize

**Comment by Godin** [comment]
Currently possible to execute `report-aggregate` for a leaf `pom` module (that is not parent and not an aggregator) to generate coverage report for modules within reactor (example - https://github.com/jacoco/jacoco/blob/v0.7.9/jacoco-maven-plugin.test/it/it-report-aggregate/report/pom.xml). Your proposal as it is will unfortunately destroy this possibility. And given that explicit selection of reports is recommended by Maven for some plugins and documented in our documentation, we see low value in working on this compared to other open subjects. But feel free to experiment and provide patch. Thank you for your understanding.
