### ISSUE TITLE
include commandline tool for merge/reporting of jacoco results in main source tree/final jars

### ISSUE THREAD

**Issue by judovana** [jacoco/jacoco#50]
Many projects are using eg Make or another commandline based toll as build framework and for launching of different testsuites.

It would be nice to have (except excellent API you have already now) direct commandline tool for merging of exec files and for report generating. I have write one by myself for this task - http://mail.openjdk.java.net/pipermail/distro-pkg-dev/attachments/20121127/ba8f6a1e/jacoco-tool-0001.diff - ( from http://mail.openjdk.java.net/pipermail/distro-pkg-dev/2012-November/020984.html) and I will be happy to help with inclusion of such a tool into your repository.

Thanx for this amazing tool,
J.

**Comment by marchof** [comment]
Will be available with PR #525.
