### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by xinye666** [jacoco/jacoco#507]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version:0.7.9
Operating system:linux
Tool integration: Maven

### Expected behaviour
fine
### Actual behaviour
17:16:47 Exception in thread "main" java.lang.reflect.InvocationTargetException
17:16:47 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:16:47 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:16:47 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:16:47 	at java.lang.reflect.Method.invoke(Method.java:498)
17:16:47 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
17:16:47 	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
17:16:47 Caused by: java.lang.StackOverflowError
17:16:47 	at java.lang.Long.hashCode(Long.java:1061)
17:16:47 	at java.lang.Long.hashCode(Long.java:1049)
17:16:47 	at java.util.HashMap.hash(HashMap.java:338)
17:16:47 	at java.util.HashMap.get(HashMap.java:556)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.data.ExecutionDataStore.get(ExecutionDataStore.java:131)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.RuntimeData.getExecutionData(RuntimeData.java:120)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.RuntimeData.getProbes(RuntimeData.java:148)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.RuntimeData.equals(RuntimeData.java:162)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.data.ExecutionData.$jacocoInit(ExecutionData.java)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.data.ExecutionData.<init>(ExecutionData.java)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.data.ExecutionDataStore.get(ExecutionDataStore.java:133)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.RuntimeData.getExecutionData(RuntimeData.java:120)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.RuntimeData.getProbes(RuntimeData.java:148)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.RuntimeData.equals(RuntimeData.java:162)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.data.ExecutionData.$jacocoInit(ExecutionData.java)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.data.ExecutionData.<init>(ExecutionData.java)
17:16:47 	at org.jacoco.agent.rt.internal_8ff85ea.core.data.ExecutionDataStore.get(ExecutionDataStore.java:133)

**Comment by marchof** [comment]
This happens if you configure multiple JaCoCo agents in different versions. Please use our forum if you need help using JaCoCo.
