### ISSUE TITLE
Some class count 0, but other class normal

### ISSUE THREAD

**Issue by ljgit** [jacoco/jacoco#515]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version: 0.7.9.201702052155
Operating system: Linux
Tool integration: Maven/Ant/API/Other: Ant

### Expected behaviour
My app is running with: -javaagent:/home/appweb/jacoco/lib/jacocoagent.jar=includes=com.x.x,output=tcpserver,address=*,port=6001. 
After some test cases, I dump the exec, and report (with ant).
Some class's coverage count was 0, but other class war normal.
They are all under the same super packages: com.x.x.
And the class was really run (there was logs).

**Comment by marchof** [comment]
Please see [FAQ](http://www.jacoco.org/jacoco/trunk/doc/faq.html):

# Why does a class show as not covered although it has been executed?

First make sure execution data has been collected. For this select the Sessions link on the top right corner of the HTML report and check whether the class in question is listed. If it is listed but not linked the class at execution time is a different class file. Make sure you're using the exact same class file at runtime as for report generation. Note that some tools (e.g. EJB containers, mocking frameworks) might modify your class files at runtime. Please see the chapter about class ids for a detailed discussion.

If you have further questions please use our [mailing list](https://groups.google.com/forum/?fromgroups=#!forum/jacoco).
