### ISSUE TITLE
Different coverage statistics for Set and Map for similar utility methods

### ISSUE THREAD

**Issue by namannigam** [jacoco/jacoco#516]
### Steps to reproduce

```
public class Utils {
    
        public static boolean isNotNullOrEmpty(Map map) {
            return map != null && !map.isEmpty();
        }
    
        public static boolean isNotNullOrEmpty(Set set) {
            return set != null && !set.isEmpty();
        }
    }
```

For which I wrote a unit tests as follows - 

 ```
   import org.junit.jupiter.api.Test;
    
    import static org.junit.jupiter.api.Assertions.*;
    
    class UtilsTest {
    
        @Test
        void testUtils() {
            assertNotNull(new Utils());
            assertFalse(Utils.isNotNullOrEmpty(new HashMap()), "Map utils failure.");
            assertFalse(Utils.isNotNullOrEmpty(new HashSet()), "Set utils failure.");
        }
    }
```

JaCoCo version:0.7.9
Operating system:MacOSX
Tool integration: Maven

### Expected behaviour

The coverage for the `isNotNullOrEmpty(Set set)` should also be 100%.

### Actual behaviour

The branch coverage is 50%. 

External Link - http://stackoverflow.com/questions/43264560/jacoco-code-coverage-difference-for-set-and-map

**Comment by marchof** [comment]
@namannigam Your method has two branching points with two branches each:

1. `map != null` and
2. `!map.isEmpty()`

Obviously your test misses two cases:

1. where `map` is `null` and
2. where `map`is not empty

This is bug tracker! Please consider using our [mailing list](https://groups.google.com/forum/?fromgroups=#!forum/jacoco) if you have general questions how to code coverage works.

**Comment by namannigam** [comment]
@marchof The reason I raised it as a bug is that the resulting coverage for the above code reads 
100% for the `Map` util while 50% for the `Set` util. The screenshot on SO link reflects that.

**Comment by marchof** [comment]
@namannigam The test you're showing will definitely not cover the method with 100% branch coverage. Are you sure this is the only execution if the method? Any other indirect invocations in your test suite?

**Comment by Godin** [comment]
@namannigam in [example.zip](https://github.com/jacoco/jacoco/files/906897/example.zip) you'll find an example that demonstrates point of @marchof - execution of `mvn clean verify` produces following report as expected:

![report](https://cloud.githubusercontent.com/assets/138671/24820457/64432784-1be9-11e7-8aa5-7dfd4f4486e3.png)

**Comment by namannigam** [comment]
@Godin @marchof Thanks for reverting. 
> Any other indirect invocations in your test suite?
My bad, one of the method was being called from another class and hence 100% covered.
