### ISSUE TITLE
Consolidating .gitignore files creates issues with git subtrees

### ISSUE THREAD

**Issue by hoyt85** [jacoco/jacoco#518]
Hey guys,

I've been using jacoco for code coverage reporting in one of my projects for some time. Typically I like to build all third party projects from source, so I'll usually include the project as a subtree (it allows for easy updates/modifications/bug fixes). I went to update my jacoco subtree today from the repo and the typical "git subtree pull" command I use deleted everything in my working directory. I'd never seen that before, so I went to investigate to see if I could track down the specific commit that caused the issue. I've identified it as [this one](https://github.com/jacoco/jacoco/commit/4585416d2d60cfcb83611e20f74794da1947b3fd). It seems consolidating the .gitignore files somehow messes with how git subtrees work. I've been using this method for some time to keep up to date with the latest jacoco changes (as well as the latest version of other third party tools), and this is the first time I've seen this happen.

Not sure if any of you guys have seen anything like this before, or whether it's even possible to fix/workaround, but I figured I should mention it to you guys just in case there are others out there with a jacoco subtree.

Thanks!
Andrew

### Steps to reproduce
set up jacoco as a git subtree in another project (from a reference prior to 4585416d2d60cfcb83611e20f74794da1947b3fd):
```
git subtree add --prefix=jacoco https://github.com/jacoco/jacoco.git d1a0f198cfc5e6397d7d6f9b912b85a0211201c7
```

attempt to pull the offending commit (or any commit after it):
```
git subtree pull --prefix=jacoco https://github.com/jacoco/jacoco.git 4585416d2d60cfcb83611e20f74794da1947b3fd
```

JaCoCo version: latest
Operating system: Ubuntu 14.04
Tool integration: Maven/Ant

### Expected behaviour
Expected to merge the changes from the commit to the jacoco subtree. You can see the expected result by doing a git subtree pull on any prior commit.

### Actual behaviour
Deletes everything in jacoco subtree as well as enclosing project.

**Comment by Godin** [comment]
Hi,

First of all - thank you for a such detailed report :thumbsup:

Must admit that I'm not a `git subtree` user/expert, however:

after initialization of a test repository as
```
cd /tmp
mkdir test
cd test
git init
git commit --allow-empty -m "Init"
```

execution of
```
git subtree add --prefix=jacoco https://github.com/jacoco/jacoco.git d1a0f198cfc5e6397d7d6f9b912b85a0211201c7
```

fails with message
```
error: no such remote ref d1a0f198cfc5e6397d7d6f9b912b85a0211201c7
```

so instead I did
```
git subtree add --prefix=jacoco https://github.com/jacoco/jacoco.git master
git reset --hard HEAD~1
git subtree add --prefix=jacoco https://github.com/jacoco/jacoco.git d1a0f198cfc5e6397d7d6f9b912b85a0211201c7
```

after that
```
git subtree pull --prefix=jacoco https://github.com/jacoco/jacoco.git 4585416d2d60cfcb83611e20f74794da1947b3fd
```

indeed puts test repository into some strange state.

But this doesn't happen if `--prefix=jacoco-prj` is used instead of `--prefix=jacoco`. Given this fact and that there is nothing special in consolidated `.gitignore`, I tend to think that this is a bug in `git subtree` that might be related to the fact that we have directory `jacoco` in our repository. As an attempt to prove such theory:
```
mkdir --parents /tmp/prj/prj
cd /tmp/prj
echo "file in subdirectory" > prj/file_in_subdirectory
echo "file in root" > file_in_root
git init
git add .
git commit -m "Init subproject repository"

mkdir /tmp/test
cd /tmp/test
git init
git commit --allow-empty -m "Init test repository"
git subtree add --prefix prj /tmp/prj master

cd /tmp/prj
touch .gitignore
git add -f .gitignore
git commit -m "add empty .gitignore"

cd /tmp/test
git subtree pull --prefix=prj /tmp/prj master
```
also puts test repository in some strange state.

**Comment by hoyt85** [comment]
Hey Godin,

Thanks so much for the prompt investigation (sorry about incomplete steps to reproduce, I just assumed subtree let you add from a specific commit). I'll be sure to re-add the subtree with a different prefix. Definitely good to know for future subtrees...

Thanks again!
Andrew

**Comment by Godin** [comment]
@hoyt85 as a user of `git subtree` you might be interesting to report this finding in correct project 😉

**Comment by hoyt85** [comment]
@Godin Will do. Just for completeness sake (for anyone who stumbles on this thread), after further testing the bug is indeed with git-subtree. If you create a subtree with a prefix that's the same as any top level directory in that project, any changes made to that project's root folder (in this case, they've added a .gitignore to the root folder), will mess up your repo when you do a git subtree pull. Changes made to the sub-project not in the root folder will not cause issues on a git subtree pull.
