### ISSUE TITLE
<skip>true</skip> cannot be overridden using -Djacoco.skip=false

### ISSUE THREAD

**Issue by rtack** [jacoco/jacoco#519]
If skip true is set in the pom.xml, like below
```
<configuration>
      <skip>true</skip>
</configuration>
```
starting the build with `-Djacoco.skip=false` the jacoco.skip property is ignored and the output is still

--- jacoco-maven-plugin:0.7.9:prepare-agent (pre-unit-test) @ commons ---
[INFO] Skipping JaCoCo execution because property jacoco.skip is set.
[INFO] surefireArgLine set to empty

I would expect that setting the property on the command line will override the value from the pom.xml

**Comment by Godin** [comment]
IMO this is how Maven works. For example given
```
<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>example</artifactId>
  <version>0.1-SNAPSHOT</version>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.20</version>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

execution of Maven 3.5.0 as `mvn test -Dmaven.test.skip=false -DskipTests=false` will anyway lead to
```
Tests are skipped.
```

To achieve what I believe you want to achieve - define property `jacoco.skip` as `true`.

**Comment by rtack** [comment]
By default I wanted it to be skipped and then only enable it in certain modules. Maybe that's the wrong way to go about it though.

**Comment by Godin** [comment]
@rtack in `pom.xml`

> define property `jacoco.skip` as `true`

```
<project>
  <properties>
    <jacoco.skip>true</jacoco.skip>
  </properties>
</project>
```

so it will be skipped by default and might be enabled via `mvn ... -Djacoco.skip=false`.

**Comment by rtack** [comment]
Ok I get it. I cannot override the skip configuration but I can override the skip property on the cli. Will try it out thanks.
