### ISSUE TITLE
Command-line offline instrumenter interface

### ISSUE THREAD

**Issue by mathjeff** [jacoco/jacoco#520]
I'd like to have a command-line interface (implemented as a .jar, runnable as `java -jar $args` rather than inside of, for example, Maven or Ant) that runs offline instrumentation on a certain set of input files, and which supports filtering based on fully-qualified classpath similar to InstrumentMojo.java

I'm planning on adding this functionality myself; I'm just opening this issue in case anyone can offer me some opinions about whether this sounds like a reasonable idea (probably the implementation is going to involve a new pom to build the cli jar and also adding some sort of filter into Instrumenter.java for distinguishing which files to instrument).

**Comment by marchof** [comment]
@mathjeff There is already a pending pull request #86 for exactly this. We didn't invest any time yet on this mostly due to the lack of any tests and documentation. Also we're unsure about the use cases. Maybe you can help us to get a better understanding by describing your scenario a bit?

Also I would prefer a CLI for more common operations (dump, report, exec file inspection) not just offline instrumentation.

**Comment by mathjeff** [comment]
Hey thanks

I'll move my discussion over to https://github.com/jacoco/jacoco/issues/50 and/or https://github.com/jacoco/jacoco/pull/86.

(My use case is that Android would like to be able to have code coverage metrics via jacoco, but the vm the tests run in isn't a jvm (hence wanting the offline instrumentation) and the build system is a custom build system (hence wanting a command-line tool))

Thanks

**Comment by marchof** [comment]
@mathjeff Then how do you create the coverage report afterwards?

**Comment by mathjeff** [comment]
@marchof You're absolutely right - although I was just tackling one at a time, I am going to be interested in a command-line report generator too.

In any case, the pull request https://github.com/jacoco/jacoco/pull/86 that you linked me to implements nearly all of what I'm looking for, leaving me mostly to do the fixups you mentioned so it can be merged.

Thanks :)
