### ISSUE TITLE
Feature Request -> Agent (TCP-Client) retry to connect to TCP Server automatically

### ISSUE THREAD

**Issue by gauravsharma071982** [jacoco/jacoco#523]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version: NA
Operating system: NA
Tool integration: NA

### Expected behaviour

Agent (TCP-Client) retry to connect to TCP Server automatically after specified time interval

### Actual behaviour
Not available

**Comment by gauravsharma071982** [comment]
adding more -> The issue i have faced is that if TCPServer is down, agent JVM needs to be bounced back to reconnect agent to tcpserver.

**Comment by marchof** [comment]
@gauravsharma071982 At what point in time do you actually use the connection? At application shutdown oder continuously (by sending dumps commands from the server)?

**Comment by marchof** [comment]
@gauravsharma071982 Any updates on this?
