### ISSUE TITLE
Feature Request -> Automatically synchronize loaded classses to TCPServer along with exec file

### ISSUE THREAD

**Issue by gauravsharma071982** [jacoco/jacoco#524]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version: NA
Operating system: NA
Tool integration: Maven/Ant/API/Other

### Expected behaviour

In my case, our TCPServer is connected to 10+ different application's running on different JVM with different classes. its it really hard to keep all applications synchronized with latest classes version. it will be really great if jacoco automatically synchronize the loaded classes to TCPServer. that will help to generate html report.

### Actual behaviour
Not available

**Comment by marchof** [comment]
@gauravsharma071982 Can you please elaborate what reports do you want to create then? Seperate ones for for each application and version?

Also: How do you deploy your applications? At some point you need to distribute releases of your applications. Why can't these release be used as a base for report generation?

**Comment by marchof** [comment]
@gauravsharma071982 Any updates on this? Will close othewise.
