### ISSUE TITLE
java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)

### ISSUE THREAD

**Issue by jinghongjun** [jacoco/jacoco#526]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version:
Operating system:
Tool integration: Maven/Ant/API/Other

**Comment by jinghongjun** [comment]
apply plugin: 'jacoco'

jacoco {
    toolVersion = "0.7.1.201405082137"
}
05-01 21:52:11.083   492   492 W System.err: java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
05-01 21:52:11.083   492   492 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:452)
05-01 21:52:11.083   492   492 W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
05-01 21:52:11.083   492   492 W System.err: 	at org.jacoco.agent.rt.internal_b0d6a23.output.FileOutput.openFile(FileOutput.java:67)
05-01 21:52:11.083   492   492 W System.err: 	at org.jacoco.agent.rt.internal_b0d6a23.output.FileOutput.startup(FileOutput.java:49)
05-01 21:52:11.083   492   492 W System.err: 	at org.jacoco.agent.rt.internal_b0d6a23.Agent.startup(Agent.java:122)
05-01 21:52:11.083   492   492 W System.err: 	at org.jacoco.agent.rt.internal_b0d6a23.Agent.getInstance(Agent.java:50)
05-01 21:52:11.083   492   492 W System.err: 	at org.jacoco.agent.rt.internal_b0d6a23.Offline.<clinit>(Offline.java:31)
05-01 21:52:11.083   492   492 W System.err: 	at com.domain.android.base.AndroidApplication.$jacocoInit(AndroidApplication.java)
05-01 21:52:11.083   492   492 W System.err: 	at com.domain.android.base.AndroidApplication.<init>(AndroidApplication.java)
05-01 21:52:11.083   492   492 W System.err: 	at java.lang.Class.newInstance(Native Method)
05-01 21:52:11.083   492   492 W System.err: 	at android.app.Instrumentation.newApplication(Instrumentation.java:996)
05-01 21:52:11.083   492   492 W System.err: 	at android.app.Instrumentation.newApplication(Instrumentation.java:981)
05-01 21:52:11.083   492   492 W System.err: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
05-01 21:52:11.083   492   492 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
05-01 21:52:11.083   492   492 W System.err: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
05-01 21:52:11.083   492   492 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
05-01 21:52:11.083   492   492 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-01 21:52:11.083   492   492 W System.err: 	at android.os.Looper.loop(Looper.java:148)
05-01 21:52:11.083   492   492 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
05-01 21:52:11.083   492   492 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
05-01 21:52:11.083   492   492 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-01 21:52:11.083   492   492 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-01 21:52:11.083   492   492 W System.err: Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
05-01 21:52:11.083   492   492 W System.err: 	at libcore.io.Posix.open(Native Method)
05-01 21:52:11.083   492   492 W System.err: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
05-01 21:52:11.083   492   492 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:438)
05-01 21:52:11.083   492   492 W System.err: 	... 21 more

Thanks!

**Comment by marchof** [comment]
@jinghongjun Please use our mailing list for usage questions. Your problem has probably been asked before, see for example #202 (google is your friend).

**Comment by dbarwacz** [comment]
It's an irony now that google places this thread as first promoted answer when googling for issue.
