### ISSUE TITLE
Icon method.gif should be different for not public method

### ISSUE THREAD

**Issue by bartsimp** [jacoco/jacoco#535]
in the html reports, every method use the the icon method.gif (a green little ball) and it's not clear the method visibility.
Will be great use a different icons for not public methods (similar to eclipse outline view). 
Red for private methods, Yellow for protected, etc..

thanks

**Comment by abalanonline** [comment]
Hello @bartsimp @marchof @Godin 

There is a "help wanted" label on this issue. Can I help jacoco project with that?

Thank you

**Comment by Godin** [comment]
As an example of costs: case of non-Java languages is unclear - e.g. Kotlin has notion of `internal` (module) visibility.

**Comment by bartsimp** [comment]
I remember slightly what was the need that made me open the issue because too much time has passed. However I think it was linked to the need to understand which strategy to apply for the tests. For example, do not test private methods, so looking at the report the icon suggest me which not-private methods were still to be tested
