### ISSUE TITLE
Jacoco 0.7.9 ArrayIndexOutOfBounds thrown for some of the source classes

### ISSUE THREAD

**Issue by erajeshgit** [jacoco/jacoco#542]
Hi Team,
I have used Jacoco 0.7.9 plugin with Maven surefire plugin to produce the code coverage report for one of my applications. I have used Offline instrumentation for this with Powermock Java Agent 1.7.
During the test case execution with PowerMock java agent, I'm getting "ArrayIndexOutOfBounds" for some of my source classes. But these classes are working fine without Jacoco. I'm facing this only after Jacoco instrumentation and during test case execution.

Can you please help me to resolve this issue.

### Steps to reproduce
JaCoCo version: 0.7.9
PowerMock Java Agent: 1.7.0Rc2
Java version: 1.6.0_3.1
Server: Weblogic 10.3.6
Operating system: Windows 7
Tool integration: Maven with Surefire plugin

### Expected behaviour
Coverage report should be generated for all source classes

### Actual behaviour
"ArrayIndexOutOfBounds" exception is thrown only for some of the source classes

**Comment by namannigam** [comment]
@erajeshgit This would have been more helpful with the exception stacktrace or minimal reproducible project link.

**Comment by Godin** [comment]
@erajeshgit as was correctly requested by @namannigam : just specification of versions is not a "steps to reproduce", so please provide reproducer or at least  some details such as stack trace that would help us to understand the issue.

**Comment by erajeshgit** [comment]
Hi,
I cannot copy the details here as its confidential.. But I'm getting "Java.Lang.ArrayIndexOutOfboundsException:1131"

Please let me know what could cause this error.. Because its working for all other classes except few and I could generate the code Coverage report also.

**Comment by Godin** [comment]
@erajeshgit can you provide details in a private email? Otherwise there is not enough details for investigations and hence nothing that we can do to help you, except of recommendation to exclude affected classes from instrumentation.

**Comment by erajeshgit** [comment]
Hi Godin,
There is no much information in the stack trace. There are only class names from where this error is thrown. PFB trace.

Java.Lang.ArrayIndexOutOfboundsException:1131
at XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
at XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
at XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by Godin** [comment]
@erajeshgit sorry, but don't know how you determined whether or not stack trace contains any hints as for me impossible to judge since stack trace was not provided. But fine, if there is no hints in stack trace, then as was said earlier - reproducer. For example you can try to create a small one separated from your initial codebase and so that it won't be confidential. Otherwise again as was said earlier
> there is not enough details for investigations and hence nothing that we can do to help you, except of recommendation to exclude affected classes from instrumentation

Thank you for your understanding.
