### ISSUE TITLE
jacoco-maven-plugin:report reports 0 classes

### ISSUE THREAD

**Issue by ctron** [jacoco/jacoco#548]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

### Steps to reproduce

JaCoCo version: 0.7.9
Operating system: Any
Tool integration: Maven

Run `mvn clean install` on https://github.com/eclipse/kapua.
Check the XML report in `kapua-qa/target/site/jacoco`.

### Expected behaviour

The XML report shows the same information as the `jacoco.exec` file.

### Actual behaviour

The `jacoco.exec` file contains the correct code coverage data. However the XML report gets created empty:

```
[INFO] --- jacoco-maven-plugin:0.7.9:report (default-report) @ kapua-qa ---
[INFO] Loading execution data file /home/centos/jenkins/workspace/kapua-eclipse-develop-ci/qa/target/jacoco.exec
[INFO] Analyzed bundle 'kapua-qa' with 0 classes
```

**Comment by Godin** [comment]
As far as I can see module `kapua-qa` has no main source files, only tests, while jacoco-maven-plugin `report` goal generates reports for main source files of module. For the reports that contain sources of other modules within Maven reactor please use `report-aggregate` - see http://www.jacoco.org/jacoco/trunk/doc/report-aggregate-mojo.html

**Comment by ctron** [comment]
So is there a way to simply convert the jacoco.exec file into the corresponding XML file using the maven plugin. https://codecov.io requires the use of XML files.

**Comment by Godin** [comment]
To find the ways to convert `exec` file into report please refer to [documentation](http://www.jacoco.org/jacoco/trunk/doc/):
As was said before - you can use `report-aggregate` -
 http://www.jacoco.org/jacoco/trunk/doc/report-aggregate-mojo.html
There is also Ant Task `report` - http://www.jacoco.org/jacoco/trunk/doc/ant.html
Not yet released Command Line Interface - http://www.jacoco.org/jacoco/trunk/doc/cli.html
