### ISSUE TITLE
Support option to audit coverage goals

### ISSUE THREAD

**Issue by mattnelson** [jacoco/jacoco#549]
When configuring a rule limit value, it would be beneficial to be able to audit that configuration value and log an informational message to highlight that the target could be modified. For example. I have a module where the instruction minimum is configured at 30%. If I add tests that bring the coverage up to 45%, I would like to be able to audit that fact and update my configuration to the new minimum. This would prevent me from refactoring tests in the future that lower the coverage target and do not fail the build.

**Comment by Godin** [comment]
@mattnelson You already can specify maximum to track improvements.

**Comment by Godin** [comment]
@mattnelson could you please respond/react on https://github.com/jacoco/jacoco/issues/549#issuecomment-308681525 ? Otherwise I'm going to close this in absence of feedback. Thank you for your understanding.

**Comment by mattnelson** [comment]
> @mattnelson You already can specify maximum to track improvements.

My primary problem with this approach would be failing the build when coverage increased. What if soft limits were introduced that alerted the user to an issue but didn't have the ability to fail the build? Think of them as warn/error level limits.

**Comment by Godin** [comment]
@mattnelson there is already property `haltOnFailure` that is `true` by default (http://www.jacoco.org/jacoco/trunk/doc/check-mojo.html), but you can change it to `false` in a separate configuration that specifies maximum.

**Comment by mattnelson** [comment]
Tried the dual execution proposal and it is close to what am expecting, but there appears to be a rounding issue that causes the other to always be off by 1%.

When target is set to 78 maximum check fails.
When target is set to 79 minimum check fails.
> [WARNING] Rule violated for bundle x: instructions covered ratio is 0.78, but expected **minimum** is 0.79
[WARNING] Rule violated for bundle x: instructions covered ratio is 0.79, but expected **maximum** is 0.78

```xml
<properties>
   <coverage.target>78</coverage.target>
</properties>
...snip...
<execution>
    <id>default-check</id>
    <goals>
        <goal>check</goal>
    </goals>
    <configuration>
        <rules><rule><limits><limit>
            <counter>INSTRUCTION</counter>
            <minimum>${coverage.target}%</minimum>
        </limit></limits></rule></rules>
    </configuration>
</execution>
<execution>
    <id>default-audit-check</id>
    <goals>
        <goal>check</goal>
    </goals>
    <configuration>
        <haltOnFailure>false</haltOnFailure>
        <rules><rule><limits><limit>
            <counter>INSTRUCTION</counter>
            <maximum>${coverage.target}%</maximum>
        </limit></limits></rule></rules>
    </configuration>
</execution>
```

**Comment by Godin** [comment]
@mattnelson let say you have 2 covered instructions out of total 11, so that ratio 2/11=0.18(18) Minimum should be lower than real value and maximum greater (https://github.com/jacoco/jacoco/blob/2a2f161920d7608630ba1163d45a858803cfef2e/org.jacoco.report/src/org/jacoco/report/check/Limit.java#L171-L176) 0.18 will be lower than real value, but not greater than it. From here, I believe that following tweak of configuration will work:
```
<minimum>${coverage.target}.0%</minimum>
<maximum>${coverage.target}.9%</maximum>
```

**Comment by mattnelson** [comment]
Thanks for the suggestion. Using upper/lower bounds of the target achieves what I was wanting.
