### ISSUE TITLE
Thread safety in StringPool

### ISSUE THREAD

**Issue by bennetyeesc** [jacoco/jacoco#550]
Doc string claims no synchronization is required for concurrent lookups. This is false.

https://github.com/jacoco/jacoco/blob/master/org.jacoco.core/src/org/jacoco/core/internal/analysis/StringPool.java#L39

Suppose we are on a uniprocessor with a malevolent scheduler.  Threads A and B are both executable.  Thread A invokes get() method for some |s|. After L43, pool.get(s) returns null.  Thread A is suspended and thread B gets to run.  Thread B also invoke get() on the same string.  Note that these are different String objects, but .equals compare the same since the characters of the strings are the same. Thread B gets to L43, where pool.get() also returns null.  Now it is obvious that both threads A and B will execute L45, pool.put(s, s); and the return value will be their respective arguments |s|. Suppose thread A executes L45 first, then thread B.  The returned value in thread A got overwritten in pool by thread B's value. Yet the two strings --- with identical characters --- should have been interned and normalized to be the same instance. Code that follow the call to the get() method, assuming that the post-condition that the returned value is normalized holds, will not execute correctly.

Worse, since HashMap is not synchronized, if thread switching (or actual concurrent execution) lets two (or more) threads enter pool.put(s, s), the HashMap object can be corrupted, leading to more undefined behavior.

### Steps to reproduce

JaCoCo version: all
Operating system: all
Tool integration: NA

**Comment by bjkail** [comment]
You have misunderstood: the javadoc is saying "this data structure can be faster than String.intern because it does not need to be thread-safe", not "this data structure is thread-safe".

**Comment by marchof** [comment]
@bennetyeesc As @bjkail mentioned: This class is nether thread-safe nor used in a concurrent context.
