### ISSUE TITLE
MethodAnalyzer.addProbe java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by aa3000** [jacoco/jacoco#564]
### Steps to reproduce

When generate report with an android project, it will always fail. It shows error as:

Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
18:46:05.451 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.jacoco.core.internal.analysis.MethodAnalyzer.addProbe(MethodAnalyzer.java:288)
18:46:05.452 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.jacoco.core.internal.analysis.MethodAnalyzer.visitProbe(MethodAnalyzer.java:210)
18:46:05.452 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.jacoco.core.internal.flow.MethodProbesAdapter.visitLabel(MethodProbesAdapter.java:86)
18:46:05.452 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.objectweb.asm.tree.LabelNode.accept(LabelNode.java:67)
18:46:05.452 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:162)
18:46:05.452 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:817)
18:46:05.453 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.jacoco.core.internal.flow.ClassProbesAdapter$2.visitEnd(ClassProbesAdapter.java:89)
18:46:05.453 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1036)
18:46:05.453 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:708)
18:46:05.453 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:521)
18:46:05.453 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:111)
18:46:05.454 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:127)

JaCoCo version:0.7.9
Operating system:ubuntu
Tool integration: gradle

### Expected behaviour
no error, and continue generate the report

### Actual behaviour
fail to generate the report

**Comment by marchof** [comment]
@aa3000 Thanks for reporting this!

Can you provide an executable reproducer?

Otherwise the class file causing this issue (name should be in the complete stack trace) and the exec file would also helpful to analyze this.

**Comment by marchof** [comment]
Without the requested information we cannot analyze this.
