### ISSUE TITLE
static method invocation sites are not covered

### ISSUE THREAD

**Issue by vladimirdolzhenko** [jacoco/jacoco#568]
### Steps to reproduce

* JaCoCo version: 0.7.8, 0.7.9
* Operating system: Windows, Linux
* Tool integration: Gradle

let's say we have following class
```java
package com;

import static com.google.common.base.Preconditions.checkArgument;

public class FastPreconditions {

    public static void checkArg(
            boolean expression,
            String errorMessageTemplate,
            int arg1
    ) {
        // fast check, avoid vargs + autoboxing
        if (!expression) {
            checkArgument(expression, errorMessageTemplate, arg1);
        }
    }
}
```

and test case for it 

```java
package com;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static com.FastPreconditions.checkArg;

public class FastPreconditionsTest {
    @Rule
    public ExpectedException thrown = ExpectedException.none();

    @Test
    public void simple1IntArg() throws Exception {
        thrown.expect(IllegalArgumentException.class);
        thrown.expectMessage("msg 1");
        checkArg(false, "msg %s", 1);
    }

    @Test
    public void simple1IntArgPasses() throws Exception {
        checkArg(true, "msg %s", 1);
    }
}
```

### Expected behaviour

Expect that the body of `checkArg` is fully covered like it is reported by IDEA

![](https://vladimirdolzhenko.github.io/hashCodeLegend/images/fastpreconditions_coverage_idea.png)

### Actual behaviour

`checkArg` has missed coverage of `checkArgument` while all 2 branches are covered

![](https://vladimirdolzhenko.github.io/hashCodeLegend/images/fastpreconditions_coverage_jacoco.png)

**Comment by Godin** [comment]
This is a known limitation of JaCoCo. Please read FAQ - http://www.jacoco.org/jacoco/trunk/doc/faq.html :

> Source code lines with exceptions show no coverage. Why?
>
> JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding line of source code is not marked as covered.

Basically it is a tradeoff between coverage in case of exceptions and runtime performance.
