### ISSUE TITLE
How can Jacoco  dump execution data frome android sub-process?

### ISSUE THREAD

**Issue by vigossjjj** [jacoco/jacoco#570]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version:0.7.6.201602180812
Operating system:Android
Tool integration: Gradle

### Expected behaviour
dump coverage data from andorid subprocess

### Actual behaviour
cat not dump subprocess execution data

**Comment by Godin** [comment]
Please note that this is a **issue tracker** and not a Q/A forum.

Please also note that this repository contains source code of JaCoCo library and some integrations such as JaCoCo Gradle Plugin are not developed here (http://www.jacoco.org/jacoco/trunk/doc/integrations.html)

Answering your question

> How can Jacoco dump execution data frome android sub-process?

in regard to library: The same way as for main process - classes of application should be instrumented.

**Comment by vigossjjj** [comment]
@Godin THX~
