### ISSUE TITLE
Jacoco Code Coverage not showing | application deployed on weblogic

### ISSUE THREAD

**Issue by ashishbha** [jacoco/jacoco#573]
Hi,

I am trying to generate code coverage for my application that is deployed on Weblogic server.

******There are many project deployed as library but I need coverage for selected project.*****

Problem :  eclipse plug-in not showing any coverage for application of selected project.

1) set server argument and start server 

-javaagent:/tmp/ashishb/jacocoJar/jacocoagent.jar=destfile=/tmp/ashishb/jacocoexec/jacoco.exec,output=tcpserver,address=omg616023.in.oracle.com,port=6300,classdumpdir=/tmp/ashishb/classdump,includes=com.XX.ck.XX.ggK*:com.XX.ck.XX.jacoco*

**Note (**com.XX.ck.XX.jacoco*** is dummy project, for this jacoco is showing coverage)**

**Note2: ggk =adapter.impl, module.party project**

2) All class file got generated relaed to ggk and jacoco in classdunp area. 

3)  jacoco is not showing coverage related to my application **(.ggk*)**, but it is showing coverage for dummy project (.jacoco*) deployed as WAR on server

**Note : It's huge application (.ggk*), contains more than 100+ projects and deployed on server as library and respective War is also deployed.** 

A help would be great, to understand why coverage is not getting generated .

Please see screenshot for better understanding
![jacoco](https://user-images.githubusercontent.com/30177623/28862714-a7e680c6-7783-11e7-89a3-3a2159bb9b6d.JPG)

**Comment by marchof** [comment]
@ashishbha Please use our mailing list for questions (you might have noticed this in the issue templae you just deleted):

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

What would also help is a exact description of your setup. Looks like you're usig a mixture of JaCoCo and EclEmma.
