### ISSUE TITLE
I would like to be able to filter methods from code coverage analysis.

### ISSUE THREAD

**Issue by steowens** [jacoco/jacoco#583]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version: 0.7.9
Operating system: Various
Tool integration: Maven

### Expected behaviour
I would expect that there is a way to disable code coverage on a per method basis for methods we wish to explicitly exclude from the coverage analysis report.  Ideally there would be an annotation on the method to allow this.

The coverage report ought to list links to each method thus excluded so it is easy to find the methods which have been flagged this way and it will be possible for code reviewers to assess whether the annotation has been used appropriately.

### Actual behaviour
There are some rumblings about filters in the future but nothing concrete.  This is a fairly high priority feature since it is the one thing that stands in the way of using coverage analysis in gating builds for build delivery pipelines.

**Comment by marchof** [comment]
This feature is already requested in #14.

It has low priority on our backlog and will not be implemented soon. We're currently focusing on automatic filtering of synthetic compiler constructs which cannot be tested at all.

Thanks for your understanding
