### ISSUE TITLE
Invalid missing coverage for lines that are actually covered

### ISSUE THREAD

**Issue by kevinCross** [jacoco/jacoco#586]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce
run the gradle build using ./gradlew build.
Inspect the jacoco coverage report in build/reports/coverage/index.html

JaCoCo version: 0.7.9
Operating system: "Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64"
Tool integration: gradle 3.5 and 4.1
Java version: (happens on all I know of) OpenJDK Runtime Environment (Zulu 8.21.0.1-macosx) (build 1.8.0_131-b11)

### Expected behaviour
There should be 100% coverage reported by the report system in the html report

### Actual behaviour
There is a large amount of lines missed. 
[bug.zip](https://github.com/jacoco/jacoco/files/1267003/bug.zip)

**Comment by Godin** [comment]
Duplicate of #587
