### ISSUE TITLE
Incorrect missing coverage reported from gradle/jacoco

### ISSUE THREAD

**Issue by kevlarC** [jacoco/jacoco#587]
This is a issue tracker. Please use our mailing list for general questions:
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

Steps to reproduce
in the bug.zip project run the gradle build using ./gradlew build.
Inspect the jacoco coverage report in build/reports/coverage/index.html

JaCoCo version: 0.7.9
Operating system: "Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64"
Tool integration: gradle 3.5 and 4.1
Java version: (happens on all I know of) OpenJDK Runtime Environment (Zulu 8.21.0.1-macosx) (build 1.8.0_131-b11)

Expected behaviour
There should be almost 100% coverage reported by the report system in the html report

Actual behaviour

with service.java: 
I would definitely expect coverage for lines  8,11,18
It would be acceptable/understandable that line 20,19 might not have coverage because of the runtime exception.
[bug.zip](https://github.com/jacoco/jacoco/files/1267215/bug.zip)

**Comment by Godin** [comment]
This is a known limitation of JaCoCo. Please see FAQ (http://www.jacoco.org/jacoco/trunk/doc/faq.html) and #370 , #279 , etc:

> Source code lines with exceptions show no coverage. Why?
>
> JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding line of source code is not marked as covered.

Basically it is a tradeoff between coverage in case of exceptions and runtime performance.

Lines 8, 11, 18, 20 are not marked because of this.
Line 19 is not marked at all because doesn't have associated bytecode instructions.

**Comment by kevinCross** [comment]
Well Im not sure this is totally true.
I believe its the reporting tool rather than the coverage tool since I believe jacoco is used in intelliJ coverage and it reports this correctly but the actual report reports it incorrectly.

**Comment by kevinCross** [comment]
![screen shot 2017-08-31 at 17 54 35](https://user-images.githubusercontent.com/30828526/29935090-8685c69a-8e75-11e7-9b5a-7917e3369170.png)

**Comment by kevinCross** [comment]
and from the documentation it definitely uses jacoco
```
Basics

Measuring code coverage is available for testing, applications, and application server run/debug configurations.

The code coverage measuring can be performed using the following runners:

IntelliJ IDEA code coverage runner (recommended).
EMMA open-source toolkit. Note that EMMA is not supported by the author any more, and works with Java 7 only when frame validation turned off (pass -noverify to the process).
JaCoCo.
```

**Comment by Godin** [comment]
@kevinCross IntelliJ by default uses own code coverage library:

![run_debug_configurations](https://user-images.githubusercontent.com/138671/29935142-0b26fcea-8e7e-11e7-86f8-8e10371eba2a.png)

And this is exactly what is stated in your quote:
> IntelliJ IDEA code coverage runner (recommended).

While AFAIK JaCoCo version in IntelliJ available as second option is very outdated, I believe that if you will switch to the second option, then for given example you'll see exactly the same as JaCoCo native report generates.

**Comment by Godin** [comment]
Here is proof using IntelliJ IDEA 2017.2.2:

![run_debug_configurations_and_service_java_-_cpp_-____projects_sonarsource_cpp_](https://user-images.githubusercontent.com/138671/29935500-3f64713a-8e7f-11e7-934a-91b4163e9810.png)

**Comment by Godin** [comment]
You can also notice that IntelliJ "sampling" mode doesn't provide branch coverage and "tracing" mode is slow on big test suites and projects, while JaCoCo native reports provides branch coverage and faster than IntelliJ "tracing" mode or at least as fast as IntelliJ "sampling".

**Comment by kevinCross** [comment]
Great thanks for the in informative answer 😄
