### ISSUE TITLE
Enhance jacoco-maven-plugin documentation

### ISSUE THREAD

**Issue by krichter722** [jacoco/jacoco#590]
### Steps to reproduce

JaCoCo version: ---
Operating system: ---
Tool integration: Maven

Visit the [jacoco-maven-plugin](http://www.jacoco.org/jacoco/trunk/doc/maven.html) as a newcomer.

### Expected and actual behaviour

  1. The documentation should contain dos if there're don'ts, i.e. add the info which properties to add to the surefire plugin, because one has to look that up otherwise which takes at least 5 minutes if you're not a surefire expert. I believe it's `-DforkCount=1`. The same for `compiled with debug information.` - it can take up to an hour to figure out how - you on the other hand have the information, so please don't make a secret out of it.
  2. Linking XML files won't work if the content-type on the web server isn't adjusted. Users who don't switch to the source view their browser only see

```

  4.0.0

  org.jacoco
  org.jacoco.examples.maven
  0.7.10-SNAPSHOT
  jar

  JaCoCo Maven plug-in example
  http://www.jacoco.org/jacoco

  
    
      junit
      junit
      4.10
      test
    
  

  
    1.5
    1.5
  

  
    
      
        org.jacoco
        jacoco-maven-plugin
        0.7.10-SNAPSHOT
        
[...]
```

if they open it in the browser. This also creates the impression that the documentation isn't maintained or has been reviewed by a lot of users and devs. A statement that different execution sections are necessary in the plugin configuration (which is unusual for Maven in my experience) and what they do is much preferred over a link to plain file.
  3. Issues like [`Skipping JaCoCo execution due to missing execution data file`](https://stackoverflow.com/questions/36304793/jacoco-with-maven-missing-execution-data-file) are impossible to avoid after reading the documentation. The user should be prepared for such pitfalls after reading the documentation.

I'm not seeking support here and I'm not eager to get jacobo running quickly. I want to get this fixed for everybody rather than just me.

**Comment by Godin** [comment]
@krichter722 first of all - thank you for your contribution.

>  `-DforkCount=1` 

As already stated on page that you link ( http://www.jacoco.org/jacoco/trunk/doc/maven.html ) - you can have any value for `forkCount` different from zero, and `1` is already a default according to documentation of `maven-surefire-plugin` ( http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#forkCount )

> `compiled with debug information`

`maven-compiler-plugin` by default configured to do so ( https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#debug ). And what if people compile Kotlin or Groovy for example and so rely on something else than `maven-compiler-plugin`? It seems counterproductive to try to document configuration of all possible third-party plugins and various scenarios of their usage, especially that they have their own documentation that indeed should be read for their efficient use. We did our best to provide bare minimum working example without unusual things and document general important requirement about debug information for the more complex configurations.

So, sorry, but don't understand what is exactly proposed for the points above.

> Linking XML files won't work if the content-type on the web server isn't adjusted.

So far we wasn't aware of any problems with display of linked XML files.
Content type seems to be correct:

```
$ curl -v -s http://www.jacoco.org/jacoco/trunk/doc/examples/build/pom.xml -o /dev/null
*   Trying 151.101.193.147...
* Connected to www.jacoco.org (151.101.193.147) port 80 (#0)
> GET /jacoco/trunk/doc/examples/build/pom.xml HTTP/1.1
> Host: www.jacoco.org
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: GitHub.com
< Content-Type: application/xml
< Last-Modified: Tue, 29 Aug 2017 23:43:50 GMT
< Access-Control-Allow-Origin: *
< Expires: Tue, 05 Sep 2017 19:57:29 GMT
< Cache-Control: max-age=600
< X-GitHub-Request-Id: F8B6:27A2A:9F43EB:E106CB:59AEFF51
< Content-Length: 2793
< Accept-Ranges: bytes
< Date: Tue, 05 Sep 2017 19:49:29 GMT
< Via: 1.1 varnish
< Age: 120
< Connection: keep-alive
< X-Served-By: cache-cdg8729-CDG
< X-Cache: HIT
< X-Cache-Hits: 1
< X-Timer: S1504640969.408388,VS0,VE1
< Vary: Accept-Encoding
< X-Fastly-Request-ID: 97bedfddcb386ad191de4566576dd613b7dac2bb
<
{ [837 bytes data]
* Connection #0 to host www.jacoco.org left intact
```

And displayed correctly in Chrome and Firefox. Could it be a problem specific to your browser?

**Comment by marchof** [comment]
@krichter722 Any updates on this? Otherwise I will close as invalid.

**Comment by Godin** [comment]
> you gave some explanations here which are clearer than on the documentation page

I haven't actually said anything that is not already written in documentation or in linked documentation of other plugins. So, sorry, but I still don't understand which **exact** changes are requested.

**Comment by marchof** [comment]
@krichter722 Double checked with Firefox 55.0.3 64-Bit, but on OSX - shows properly. Maybe corporate firewall changing headers?

Regarding documentation I suggest to open specific issue or pull request what exactly needs to be changed on what page.
