### ISSUE TITLE
Can not generate exec file by -Djacoco.destFile=./coverage/jacoco.exec

### ISSUE THREAD

**Issue by binbjz** [jacoco/jacoco#592]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce (I have installed jacoco plugin on jenkins)
mvn clean test -Dmaven.test.failure.ignore=true -Djacoco.destFile=./coverage/jacoco.exec org.jacoco:jacoco-maven-plugin:prepare-agent

JaCoCo version: 0.7.9
Operating system: centos6.5
Tool integration: Maven/Ant/API/Other
Maven

### Expected behaviour
it will create coverage directory ad generate data file jacoco.exec

### Actual behaviour
coverage directory and data file jacoco.exec could not be generated

## By the way
I need generate exec file by command line with mvn command, I can generate jacoco.exec in another maven project by using the same command, so What options did I lose? 

The following is jenkins log output
[JaCoCo plugin] Number of found exec files for pattern \*\*/hadoop-project/coverage/**.exec: 0

**Comment by Godin** [comment]
> I can generate jacoco.exec in another maven project by using the same command, so What options did I lose?

There is no way to guess difference in configurations of your projects.

Quoting documentation of `prepare-agent` (http://www.jacoco.org/jacoco/trunk/doc/prepare-agent-mojo.html):

> Prepares a property pointing to the JaCoCo runtime agent that can be passed as a VM argument to the application under test.

So check why it is not passed and thus why agent is not used in your project.

Last, but not least - warn you again that this is bug tracker and not a Q/A forum.

**Comment by binbjz** [comment]
Hi Godin, I think it could not genera exec by the property, the should be issue. But I am not sure.

**Comment by binbjz** [comment]
Prepares a property pointing to the JaCoCo runtime agent that can be passed as a VM argument to the application under test.

Hi Godin, how should I  prepares a property pointing to the JaCoCo runtime agent that can be passed as a VM argument to the application under test ?

**Comment by Godin** [comment]
Given

`src/test/java/Test.java`:
```
public class Test {
  @org.junit.Test
  public void test() {
  }
}
```

`pom.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>example</artifactId>
  <version>0.1-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.20</version>
        <configuration>
          <!--
          no argLine here
          to avoid common mistake described on page http://www.jacoco.org/jacoco/trunk/doc/prepare-agent-mojo.html
          -->
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

Execution of `mvn -X org.jacoco:jacoco-maven-plugin:0.7.9:prepare-agent clean test`:
```
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default-cli) @ example ---
[INFO] argLine set to -javaagent:/home/godin/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/tmp/jacoco/target/jacoco.exec
...
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ example ---
...
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-surefire-plugin:2.20:test' with basic configurator -->
[DEBUG]   (s) additionalClasspathElements = []
[DEBUG]   (s) argLine = -javaagent:/home/godin/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/tmp/jacoco/target/jacoco.exec
...
[DEBUG] Forking command line: /bin/sh -c cd /tmp/jacoco && /home/godin/.java-select/versions/jdk1.8.0_131/jre/bin/java -javaagent:/home/godin/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/tmp/jacoco/target/jacoco.exec -jar /tmp/jacoco/target/surefire/surefirebooter2821621800873046096.jar /tmp/jacoco/target/surefire 2017-09-10T15-39-54_076-jvmRun1 surefire7032424254257464177tmp surefire_04455499659361330086tmp
...
```

property `argLine` is set for `maven-surefire-plugin` ( http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#argLine ), used by `maven-surefire-plugin` and passed by it to JVM.

**Comment by binbjz** [comment]
Hi Given, I can not modify pom.xml, I can only modify script in "Pre Steps --> Execute shell command", because we team can only use jenkins to get code coverage and download maven project by "git clone" way from git branch.

**Comment by Godin** [comment]
JaCoCo agent must be passed to JVM - this is the requirement that must be satisfied.
If you can not satisfy this requirement, there is nothing what we can do.
Talk to the guys who can modify `pom.xml` or patch it in Jenkins after cloning.

**Comment by binbjz** [comment]
@Godin You helped me a lot. I really appreciate it.
