### ISSUE TITLE
Getting error "Could not load definitions"

### ISSUE THREAD

**Issue by vivekkatakam** [jacoco/jacoco#593]
I am trying to run Jococo using ant and I am getting the following error 

### Steps to reproduce

JaCoCo version: 0.5
Operating system:RHEL 7.3
Tool integration: Ant,Java 1.8 

### Expected behaviour
should compile

### Actual behaviour
Getting the following error:
Could not load definitions from resouce org/jacoco/ant/antlib.xml. It could not be found.

Can you please suggest.

Thanks and Regards,
Vijay

**Comment by Godin** [comment]
First of all - this is our bug tracker and not a Q&A forum, for the questions please use Users Mailing List at https://groups.google.com/forum/?fromgroups=#!forum/jacoco

> JaCoCo version: 0.5

You're using very old version, please use latest, which is 0.7.9 as of today.

> Could not load definitions from resouce org/jacoco/ant/antlib.xml. It could not be found.

You're not providing enough details about your configuration to be able to reproduce the problem and to say precisely what is wrong with your configuration.

However simple search in internet shows that such error is not specific to JaCoCo and indicates incorrect addition of non-standard Ant tasks to your build. Please consult with Ant documentation about addition of tasks and make sure that you correctly add JaCoCo Ant Tasks, e.g.:

```
<taskdef uri="antlib:org.jacoco.ant" resource="org/jacoco/ant/antlib.xml">
  <classpath path="path/to/jacocoant.jar" />
</taskdef>
```
