### ISSUE TITLE
Maven Central does not have jacococli.jar

### ISSUE THREAD

**Issue by evanchsa** [jacoco/jacoco#595]
### Steps to reproduce

JaCoCo version: 0.7.9
Operating system: All
Tool integration: Other

### Expected behaviour

The .zip file artifact for jacoco-0.7.9 on Maven central does not include jacococli.jar. The only way (I have found at least) is to download the .zip file from jacoco.org's oss.sonatype.com repo.

The org.jacoco.cli artifact also does not exist on Maven central.

**Comment by Godin** [comment]
@evanchsa as you can see at http://www.jacoco.org/jacoco/trunk/doc/changes.html Command Line Interface has been added for the version after 0.7.9 that was not yet released, so correct that it is not available in Maven Central that is for releases.

**Comment by evanchsa** [comment]
Thanks. I just looked at the change log to see when it was added.
