### ISSUE TITLE
Using Jacoco with Gradle Kotlin DSL

### ISSUE THREAD

**Issue by gmariotti** [jacoco/jacoco#612]
Hi, I'm trying to convert my `build.gradle` to `build.gradle.kts`, but I'm having a problem with the jacoco plugin.

### Steps to reproduce

My `build.gradle.kts` for jacoco is:

```kotlin
plugins {
    id("jacoco")
}

// other non jacoco-related code

tasks.withType<JacocoReport> {
    reports {
        xml.apply {
            isEnabled = true
            destination = File("build/reports/jacoco.xml")
        }
        executionData(tasks.withType<Test>())
    }
}
```

### Actual Behaviour

And when I run `gradle check jacocoTestReport --info`, I get the following error:

```bash
> Task :jacocoTestReport
Putting task artifact state for task ':jacocoTestReport' into context took 0.0 secs.
Executing task ':jacocoTestReport' (up-to-date check took 0.026 secs) due to:
  Task has failed previously.
[ant:jacocoReport] Loading execution data file /Users/guido.mariotti/Documents/IntelliJIDEAProjects/vault-kotlin/build/jacoco/test.exec

:jacocoTestReport (Thread[Task worker for ':',5,main]) completed. Took 0.456 secs.
```

Am I doing something wrong?

Operating system: macOS Sierra 10.12.6
Tool integration: Gradle

**Comment by Godin** [comment]
JaCoCo Plugin for Gradle is [developed in Gradle sub-project](https://github.com/gradle/gradle/tree/master/subprojects/jacoco) by Gradle team, as well as Gradle Kotlin DSL is not developed by us. So please contact respective tools providers. Thank you for your understanding.

P.S.
> Task has failed previously.

Gradle caches results of execution of tasks, so in absence of changes it won't be executed - message literally says: previous execution failed.
