### ISSUE TITLE
Android Project with ReatNative generate the .ec is 0Byte, becasue  java.lang.reflect.InvocationTargetException.

### ISSUE THREAD

**Issue by Richard00213** [jacoco/jacoco#619]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version:
Operating system:
Tool integration: Maven/Ant/API/Other

**Comment by Richard00213** [comment]
Android Project with ReatNative generate the .ec is 0Byte, becasue  java.lang.reflect.InvocationTargetException.
when excute  out.write((byte[]) agent.getClass().getMethod("getExecutionData", boolean.class)
                    .invoke(agent, false));

Add, my App project is Hybdrid , my app frist view is RN.

**Comment by Godin** [comment]
There is no
```
out.write((byte[]) agent.getClass().getMethod("getExecutionData", boolean.class).invoke(agent, false));
```
in our codebase, thus and in absence of clear steps to reproduce your problem, the only thing that we can advice is to contact respective integration provider, which are developers of Android Gradle Plugin, I assume, in this case.

**Comment by Richard00213** [comment]
In the JacocoInstrumentation.java have the out.write((byte[]) agent.getClass().getMethod("getExecutionData", boolean.class).invoke(agent, false));  When i quit my app, this tell me java.lang.reflect.InvocationTargetException and the .ec is 0 byte.

**Comment by Godin** [comment]
Once again there is no `JacocoInstrumentation.java` in our repository - please contact developers of Android platform.
