### ISSUE TITLE
Filter default constructors

### ISSUE THREAD

**Issue by dmitrikudrenko** [jacoco/jacoco#621]
### Steps to reproduce

JaCoCo version: 0.7.10-SNAPSHOT
Operating system: mac os
Tool integration: gradle

In filtering options avoiding private constructor is already implemented. If class doesn't have constructor, it is marked as missed instruction. For example,
```
public final class A {
}
```
will be marked as missed.

### Expected behaviour
Class would be marked as missed
### Actual behaviour
Class is marked is missed.

**Comment by marchof** [comment]
@dmitrikudrenko In this case a public constructor is created by the compiler. This is why it is not filtered (yet).

@Godin For me it would make sense to filter any empty constructor. Either it is created by the compiler or there is nothing to test. WDYT?

**Comment by Godin** [comment]
@marchof There are two cases:
either there is no need to create instance of class, i.e. all methods are static, then why not making explicit `private` constructor that will be filtered and which is a good practice;
or instance is needed and so presence of tests cover it.

Summing up: there is good practice that is enforced by non-filtering and no good reasons to filter.

**Comment by marchof** [comment]
@Godin I agree that there are two cases. But if instance creation does not involve any code beside a empty constructor what it the point about testing here?

**Comment by Godin** [comment]
@marchof my point is that we don't enforce testing of empty constructor by not having filter - it anyway will be covered, while by not having filter we enforce marking it `private` when it is not needed.

**Comment by Godin** [comment]
@dmitrikudrenko given the discussion above - there is no reasons to filter default constructors, so could you please elaborate more about your request?

**Comment by dmitrikudrenko** [comment]
Yeah, my case is about util's classes that contain only static methods. I agree with your opinion about private constructors, but now I have big amount of those classes and I don't want to change they. So it would be perfect to have ability to enable a filter

**Comment by Godin** [comment]
Given your description, nothing really prevents introduction of explicit `private` constructors. And for the reasons described above we don't plan to filter default constructors.
