### ISSUE TITLE
Do we have a work around to support android code ProGuard?

### ISSUE THREAD

**Issue by cyxcw1** [jacoco/jacoco#625]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version: 0.7.9
Operating system: macOS
Tool integration: Maven/Ant

### Expected behaviour
When open ProGuard in an android project, support code coverage normally.

### Actual behaviour
We do not support now!!!

As we know, we can open code ProGuard in an android project. The class files are ProGuard when a build is completed, so Jacoco can not support well.
Do we have a work around for this case?

**Comment by cyxcw1** [comment]
Is it because I have a post on google group?

**Comment by marchof** [comment]
> This is a issue tracker. Please use our mailing list for general questions:
