### ISSUE TITLE
Unbalanced monitorenter / monitorexit instructions in instrumented bytecode.

### ISSUE THREAD

**Issue by allenhair** [jacoco/jacoco#626]
Jacoco will sometimes insert a probe before the end label of a try-catch block. When this happens, the probe will be covered by the range of the catch clause. This can lead to code paths where monitorexit can be called twice.

For example, consider the following:
```
  Code:
          ...
     9: monitorenter
    10: iload_1
    11: ifeq          23
    14: aload_2
    15: monitorexit
    16: aload_0
          ...
    34: astore_3
    35: aload_2
    36: monitorexit
    37: aload_3
          ...
  Exception table:
     from    to  target type
        10    16    34   any
        34    37    34   any
```

The range of the catch clauses are inclusive on the "from" end and exclusive on the "to" end, so that all instructions after monitorenter are covered, including the final monitorexit (but not the following aload_0). If any of these throw, we'll jump to PC 34 so that monitorexit is executed no matter what.

However, when instrumented, we get the following:
```
  Code:
          ...
    13: monitorenter
    14: aload_2
    15: iconst_3
    16: iconst_1
    17: bastore
    18: iload_1
    19: ifne          29
    22: aload_2
    23: iconst_4
    24: iconst_1
    25: bastore
    26: goto          47
    29: aload_3
    30: monitorexit
    31: aload_2
    32: iconst_5
    33: iconst_1
    34: bastore
    35: aload_0
          ...
    58: astore        4
    60: aload_3
    61: monitorexit
    62: aload         4
          ...
  Exception table:
     from    to  target type
        14    35    58   any
        58    62    58   any
```

In this case, the probe inserted before the aload_0 (PC 35) instruction becomes covered by the catch clause. As a result, it is possible to execute monitorexit twice (on PC 30, and then again on PC 61) if any of the probe instructions (PC 31-34) throw.

### Steps to reproduce

JaCoCo version: 0.7.10-SNAPSHOT
Operating system: Linux
Tool integration: CLI

Compile and instrument the attached [Check.java](https://github.com/jacoco/jacoco/files/1523374/Check.java.txt)
class, then inspect the bytecode:
1. javac Check.java
2. java -jar jacococli.jar instrument Check.class --dest instrumented
3. javap -c instrumented/Check.class

### Expected behaviour

The catch clause does not cover any instructions after monitorexit. That is, the exception table entry should be:
```
  from    to  target type
     14    31    58   any
```

### Actual behaviour

The exception table entry covers the probe instructions that occur after monitorexit succeeds. The exception table entry is:
```
  from    to  target type
     14    35    58   any
```

**Comment by allenhair** [comment]
For reference, this is pretty similar to #265

**Comment by Godin** [comment]
Hi @allenhair , first of all - your reports are always a pleasure to read. Thank you for such great level of details! 👍

> As a result, it is possible to execute monitorexit twice (on PC 30, and then again on PC 61) if any of the probe instructions (PC 31-34) throw.

While theoretically possible that probe instruction can throw exception, I think that practically probability of this is very low. So my guess is that the real problem here is that such class files do not pass bytecode verification by Android Runtime similarly to #265 ? I'm asking this question because there should be very good reason to change version of exec file as it was done in your PR #627 , since such change will have dramatical consequences for users of downstream projects (such as Jenkins Plugin) that unfortunately read exec file.

**Comment by allenhair** [comment]
Thanks for the kind words. You are correct - we're dealing with a similar failure to pass bytecode verification, even though those instructions probably won't throw in practice.

From your [comment on #627](https://github.com/jacoco/jacoco/pull/627#discussion_r154752154) it sounds like we may be able to avoid changing the exec file version. I'd be happy to remove that from the PR, but will defer to your expertise.

**Comment by Godin** [comment]
Do you know if there is a way to disable verification in Android Runtime as a temporary workaround?

BTW should be noted that seems that some verification is missing in current [StructuredLockingTest.java](https://github.com/jacoco/jacoco/blob/e1502d10bfe8eda0a921cc8f34db3fb8f7236c4a/org.jacoco.core.test/src/org/jacoco/core/test/validation/StructuredLockingTest.java) - quick attempt to use it on the provided example didn't lead to any failures of assertions.

**Comment by allenhair** [comment]
We do have a workaround available, so this doesn't block our use of JaCoCo completely.

I'll take a look at StructuredLockingTest to see what's going on.

**Comment by Godin** [comment]
> We do have a workaround available, so this doesn't block our use of JaCoCo completely.

What about other users? :wink: Can you share it?

**Comment by allenhair** [comment]
The workaround is to disable dex (Android bytecode) preoptimization when building the system image (i.e. set WITH_DEXPREOPT=false).  See [System ROM configuration](https://source.android.com/devices/tech/dalvik/configure#system_rom).

Verification will still fail at runtime, but we'll fall back to a slower mode of execution with additional access checks.

**Comment by Godin** [comment]
In fact this also has negative and observable impact on JIT in HotSpot JVM. According to http://hg.openjdk.java.net/jdk/jdk/file/6c4bdbf90897/src/jdk.internal.vm.compiler/share/classes/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/UnbalancedMonitorsTest.java#l42 :

> methods with unstructured locking aren't compiled and fall back to the interpreter

And here is example:
```java
class Example {
  public static void main(String[] args) {
    while (true) {
      long t = System.currentTimeMillis();
      target();
      t = System.currentTimeMillis() - t;
      if (t > 20) {
        System.out.println(t);
      }
    }
  }

  static Object lock = new Object();

  static void target() {
    try {
      synchronized (lock) {
        for (int i = 0; i < 10_000_000; i++) {
          nop();
        }
        return;
      }
    } finally {
      nop();
    }
  }

  static void nop() {
  }
}
```

Using
```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

Normally output of `java Example` will be empty, because method `target` is fast thanks to JIT optimizations.

However similarly to initial example - instrumentation adds probe at the end of try-catch after `monitorexit`:
```
...
        48: monitorexit
        49: aload_0
        50: bipush        11
        52: iconst_1
        53: bastore
...
        63: astore_3
        64: aload_1
        65: monitorexit
...
      Exception table:
         from    to  target type
            10    54    63   any
...
```

And execution with agent is much slower:
```
$ java \
    -javaagent:jacoco-0.7.9/lib/jacocoagent.jar \
    Example
451
436
438
```
and
```
java \
    -javaagent:jacoco-0.7.9/lib/jacocoagent.jar \
    -XX:+PrintCompilation \
    -Xlog:monitormismatch=info \
    Example
```
shows
```
    219  338 % !   3       Example::target @ 22 (86 bytes)
[0.220s][info][monitormismatch] Monitor mismatch in method  Example::target: monitor stack height merge conflict
[0.220s][info][monitormismatch] Monitor mismatch in method  Example::target: monitor stack height merge conflict
compilation bailout: invalid parsing
    219  338 % !   3       Example::target @ 22 (86 bytes)   COMPILE SKIPPED: invalid parsing (retry at different tier)
    221  339 % !   4       Example::target @ 22 (86 bytes)
[0.221s][info][monitormismatch] Monitor mismatch in method  Example::target: monitor stack height merge conflict
[0.221s][info][monitormismatch] Monitor mismatch in method  Example::target: monitor stack height merge conflict
    221  339 % !   4       Example::target @ 22 (86 bytes)   COMPILE SKIPPED: cannot parse method (retry at different tier)
```

And, interestingly, seems that this does not impact execution with Eclipse OpenJ9.

**Comment by Godin** [comment]
When using agent from PR #627 - method is compiled by JIT. @allenhair :thumbsup:

**Comment by Godin** [comment]
Just for fun and for the record: if I'm not mistaken, then following modification

```diff --git i/org.jacoco.core/src/org/jacoco/core/internal/analysis/MethodAnalyzer.java w/org.jacoco.core/src/org/jacoco/core/internal/analysis/MethodAnalyzer.java
index 5a7239e0..835457ee 100644
--- i/org.jacoco.core/src/org/jacoco/core/internal/analysis/MethodAnalyzer.java
+++ w/org.jacoco.core/src/org/jacoco/core/internal/analysis/MethodAnalyzer.java
@@ -30,6 +30,7 @@ import org.jacoco.core.internal.flow.MethodProbesVisitor;
 import org.objectweb.asm.Handle;
 import org.objectweb.asm.Label;
 import org.objectweb.asm.MethodVisitor;
+import org.objectweb.asm.Opcodes;
 import org.objectweb.asm.tree.AbstractInsnNode;
 import org.objectweb.asm.tree.MethodNode;
 import org.objectweb.asm.tree.TryCatchBlockNode;
@@ -122,6 +123,13 @@ public class MethodAnalyzer extends MethodProbesVisitor

                methodVisitor.visitCode();
                for (final TryCatchBlockNode n : methodNode.tryCatchBlocks) {
+
+                 if (n.end.getPrevious().getOpcode() == Opcodes.MONITOREXIT) {
+                         if (LabelInfo.needsProbe(n.end.getLabel())) {
+                                 System.err.println(className + " " + methodNode.name);
+                         }
+                 }
+
                        n.accept(methodVisitor);
                }
                currentNode = methodNode.instructions.getFirst();
```

allows detection of affected methods in JAR files

```
java -jar jacococli.jar classinfo --quiet ~/.m2
```
