### ISSUE TITLE
Jacoco Excludes for excluding 100 different classes

### ISSUE THREAD

**Issue by erajeshgit** [jacoco/jacoco#628]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

I have to exclude more than 300 classes from Jacoco code coverage report and these are under different packages. I have to add 300 exclude lines in pom.xml and it looks bad. Please let me know if there is any other way to keep these excludes out of Pom.xml

### Steps to reproduce

JaCoCo version: 0.7.9
Operating system: Linux
Tool integration: Maven/Ant/API/Other: Maven

**Comment by andrioli** [comment]
http://www.jacoco.org/jacoco/trunk/doc/report-mojo.html#excludes. 

Is good read the doc before open a ticket.

**Comment by andrioli** [comment]
If you can't use the wildcard you will need to list all classes in pom.xml

**Comment by erajeshgit** [comment]
if there are 300 classes then do I need to use 300 lines of exclude in pom.xml?
