### ISSUE TITLE
JaCoCo doesn't find all Lombok annotations

### ISSUE THREAD

**Issue by precupqdm** [jacoco/jacoco#633]
### Steps to reproduce
I've got a project set up with a `report-aggregate` goal based on [this one](https://github.com/jacoco/jacoco/tree/master/jacoco-maven-plugin.test/it/it-report-aggregate) that's using Lombok.

JaCoCo version: 0.7.10-SNAPSHOT
Operating system: Debian
Tool integration: Maven
Lombok version: 1.16.16

### Expected behavour
No Lombok generated functions appear in my aggregate report.

### Actual behavour
All Lombok generated functions appear in my aggregate report.

### Steps to fix
If you want me to I'll make a PR for this, not sure what your workflow is. In [LombokGeneratedFilter](https://github.com/jacoco/jacoco/blob/master/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/LombokGeneratedFilter.java), it currently returns `methodNode.invisibleAnnotations`, but for me, all the Lombok annotations were in `methodNode.visibleAnnotations`. I'm not sure if lombok has changed the annotation retention policy or what, but making `getAnnotations` into the following fixes the issue for me and should be backwards compatible if an older version of Lombok was adding annotations differently.

```
@Override
List<AnnotationNode> getAnnotations(final MethodNode methodNode) {
 if (methodNode.visibleAnnotations == null) {
  return methodNode.invisibleAnnotations;
 } else if (methodNode.invisibleAnnotations == null) {
  return methodNode.visibleAnnotations;
 }

 List<AnnotationNode> annotations = new ArrayList<AnnotationNode>(methodNode.visibleAnnotations);
 annotations.addAll(methodNode.invisibleAnnotations);
 return annotations;
}
```

**Comment by Godin** [comment]
Hi @precupqdm ,

> for me, all the Lombok annotations were in methodNode.visibleAnnotations

could you please provide reproducer? I'm asking because 
* just now repeated a test that we did in past with Lombok 1.16.16 (see https://github.com/jacoco/jacoco/pull/513#issuecomment-291170668) - annotations are runtime invisible
* as was as in documentation - https://projectlombok.org/api/lombok/Generated.html
* and according to https://github.com/rzwitserloot/lombok/blame/master/src/core/lombok/Generated.java#L39 it has `@Retention(RetentionPolicy.CLASS)` since the beginning till today.

**Comment by precupqdm** [comment]
I'm currently unable to reproduce it on a different Debian machine. I'll
investigate further in the morning, looks like it's probably something on
my end. My apologies if it is.

**Comment by precupqdm** [comment]
Alright, this has been an odd morning. I did manage to reproduce it on the same machine as yesterday, but after clearing my m2 cache it's no longer happening. Something must've been in a weird state on my machine. Thanks for taking the time to look into this; my apologies for the false positive.
