### ISSUE TITLE
Android Proguard Failed: can't find referenced class org.jacoco.agent.rt.internal_8ff85ea.Offline

### ISSUE THREAD

**Issue by jega-ms** [jacoco/jacoco#637]
I have an flavor based android library project which will generate the AAR file. I have integrated the Jacoco it is works fine if we define explicitly . Incase if i  turn on "testCoverageEnabled" option under the debug build types, the proguard is throwing an exception  "**Warning: xxx.xxx.xxx.SomeClassName: can't find referenced class org.jacoco.agent.rt.internal_b0d6a23.Offline**" ,  I'm not sure how jacoco is getting included with pro-guard task. 

**My Build Commands:**
**./gradlew clean build** ( want to build debug and release together)

### Steps to reproduce

- Create new Android App
- Create new ARR Library and link to main app
-  Add two flavors on both project `(e.g Flavour1 & Flavour2)`
- Integrated the Jacoco ( use this file [ref](https://github.com/mgouline/android-samples/blob/master/jacoco/jacoco.gradle))
- In ARR Library Module and App Module enable automatic test Coverage. [Ref](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.BuildType.html#com.android.build.gradle.internal.dsl.BuildType:testCoverageEnabled)
``` 
debug {
 debutestCoverageEnabled true
}
``` 
-  run build command `"./gradlew clean build"`

JaCoCo version: 0.7.9 
Operating system: Mac & CentoS 
Tool integration:  Android Gradle 

### Expected behavior
 Build should succeed with release and debug version 

### Actual behavior
Getting exception 
```
Warning: xxx.xxx.xxx.SomeClassName1: can't find referenced class org.jacoco.agent.rt.internal_b0d6a23.Offline
Warning: xxx.xxx.xxx.SomeClassName2: can't find referenced class org.jacoco.agent.rt.internal_b0d6a23.Offline
Warning: xxx.xxx.xxx.SomeClassName3: can't find referenced class org.jacoco.agent.rt.internal_b0d6a23.Offline
Warning: xxx.xxx.xxx.SomeClassName4: can't find referenced class org.jacoco.agent.rt.internal_b0d6a23.Offline
```

**Comment by Godin** [comment]
A so-called "offline instrumentation" is used for Android - http://www.jacoco.org/jacoco/trunk/doc/offline.html:

> Unlike with on-the-fly instrumentation offline instrumented classes get a direct dependency on the JaCoCo runtime.

So in this case dependency of instrumented classes on `org.jacoco.agent.rt.[...].Offline` is expected.

Either ignore warning, or teach ProGuard to find corresponding JAR that is used at runtime and contains this class. Or I even would not recommend to use ProGuard while measuring code coverage.
