### ISSUE TITLE
Generate global .exec file with report-aggregate for multi-module project

### ISSUE THREAD

**Issue by Siceron** [jacoco/jacoco#638]
Hello,

First of all I'm using jacoco 0.7.9 with maven. I'm also using sonarQube 4.5.6.

I have a multi-module project and I used the report-aggregate goal in order to have a global coverage report and it works fine, but I want to use it with sonarQube and the problem is that sonarQube is expecting a .exec file. Same for using it with analyze coverage of Intellij.

Is it possible to generate a .exec file along with the .html/csv/xml ones that could be used for a multi-module project ?

Thanks in advance for your response.

**Comment by Godin** [comment]
Hi,

According to SonarQube documentation https://docs.sonarqube.org/display/PLUG/Code+Coverage+by+Unit+Tests+for+Java+Project :
starting from SonarQube version 6.2 you can specify multiple exec files using property `sonar.jacoco.reportPaths`. 4.5.6 is two years old, so why not simply update your SonarQube instance and benefit from this property (and don't forget to update its plugins, especially Java plugin).

There is also
* possibility to produce single exec file from the beginning by configuring [JaCoCo Agent property `destfile`](http://www.jacoco.org/jacoco/trunk/doc/agent.html) via [`destFile` property of `prepare-agent` goal of jacoco-maven-plugin](http://www.jacoco.org/jacoco/trunk/doc/prepare-agent-mojo.html#destFile)
* [`merge` goal in jacoco-maven-plugin](http://www.jacoco.org/jacoco/trunk/doc/merge-mojo.html)
* [`merge` task in JaCoCo Ant Tasks](http://www.jacoco.org/jacoco/trunk/doc/ant.html#merge) and [maven-antrun-plugin](http://maven.apache.org/plugins/maven-antrun-plugin/)
* starting from JaCoCo 0.8.0 there is [Command Line Interface with command `merge`](http://www.jacoco.org/jacoco/trunk/doc/cli.html)

BTW answer on exactly this question already exists in JaCoCo Users Mailing List - 
 https://groups.google.com/d/msg/jacoco/-ipUlIfZfdo/FD5HYltzCAAJ
