### ISSUE TITLE
Private constructor not filtered out by JaCoCo 0.8.0

### ISSUE THREAD

**Issue by danielleberre** [jacoco/jacoco#642]
### Steps to reproduce

JaCoCo version: 0.8.0
Operating system: Linux
Tool integration: Ant + SonarQube 6.7

### Expected behaviour

I downloaded the version 0.8.0 of JaCoCo because I was annoyed to see that the coverage
of my code was incorrect due to a private constructor never called in the tests.

The code is the following:

```
public final class ConsListFactory {

    private ConsListFactory() {
        // pour empêcher la création d'instances de cette classe
    }
   ...
```
I noticed that such case is supposed to be filtered out in 0.8.0.

I updated my jacocoant.jar to 0.8.0.

```
658808  2 jan 21:52 jacocoant.jar
75a93fc76d0ca54b749a9821f01f272330e6399b  lib/jacocoant.jar
```
I expected to see that private constructor ignored in the coverage report.

### Actual behaviour

The coverage report still reports the private constructor as uncovered in the report.

**Comment by Godin** [comment]
Using `src/ConsListFactory.java`

```
public final class ConsListFactory {

    private ConsListFactory() {
        // pour empêcher la création d'instances de cette classe
    }

    public static void main(String[] args) {
      // constructor is not used
    }
}
```

and `build.xml`

```
<project xmlns:jacoco="antlib:org.jacoco.ant">

  <taskdef uri="antlib:org.jacoco.ant" resource="org/jacoco/ant/antlib.xml">
    <classpath path="jacocoant.jar" />
  </taskdef>

  <target name="clean">
    <delete dir="target/" />
  </target>

  <target name="compile" depends="clean">
    <mkdir dir="target/classes" />
    <javac srcdir="src" destdir="target/classes" debug="true" includeantruntime="false" />
  </target>

  <target name="test" depends="compile">
    <jacoco:coverage destfile="target/jacoco.exec">
      <java classname="ConsListFactory" fork="true">
        <classpath path="target/classes" />
      </java>
    </jacoco:coverage>
  </target>

  <target name="report" depends="test">
    <jacoco:report>
      <executiondata>
        <file file="target/jacoco.exec" />
      </executiondata>
      <structure name="Example">
        <classfiles>
          <fileset dir="target/classes" />
        </classfiles>
        <sourcefiles encoding="UTF-8">
          <fileset dir="src" />
        </sourcefiles>
      </structure>
      <html destdir="target/report" />
    </jacoco:report>
  </target>

</project>
```

`ant report` produces correctly filtered report:

![report](https://user-images.githubusercontent.com/138671/34923025-1e386320-f998-11e7-90d9-482643c4c52c.png)

> Tool integration: Ant + **SonarQube** 6.7

Quoting http://www.jacoco.org/jacoco/trunk/doc/changes.html :

> Note: Tools that directly read exec files and embed JaCoCo for this (such as **SonarQube** or Jenkins) will provide filtering functionality only after **they updated** to this version of JaCoCo.

Quoting https://groups.google.com/d/msg/jacoco/e2PVMeMvA8k/uHsJbi4iAQAJ :

> ### Please Note
> 
> Tools that directly read exec files (which is not a final report) and embed JaCoCo for generation of report will provide filtering functionality only after they updated to this version of JaCoCo.
> So **please follow/wait/etc respective vendors such as**
> **SonarQube** - https://jira.sonarsource.com/browse/SONARJAVA-2608

See also https://github.com/jacoco/jacoco/pull/513#issuecomment-293176354 , https://github.com/jacoco/jacoco/issues/575

> downloaded the version 0.8.0 of JaCoCo because I was annoyed

We are annoyed by ignorance of announcements/changelog and absence of search before creation of tickets. Please show a bit of respect to developers of a tool provided for you for free.

Thank you for your understanding.

**Comment by danielleberre** [comment]
I am sorry if you took my report as a criticism for JaCoCo: I I looked around and found the changelog with the fix for the private constructor filter.

It was not obvious to me that the filtering happens after the exec file I created, now I know, thanks for that information.
