### ISSUE TITLE
Jacoco not ignoring Lombok @Generated annotation

### ISSUE THREAD

**Issue by ezraroi** [jacoco/jacoco#643]
JaCoCo version: 0.8.0
Operating system: Linux
Tool integration: Gradle 4.4.1
Lombok version: 1.6.18

lombok.config
```
config.stopBubbling = true
lombok.addLombokGeneratedAnnotation = true
```

### Expected behaviour

code generated by Lombok should be ignored in coverage calculation

### Actual behaviour
Jacoco is not ignoring @Data annotation for example
![image](https://user-images.githubusercontent.com/5808368/35387024-dabb7028-01d6-11e8-90a0-f2918430491f.png)

![image](https://user-images.githubusercontent.com/5808368/35387029-e4f25386-01d6-11e8-82ee-b4e0d20262ba.png)

**Comment by Godin** [comment]
Here is example ([example.zip](https://github.com/jacoco/jacoco/files/1663951/example.zip)) with Maven showing that methods in a class with `@Data` annotation are perfectly filtered:

![methods](https://user-images.githubusercontent.com/138671/35388548-8a53d9ce-01d4-11e8-8429-41bf57729ef6.png)

![source](https://user-images.githubusercontent.com/138671/35388552-8c433144-01d4-11e8-94c9-5df77cabdd7a.png)

So please provide **complete** reproducer demonstrating your problem.

**Comment by Godin** [comment]
Without reproducer there is nothing what we can investigate, so closing this ticket.
Thank you for your understanding.
