### ISSUE TITLE
Android module containing tests only

### ISSUE THREAD

**Issue by xni06** [jacoco/jacoco#647]
Thanks for the library - good work.

In modules where I have the traditional setup of sources in `src/main/java` and `src/test/java`, reports are successfully created

However, I have one setup where I have module `database` containing `src/main/java` while the `src/test/java` tests are contained in a separate module, `database-test`. When the report is generated, `database` shows no coverage which is sort of expected as the tests are contained in a different module. 

Is there a way to get the report to show the true coverage?

**Comment by marchof** [comment]
@xni06 Hi, thanks for your feedback! As you might have seen in the bug template you deleted when you submitted this issue have a mailing list for questions:

> This is a issue tracker. Please use our mailing list for general questions: 
> https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please have a look at the [report-aggregate](http://www.jacoco.org/jacoco/trunk/doc/report-aggregate-mojo.html) goal for your case. The JaCoCo project itself has the same setup as you described.

**Comment by Godin** [comment]
@marchof as he mentioned "Android", I guess that he is interested in Gradle example. @xni06 while we don't provide such in our documentation, you can find a lot of them and about this in internet. So before asking a question here or in mailing list, please do a bit of home work.

**Comment by xni06** [comment]
...or perhaps it would be better if I posted my comment against the correct repo instead! Sorry, but this comment was not supposed to be against this repo.
