### ISSUE TITLE
[Question/Feature request] Is there a way to configure jacoco in external file?

### ISSUE THREAD

**Issue by CyborTronik** [jacoco/jacoco#651]
Would be nice to keep all jacoco configuration in a separate file like happens for loggers (ex: log4j.xml,  logback.xml/yaml )
Is there a way to achieve that ?

**Comment by marchof** [comment]
log4j.xml etc. are runtime configurations. JaCoCo is a tool which integrates in Maven, Ant etc and uses the respective configuration mechanisms. Only in case of offline instrumentation the JaCoCo runtime configuration can be provided in a separate property file. See [documentation](http://www.jacoco.org/jacoco/trunk/doc/offline.html).

@CyborTronik Please use our mailing list for general questions.

**Comment by Godin** [comment]
In addition to what was said by @marchof : Maven properties can be read from external file for example using http://www.mojohaus.org/properties-maven-plugin/ - see https://github.com/jacoco/jacoco/issues/628#issuecomment-349449352 , Ant properties also can be read from external file.
