### ISSUE TITLE
Is there anyway to exclude springCGLIB classes in coverage report

### ISSUE THREAD

**Issue by xunwu** [jacoco/jacoco#655]
I used jacoco on the fly to generate coverage data for function test

JaCoCo version: 0.8.0
Operating system: MacOS
Tool integration: Maven

For example:
I have a class 
TimeseriesQueryController..EnhancerBySpringCGLIB..eb356a5c
and 
TimeseriesQueryController

### Expected behaviour
Exclude class generated by SpringCGLIB

### Actual behaviour
Included all the classes from EnhancerBySpringCGLIB

**Comment by marchof** [comment]
Our issue template says:

> This is a issue tracker. Please use our mailing list for general questions: 
> https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also you may want to check our documentation for the Maven report goal:

http://www.jacoco.org/jacoco/trunk/doc/report-mojo.html

Here you will find a `exclude` property to exclude class files by name e.g. (`*EnhancerBySpringCGLIB*`)
