### ISSUE TITLE
jacoco 0.7.9 -> Unable to extract agent jar

### ISSUE THREAD

**Issue by Vazzilena** [jacoco/jacoco#665]
Hey,

Our jacoco configuration is trough ANT:

```
      <mkdir dir="@{category}"/>
      <jacoco:coverage destfile="@{category}/jacoco.exec" append="true">
        <junit showoutput="true" printsummary="yes" fork="${fork.option}" maxmemory="1024M"
          dir="@{category}">
          <formatter type="xml"/>
          <jvmarg line="${jvm.args}"/>
          <jvmarg value="-DLOGLEVEL=${log.level}"/>
          <jvmarg value="-DTESTLOGLEVEL=${test.log.level}"/>
          <jvmarg value="-DEnableDebug=${debug.flag}"/>
          <jvmarg value="-DLICENSE_DIR=@{license.directory}"/>
          <jvmarg value="-DLICENCE_FILE=@{license.file}"/>
          <jvmarg value="-DJUnitBasePort=${junit.base.port}"/>
          <jvmarg
            value="-Dnirvana.test.server.classpath_extra=@{um.server.classpath}${path.separator}@{extra.classpath}"/>
          <jvmarg value="-Dnirvana.test.server.classpath_nostd=yes"/>
          <jvmarg value="-Dnirvana.test.requiredCategories=@{category}"/>
          <jvmarg value="-DGETCOVERAGE=${server.code.coverage.option}"/>
          <jvmarg value="-DJACOCO_PATH=${jacocoagent.location}"/>
          <classpath>
            <pathelement path="@{classpath}"/>
            <pathelement path="@{um.server.classpath}"/>
          </classpath>
          <test name="@{suite}" todir="${basedir}/@{category}"/>
        </junit>
      </jacoco:coverage>
```

Every now and then I get exception like this one during remote execution:

```
19:06:13     [mkdir] Created dir: C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\com.pcbsys.nirvana.junit.categories.TestClassifier.PromotionUnitTest
19:06:13 [jacoco:coverage] Enhancing junit with coverage
19:06:14 
19:06:14 BUILD FAILED
19:06:14 C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\build_Promotion_Copy.xml:443: The following error occurred while executing this line:
19:06:14 C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\build_Promotion_Copy.xml:665: The following error occurred while executing this line:
19:06:14 C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\build_Promotion_Copy.xml:670: The following error occurred while executing this line:
19:06:14 C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\build_Promotion_Copy.xml:734: **Unable to extract agent jar**
```

Looking at the code, I am thinking the exception is thrown by AbstractCoverageTask:

http://www.eclemma.org/jacoco/trunk/coverage/org.jacoco.ant/org.jacoco.ant/AbstractCoverageTask.java.html

I don't see any reason for this exception. Can you please help?

**Comment by marchof** [comment]
Hi, 

can you please provide the full stack trace of the failure (run Ant with
-v option). 

Regards,
-marc 

On 2018-03-26 20:52, Vazzilena wrote:

> Hey, 
> 
> Our jacoco configuration is trough ANT:
> 
> <mkdir dir="@{category}"/>
> <jacoco:coverage destfile="@{category}/jacoco.exec" append="true">
> <junit showoutput="true" printsummary="yes" fork="${fork.option}" maxmemory="1024M"
> dir="@{category}">
> <formatter type="xml"/>
> <jvmarg line="${jvm.args}"/>
> <jvmarg value="-DLOGLEVEL=${log.level}"/>
> <jvmarg value="-DTESTLOGLEVEL=${test.log.level}"/>
> <jvmarg value="-DEnableDebug=${debug.flag}"/>
> <jvmarg value="-DLICENSE_DIR=@{license.directory}"/>
> <jvmarg value="-DLICENCE_FILE=@{license.file}"/>
> <jvmarg value="-DJUnitBasePort=${junit.base.port}"/>
> <jvmarg
> value="-Dnirvana.test.server.classpath_extra=@{um.server.classpath}${path.separator}@{extra.classpath}"/>
> <jvmarg value="-Dnirvana.test.server.classpath_nostd=yes"/>
> <jvmarg value="-Dnirvana.test.requiredCategories=@{category}"/>
> <jvmarg value="-DGETCOVERAGE=${server.code.coverage.option}"/>
> <jvmarg value="-DJACOCO_PATH=${jacocoagent.location}"/>
> <classpath>
> <pathelement path="@{classpath}"/>
> <pathelement path="@{um.server.classpath}"/>
> </classpath>
> <test name="@{suite}" todir="${basedir}/@{category}"/>
> </junit>
> </jacoco:coverage>
> 
> Every now and then I get exception like this one during remote execution: 
> 
> 19:06:13 [mkdir] Created dir: C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\com.pcbsys.nirvana.junit.categories.TestClassifier.PromotionUnitTest
> 19:06:13 [jacoco:coverage] Enhancing junit with coverage
> 19:06:14
> 19:06:14 BUILD FAILED
> 19:06:14 C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\build_Promotion_Copy.xml:443: The following error occurred while executing this line:
> 19:06:14 C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\build_Promotion_Copy.xml:665: The following error occurred while executing this line:
> 19:06:14 C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\build_Promotion_Copy.xml:670: The following error occurred while executing this line:
> 19:06:14 C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\build_Promotion_Copy.xml:734: Unable to extract agent jar 
> 
> Looking at the code, I am thinking the exception is thrown by AbstractCoverageTask: 
> 
> http://www.eclemma.org/jacoco/trunk/coverage/org.jacoco.ant/org.jacoco.ant/AbstractCoverageTask.java.html 
> 
> I don't see any reason for this exception. Can you please help? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

  

Links:
------
[1] https://github.com/jacoco/jacoco/issues/665
[2]

**Comment by Vazzilena** [comment]
Here it is:

10:57:50 BUILD FAILED
10:57:50 C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\build_Promotion_Copy.xml:443: The following error occurred while executing this line:
10:57:50 C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\build_Promotion_Copy.xml:665: The following error occurred while executing this line:
10:57:50 C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\build_Promotion_Copy.xml:670: The following error occurred while executing this line:
10:57:50 C:\jenkins\workspace\10.2.S_release_test_admin_win\build\change-management\build_Promotion_Copy.xml:734: Unable to extract agent jar
10:57:50 	at org.jacoco.ant.AbstractCoverageTask.getAgentFile(AbstractCoverageTask.java:245)
10:57:50 	at org.jacoco.ant.AbstractCoverageTask.getLaunchingArgument(AbstractCoverageTask.java:220)
10:57:50 	at org.jacoco.ant.CoverageTask$JavaLikeTaskEnhancer.addJvmArgs(CoverageTask.java:161)
10:57:50 	at org.jacoco.ant.CoverageTask$JavaLikeTaskEnhancer.enhanceTask(CoverageTask.java:151)
10:57:50 	at org.jacoco.ant.CoverageTask.addTask(CoverageTask.java:75)
10:57:50 	at org.apache.tools.ant.UnknownElement.handleChildren(UnknownElement.java:367)
10:57:50 	at org.apache.tools.ant.UnknownElement.configure(UnknownElement.java:204)
10:57:50 	at org.apache.tools.ant.UnknownElement.maybeConfigure(UnknownElement.java:163)
10:57:50 	at org.apache.tools.ant.Task.perform(Task.java:347)
10:57:50 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
10:57:50 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
10:57:50 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
10:57:50 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:57:50 	at java.lang.reflect.Method.invoke(Method.java:498)
10:57:50 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
10:57:50 	at org.apache.tools.ant.Task.perform(Task.java:348)
10:57:50 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
10:57:50 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
10:57:50 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
10:57:50 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:57:50 	at java.lang.reflect.Method.invoke(Method.java:498)
10:57:50 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
10:57:50 	at org.apache.tools.ant.Task.perform(Task.java:348)
10:57:50 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
10:57:50 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
10:57:50 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
10:57:50 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:57:50 	at java.lang.reflect.Method.invoke(Method.java:498)
10:57:50 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
10:57:50 	at org.apache.tools.ant.Task.perform(Task.java:348)
10:57:50 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
10:57:50 	at net.sf.antcontrib.logic.ForTask.doSequentialIteration(ForTask.java:259)
10:57:50 	at net.sf.antcontrib.logic.ForTask.doToken(ForTask.java:268)
10:57:50 	at net.sf.antcontrib.logic.ForTask.doTheTasks(ForTask.java:299)
10:57:50 	at net.sf.antcontrib.logic.ForTask.execute(ForTask.java:244)
10:57:50 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
10:57:50 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
10:57:50 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:57:50 	at java.lang.reflect.Method.invoke(Method.java:498)
10:57:50 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
10:57:50 	at org.apache.tools.ant.Task.perform(Task.java:348)
10:57:50 	at org.apache.tools.ant.Target.execute(Target.java:435)
10:57:50 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
10:57:50 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
10:57:50 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
10:57:50 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
10:57:50 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
10:57:50 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
10:57:50 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
10:57:50 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
10:57:50 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:57:50 	at java.lang.reflect.Method.invoke(Method.java:498)
10:57:50 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
10:57:50 	at org.apache.tools.ant.Task.perform(Task.java:348)
10:57:50 	at org.apache.tools.ant.Target.execute(Target.java:435)
10:57:50 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
10:57:50 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
10:57:50 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
10:57:50 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
10:57:50 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
10:57:50 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
10:57:50 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
10:57:50 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
10:57:50 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
10:57:50 Caused by: java.io.IOException: The system cannot find the path specified
10:57:50 	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
10:57:50 	at java.io.File.createTempFile(File.java:2024)
10:57:50 	at java.io.File.createTempFile(File.java:2070)
10:57:50 	at org.jacoco.agent.AgentJar.extractToTempLocation(AgentJar.java:74)
10:57:50 	at org.jacoco.ant.AbstractCoverageTask.getAgentFile(AbstractCoverageTask.java:238)
10:57:50 	... 63 more
10:57:50 
10:57:50 Total time: 8 seconds
10:57:50 Build step 'Invoke Ant' marked build as failure
10:57:51 Recording test results

**Comment by Vazzilena** [comment]
Where exactly is this temporary location? 
I see [Caused by: java.io.IOException: The system cannot find the path specified] - perhaps some path location issues?

**Comment by Godin** [comment]
@Vazzilena first of all - this is not a Q/A forum, as stated in template that was overlooked and removed while initially filling your question - for questions please use users mailing list. Please do so in future.

Secondly

> Where exactly is this temporary location?

This question has nothing to do with JaCoCo - according to [Javadoc of `java.io.File.createTempFile`](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#createTempFile(java.lang.String,%20java.lang.String,%20java.io.File)) :

> The default temporary-file directory is specified by the system property `java.io.tmpdir`. On UNIX systems the default value of this property is typically "/tmp" or "/var/tmp"; on Microsoft Windows systems it is typically "C:\\WINNT\\TEMP".

so we can't tell where it is exactly in your case.

**Comment by Vazzilena** [comment]
Okay, thanks for looking into this anyway.

I feel like the exception I see - [**Caused by: java.io.IOException: The system cannot find the path specified**] is some kind of issue and never attempted to use place this as Q/A forum…

The problem appears to be happening only on Jenkins Windows Slaves that are connected using SSH -> SSH seems to mess up variables like %TMP% and %TEMP% -> a workaround in my case was to pass in Jenkins slave configuration java.io.tmpdir=C:\Users\USER_NAME~1\AppData\Local\Temp\2

**Comment by Vazzilena** [comment]
Guys,
I am seeing this issue quite often and I honestly don’t understand it. 
The environment setting that we have on the failing machine is: 
java.io.tmpdir=C\:\\Users\\NIRDEV~1\\AppData\\Local\\Temp\\2\\

This directory is valid, it exists and there are already a couple of files in it (created by different applications - C:\Users\nirdevadm\AppData\Local\Temp\2).
When I manually try to create a file in that location (using the same user with same access level) – there are no issues. 
I cannot overwrite the java.io.tmpdir property everywhere in the environment as that will affect lots of other applications. Is there a workaround? 
[full_output.txt](https://github.com/jacoco/jacoco/files/2108845/full_output.txt)

**Comment by marchof** [comment]
@Vazzilena You need to fix your environment. Make sure the service running Jenkins has write access to the given directory. Also you can configure a different value for java.io.temp in Jenkins only for this specific job.

Please use our mailing list instead of posting on closed issues.
