### ISSUE TITLE
Jacoco issue with scr.felix @Reference annotation

### ISSUE THREAD

**Issue by manisha3688** [jacoco/jacoco#666]
Issue- 
For properties using felix @Reference tag, the code coverage report is including bind and unbind methods of the annotation which cannot be tested.
Expected Behaviour - Not to include methods associated with annotations which are not part of the class methods, in the trst coverage report similar to how it behaves in corbetura or atleast provide filter to exclude them.
Jacoco - version 0.8.0
Replication-In a java class, have any property annotated with @Reference class of  org.apache.felix.scr.annotations package and include maven-scr-plugin in pom.xml.

**Comment by marchof** [comment]
@manisha3688 JaCoCo works on Java class files. It cannot distinguish between you code and generated code. Unless the generator marks the generated method with a annotation as such (retention class or runtime required).

We have filters for Lombok (#513) and Groovy (#610).

Please check with the Apache Felix project to create such annotation.
