### ISSUE TITLE
JUnit5 junitlauncher ant task.

### ISSUE THREAD

**Issue by gaurangparmar** [jacoco/jacoco#673]
Hello Team,

Ant 1.10.3 introduces initial support for JUnit5 in the form of the junitlauncher task. Required JUnit5 junitlauncher ant task support to generate jacoco exec file so we can submit to Sonar for code coverage.

Ant Doc: https://ant.apache.org/manual/Tasks/junitlauncher.html

**Comment by Godin** [comment]
As per http://www.jacoco.org/jacoco/trunk/doc/ant.html :

> If the `coverage` task is not suitable for your launch target, you might alternatively use the `agent` task to create the Java agent parameter.

Have you tried this?

**Comment by gaurangparmar** [comment]
Current 1.10.3 seems to be does not support fork and/or additional VM arguments so it seems to be difficult to run jacoco in ant script. So I will try to use jacocoagent in ANT_OPTS or JAVA_OPTS as of now.

From Ant release notes - "Ant 1.10.3 introduces initial support for JUnit5 in the form of the junitlauncher task. The new task is fully functional but currently lacks a few features like forking a new JVM for tests which will be added in upcoming releases."

**Comment by Godin** [comment]
There is also offline instrumentation (see task `jacoco:instrument`), but recommended way for code coverage analysis with JaCoCo is on-the-fly instrumentation using agent.

> Current 1.10.3 seems to be does not support fork

and in this case there is nothing what we can do to integrate agent - ask developers of Ant to bring support of fork. Thank you for your understanding.

**Comment by don-vip** [comment]
Support of fork is coming in a future release, see https://github.com/apache/ant/pull/67

**Comment by Godin** [comment]
@don-vip Thank you for notification. Since this is not released and you have an interest in this, why not checking whether it will support additional JVM arguments to specify agent (#673 (comment))? :wink: and if not - send feedback directly to Ant developers.

**Comment by don-vip** [comment]
Sure, I'll give it a try! :)

**Comment by dgeissl** [comment]
Support via `junitlauncher` seems to be planned for ant 1.10.6 (see tag on https://github.com/apache/ant/commit/7b29e8ff8643b6a0ebb6e53927544cb149c19c01)

**Comment by jaikiran** [comment]
FWIW - Apache Ant 1.10.6 has been released this week and it contains "fork" mode support for the junitlauncher task https://ant.apache.org/manual/Tasks/junitlauncher.html#fork. Please do give it a try and see if it solves the usecases with jacoco, in your projects.

**Comment by Godin** [comment]
Here is [example.zip](https://github.com/jacoco/jacoco/files/3264176/example.zip) that demonstrates usage of JaCoCo Ant Task `agent` and `fork` element of `junitlauncher` task introduced Ant 1.10.6.

So I propose to close this ticket, WDYT @marchof ?

**Comment by marchof** [comment]
@Godin We might add a hint to documentation or add an FAQ entry about this?

**Comment by Godin** [comment]
@marchof something else in addition to what we already have - see https://github.com/jacoco/jacoco/issues/673#issuecomment-381767119 ?

**Comment by marchof** [comment]
We can defer until we get specific questions in ML.

**Comment by marchof** [comment]
Ant 1.10.x depends on Java 8, while the baseline for JaCoCo is Java 5. So currently we cannot add implementation and tests for it without major hacks in our build. To manage expectations I close this with WONTFIX.
