### ISSUE TITLE
Test case using mockito shows no coverage in jacoco

### ISSUE THREAD

**Issue by jgwilson42** [jacoco/jacoco#676]
### Steps to reproduce

JaCoCo version: 0.8.1
Operating system: OS X High Sierra
Tool integration: Maven

Code available from: https://github.com/diffblue/java-demo/tree/coverageError

Command to generate Jacoco report: `mvn clean jacoco:prepare-agent test jacoco:report -Dmaven.test.failure.ignore=true`

Command to generate Cobertura report: `mvn cobertura:cobertura`

### Expected behaviour

The test case `com.diffblue.javademo.serveraccess.DatabaseDaoTest.DatabaseDao_connectToDb_000_98b085642685b7e2` should cover the methods `getInstance`, `connectToDb` and the constructor. This is 
shown in the cobertura report (attached).

[cobertura.zip](https://github.com/jacoco/jacoco/files/1928558/cobertura.zip)

### Actual behaviour

The jacoco report (attached) shows no coverage.

[jacoco-ut.zip](https://github.com/jacoco/jacoco/files/1928559/jacoco-ut.zip)

**Comment by Godin** [comment]
Seems that you use PowerMock, so please read https://github.com/powermock/powermock/wiki/Code-coverage-with-JaCoCo
