### ISSUE TITLE
cover line number is not same with highlight line number in file

### ISSUE THREAD

**Issue by lillian87** [jacoco/jacoco#677]
![2018-04-23_15-08-36](https://user-images.githubusercontent.com/35125865/39111618-57a8c808-4708-11e8-8ce8-1ee04ea1a756.png)
![capture](https://user-images.githubusercontent.com/35125865/39111619-57eed640-4708-11e8-991a-22052fa7c8bd.PNG)

This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version:0.8.2
Operating system:Linux
Tool integration: Other

### Expected behaviour
cover line number is  same with highlight line number in file

### Actual behaviour
cover line number is not same with highlight line number in file

**Comment by marchof** [comment]
@lillian87 What exactly is your issue? Method getInputStream has 1 line of code source code which is also shown in the table.

**Comment by Godin** [comment]
@lillian87 column `Lines` shows **total number of lines**, column `Missed` shows number of not covered lines, therefore number of covered lines in method `getInputStream` is `1 - 0 = 1` and perfectly matches highlighting, information about other methods also matches highlighting.

**Comment by lillian87** [comment]
forget it, sorry for the mistake, I thought lines show the all line number for this file
