### ISSUE TITLE
How to use the filters 

### ISSUE THREAD

**Issue by lambiase1u** [jacoco/jacoco#678]
Hello guys,
I would like to understand better how to use the different [filters ](https://github.com/jacoco/jacoco/wiki/FilteringOptions) of jacoco. Because i try to put a rule to apply filters but it's seems is not woking. 

Please find below the rule  :
```xml
<rule>  
        <element>CLASS</element>  
               <excludes>  
                     <exclude>**/com/dexiabil/myservice/vo/*</exclude>  
                     <exclude>JAVAC.SYNTHCLASS</exclude>  
                     <exclude>JAVAC.SYNTHMETH</exclude>  
                </excludes>  
 </rule>   
```
The first package are not covered anymore but the filters not seem to be apply. 

Also i would like to know if it's possible to exclude only methods but for all the classes.
Something like this : 

```xml
<rule implementation="org.jacoco.maven.RuleConfiguration">
		<element>METHOD</element>
		<excludes>
			<exclude>get*</exclude>
			<exclude>set**</exclude>
			<exclude>equals*</exclude>
			<exclude>compare*</exclude>
			<exclude>hashCode*</exclude>
			<exclude>toString</exclude>
		</excludes>
</rule>
```
Could you let me know if  my understading of the tool is good  ?
Thank you in advances.

**Comment by marchof** [comment]
No, this is not how filters work.

If you study our bug template you find the place to ask questions.
