### ISSUE TITLE
Ignore javax.annotation.Generated

### ISSUE THREAD

**Issue by drekbour** [jacoco/jacoco#685]
Based on recent changes to ignore lombok.Generated, it should be evident that that (JDK standard) javax.annotation.Generated be handled identically.

**Comment by marchof** [comment]
This has been discussed here many time before. `javax.annotation.Generated` has retention `SOURCE`:

https://docs.oracle.com/javase/9/docs/api/javax/annotation/Generated.html

This means it is not available in class files and cannot be used ba JaCoCo -- which does not process source files.
