### ISSUE TITLE
Can't build when using Kotlin inline and crossinline functions that are in another module.

### ISSUE THREAD

**Issue by frankkubista** [jacoco/jacoco#688]
### Steps to reproduce
Create a base module that contains an inline function and a module the depends on the base module and use that inline function in the dependent module. Then try to do a build. 
./gradlew :app:assembleInternalDebug --stacktrace

```kotlin
inline fun EditText.onTextChange(crossinline onChange: (String) -> Unit): Disposable {
  val textWatcher = object : TextWatcher {
    override fun afterTextChanged(password: Editable?) {
    }

    override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {
    }

    override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
      onChange(s?.toString() ?: "")
    }
  }

  addTextChangedListener(textWatcher)

  return object : Disposable {
    @kotlin.jvm.Volatile
    override var isDisposed: Boolean = false
      private set

    override fun dispose() {
      removeTextChangedListener(textWatcher)
      isDisposed = true
    }
  }
}
```

JaCoCo version: 0.8.1
Operating system: macOs 10.13.3
Tool integration: Gradle

### Expected behaviour
The build should not fail.

### Actual behaviour
We have an inline function in our base module that works and builds fine when we only use it in the base module, but when we use that function in another module we get a build error. If we remove the inline keyword it builds fine in the base and dependent modules.

./gradlew :app:assembleInternalDebug --stacktrace

A failure occurred while executing com.android.build.gradle.internal.transforms.JacocoTransform$JacocoWorkerAction
Unable to instrument file with Jacoco: /Users/xxx/workspace/xxx/features/xxx/build/tmp/kotlin-classes/internalDebug/com/xxx/xxx/xxx/xxx/CustomView$onFinishInflate$$inlined$onTextChange$2.class

**Comment by Godin** [comment]
> Create a base module that

Could you please provide reproducer in a self-sufficient form, e.g. attach archive with all materials? or at least class file `CustomView$onFinishInflate$$inlined$onTextChange$2.class`? full stack trace? This will definitely speed up investigations. Thanks.

**Comment by frankkubista** [comment]
Attached is a sample app that reproduces the issue and the full stack trace. If you run ./gradlew :app:assembleDebug --stacktrace you will get the build error.

[TestApplication.zip](https://github.com/jacoco/jacoco/files/2068471/TestApplication.zip)

[Jacoco stacktrace.txt](https://github.com/jacoco/jacoco/files/2068482/Jacoco.stacktrace.txt)

**Comment by marchof** [comment]
Thanks for the full stack trace! Here is the problem:

    Class com/example/frankkubista/testapplication/feature/MainActivity$onCreate$$inlined$onTextChange$1 is already instrumented.

Looks like your build tries to instrument a class which has already been instrumented before. This is not supported by JaCoCo. Please report this to Grade/Kotlin. Nothing that we can do here at the JaCoCo project.

**Comment by ScottPierce** [comment]
@marchof For clarification, what do you mean that it's already been instrumented before?

**Comment by Godin** [comment]
A little addition to what @marchof said - as you can see from error message an attempt to instrument already instrumented class is triggered by **Gradle Android Plugin** :

```
> There was a failure while executing work items
   > A failure occurred while executing com.android.build.gradle.internal.transforms.JacocoTransform$JacocoWorkerAction
```

@ScottPierce instrumentation - is a process of modification of classes that enables recording of coverage information

**Comment by lukaville** [comment]
Copied the issue to Google bug tracker https://issuetracker.google.com/issues/110763361
