### ISSUE TITLE
Use SPI for method filters

### ISSUE THREAD

**Issue by remal** [jacoco/jacoco#697]
Method filters list is not extensible right now. It's defined in `Filters.ALL`. Please use `java.util
.ServiceLoader` to load filters.

**Comment by andrioli** [comment]
I suggested it some time ago (see: https://github.com/jacoco/jacoco/issues/14#issuecomment-254070564). Also, note that ServiceLoader is only available to Java >= 6 and JaCoCo still support Java 5

**Comment by marchof** [comment]
We're not yet there to publish an stable API for filtering. It is still changing as we add new filters. In this process we should learn how a future API might look like. Some improvements have been made by adding `IFilterContext` in 281538b.

As a first step we can provide a internal API to add filters for experimental usage.

As the final step we need to find a way how custom filter code can be added in our various integrations.

I leave this issue open for future activity.

**Comment by marchof** [comment]
@remal Do you have a requirement for a specific filter which is missing right now?

**Comment by remal** [comment]
@marchof I'd like to filter-out methods using my own annotation. I couldn't manage to find out if Jacoco provides a Maven artifact with such annotation...

**Comment by remal** [comment]
@marchof I understand your point, but for a better code readability sometimes it's better to use another annotation, not "Generated". Please consider implementing it.

**Comment by szhem** [comment]
@marchof, @remal, @andrioli  found this issue after just raising a corresponding PR-s for java 5+ (#847) and java 6+ (#846)

**Comment by marchof** [comment]
We decided not to support filtering SPI. We don't think we can handle the amount of support requests we end up here when people start using custom filters which are created by 3rd parties and something goes wrong.
