### ISSUE TITLE
MethodAnalyzer constructor is now at package visibility

### ISSUE THREAD

**Issue by dbhatte** [jacoco/jacoco#698]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html
The commit https://github.com/jacoco/jacoco/commit/1962cf59bc403a27f68c55b39bb833b00fa386a0#diff-3e9be84b8e6db90bab251bbb404fef07R94
made MethodAnalyzer constructor is now at package level visibility.
This causes the sbt-jacoco to break.
Can you please make it public again if it is not too much of a hassle?

### Steps to reproduce

JaCoCo version: 0.8.0
Operating system: Mac HighSierra
Tool integration: SBT/Play Framework

**Comment by Godin** [comment]
I have temptation to reject this request, because `org.jacoco.core.internal.analysis.MethodAnalyzer` is clearly in internal package and never been part of JaCoCo APIs.

**Comment by marchof** [comment]
@dbhatte This is clearly internal packages and we will not manage compatibility on internal packages. Just recently we had more changes with this constructor.

Please never ever rely on internal classes. Instead please ask for a feature request ("We need an public API so we can do X").
