### ISSUE TITLE
JaCoCo Command Line Interface (CLI) Report generation leads to: Caused by: java.lang.IllegalStateException: Class $CLASS is already instrumented

### ISSUE THREAD

**Issue by ncimino** [jacoco/jacoco#700]
### Steps to reproduce

JaCoCo version: 0.8.1
Operating system: Windows 10
Tool integration: CLI

I'm using JUnit to test my code and to access private methods/fields I use reflection which doesn't play well with JaCoCo on-the-fly instrumentation; Therefore, I started doing the off-line instrumentation.

I use the following command to perform the off-line instrumentation:

```
java.exe \
  -jar C:\jacoco\jacococli.jar \
  instrument \
  C:\project\main\main.jar \
  --dest C:\project\coverage
```

After that I end up with the instrumented JAR here:

- C:\project\coverage\main.jar

I then run my JUnit tests and on the classpath I provide:

```
C:\jacoco\jacocoagent.jar;C:\project\coverage\main.jar;...
```

This seems to work fine as I end up with the jacoco.exec file I expect.

### Actual behaviour

When I try to generate a report for this jacoco.exec file using:

```
java.exe \
  -jar C:\jacoco\jacococli.jar \
  report \
  C:\project\coverage\jacoco.exec \
  --classfiles C:\project\coverage\main.jar \
  --html C:\project\coverage\report
```

I then receive this error message:

```
Exception in thread "main" java.io.IOException: Error while analyzing C:\project\coverage\main.jar@my/package/MyClass.class.
        at org.jacoco.cli.internal.core.analysis.Analyzer.analyzerError(Analyzer.java:166)
        at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:138)
        at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:161)
        at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:197)
        at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeZip(Analyzer.java:269)
        at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:200)
        at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:230)
        at org.jacoco.cli.internal.commands.ClassInfo.execute(ClassInfo.java:58)
        at org.jacoco.cli.internal.Main.execute(Main.java:89)
        at org.jacoco.cli.internal.Main.main(Main.java:104)
Caused by: java.lang.IllegalStateException: Class my/package/MyClass is already instrumented.
        at org.jacoco.cli.internal.core.internal.instr.InstrSupport.assertNotInstrumented(InstrSupport.java:176)
        at org.jacoco.cli.internal.core.internal.analysis.ClassAnalyzer.visitField(ClassAnalyzer.java:85)
        at org.jacoco.cli.internal.asm.ClassVisitor.visitField(ClassVisitor.java:294)
        at org.jacoco.cli.internal.asm.ClassReader.readField(ClassReader.java:883)
        at org.jacoco.cli.internal.asm.ClassReader.accept(ClassReader.java:694)
        at org.jacoco.cli.internal.asm.ClassReader.accept(ClassReader.java:500)
        at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:120)
        at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:136)
        ... 8 more
````

Why, when I try to generate a report, do I get error messages about a class already being instrumented?

### Expected behaviour

I just found that I should be using the non-instrumented JAR for generating the report i.e.

```
java.exe \
  -jar C:\jacoco\jacococli.jar \
  report \
  C:\project\coverage\jacoco.exec \
  --classfiles C:\project\main\main.jar \
  --html C:\project\coverage\report
```

_Notice: The main\main.jar instead of the coverage\main.jar_

It would be nice if the report generation produced a better error message. Telling me that a class was already instrumented when I'm trying to generate a report isn't helping me identify the root cause.

**Comment by Godin** [comment]
> I'm using JUnit to test my code and to access private methods/fields I use reflection which doesn't play well with JaCoCo on-the-fly instrumentation; Therefore, I started doing the off-line instrumentation.

Reflection and on-the-fly instrumentation play very well together. In both cases independently from the way of instrumentation (on-the-fly or offline) your code must ignore synthetic members as stated in our [FAQ](https://www.jacoco.org/jacoco/trunk/doc/faq.html) :

> My code uses reflection. Why does it fail when I execute it with JaCoCo?
>
> To collect execution data JaCoCo instruments the classes under test which adds two members to the classes: A private static field $jacocoData and a private static method $jacocoInit(). Both members are marked as synthetic.
>
> Please change your code to ignore synthetic members. This is a good practice anyways as also the Java compiler creates synthetic members in certain situation.

And we strongly do not recommend usage of offline instrumentation due to various reasons, one of which being complexity of a setup compared to on-the-fly instrumentation, and offline instrumentation is not needed in 99% of cases.

---

> Why, when I try to generate a report, do I get error messages about a class already being instrumented?

As you already correctly understood - this message indicates attempt to generate report using instrumented classes, while it requires original non-instrumented classes. Message indeed can be improved.

**Comment by marchof** [comment]
@Godin What is your proposal for to improve the message? We use the same assertion for intsrumentation and analysis. Maybe something like:

> Cannot process instrumented class X. Please supply original class files.

**Comment by Godin** [comment]
@marchof either different messages for instrumentation and analysis, or indeed single message that suits both - slightly modified variant of your proposal:
`Cannot process instrumented class X. Please supply original non-instrumented classes.`

**Comment by ncimino** [comment]
Yes I think this message would've helped me sort the issue out much faster.

@Godin Thanks for the info about synthetic members!!

**Comment by Godin** [comment]
I'm closing this ticket since message was changed by #703

**Comment by NaseemAd** [comment]
Can you please mention how to point to original non-instrumentated classes in the offline instrumentation of Jacoco. I am using PowerMock for partial mocking and so I have to use the offline instrumentation.

**Comment by Godin** [comment]
@NaseemAd first of all this is not a Q/A forum, so please stop writing questions in unrelated tickets. There is Users Mailing list for questions - https://groups.google.com/forum/?fromgroups=#!forum/jacoco

In case of CLI simply use separate directories to preserve original classes:

```
java -jar jacococli.jar instrument \
    dir_with_original_classes \
    --dest dir_with_instrumented_classes

java -jar jacococli.jar report \
    jacoco.exec \
    --classfiles dir_with_original_classes \
    --html dir_with_report
```

Same in case of Ant:

```
<jacoco:instrument destdir="dir_with_instrumented_classes">
    <fileset dir="dir_with_original_classes" includes="**/*.class"/>
</jacoco:instrument>
```

In case of Maven use `restore-instrumented-classes` https://www.jacoco.org/jacoco/trunk/doc/restore-instrumented-classes-mojo.html
