### ISSUE TITLE
Matching classes with source files from the XML report

### ISSUE THREAD

**Issue by gabriel-v** [jacoco/jacoco#701]
Here is an example JaCoCo XML report:

        <report name="example">
            <package name="org/example">
                <class name="org/example/AnotherTopLevelClass">
                    ...
                </class>
                <class name="org/example/Person">
                    ...
                </class>
                <sourcefile name="Person.java">
                    ...
                </sourcefile>
            </package>
            ...
        </report>

The file `Person.java` holds two classes: `Person` and `AnotherTopLevelClass`.

In this case, there is no way to link the class coverage information (the `<class/>` elements) with the file coverage information (the `<sourcefile/>` elements) for cases in which multiple top level classes are implemented in a single Java file.

This problem does not occur if each `.java` file has only one top class, because Java requires the public class and the name to have the same name.

Here is a report format that would solve the issue:

        <report name="example">
            <package name="org/example">
                <sourcefile name="Person.java">
                    <class name="org/example/AnotherTopLevelClass">
                        ...
                    </class>
                    <class name="org/example/Person">
                        ...
                    </class>
                    ...
                </sourcefile>
            </package>
            ...
        </report>

How would one link the `<class/>` and `<sourcefile/>` instances from the XML reports?

### Version details

JaCoCo version: 0.8.0
Operating system: Linux
Tool integration: Gradle

**Comment by marchof** [comment]
This is correct. In our API we have an attribute `sourceFileName` on class. Probably this would help in this situation.

**Comment by Godin** [comment]
As a remark: shouldn't be forgotten that structural changes in a XML report might break existing consumers of such reports.

**Comment by gabriel-v** [comment]
> As a remark: shouldn't be forgotten that structural changes in a XML report might break existing consumers of such reports.

I was only using the modified report structure to get the point across.

>  In our API we have an attribute `sourceFileName` on class.

Yes, that would solve the issue. Is this already implemented in the 0.8.1 release?

**Comment by gabriel-v** [comment]
I don't see the `sourceFileName` attribute in [the dtd for the xml report](https://github.com/jacoco/jacoco/blob/b9d1b54e300318b470d9fedccc69d75187016444/org.jacoco.report/src/org/jacoco/report/xml/report.dtd#L44). Besides adding that, what are the other steps to implement this?

**Comment by Godin** [comment]
> > In our API we have an attribute sourceFileName on class.
>
> Is this already implemented in the 0.8.1 release?
>
> I don't see the sourceFileName attribute in the dtd for the xml report. Besides adding that, what are the other steps to implement this?

In API means in https://www.jacoco.org/jacoco/trunk/doc/api/org/jacoco/core/analysis/IClassCoverage.html#getSourceFileName()

This is available in Java API since a long time, but as far as I can see currently not written into XML report: https://github.com/jacoco/jacoco/blob/v0.8.1/org.jacoco.report/src/org/jacoco/report/internal/xml/XMLCoverageWriter.java#L83-L90
and maybe should be written.

All the code and documentation are publicly available, more exact explanation of "steps to implement this" IMO are equivalent to actually doing them.

**Comment by gabriel-v** [comment]
Thank you for the details. That was the best explanation I could have asked for.

**Comment by marchof** [comment]
@Godin Regarding compatibility: I would pump the schema version to 1.1, so existing consumers who do schema validation can see the difference. Anyhow the new attribute will be optional, as this can only provided for classes complied with schema information.

**Comment by Godin** [comment]
@marchof my comment was about initial proposal, addition of attribute is indeed more safe.
