### ISSUE TITLE
Allow to filter methods from coverage which are below a certain complexity

### ISSUE THREAD

**Issue by kwin** [jacoco/jacoco#728]
Similar to what is possible with Atlassian Clover with the `maxComplexity`, jacoco should allow to filter out methods which do not exceed a certain complexity from the coverage calculation.

**Comment by Godin** [comment]
In short/mid term plan we do not plan to add more options into configuration, especially that you already can use [JaCoCo APIs](https://www.jacoco.org/jacoco/trunk/doc/api/index.html) for generation of your own report or simply extract this information from XML report. Thank you for your understanding.
