### ISSUE TITLE
Support for JDK 1.8.0

### ISSUE THREAD

**Issue by szegedi** [jacoco/jacoco#74]
### Status Overview

Latest snapshot build: [Snapshot Repository](https://oss.sonatype.org/content/repositories/snapshots/org/jacoco/jacoco/0.7.0-beta-SNAPSHOT/)
#### [x] ASM5: Release Required

We need a new ASM version which supports class file version 52.0. ASM 5.0_BETA is released to Maven central repo.
- [ASM Bug 316481](http://forge.ow2.org/tracker/?func=detail&atid=100023&aid=316481&group_id=23) (fixed)
#### [x] Adjust JaCoCo to new ASM APIs: Done

JaCoCo needs to be adjusted to ASM5 APIs. This has been done on a experimental branch.
#### [x] Select proper runtime implementation: Done

The ModifiedSystemClassRuntime does not work any more with JRE 8. So an alternative Runtime has to be selected. The UrlStreamHandlerRuntime seems to do the job.
#### [x] Maven JavaDoc: Workaround

With JDK 8 JavaDoc generated by Maven fails to compile due to Lint checks. As a workaround we can disable this check for the Maven plugin.
- JaCoCo #83
- [Maven Plugin Tools Bug 244](http://jira.codehaus.org/browse/MPLUGIN-244)
#### [x] Invalid Line Numbers: Fixed with JDK Build 103

The JDK 8 compiler missed line number information in certain cases which makes our integration tests fail (and also leads to wrong line coverage results).
- [Bug JDK-8020689](http://bugs.sun.com/view_bug.do?bug_id=8020689)

**Comment by cogmission** [comment]
Still now working... Are you guys going to ever fix this?  (not being snarky - but really wondering?)

**Comment by Godin** [comment]
@cogmission Latest versions of JaCoCo do support Java 8. The first version with Java 8 support (0.7.0) has been released more than year ago. If you have a problem, then please start a discussion in Users Mailing List - see http://www.eclemma.org/jacoco/trunk/doc/support.html

**Comment by cogmission** [comment]
@godin Been there, been ignored by that... :-)
See: https://groups.google.com/forum/#!searchin/jacoco/coveralls/jacoco/gWhgsmaz_hI/3CmyybfSBAAJ

**Comment by Godin** [comment]
@cogmission Answered there. For the record - seems completely unrelated to Java 8.
