### ISSUE TITLE
Weird coverage behavior with Kotlin .trim()

### ISSUE THREAD

**Issue by bootstraponline** [jacoco/jacoco#754]
### Steps to reproduce

JaCoCo version: 0.8.2
Operating system: macOS High Sierra 10.13.6
Tool integration: Gradle

Run JaCoCo using gradle on this Kotlin code:

```kotlin
    fun returnString(): String {
        return "string"
    }

    fun coverage1() {
        returnString().trim()
    }

    fun coverage2() {
        returnString()
    }
```

Here's the code for Kotlin's `trim()` method:
```kotlin
/**
 * Returns a string having leading and trailing whitespace removed.
 */
@kotlin.internal.InlineOnly
public inline fun String.trim(): String = (this as CharSequence).trim().toString()

```

### Expected behaviour
I expect the line to be fully covered when using Kotlin `.trim()`

### Actual behaviour

<img width="275" alt="screen shot 2018-09-07 at 2 34 52 pm" src="https://user-images.githubusercontent.com/1173057/45236914-43b6b800-b2ab-11e8-9d57-a4c73c572c96.png">

**Comment by bootstraponline** [comment]
Duplicate of https://github.com/jacoco/jacoco/issues/654

**Comment by Godin** [comment]
There are two independent aspects: first one - is that bytecode of `trim` is inlined into `coverage1`, second one - is presence of `as` operator in implementation of `trim`.

Presence of branch generated by Kotlin compiler for `as` operator can be seen independently from inlining - compilation of

```
fun example() {
    returnString() as CharSequence
}
```

results in following bytecode

```
         0: aload_0
         1: invokevirtual #15                 // Method returnString:()Ljava/lang/String;
         4: dup
         5: ifnonnull     18
         8: new           #17                 // class kotlin/TypeCastException
        11: dup
        12: ldc           #19                 // String null cannot be cast to non-null type kotlin.CharSequence
        14: invokespecial #23                 // Method kotlin/TypeCastException."<init>":(Ljava/lang/String;)V
        17: athrow
        18: checkcast     #25                 // class java/lang/CharSequence
        21: pop
        22: return
```

which clearly contains branch at offset 5 and which is similar to bytecode of function `coverage1`:

```
         0: aload_0
         1: invokevirtual #15                 // Method returnString:()Ljava/lang/String;
         4: astore_1
         5: aload_1
         6: dup
         7: ifnonnull     20
        10: new           #17                 // class kotlin/TypeCastException
        13: dup
        14: ldc           #19                 // String null cannot be cast to non-null type kotlin.CharSequence
        16: invokespecial #23                 // Method kotlin/TypeCastException."<init>":(Ljava/lang/String;)V
        19: athrow
        20: checkcast     #25                 // class java/lang/CharSequence
        23: invokestatic  #31                 // Method kotlin/text/StringsKt.trim:(Ljava/lang/CharSequence;)Ljava/lang/CharSequence;
        26: invokevirtual #34                 // Method java/lang/Object.toString:()Ljava/lang/String;
        29: pop
        30: return
```

What is interesting here:
* https://kotlinlang.org/docs/reference/typecasts.html#unsafe-cast-operator states that `as` operator throws exception when its left-hand side is `null` and **right-hand side is a non-nullable type**
* return type of function `returnString` is non-nullable `String`

still null-check is not omitted. @goodwinnk @fabianishere do you have ideas or maybe know why is so?

Also what is interesting - is that in some cases null-checks are implemented via calls to intrinsic functions (`kotlin.jvm.internal.Intrinsics`) such as `checkExpressionValueIsNotNull` or `checkReturnedValueIsNotNull` or `checkParameterIsNotNull`, while in this case as like in case of `lateinit` - directly.

In any case maybe we can implement filter for bytecode that is generated for `as` operator similarly to filter for `lateinit` - [added a note to our filtering wish list](https://github.com/jacoco/jacoco/wiki/FilteringOptions/_compare/2d7cd2314b9202e22565ab21eee55e13ade7b6f4...d80516a9b8133ae8ea76713dea9af28047443061).

Should also be mentioned that coverage engine developed by JetBrains and embedded in IntelliJ IDEA also believes that line is partially covered:

![intellij](https://user-images.githubusercontent.com/138671/45240446-05d88480-b2e9-11e8-8238-19b58b2b5d8d.png)

**Comment by Janarthanam** [comment]
@bootstraponline This exact same issue also happens for `String.toByteArray()` as well. That method is also inlined and used `as` and generates byte code for `TypeCastException`. It will be nice to see this fixed.

**Comment by goodwinnk** [comment]
@Godin Thank you for the great analysis and mentioning. I have created https://youtrack.jetbrains.com/issue/KT-27427 issue about unneeded null-check.
