### ISSUE TITLE
Analyzer is not loading inner classes

### ISSUE THREAD

**Issue by javydreamercsw** [jacoco/jacoco#755]
### Steps to reproduce

JaCoCo version: 0.8.2
Operating system: Mac
Tool integration: API

Having a class with inner classes does show in the JaCoCo report but it's not extracted with the analyzer.

### Expected behaviour
When analyzing AnylizerTest there most be entries for BrokenInputStream and EmptyStructureVisitor.

### Actual behaviour
Only AnylizerTest shows.

**Comment by marchof** [comment]
@javydreamercsw Please provide an executable reproducer how you use the JaCoCo API. JaCoCo does consider inner classes if used correctly, see for Example `Var`and `Fix`in class `LineImpl`:

https://www.jacoco.org/jacoco/trunk/coverage/org.jacoco.core/org.jacoco.core.internal.analysis/LineImpl.java.html

Please note that inner classes are separate class files. You need to feed them to the `Analyzer` to show up in the report.

**Comment by Godin** [comment]
Report is always constructed with use of `Analyzer`, therefore statements

> class with inner classes does show in the JaCoCo report
> but it's not extracted with the analyzer

contradict each other.

> When analyzing AnylizerTest there most be entries for BrokenInputStream and EmptyStructureVisitor.

No - when analyzing single class-file, only this class-file must and is analyzed by design.

**Comment by javydreamercsw** [comment]
They do show in the report but not when I'm trying to retrieve via the API. I was expecting them to show when analyzing a class file but they don't show up.

```
private List<IClassCoverage> getJacocoCoverageData(ExecutionDataStore execDataStore,
          String classFile) throws IOException
  {
    List<IClassCoverage> result = new ArrayList<>();
    logger.debug("Processing coverage for class: " + classFile);
    final CoverageBuilder coverageBuilder = new CoverageBuilder();
    final Analyzer analyzer = new Analyzer(execDataStore, coverageBuilder);
    File file = new File(this.workspaceRoot, classFile);
    logger.debug("Analyzing coverage in: " + file);
    if (file.exists())
    {
      try (FileInputStream fis = new FileInputStream(file))
      {
        analyzer.analyzeClass(fis, file.getAbsolutePath());
      }
      Iterator<IClassCoverage> it = coverageBuilder.getClasses().iterator();
      while (it.hasNext())
      {
        IClassCoverage next = it.next();
        logger.info(next.getName());
        result.add(next);
      }
    }
    return result;
  }
```

**Comment by javydreamercsw** [comment]
So how do I extract the data from the inner classes?

**Comment by javydreamercsw** [comment]
What I meant is that the inner classes are not retrievable from CoverageBuilder#getClasses() when used as CoverageVisitor.

**Comment by marchof** [comment]
@javydreamercsw Inner classes are actually separate classes. Therefore there is a separate class file and `Analyzer` will create a separate `IClassCoverage` instance. In your code snippet you need to invoke `getJacocoCoverageData()` for the inner class to get its coverage.

The typical usage of `Analyzer` is to use one instance and supply all class files of a project to it. It even has methods to e.g. process a folder with all class files in it, or to process a JAR file with all classes in it.

**Comment by Godin** [comment]
And here is complete example:

compilation of `Outer.java`

```
class Outer {
  class Inner {
  }
}
```

results in two files

```
$ ls /tmp/jacoco
'Outer$Inner.class'   Outer.class   Outer.java
```

execution of

```
import org.jacoco.core.analysis.Analyzer;
import org.jacoco.core.analysis.CoverageBuilder;
import org.jacoco.core.data.ExecutionDataStore;

import java.io.File;
import java.io.IOException;

public class Example {

    public static void main(String[] args) throws IOException {
        ExecutionDataStore dataStore = new ExecutionDataStore();
        CoverageBuilder coverageBuilder = new CoverageBuilder();
        Analyzer analyzer = new Analyzer(dataStore, coverageBuilder);
        analyzer.analyzeAll(new File("/tmp/jacoco/Outer.class"));
        analyzer.analyzeAll(new File("/tmp/jacoco/Outer$Inner.class"));

        System.out.println(
                coverageBuilder.getClasses()
        );
        System.out.println(
                coverageBuilder.getSourceFiles()
        );
    }

}
```

produces

```
[Outer$Inner [CLASS], Outer [CLASS]]
[Outer.java [SOURCEFILE]]
```

as expected - there are two classes (named `Outer` and `Outer$Inner`) compiled from same source file.
