### ISSUE TITLE
ekstazi like feature in the junit tag

### ISSUE THREAD

**Issue by cosmoJFH** [jacoco/jacoco#758]
Every time I launch the ant target jacoco in my aplication, all the junit tests are executed. If I update one of them in order to improve the coverage, and I execute the  ant target jacoco, all the junit tests will be executed again, and not just the updated ones as I would need. Note that the execution of the junit tests takes a few hours. 

Is this feature available in the ant?
Could it be possible to regenerate the coverage for only the updated junit tests?

Thanks for the tool, it is simple amazing!!

**Comment by marchof** [comment]
@cosmoJFH I don't know whether this feature is available in Ant. You better ask at the Ant project.

And yes, JaCoCo can combine execution data from multiple runs (see `merge` task or `append` option.
