### ISSUE TITLE
Incorrect line and method coverage for maven multi module project 

### ISSUE THREAD

**Issue by Shriram-Freshworks** [jacoco/jacoco#759]
### Steps to reproduce

JaCoCo version: 0.8.2
Operating system: MacOS High Sierra 
Tool integration: Maven

I am using jenkins jacoco-plugin in order to generate code coverage report for my multi module maven project.

### Expected behaviour
Correct coverage should be show for all the Classes, methods, lines hit by unit test cases in the project.

### Actual behaviour
A lot of methods,lines which were hit in unit test cases are skipped during report generation and as a result we are getting very less code coverage than we actually expected.

**Comment by Godin** [comment]
As you can see in our documentation at page https://www.jacoco.org/jacoco/trunk/doc/integrations.html - Jenkins Plugin is not developed by us. In case of troubles with third-party integrations please contact corresponding providers. In case of Jenkins - https://github.com/jenkinsci/jacoco-plugin
