### ISSUE TITLE
Code Coverage not generated with Eclipse Photon and openJDK

### ISSUE THREAD

**Issue by szgy** [jacoco/jacoco#769]
### Configuration
Eclipse version:
Eclipse IDE for Java Developers

Version: Photon Release (4.8.0)
Build id: 20180619-1200

Java version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

JaCoCo version:
org.jacoco.core, Version: 0.8.1.v20180329-202 
Observation: the version delivered by eclipse

JUnit version
5 or 4 - issue appears on both Junit versions selected when the unit test is created.

### Steps to reproduce
1. Install fresh eclipse photon 
2. Add openJDK as default JDK version
3. Create a simple project with a simple unit test. for example: [coverageExperiment.zip](https://github.com/jacoco/jacoco/files/2487158/coverageExperiment.zip)
4. Run Coverage As -> JUnit Test (either on test file, either on project) 

### Expected behaviour
Coverage view appears in Eclipse with coverage data

### Actual behaviour
Received stack trace in console:
[exception.txt](https://github.com/jacoco/jacoco/files/2487150/exception.txt)

Eclipse messages in order acknowledged with OK:
No coverage data has been collected during this coverage session. Please do not terminate the Java process manually from Eclipse.
’org.eclipse.eclemma.internal.core.launching.AgentServer’ has encountered a problem. Error while dumping coverage data (code 5013).

### Observation
Same project generates coverage data on Jdk10

**Comment by Godin** [comment]
As per JaCoCo changelog ( https://www.jacoco.org/jacoco/trunk/doc/changes.html ) - support for Java 11 was added in version 0.8.2
And as per Eclipse EclEmma changelog ( https://www.eclemma.org/changes.html ) - it uses JaCoCo 0.8.2 starting from version 3.1.1
So either upgrade your EclEmma, or upgrade Eclipse from Photon to SimRel 2018‑09.

**Comment by marchof** [comment]
@Godin The error message is misleading. Aren't we suppressing the original exception here?

**Comment by Godin** [comment]
@marchof yes - as it always been `ModifiedSystemClassRuntime` hides original exception, because original exception happens inside transformer. Also AFAIR original exception from ASM is or at least was not very meaningful either. While maybe we can improve this, IMO anyway should be tracked separately from this ticket.

**Comment by marchof** [comment]
@Godin I was actually primarily referring to the JaCoCo message in the console. I'll try to understand why we loose the original exception.
