### ISSUE TITLE
Add filter for exhaustive switch-expression

### ISSUE THREAD

**Issue by Godin** [jacoco/jacoco#771]
Currently for exhaustive switch-expression ([JEP 361](https://openjdk.java.net/jeps/361))

```java
public class SwitchExpressionTarget {

	private enum E {
		TRUE, FALSE,
	}

	private static int target(E e) {
		return switch (e) {
			case TRUE -> 1;
			case FALSE -> 0;
		};
	}

	public static void main(String[] args) {
		target(E.TRUE);
		target(E.FALSE);
	}

}
```

with JDK 14 EA b29

```
$ java --version
openjdk version "14-ea" 2020-03-17
OpenJDK Runtime Environment (build 14-ea+29-1384)
OpenJDK 64-Bit Server VM (build 14-ea+29-1384, mixed mode, sharing)

$ javac --release 14 SwitchExpressionTarget.java

$ java -javaagent:jacoco-0.8.5/lib/jacocoagent.jar SwitchExpressionTarget 

$ java -jar jacoco-0.8.5/lib/jacococli.jar \
    report jacoco.exec \
    --classfiles SwitchExpressionTarget.class \
    --sourcefiles . \
    --html report
```

we produce

![report](https://user-images.githubusercontent.com/138671/47281473-91794c80-d5db-11e8-8c93-72024b4e25b0.png)

branch that throws `IncompatibleClassChangeError` should be filtered out

```
  private static int target(SwitchExpressionTarget$E);
    descriptor: (LSwitchExpressionTarget$E;)I
    flags: (0x000a) ACC_PRIVATE, ACC_STATIC
    Code:
      stack=2, locals=2, args_size=1
         0: getstatic     #2                  // Field SwitchExpressionTarget$1.$SwitchMap$SwitchExpressionTarget$E:[I
         3: aload_0
         4: invokevirtual #3                  // Method SwitchExpressionTarget$E.ordinal:()I
         7: iaload
         8: lookupswitch  { // 2
                       1: 36
                       2: 41
                 default: 46
            }
        36: iconst_1
        37: istore_1
        38: goto          54
        41: iconst_0
        42: istore_1
        43: goto          54
        46: new           #4                  // class java/lang/IncompatibleClassChangeError
        49: dup
        50: invokespecial #5                  // Method java/lang/IncompatibleClassChangeError."<init>":()V
        53: athrow
        54: iload_1
        55: ireturn
      LineNumberTable:
        line 8: 0
        line 9: 36
        line 10: 41
        line 8: 55
```

**Comment by Godin** [comment]
Note that the only difference in bytecode for

```
public class SwitchExpressionTarget {

    private enum E {
	TRUE, FALSE,
    }

    private static int target(E e) {
	return switch (e) {
	    case TRUE -> 1;
	    case FALSE -> 0;
	    default -> throw new IncompatibleClassChangeError();
	};
    }

    public static void main(String[] args) {
	target(E.TRUE);
	target(E.FALSE);
    }

}
```

is `LineNumberTable`.

**Comment by Godin** [comment]
Similarly in case of Pattern Matching for switch ([JEP 406](https://openjdk.java.net/jeps/406)) 

the only difference in bytecode for

```java
class Example {
	sealed interface S permits A, B {}
	final class A implements S {}
	final class B implements S {}

	int example(S s) {
		return switch (s) {
		case A a -> 0;
		case B b -> 1;
		default -> throw new IncompatibleClassChangeError();
		};
	}
}
```

and

```java
class Example {
	sealed interface S permits A, B {}
	final class A implements S {}
	final class B implements S {}

	int example(S s) {
		return switch (s) {
		case A a -> 0;
		case B b -> 1;
		};
	}
}
```

is `LineNumberTable`

diff between outputs of `javap -v -p Example.class`

```diff
         line 7: 0
         line 8: 44
         line 9: 54
-        line 10: 64
-        line 7: 72
+        line 7: 64
```

**Comment by sbrunov** [comment]
(Just for the record.)

Have just faced this issue with the **exhaustive** switch-expressions ([JEP 361: Switch Expressions](https://openjdk.java.net/jeps/361)).

# Environment
## Java
```
$ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Debian-1)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Debian-1, mixed mode, sharing)
```

## JaCoCo Maven plugin
```
<plugin>
    <groupId>org.jacoco</groupId>
    <artifactId>jacoco-maven-plugin</artifactId>
    <version>0.8.7</version>
</plugin>
```

Best regards,  
Sergey Brunov.

**Comment by narner90** [comment]
Are there any ways to omit the uncovered lines from an exhaustive switch-expression from the coverage report via configuration?

**Comment by marchof** [comment]
@narner90 As you can read from the status of this issue: It is **OPEN**. This means we're working on it. It is not yet implemented.

**Comment by ice1000** [comment]
@narner90 I saw a WIP branch https://github.com/jacoco/jacoco/tree/java17_jep406_switch_pattern_matching, so they are indeed working on it. The existence of the branch gives me some confidence that this feature is gonna be shipped one day...

**Comment by alexandrenavarro** [comment]
Hi, I had a lot of project where we forced test coverage to 100% and the only stuff we can't easily test is the switch on an enum.
Today we prefer to move to if / else (the easiest fix) just not to change our check to != 100% in the maven jacoco plugin.
So it should be great to have it.
Just for information, I discussed with some of your team mates on SonarQube at Devoxx France and told me to create the issue (I just commented the one you are already created).

**Comment by ekoutanov** [comment]
+1

**Comment by ice1000** [comment]
Why the comment is deleted?

**Comment by marchof** [comment]
@ice1000 What exactly is the value of a "+1" comment? Just use Github's thumbs-up function or contribute something for the solution.

**Comment by ice1000** [comment]
> @ice1000 What exactly is the value of a "+1" comment? Just use Github's thumbs-up function or contribute something for the solution.

I see. I didn't know it's a duplicate

**Comment by mreichenbach-igniti** [comment]
> Hi, I had a lot of project where we forced test coverage to 100% and the only stuff we can't easily test is the switch on an enum. Today we prefer to move to if / else (the easiest fix) just not to change our check to != 100% in the maven jacoco plugin. So it should be great to have it. Just for information, I discussed with some of your team mates on SonarQube at Devoxx France and told me to create the issue (I just commented the one you are already created).

I'm in the same situation now and it's sad to see, that this issue could not be solved in the last 4 years :disappointed:

**Comment by marchof** [comment]
@lolo101 This project is maintained by two people in their spare time. We well aware of the list of bugs and feature request. The more people waste our time with helpless comments the less we're motivated and have time for actual work. The only thing that would speed up things is a pair of helping hands to craft a clean and tested pull request and maybe even help with maintaince --- just dreaming.

**Comment by lolo101** [comment]
Hi @marchof 

I didn't mean to be offensive.

You're absolutely right about helpless comments, I'll try to improve my helpfulness :slightly_smiling_face: 

I cloned the repo and ran the tests and I'm quite surprised about the result since there is actually a test for exhaustive switch-expression : 
```java
public class SwitchExpressionsTarget {
	...
	private static void exhaustiveSwitchExpression(Stubs.Enum e) {

		nop(switch (e) { // assertExhaustiveSwitchExpression()
		case A -> i1(); // assertFullyCovered()
		case B -> i1(); // assertFullyCovered()
		case C -> i1(); // assertExhaustiveSwitchExpressionLastCase()
		}); // assertEmpty()

	}
}
```
and all test passed: 
```
$ mvn clean verify -P java19-bytecode
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for root 0.8.11-SNAPSHOT:
[INFO] 
[INFO] JaCoCo ............................................. SUCCESS [  1.373 s]
[INFO] JaCoCo :: Core ..................................... SUCCESS [  7.226 s]
[INFO] JaCoCo :: Report ................................... SUCCESS [  2.348 s]
[INFO] JaCoCo :: Agent RT ................................. SUCCESS [  0.751 s]
[INFO] JaCoCo :: Agent .................................... SUCCESS [  1.072 s]
[INFO] JaCoCo :: Ant ...................................... SUCCESS [  1.478 s]
[INFO] JaCoCo :: Command Line Interface ................... SUCCESS [  1.818 s]
[INFO] JaCoCo :: Examples ................................. SUCCESS [  1.291 s]
[INFO] JaCoCo :: Maven Plugin ............................. SUCCESS [  3.184 s]
[INFO] JaCoCo :: Tests .................................... SUCCESS [  0.058 s]
[INFO] JaCoCo :: Test :: Core ............................. SUCCESS [  2.826 s]
[INFO] JaCoCo :: Test :: Core :: Validation ............... SUCCESS [  0.046 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 5 ........ SUCCESS [  1.067 s]
[INFO] JaCoCo :: Test :: Core :: Validation Kotlin ........ SUCCESS [  5.639 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 7 ........ SUCCESS [  0.799 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 8 ........ SUCCESS [  0.770 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 14 ....... SUCCESS [  0.712 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 16 ....... SUCCESS [  0.669 s]
[INFO] JaCoCo :: Test :: Core :: Validation Groovy ........ SUCCESS [  1.978 s]
[INFO] JaCoCo :: Test :: Core :: Validation Scala ......... SUCCESS [  3.789 s]
[INFO] JaCoCo :: Test :: Report ........................... SUCCESS [  1.889 s]
[INFO] JaCoCo :: Test :: Agent RT ......................... SUCCESS [  4.200 s]
[INFO] JaCoCo :: Test :: Agent ............................ SUCCESS [  0.666 s]
[INFO] JaCoCo :: Test :: Ant .............................. SUCCESS [  6.197 s]
[INFO] JaCoCo :: Test :: Command Line Interface ........... SUCCESS [  2.103 s]
[INFO] JaCoCo :: Test :: Examples ......................... SUCCESS [  7.991 s]
[INFO] JaCoCo :: Test :: Maven Plugin ..................... SUCCESS [ 59.327 s]
[INFO] JaCoCo :: Documentation ............................ SUCCESS [  2.953 s]
[INFO] JaCoCo :: Distribution ............................. SUCCESS [  0.483 s]
[INFO] root ............................................... SUCCESS [  0.002 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:04 min
[INFO] Finished at: 2023-06-02T16:49:26+02:00
[INFO] ------------------------------------------------------------------------
```
I'm probably missing something here. I keep digging.

Keep up the good work :wink:

**Comment by marchof** [comment]
@lolo101 Thanks for picking this up! If you look at the assertion method in [SwitchExpressionsTest.java](https://github.com/jacoco/jacoco/blob/master/org.jacoco.core.test.validation.java14/src/org/jacoco/core/test/validation/java14/SwitchExpressionsTest.java) you see that some lines are always party covered (different lines, depending on the compiler). So the current test only asserts the status quo.

**Comment by lolo101** [comment]
Ok here is the strategy I have in mind: adding a filter for switches (`LOOKUPSWITCH` & `TABLESWITCH`), which select the **default label** that has **no** next instruction node of type `LINE`, and adds it to the `MethodCoverageCalculator`'s ignored list

I tested it with the OpenJDK compiler and it looks ok. However, my tests are not exhaustive yet.

Does it look right? What compilers should be tested?

**Comment by marchof** [comment]
@lolo101 If you create a PR we will automatically run the tests with all JDK compilers (Java 5 - Java 21) as well as ECJ compiler. Typically avoid manual testing.

Please note that also @Godin just jumped in here with #1472.

**Comment by Godin** [comment]
@lolo101 your approach seems correct to me - at least I don't see other way for JaCoCo to distinguish between exhaustive switch generated by compiled and non-exhaustive switch written by human, i.e. between

```
enum E { TRUE, FALSE }

int example(E e) {
  return switch (e) {
  case TRUE -> 1;
  case FALSE -> 0;
  };
}
```

and

```
enum E { TRUE, FALSE }

int example(E e) {
  return switch (e) {
  case TRUE -> 1;
  default -> throw new IncompatibleClassChangeError();
  };
}
```

In a few minutes I'll push my implementation of this approach - #1472

FYI our build is described at https://www.jacoco.org/jacoco/trunk/doc/build.html
and CI configuration is at https://github.com/jacoco/jacoco/blob/master/.azure-pipelines/azure-pipelines.yml

**Comment by mreichenbach-igniti** [comment]
thanks a lot for fixing this :heart: is there already a time planned when a new version will be released (which includes this fix)?

**Comment by Godin** [comment]
@mreichenbach-igniti See https://www.jacoco.org/jacoco/trunk/doc/faq.html

> ### When will feature X be released?
> **JaCoCo is maintained by volunteers in their free time. Since we cannot guarantee free capacity, we do not commit to particular release dates.** Typically, you can expect a couple of releases every year.
>
> In the [change log](https://www.jacoco.org/jacoco/trunk/doc/changes.html), you can see all features that have been implemented in master branch and will be available with the next release. And in the meantime you can test latest build of master branch ([Maven SNAPSHOT](https://www.jacoco.org/jacoco/trunk/doc/repo.html)) and provide feedback to us.
