### ISSUE TITLE
strange code coverage report 

### ISSUE THREAD

**Issue by daichuanfei** [jacoco/jacoco#775]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version:jacocoagent about 0.7(not sure)
Operating system:Linux version 2.6.32-431.20.3.el6.mt20161028.x86_64
Tool integration: API

### Expected behaviour
I find a strange phenomenon about jacoco when I do a api test.I am sure this api has been tested through some cases.The report shows some lines in the method is covered at the begining  and end,but the code line int the middle seems does not cover.(my English is poor,sorry)

### Actual behaviour
![image](https://user-images.githubusercontent.com/17944903/47493071-0620e500-d881-11e8-88b2-02314c320103.png)

**Comment by marchof** [comment]
@daichuanfei There was some work in JaCoCo 7.x versions to improve corner cases with exceptions.

Please upgrade to the latest version 0.8.2 and test again.

**Comment by daichuanfei** [comment]
> @daichuanfei There was some work in JaCoCo 7.x versions to improve corner cases with exceptions.
> 
> Please upgrade to the latest version 0.8.2 and test again.
is it compatible with jdk1.7 or jdk1.8?

**Comment by daichuanfei** [comment]
thanks,I am tyring

**Comment by daichuanfei** [comment]
![image](https://user-images.githubusercontent.com/17944903/47721809-e2e4a400-dc8b-11e8-870e-494abe015c29.png)
I replace old jacocoagent.jar with 0.8 ,but seem the jacoco start-up fail

**Comment by marchof** [comment]
You also need to upgrade JaCoCo in your entire system. Looks like you're still using a old version of JaCoCo in your custom tool (com.dp.auto...)

**Comment by daichuanfei** [comment]
yes,you are right! I have solved the proplem。Thank you very much!
