### ISSUE TITLE
failed to create a coverage report after executing"Runtime.getRuntime().halt(123)"

### ISSUE THREAD

**Issue by moalboaltaro** [jacoco/jacoco#777]
### Steps to reproduce

JaCoCo version: 3.1.1
Operating system: Windows 10
Tool integration: Eclipse

### Expected behaviour

a coverage report succesfully created

### Actual behaviour
after I execute following code on my eclipse
Runtime.getRuntime().halt(123);

no coverage report created with following error messages:
No coverage data has been collected during this coverage session.
Please do not terminate the java process manually from Eclipse.
'org.eclipse.eclemma.internal.core.launching.AgentServer' has encountered a problem.
Error while dumping coverage data(code 5013)

**Comment by marchof** [comment]
JaCoCo needs a proper JVM shutdown to write execution data. This is not the case if you enforce an termination. Use System.exit() instead.

https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#halt(int)
