### ISSUE TITLE
Fix MethodAnalyzerTest

### ISSUE THREAD

**Issue by Godin** [jacoco/jacoco#788]
`createTryCatchBlock` in `MethodAnalyzerTest` creates following bytecode

```
l1: aload         // line 1001
    invokevirtual
l2: goto l4
l3: astore        // line 1002
l4: return        // line 1003
```

with exception handler `l3` for `l1-l2`.

`probe[0]` is inserted before `goto` - execution status of `try` body
`probe[1]` is inserted after `astore` - execution status of exception handler
`probe[2]` is inserted before `return` - execution status of `return`

Test `try_catch_should_show_exception_handler_missed_when_probe_is_not_executed` that was added in ac25a3f5a9b40fdc95a6bdd830e2282146720313 :

https://github.com/jacoco/jacoco/blob/ac25a3f5a9b40fdc95a6bdd830e2282146720313/org.jacoco.core.test/src/org/jacoco/core/internal/analysis/MethodAnalyzerTest.java#L709-L717

Has following problems:

1. `probe[0] = true` twice
2. test name is inconsistent with assertion, because the only assertion about uncovered instruction - is about line `1003`, which is not start of exception handler

Moreover if dump is not taken in the middle of the method, then `probe[2]` can't be `false`
* when `probe[0]` is `true`, because `goto` can't throw
* when `probe[1]` is `true`, because there is no instructions between them

**Comment by marchof** [comment]
@Godin Since the refactoring in #744 I wonder about the scope of this unit tests: Filtering is not in scope of `MethodAnalyzer` any more and should be removed from this unit test. WDYT?

**Comment by Godin** [comment]
@marchof 

> Filtering is not in scope of MethodAnalyzer any more and should be removed from this unit test. WDYT?

Let's leave them for the time being.
