### ISSUE TITLE
This means no instrumented class has been loaded before.

### ISSUE THREAD

**Issue by mumianhua** [jacoco/jacoco#792]
Or to be more precise: No instrumented class has been loaded before by the same classloader than your code above.

_Originally posted by @marchof in https://github.com/jacoco/jacoco/issues/227#issuecomment-51005338_
hi, i just use jacoco offline mode  to create jacoco.ec file  in Android APK with ant. the classes are instrumented, and copy to another dir, besides,  jacocoagent.jar and instrumented class dir are both added on classpath, and i collect jacoco excution data with java inflection. but it turns out that jacoco agent not started, so i am really confused.  i do as follows:
in the build.xml , i add
<taskdef uri="antlib:org.jacoco.ant" resource="org/jacoco/ant/antlib.xml">
        <classpath path="libs/jacocoant.jar" />
        <classpath path="libs/jacocoagent.jar" />
        <classpath path="./libs/instrumentClass" />
    </taskdef>

<target name="instrument" xmlns:jacoco="antlib:org.jacoco.ant">
        
        <mkdir dir="./libs/instrumentClass"/>
        <jacoco:instrument destdir="./libs/instrumentClass">
            <fileset dir="${outdir-classes}" />
        </jacoco:instrument>
    </target>
*****the instrument target invoked after compile target***

********after test i collect execution data like this:********
out = new FileOutputStream(ecfilePath, false);
            Object agent = Class.forName("org.jacoco.agent.rt.RT")
                    .getMethod("getAgent")
                    .invoke(null);
            out.write((byte[]) agent.getClass().getMethod("getExecutionData", boolean.class)
                    .invoke(agent, false));

i am really grateful if you can help me !

**Comment by marchof** [comment]
???

Please try to formulate a understandable question on our user forum.
