### ISSUE TITLE
Class level @Generated annotation does not work for retentionPolicy CLASS

### ISSUE THREAD

**Issue by maikebertpsc** [jacoco/jacoco#797]
### Steps to reproduce

JaCoCo version: 0.8.2
Tool integration: Maven/SonarQube

### Expected behaviour

We created a @Generated annotation with retention policy CLASS:
```
@Target({ElementType.CONSTRUCTOR, ElementType.METHOD, ElementType.FIELD, ElementType.TYPE})
@Retention(RetentionPolicy.CLASS)
public @interface Generated {
    String by() default "";
}
```

SonarQube is working fine ignoring new methods for coverage annotated with that annotation.
We expect to have this working fine also when used on class level.

### Actual behaviour

But instead usage on class level is just ignored. All the lines are still reported to need coverage.

Even worse: When used on class and method level the method level annotation stops working also.

**Comment by Godin** [comment]
After execution of `mvn clean verify` on [example.zip](https://github.com/jacoco/jacoco/files/2668548/example.zip) JaCoCo report (`target/site/jacoco/index.html`) generated by our `jacoco-maven-plugin` is following

![1](https://user-images.githubusercontent.com/138671/49816927-3c51ef80-fd6f-11e8-9e94-3c829f503d65.png)

![2](https://user-images.githubusercontent.com/138671/49816942-44aa2a80-fd6f-11e8-962e-e4f48150ae7e.png)

And after removal of all `Generated` annotations is following

![3](https://user-images.githubusercontent.com/138671/49816973-5c81ae80-fd6f-11e8-8cdb-722e69ff5e50.png)

![4](https://user-images.githubusercontent.com/138671/49816988-64415300-fd6f-11e8-9242-083066e58540.png)

Thus as you can see from the above - JaCoCo performs filtering correctly and our `jacoco-maven-plugin` shows expected report.

As you can see in our documentation on page https://www.jacoco.org/jacoco/trunk/doc/integrations.html - integration with SonarQube is not developed by us. Questions about third-party integrations should be addressed to vendors of corresponding integrations.

**Comment by maikebertpsc** [comment]
Thanks Godin for having a look to my issue.

Your example is not about that case of having @Generated annotation on class level, right?

**Comment by Godin** [comment]
@maikebertpsc look at 3rd screenshot or download, unzip and you'll see that it includes all 3 cases - annotation at class level, annotation at method level and annotation at both levels.
