### ISSUE TITLE
Preserve empty IClassCoverage nodes in CoverageBuilder and in XML report

### ISSUE THREAD

**Issue by m-g-sonar** [jacoco/jacoco#806]
Hey all,

Integrations that consume XML reports are unable to distinguish between two reasons of classes and sources absence in the report

* does not contain executable lines (e.g. Java interfaces without default methods) or was filtered out (e.g. marked with `@Generated` annotation)
* was not analyzed at all

and therefore cannot inform user about last one.

This happens because of

https://github.com/jacoco/jacoco/blob/v0.8.2/org.jacoco.core/src/org/jacoco/core/analysis/CoverageBuilder.java#L101-L102

which was added a long time ago in version 0.3.2 by

https://github.com/jacoco/jacoco/commit/e47d22d5205ec826f82b3072289f56564a3f74d6

----

This is exactly what happens with both SonarQube integrations (one [that reads XML](https://github.com/SonarSource/sonar-jacoco) and another [that reads exec-file](https://github.com/SonarSource/sonar-java/tree/5.9.2.16552/java-jacoco)) - https://github.com/jacoco/jacoco/issues/797 : in absence of information for source file (in XML report in first case, `CoverageBuilder` in second), SonarQube assumes that it was not executed/analyzed and tries to estimate from syntax tree of source file its missed coverage, and this estimation is not consistent with filtering of `@Generated` by JaCoCo.

----

There are some workarounds for integrations that read exec-file - e.g. custom `ICoverageVisitor` that will track `IClassCoverage.getSourceFileName()` prior delegation to `CoverageBuilder`.

However there are doesn't seem to be any option for integrations that read only XML reports.

----

Could you please (re)consider preservation of empty `IClassCoverage` nodes in `CoverageBuilder` and in XML report, and skip them only when generating HTML ?

Cheers,
Michael

**Comment by marchof** [comment]
What about filtered methods? We also exclude them from the internal data structures, so will not be emitted in XML:

https://github.com/jacoco/jacoco/blob/master/org.jacoco.core/src/org/jacoco/core/internal/analysis/ClassAnalyzer.java#L116

**Comment by Godin** [comment]
@marchof this is about about ability

> to distinguish between two reasons of **classes and sources** absence in the report

not about methods.

**Comment by marchof** [comment]
Sure this request is about classes. My question was more about consistency in the implementation.

**Comment by Godin** [comment]
@m-g-sonar after end-to-end test of #817 , I realized that unfortunately this won't be enough 😞 because zero values are not saved ( https://github.com/SonarSource/sonarqube/blob/7.5/sonar-scanner-engine/src/main/java/org/sonar/scanner/sensor/DefaultSensorStorage.java#L487-L493 ) and hence estimation will take place ( https://github.com/SonarSource/sonarqube/blob/7.5/sonar-scanner-engine/src/main/java/org/sonar/scanner/source/ZeroCoverageSensor.java#L66 ).

**Comment by Godin** [comment]
@henryju thank you for creation of https://jira.sonarsource.com/browse/SONAR-11641

FYI end-to-end test of #817 passes after following modification in SonarQube

```diff
diff --git a/sonar-scanner-engine/src/main/java/org/sonar/scanner/sensor/DefaultSensorStorage.java b/sonar-scanner-engine/src/main/java/org/sonar/scanner/sensor/DefaultSensorStorage.java
index 68716b84f3..2599d3c90e 100644
@@ -487,7 +487,7 @@ public class DefaultSensorStorage implements SensorStorage {
   public void store(DefaultCoverage defaultCoverage) {
     DefaultInputFile inputFile = (DefaultInputFile) defaultCoverage.inputFile();
     inputFile.setPublished(true);
-    if (defaultCoverage.linesToCover() > 0) {
+    if (defaultCoverage.linesToCover() >= 0) {
       saveCoverageMetricInternal(inputFile, LINES_TO_COVER, new DefaultMeasure<Integer>().forMetric(LINES_TO_COVER).withValue(defaultCoverage.linesToCover()));
```

before

![before-1](https://user-images.githubusercontent.com/138671/51344555-33a0b780-1a99-11e9-8051-82d6672f2464.png)
![before-2](https://user-images.githubusercontent.com/138671/51344559-356a7b00-1a99-11e9-944f-f00f59361bef.png)
![before-3](https://user-images.githubusercontent.com/138671/51344565-37ccd500-1a99-11e9-847f-12043875c1fe.png)
![before-4](https://user-images.githubusercontent.com/138671/51344568-3a2f2f00-1a99-11e9-91af-87c004c64202.png)

and after

![after-1](https://user-images.githubusercontent.com/138671/51344574-3dc2b600-1a99-11e9-8170-5d054444c9e2.png)
![after-2](https://user-images.githubusercontent.com/138671/51344579-40bda680-1a99-11e9-8344-7ec90c693ee0.png)
![after-3](https://user-images.githubusercontent.com/138671/51344580-40bda680-1a99-11e9-8fb6-943a63433147.png)
![after-4](https://user-images.githubusercontent.com/138671/51344581-40bda680-1a99-11e9-9c05-12edf3318d7e.png)

as expected.

**Comment by m-g-sonar** [comment]
Wow, that's nice! So it means that changes are not necessarily required immediately on SonarJava side (reading exec reports), as SonarQube will be able to read XML format better. In such context, maybe we can start thinking about deprecating the exec reader on the SonarQube Java plugin.

Nice job! :+1:

**Comment by Godin** [comment]
@m-g-sonar as far as I can see this is not just about XML and this has exact same positive impact also in case of `exec` - empty `ISourceFileCoverage` nodes are preserved by `CoverageBuilder`, so that https://github.com/SonarSource/sonar-java/blob/5.10.1.16922/java-jacoco/src/main/java/org/sonar/plugins/jacoco/UnitTestAnalyzer.java#L128-L133 saves zero values.

In any case +1 about deprecating `exec` reader in SonarJava in favor of XML :thumbsup: (what AFAIK was in plans/thoughts when import of XML was introduced) - not even counting that this will give JaCoCo more freedom for changes that require changes in `exec`, at least simply because two ways to achieve the same is IMO misleading for SonarQube users, and especially given that in SonarQube `exec` works for Java but not for Kotlin while XML works for both.

**Comment by Godin** [comment]
> will save zero values

after following modifications

```diff
diff --git i/java-frontend/src/main/java/org/sonar/java/resolve/BytecodeCompleter.java w/java-frontend/src/main/java/org/sonar/java/resolve/BytecodeCompleter.java
index e4ed55f83..5ed280585 100644
--- i/java-frontend/src/main/java/org/sonar/java/resolve/BytecodeCompleter.java
+++ w/java-frontend/src/main/java/org/sonar/java/resolve/BytecodeCompleter.java
@@ -40,7 +40,7 @@ import org.sonar.plugins.java.api.semantic.Symbol;

 public class BytecodeCompleter implements JavaSymbol.Completer {

-  public static final int ASM_API_VERSION = Opcodes.ASM7_EXPERIMENTAL;
+  public static final int ASM_API_VERSION = Opcodes.ASM7;

   private Symbols symbols;
   private final ParametrizedTypeCache parametrizedTypeCache;
diff --git i/pom.xml w/pom.xml
index 2561872f3..8ab4abce4 100644
--- i/pom.xml
+++ w/pom.xml
@@ -87,8 +87,8 @@
     <analyzer.commons.version>1.10.2.456</analyzer.commons.version>
     <orchestrator.version>3.21.0.1721</orchestrator.version>
     <sslr.version>1.23</sslr.version>
-    <jacoco.version>0.8.2</jacoco.version>
-    <asm.version>6.2.1</asm.version>
+    <jacoco.version>0.8.3-SNAPSHOT</jacoco.version>
+    <asm.version>7.0</asm.version>
     <argLine>-Xmx512m</argLine>
     <gitRepositoryName>sonar-java</gitRepositoryName>
```

and for the record I use following `pom.xml` for end-to-end tests

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>example</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.3-SNAPSHOT</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
              <goal>report</goal>
            </goals>
            <configuration>
              <!--
              values are distinct from default values in SonarQube
              so that format is controlled by profiles below
              -->
              <destFile>target/jacoco/jacoco.exec</destFile>
              <dataFile>target/jacoco/jacoco.exec</dataFile>
              <outputDirectory>target/jacoco</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>xml</id>
      <properties>
        <sonar.coverage.jacoco.xmlReportPaths>target/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
      </properties>
    </profile>
    <profile>
      <id>exec</id>
      <properties>
        <sonar.jacoco.reportPaths>target/jacoco/jacoco.exec</sonar.jacoco.reportPaths>
      </properties>
    </profile>
  </profiles>

</project>
```
