### ISSUE TITLE
try-with-resources Statement: wrong coverage 

### ISSUE THREAD

**Issue by mquasten** [jacoco/jacoco#82]
```
...
try(final ObjectOutputStream out = new ObjectOutputStream(baos))  {
    ....
}
```

Result: 4 of 8 branches missed.

I think that is not possible.  When I wirite it without the java 7 feature than the coverage is ok, means 100%;

```
...
ObjectOutputStream out = null;
try {
       out=new ObjectOutputStream(baos);
        ...
} finally {
        out.close;
}
```

For  try-with-resources Statement checking branches should be skipped.

**Comment by ziesemer** [comment]
FYI - http://stackoverflow.com/questions/17354150/8-branches-for-try-with-resources-jacoco-coverage-possible (http://stackoverflow.com/a/17356707/751158 , in particular) has some very comprehensive details as to what is happening here, and why it is probably non-trivial for JaCoCo to transparently handle this as many might expect.
