### ISSUE TITLE
Support both embedded and managed JVM in Arquillian tests

### ISSUE THREAD

**Issue by james-r-smith** [jacoco/jacoco#841]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

* Create project with Arquillian, TestNG, and TomEE Embedded Container
* Create basic Arquillian tests
* Configure JaCoCo plugin
* Switch TomEE Embedded Container to TomEE Remote Container
* (No Code Coverage Shown)
* Configure argLine [shown here](https://stackoverflow.com/questions/54210307/arquillian-tomee-remote-jacoco-code-coverage)
* Only tests ran as client are covered, while other tests are left uncovered ([as shown here](https://stackoverflow.com/questions/54412555/arquillian-integration-test-code-coverage-issue-with-jacoco))

JaCoCo version: 0.8.3
Operating system: MacOS
Tool integration: Maven

### Expected behaviour

Coverage to work for both JVM's.

### Actual behaviour

Coverage will only work on either client JVM, or remote JVM.

**Comment by Godin** [comment]
I hope you realize that not everyone deal with Arquillian, TomEE and many other existing technologies on a daily basis. And not everyone wanna waste their time on almost blind guessing of how exactly "create A, B and configure C" to reproduce your difficulty. And thus instead always better to **provide complete runnable example**.

But ok let's pretend that very small group of maintainers here, who work on project in their spare time, don't have anything else to do than guessing someones configs.

I don't know what you mean by "tests ran as client" and "other tests", "client JVM" and "remote JVM", but

* based on your first link created `ExampleTest` which will be executed by `maven-surefire-plugin` and should cover class `Service` via remote HTTP call
* and based on your second link created `ExampleIT` which will be executed by `maven-failsafe-plugin` and should cover class `Bean`

You'll find all code in [example.zip](https://github.com/jacoco/jacoco/files/2846849/example.zip) and execution of `mvn verify` produces following report as expected in directory `target/site/jacoco/`

![org_example](https://user-images.githubusercontent.com/138671/52505723-b32f2b80-2bec-11e9-890f-044dffadfb94.png)

**Comment by james-r-smith** [comment]
@Godin, I apologize for not providing an example. I will make sure to if I raise another issue.

While the sample you provided covers 100%, if you swap JUnit with TestNG, the coverage fails for non-client code (e.g. `Bean`, or `ExampleIT`). The example you provided did help to clearly spot this bug, so I'm very thankful for your reply.

You can find the TestNG version [here](https://github.com/jacoco/jacoco/files/2852187/example.zip). Could you please look into this whenever you get the chance to and let me know if this is a bug? I appreciate your time.

**Comment by Godin** [comment]
JaCoCo doesn't execute nor your tests, nor your code, it only records execution of code in JVM that uses JaCoCo Java Agent (`-javaagent` JVM option) and saves this data using JVM shutdown hook.

So are you sure that in your example

1. correct JVM is started with correct `-javaagent`
2. shutdown hooks in this JVM are executed
    * JVM is not killed
    * and hooks executed properly - see https://bugs.openjdk.java.net/browse/JDK-8154017
3. test and code under test are actually executed - see https://github.com/cbeust/testng/issues/1513

???

----

After following modification of your example

```diff
--- pom.xml
+++ pom.xml
@@ -46,7 +46,7 @@
     <dependency>
       <groupId>org.testng</groupId>
       <artifactId>testng</artifactId>
-      <version>6.14.3</version>
+      <version>6.10</version>
       <scope>test</scope>
     </dependency>
     <!-- Arquillian TestNG -->
diff --git c/src/test/java/org/example/ExampleIT.java i/src/test/java/org/example/ExampleIT.java
index 623138c..f0b6f31 100644
--- src/test/java/org/example/ExampleIT.java
+++ src/test/java/org/example/ExampleIT.java
@@ -9,6 +9,8 @@ import org.testng.annotations.Test;

 import javax.inject.Inject;

+import java.io.File;
+
 import static org.testng.Assert.assertEquals;

 public class ExampleIT extends Arquillian {
@@ -20,6 +22,7 @@ public class ExampleIT extends Arquillian {
   public static WebArchive createDeployment() {
     return ShrinkWrap.create(WebArchive.class)
       .addClass(Bean.class)
+      .addAsLibrary(new File("/Users/evgeny.mandrikov/.m2/repository/org/testng/testng/6.10/testng-6.10.jar"))
       .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
   }
```

I receive

![after](https://user-images.githubusercontent.com/138671/52592359-7fe7d900-2e46-11e9-877e-1dc0f9d27446.png)

while before modification

![before](https://user-images.githubusercontent.com/138671/52592461-b7568580-2e46-11e9-8e66-201dfc8da6f4.png)

----

From the above IMO clear that root of your problem is not in JaCoCo.

**Comment by james-r-smith** [comment]
@Godin, adding the following fixed it:

```java
PomEquippedResolveStage pomEquippedResolveStage = Maven.resolver().loadPomFromFile("pom.xml");

File[] externalLibs = pomEquippedResolveStage.resolve(
        "org.testng:testng"
).withTransitivity().asFile();

return ShrinkWrap.create(WebArchive.class)
      .addClass(Bean.class)
      .addAsLibraries(externalLibs)
      .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
```

It seems to be related to TestNG. I'll see if I can get their input on this. Thank you for your help.
