### ISSUE TITLE
Object Isn't being reported despite being used.

### ISSUE THREAD

**Issue by rubsnick** [jacoco/jacoco#856]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce
Create a Kotlin Object 
```
object Foo {
        const val PREFIX = "foo:"
}
```
call`Foo.PREFIX` 

JaCoCo version:0.8.3
Operating system: Mac OSX
Tool integration: Gradle

### Expected behaviour
Code coverage for the Foo Object to be reported.

### Actual behaviour
Code coverage for the Foo Object isn't reported despite referencing it.

**Comment by Godin** [comment]
At runtime `object Foo` is not accessed, because `const val PREFIX = "foo:"` is [compile-time constant](https://kotlinlang.org/docs/reference/properties.html#compile-time-constants).
