### ISSUE TITLE
springframework  org.springframework.web.util.UriComponentsBuilder issue

### ISSUE THREAD

**Issue by gsbtech** [jacoco/jacoco#866]
### Steps to reproduce

When invoking org.springframework.web.util.UriComponentsBuilder  to build a uri query from a Java POJO, some Jacoco_data gets embedded into the result.  It is getting confused with "instrument_types"

JaCoCo version: 0.8.0-0.8.3
Operating system: Mac High Sierra
Tool integration: Maven
springframework jar version: I used spring 4.3.10.RELEASE and 4.3.18.RELEASE

### Expected behaviour
"http://localhost/test/v2/fees?disable_catalog=false&purchaser=XOOM&send_amount=10&destination.types=LEGACY_BILLPAY&destination.types=TOP_UP&destination.types=DELIVERY&destination.types=ATM&destination.country_code=GT&destination.currency_code=GTQ&funding.instrument_types=DRN&funding.instrument_types=ACH&funding.instrument_types=CARD&funding.country_code=US&funding.currency_code=USD"

### Actual behaviour
Response contains ".$jacoco_data=" at the end as you see in:

"http://localhost/test/v2/fees?disable_catalog=false&purchaser=XOOM&send_amount=10&destination.types=DEPOSIT&destination.types=DELIVERY&destination.types=LEGACY_BILLPAY&destination.types=BILL_PAY&destination.types=PICKUP&destination.country_code=GT&destination.currency_code=GTQ&destination.$jacoco_data=[Z@71304a7c&funding.instrument_types=CARD&funding.instrument_types=DRN&funding.country_code=US&funding.currency_code=USD&funding.$jacoco_data=[Z@11e1b0e7&$jacoco_data=[Z@782516dc"

**Comment by gsbtech** [comment]
What is the reason for closing this issue? 

spring is a popular framework.

**Comment by Godin** [comment]
@gsbtech quoting [answer on the exactly the same question in mailing list](https://groups.google.com/d/msg/jacoco/8hucIqaS1Cc/TqGWFRHQAgAJ) , I guess also created by you (btw please don't create such cross-posts in future):

> Quoting FAQ ( https://www.jacoco.org/jacoco/trunk/doc/faq.html ) :
>
>> ### My code uses reflection. Why does it fail when I execute it with JaCoCo?
>>
>> To collect execution data JaCoCo instruments the classes under test which adds two members to the classes: A private static field $jacocoData and a private static method $jacocoInit(). Both members are marked as synthetic.
>>
>> Please change your code to ignore synthetic members. This is a good practice anyways as also the Java compiler creates synthetic members in certain situation.
>
> In other words:
> If your code uses reflection, then change it to ignore synthetic members.
> If code of third-party library uses reflection, then request vendor of this library to change their code to ignore synthetic members.
>
> Or exclude this "POJO" from instrumentation by JaCoCo.
>
> Or if you are lucky to be able to use Java 11, then you can try to use next (not yet released) 0.8.4-SNAPSHOT version of JaCoCo which doesn't add synthetic field to Java 11 class files.

**Comment by Godin** [comment]
Furthermore field is marked as [`transient`, indicating that it is not part of the persistent state of an object](https://docs.oracle.com/javase/specs/jls/se11/html/jls-8.html#jls-8.3.1.3).

**Comment by gsbtech** [comment]
Thank you. Somehow my search did not find the issues with the internal variables. I noticed later it was related to synthetic fields.
