### ISSUE TITLE
Gradle subprojects merge example

### ISSUE THREAD

**Issue by marcofranssen** [jacoco/jacoco#868]
I'm unable to get a working code coverage report for sonarqube plugin so all the covered code is reflected. There are always some of my subprojects missing from the coverage report which is invalid as they are touched by my tests for sure.

Is there anyone able to provide a good example on the official documentation page over here?

https://docs.gradle.org/current/userguide/jacoco_plugin.html

It seems there are many people suffering from this, all providing different approaches, all giving different, but inaccurate results.

Would be great if there is a complete example on how to use jacocoMerge tasks with gradle 5.3 using a gradle project with subprojects.

Below an extract of my build gradle with the last approach I tried for getting the gradle stuff merged.

```groovy
plugins {
    id "org.sonarqube" version "2.7"
    id 'jacoco'
}

def allTestCoverageFile = "${buildDir}/jacoco/allTestCoverage.exec"

task jacocoMerge(type: JacocoMerge, group: 'verification') {
    subprojects.each { subproject ->
        executionData subproject.tasks.withType(Test)
    }
}

sonarqube {
    properties {
        property "sonar.scm.provider", "git"
        property "sonar.jacoco.reportPaths", allTestCoverageFile
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'jacoco'

    sonarqube {
        properties {
            property "sonar.jacoco.reportPaths", allTestCoverageFile
        }
    }
}

project(':projectA') {
    dependencies {
        compile project(':projectB')
        compile project(':projectC')
    }
}

project(':projectB') {
    dependencies {
        compile project(':projectC')
    }
}

project(':projectC') {
    dependencies {
    }
}
```

**Comment by marchof** [comment]
Neither Gradle nor Sonarqube is maintained by the JaCoCo project:

https://www.jacoco.org/jacoco/trunk/doc/integrations.html

Please contact the respective projects.

**Comment by marcofranssen** [comment]
After a 2 days of trying different things I found the following to be working. Not sure if this is the best approach, but this at least works for me now.

I think the key is to have the jacocomerge being called using the `test.finalizedBy(jacocoMerge)` to get it working.

```
plugins {
    id "org.sonarqube" version "2.7"
    id 'jacoco'
}

repositories {
    mavenCentral()
}

def allTestCoverageFile = "${rootProject.buildDir}/jacoco/allTestCoverage.exec"
task jacocoMerge(type: JacocoMerge, group: 'verification') {
    destinationFile = file(allTestCoverageFile)
    executionData = project.fileTree(dir: '.', include:'**/build/jacoco/test.exec')
}

jacoco {
    toolVersion = "0.8.3"
}

sonarqube {
    properties {
        property "sonar.scm.provider", "git"
        property "sonar.jacoco.reportPaths", allTestCoverageFile
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'jacoco'

    sonarqube {
        properties {
            property "sonar.jacoco.reportPaths", allTestCoverageFile
        }
    }

    test.finalizedBy(jacocoMerge)
}

project(':projectA') {
    dependencies {
        compile project(':projectB')
        compile project(':projectC')
    }
}

project(':projectB') {
    dependencies {
        compile project(':projectC')
    }
}

project(':projectC') {
    dependencies {
    }
}
```

Is this the best approach to do this? If yes it might make sense to add this to the jacoco plugin documentation as an example to use it for multimodule gradle projects.
