### ISSUE TITLE
adding custom filter

### ISSUE THREAD

**Issue by nberserk** [jacoco/jacoco#870]
Hi community.
I want to add my own custom filter for coverage calculation. this filter is whitelist-based annotation. means only annotated function will be included for the coverage report.

is there any way to accomplish this requirement? 
I've search on the web. but I could not find any clues yet.

any feedback or clues would be helpful to me.
thanks in advance.

**Comment by Godin** [comment]
> I want to add my own custom filter for coverage calculation. this filter is whitelist-based annotation. means only annotated function will be included for the coverage report.
> is there any way to accomplish this requirement?

There is no API for custom filters. And there is no such filter out-of-the-box.
However if you know list of methods, then you can extract all required information from XML report.

And please in future as stated in template - do not use issue tracker for questions, there is users mailing list for this.
