### ISSUE TITLE
Jacoco does not show correct report if test files change but the code stays the same

### ISSUE THREAD

**Issue by slavik57** [jacoco/jacoco#871]
### Steps to reproduce

JaCoCo version: 0.8.3
Operating system: Windows 10 Pro
Tool integration: Gradle

1. Create a class with 2 functions:
```
public class TestMePlease {
  public int foo1() { return 1; }
  public int foo2() { return 2; }
}
```

2. Create a test class which tests function `foo1`:
```
public class TestingAsYouReqested {
  @Test
  public void testFoo1() {
    int foo1 = new TestMePlease().foo1();
  }
}
```
3. Run the test and create the report: 
```
gradle test jacocoTestReport
```
Produces the following report:
![image](https://user-images.githubusercontent.com/6184997/56198266-40ef2300-6043-11e9-8092-7fd4b5186eb7.png)

4. Change the testing function:
```
public class TestingAsYouReqested {
  @Test
  public void testFoo1() {
    int foo2 = new TestMePlease().foo2();
  }
}
```
5. Run the test and create the report: 
```
gradle test jacocoTestReport
```
### Expected behaviour
This should show that only the `foo2` function is covered like so:
![image](https://user-images.githubusercontent.com/6184997/56198292-4ba9b800-6043-11e9-9bcb-52880200884e.png)

### Actual behaviour
Both `foo1` and `foo2` are shown as covered:
![image](https://user-images.githubusercontent.com/6184997/56198331-69771d00-6043-11e9-98e8-0f92f0e753a0.png)

### Other information
* If we add a `clean` step before the `test` step - it works as expected
* If we rename the function `foo1` to be `foo3` and run the `gradle test jacocoTestReport` again - it shows the correct result:
![image](https://user-images.githubusercontent.com/6184997/56198582-db4f6680-6043-11e9-953f-45c61cd6f487.png)
* After renaming from `foo1` to `foo3` we now change the name back to be `foo1` (from `foo3`). We run the `gradle test jacocoTestReport` again, it returns to be showing incorrect result:
![image](https://user-images.githubusercontent.com/6184997/56198679-08037e00-6044-11e9-805b-2bc2330b7108.png)

**Comment by Godin** [comment]
[JaCoCo agent](https://www.jacoco.org/jacoco/trunk/doc/agent.html) has parameter `append`, which [defaults to `true` in Gradle](https://docs.gradle.org/4.10.1/dsl/org.gradle.testing.jacoco.plugins.JacocoTaskExtension.html#org.gradle.testing.jacoco.plugins.JacocoTaskExtension:append), and in this case it is expected that `exec` file accumulates information in absence of `clean` that removes this file.

Also please note that [integration with Gradle is third-party in respect to this repository](https://www.jacoco.org/jacoco/trunk/doc/integrations.html).
