### ISSUE TITLE
怎么调整粒度到行

### ISSUE THREAD

**Issue by zytcharming** [jacoco/jacoco#874]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version:
Operating system:
Tool integration: Maven/Ant/API/Other

**Comment by Godin** [comment]
we don't speak Chinese
