### ISSUE TITLE
Code not covered for mockito test cases even though code is executed

### ISSUE THREAD

**Issue by bvishweshwar** [jacoco/jacoco#876]
### Steps to reproduce

gradle build - used to build

Attached is build.gradle file.
[build.txt](https://github.com/jacoco/jacoco/files/3152251/build.txt)

### Tools
Codebase: groovy
JaCoCo version: 0.8.1.201803210924
Operating system: Windows
Tool integration: gradle

### Expected behaviour
Test cases written in mockito should cover code.

### Actual behaviour
Code is not covered for test cases written in mockito.

**Comment by marchof** [comment]
JaCoCo Gradle plugin is not developed by us. Please contact gradle project.

**Comment by Godin** [comment]
Also for future - when reporting issues please make sure to **include everything** required to reproduce the problem, **including code and tests**, and not just a random piece.
