### ISSUE TITLE
Greater precision for percentages in reports

### ISSUE THREAD

**Issue by paul-hammant** [jacoco/jacoco#878]
It would be great to be able to make a setting for JaCoCo's maven plugin to change from NN percentages to NN.n. I scoured the docs and GH issues and couldn't see how.

I'd use it in my coverage collecting script. Ref: https://twitter.com/paul_hammant/status/1127100345920970752

**Comment by jjlharrison** [comment]
We do something similar for CI notification emails, we parse the XML report for the added precision.

**Comment by marchof** [comment]
The HTML format is not considered an API. The internal structure may change at any time. For programmatic access we provide the XML report with an stable DTD.

Two remarks regarding your use case:

1) I started working on customizable columns in #382 long time ago. The number formats are not yet in scope but I added a reminder for it.
2) I hacked SVG batch support for JaCoCo some time ago and just pushed it so you can have a look: #879

**Comment by paul-hammant** [comment]
@jjlharrison can you share you XML parsing code?  I looked at the CSV dump, but it does not have totals :-(

**Comment by paul-hammant** [comment]
@marchof  - looks good. Do you think the PR would be merged and released?

**Comment by marchof** [comment]
@paul-hammant I'll try to finalize the PR this weeks.

[This](https://gist.github.com/marchof/a0cc43e0a078cf9e2e23485ba3ed7a1b) is how the badge would look like.

**Comment by paul-hammant** [comment]
Cool. I'd prefer 
![2019-05-13_1538](https://user-images.githubusercontent.com/82182/57630370-66fdd980-7595-11e9-9d7f-fbc5fa1665e1.png) of course :)

**Comment by Godin** [comment]
@paul-hammant could you please elaborate more about practical use of badge other than to show off? And what is the practical use of one digit after dot compared to "of course" two for example? Why badge contains only one counter, whereas report contains other quite valuable counters?

Furthermore as [was already said in mailing list]() you already can easily process XML and get desired precision. For example following XSLT

```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xsl:output method="xml" indent="yes" omit-xml-declaration="yes" />
  <xsl:template match="/">

    <xsl:variable name="instructions_c" select="report/counter[@type='INSTRUCTION']/@covered"/>
    <xsl:variable name="instructions_m" select="report/counter[@type='INSTRUCTION']/@missed"/>
    <xsl:variable name="instructions" select="format-number($instructions_c div ($instructions_c + $instructions_m) * 100, '###.00')"/>

    <svg xmlns="http://www.w3.org/2000/svg" width="200" height="20">
      <clipPath id="button">
        <rect width="200" height="20" rx="3" fill="#fff"/>
      </clipPath>
      <linearGradient id="light" x2="0" y2="100%">
        <stop offset="0" stop-opacity="0.1" stop-color="#bbb"/>
        <stop offset="1" stop-opacity="0.1"/>
      </linearGradient>
      <g clip-path="url(#button)">
        <rect height="20" width="120" fill="#555"/>
        <rect x="120" height="20" width="80" fill="#4c1"/>
        <rect height="20" width="200" fill="url(#light)"/>
      </g>
      <g text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
        <text x="60" y="15" fill="#000" fill-opacity="0.3">instructions coverage</text>
        <text x="60" y="14" fill="#fff">instructions coverage</text>

        <text x="160" y="15" fill="#000" fill-opacity="0.3">
          <xsl:value-of select="$instructions"/>%
         </text>
        <text x="160" y="14" fill="#fff">
          <xsl:value-of select="$instructions"/>%
        </text>
      </g>
    </svg>
  </xsl:template>
</xsl:stylesheet>
```

produces following SVG

![badge_svg](https://user-images.githubusercontent.com/138671/57662295-2337be00-75ef-11e9-824d-4f5316ea2807.png)

@marchof IMO formatting must be consistent/exactly the same as in HTML report to avoid any confusion. We can try with only one counter - instructions, but I have strong feeling that we'll quickly end-up with requests to create others, which maybe not such a bad option - showing some of them or even all will be possible. However do we really want to increase maintenance costs (questions/requests) by addition of feature with doubtful practical value, which already raises debates about precision and which is easily implementable outside? isn't this from the same strabge series as #684?

**Comment by paul-hammant** [comment]
I'm training project managers to read READMEs any speak to dev teams if coverage lowers. I only a single figure in order to get the project manager to act versus not act. I'm not going to send them off to HTML reports - too many clicks, too much detail, too much eye scanning. The HTML report can be what the developer looks at, whereas it was the project manager that asked them to investigate and report back

**Comment by marchof** [comment]
@paul-hammant Oh dear. I always tried to advocate for wise usage of coverage reports directly by the developers. Wise usage to me means to look at the absolute amount of uncovered code and identify places where testing can be improved. And this as early as possible in the development process. At best even before new code is pushed.

Focusing on percentage values to satisfy managers typically leads to useless test code without actual assertions.

**Comment by paul-hammant** [comment]
Say a Maven module was at 34% coverage (from integration tests), and we're wanting 1] to raise that to an acceptable level, and 2] shift to unit tests for a 100x speed up (per test), and then one morning coverage is down at 33% despite that team 'ask'. Sure, I'm going to think I'm right to use coverage as an indicator. And per #878 wish I had a decimal position :-P 

I'm a 18 year user of Intellij in TDD/XP teams and blog a lot about testability - https://paulhammant.com/2012/11/01/testability-and-cost-of-change/ - being one :)

**Comment by nhoxbypass** [comment]
Any progression on this?

I think this feature is really helpful.
