### ISSUE TITLE
Default arguments in open Kotlin function cause untestable branches

### ISSUE THREAD

**Issue by clydebarrow** [jacoco/jacoco#882]
### Steps to reproduce
Test this class:
````kotlin
open class TestClass {

    open fun testFun(arg1: String, arg2: String = "abc"): String {
        return arg2
    }
}
````
with this junit test code:

````kotlin
class TestClassTest {

    @Test
    fun testFun() {
        val testClass = TestClass()
        assertEquals("abc", testClass.testFun("123"))
        assertEquals("def", testClass.testFun("123", "def"))
        assertEquals("abc", testClass.testFun("123", "abc"))
    }
}
````
and examine the coverage of `TestClass`

### Environment
JaCoCo version: 0.8.4
Operating system: Macos
Tool integration: Gradle

### Expected behaviour
`TestClass` should show complete coverage

### Actual behaviour
The synthetic function `testFun$default(TestClass, String, String, int, Object)` which implements default arguments is shown as missing coverage of one branch and 5 instructions. See image below.

The issue occurs only with open functions. It appears Kotlin  inserts additional code which is presumably invoked only when the function is overridden. The particular use-case which led to this is in a Spring Boot environment where annotations such as `@Transactional` automatically make classes open, rather than the Kotlin default of final.

![Screenshot 2019-05-15 17 25 02](https://user-images.githubusercontent.com/2366188/57756363-694b6980-7736-11e9-82d5-56094ebaa4ff.png)

**Comment by Godin** [comment]
For `Example.kt`

```
class Example {
  fun f(s: String = "") {
  }
}
```

according to `kotlinc Example.kt && javap -v -p Example.class` Kotlin compiler 1.30.1 produces

```
   public static void f$default(Example, java.lang.String, int, java.lang.Object);
    descriptor: (LExample;Ljava/lang/String;ILjava/lang/Object;)V
    flags: ACC_PUBLIC, ACC_STATIC, ACC_SYNTHETIC
    Code:
      stack=2, locals=4, args_size=4
         0: iload_2
         1: iconst_1
         2: iand
         3: ifeq          9
         6: ldc           #22                 // String
         8: astore_1
         9: aload_0
        10: aload_1
        11: invokevirtual #24                 // Method f:(Ljava/lang/String;)V
        14: return
      LineNumberTable:
        line 2: 6
```

whereas for

```
open class Example {
  open fun f(s: String = "") {
  }
}
```

produces

```
  public static void f$default(Example, java.lang.String, int, java.lang.Object);
    descriptor: (LExample;Ljava/lang/String;ILjava/lang/Object;)V
    flags: ACC_PUBLIC, ACC_STATIC, ACC_SYNTHETIC
    Code:
      stack=3, locals=4, args_size=4
         0: aload_3
         1: ifnull        14
         4: new           #22                 // class java/lang/UnsupportedOperationException
         7: dup
         8: ldc           #24                 // String Super calls with default arguments not supported in this target, function: f
        10: invokespecial #27                 // Method java/lang/UnsupportedOperationException."<init>":(Ljava/lang/String;)V
        13: athrow
        14: iload_2
        15: iconst_1
        16: iand
        17: ifeq          23
        20: ldc           #29                 // String
        22: astore_1
        23: aload_0
        24: aload_1
        25: invokevirtual #31                 // Method f:(Ljava/lang/String;)V
        28: return
      LineNumberTable:
        line 2: 20
```

So indeed there is additional instructions and one more branch in bytecode. Thank you for reporting this.

**Comment by Godin** [comment]
@clydebarrow this was resolved in master branch, so you can test snapshot version - https://www.jacoco.org/jacoco/trunk/doc/repo.html

**Comment by clydebarrow** [comment]
Yes, that has resolved the problem, thank you.

**Comment by Godin** [comment]
@clydebarrow thank you for testing! 👍 ❤️
