### ISSUE TITLE
Code coverage of lambda expression shows only one line  

### ISSUE THREAD

**Issue by SahilAggarwalG** [jacoco/jacoco#885]
JaCoCo version: 0.7.9
Operating system:Centos7
Tool integration: SBT-Jacoco

we are using junit and jmockit for unit testing and use scala build tool(sbt) 

We have code which returns Future , it has only one line in method and that line is lambda expression as follows : 

    @Override
    public ServiceCall<ManualDialCustomerRequest, Interaction> dialAndCreateInteraction() {
        return request -> {

                          //Line 1 
                           // Line 2 
                           . . . . . and so many lines 
                          return object  }
} 

Now , when we run jacoco tool it shows 100% code coverage and lines covered is 1 of 1  but it should also count lines inside lambda expression  . and if i write body of lambda expression in a private method it is working   . please help why it is shhowing total 1 line in above method .

**Comment by Godin** [comment]
Provided information is clearly not enough to reproduce and understand your problem - provided code even can't be compiled.

Given following `src/Example.java` where methods return lambda with many lines

```
class Example {
    static Runnable example1() {
        return () -> {
            System.out.println("line 1");
            System.out.println("line 2");
            System.out.println("line 3");
        };
    }

    static Runnable example2() {
        return () -> {
            System.out.println("line 1");
            System.out.println("line 2");
            System.out.println("line 3");
        };
    }

    public static void main(String[] args) {
        example1(); // lambda body not executed
        example2().run(); // lambda body executed
    }
}
```

using

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

execution of

```
mkdir classes
javac src/Example.java -d classes
java -javaagent:jacoco-0.8.4/lib/jacocoagent.jar -cp classes Example
java -jar jacoco-0.8.4/lib/jacococli.jar report jacoco.exec \
    --classfiles classes \
    --sourcefiles src \
    --html report
```

generates following report

![report](https://user-images.githubusercontent.com/138671/58099444-efa2f800-7bdb-11e9-861e-7cca376030c2.png)

which clearly shows that there is no problem with lines inside lambdas.

**Comment by SahilAggarwalG** [comment]
@Godin  , 

Your exapmle is appropriate ,

My case in your example is as follows : 

Scnario : 
1 . In you example i have written test case for example1() 
2. example1().run is called by some library (in my case it is some jar of lagom framework )

Actual Output : 
1. Coverage reports of jacoco shows that is is only one total lines in example1() and coverage is 100% . 

Expected Output 
2. i want that lines of this dynamic lambda function should also be covered in code coverage , but this function is not showing in jacoco reports  .

**Comment by marchof** [comment]
@SahilAggarwalG As @Godin already wrote: If you want us to investigate this issue please provide a executable reproducer. Preferably a github repo with a minimal project that demonstrates the issue. Otherwise we cannot analyze your problem.

**Comment by Godin** [comment]
Closing in absence of reproducer, feel free to reopen when you'll be able to provide it.
