### ISSUE TITLE
how to merge report after service restart

### ISSUE THREAD

**Issue by sunmoondeer** [jacoco/jacoco#899]
The exec and report will be computed from scratch after service restart, normally, test env will be restarted multiple times, what should i do  if I want to keep the old coverage info?

**Comment by Godin** [comment]
Could you please read what is stated in the issue template

> This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

and stop asking questions in our issue tracker.
