### ISSUE TITLE
Jacoco falsely marked Kotlin-logging logger as untested

### ISSUE THREAD

**Issue by sluongng** [jacoco/jacoco#903]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version: 0.8.4
Operating system: Ubuntu 1904
Tool integration: Maven

Add kotlin-logging library to project
```xml
        <kotlin-logging.version>1.6.26</kotlin-logging.version>
...
        <dependency>
            <groupId>io.github.microutils</groupId>
            <artifactId>kotlin-logging</artifactId>
            <version>${kotlin-logging.version}</version>
        </dependency>
```

Acquire logger object using kotlin-logging api

```kotlin
    private val log = KotlinLogging.logger {}
```

Run test with jacoco report

### Expected behaviour
All code are covered

### Actual behaviour
![image](https://user-images.githubusercontent.com/26684313/60806368-fc3fd780-a1ac-11e9-8b14-6b837b399123.png)
![image](https://user-images.githubusercontent.com/26684313/60806374-ffd35e80-a1ac-11e9-94c9-dd3d46e860a6.png)

** Originally reported ** https://github.com/MicroUtils/kotlin-logging/issues/68

**Comment by Godin** [comment]
JaCoCo absolutely correctly shows that code contains lambda that is never executed.

And actually doesn't force you to do anything about it, however

* Either kotlin-logging should be modified to do invocation in this case, what was already mentioned in MicroUtils/kotlin-logging#68, absence of measurements is strange - maybe cost is negligible or maybe JIT is able to eliminate this invocation completely

* Or use companion object, what also was already mentioned in MicroUtils/kotlin-logging#68 :

![package](https://user-images.githubusercontent.com/138671/60833633-f652f200-a1be-11e9-87af-c27529f59d76.png)

![source](https://user-images.githubusercontent.com/138671/60833644-fa7f0f80-a1be-11e9-80e0-30dc5c1b9856.png)

* Seems that code of any lambda that is inside of anything named `log` (including such `var log = KotlinLogging.logger {}` initializers) will be placed by Kotlin compiler into a class file whose name will contain `$log$`, so with all positive and negative consequences you can exclude all `**/*$log$*.class` files from JaCoCo report generation
