### ISSUE TITLE
Private constructor + throwing exception

### ISSUE THREAD

**Issue by mfolnovic** [jacoco/jacoco#914]
### Steps to reproduce

I have an utility class with private constructor:

```
public final class ClassUtil {

    private ClassUtil() {
        throw new AssertionError();
    }

}
```

(per suggestion from Effective Java, 2nd edition, Item 4)

After running `mvn clean test jacoco:report`...

JaCoCo version: 0.8.4
Operating system: Linux
Tool integration: Maven

### Expected behaviour

I expect to see coverage 100%.

### Actual behaviour

I see coverage 0%.

**Note**: I'm aware of filtering options, and this works as expected if constructor is empty, as it clearly says:
> :white_check_mark: Private **empty** constructors that do not have arguments - Done in 0.8.0

I think this filter could also detect if constructor is throwing exception. :blush:

**Comment by marchof** [comment]
Hi @mfolnovic, first of all sorry for the late reply! We intensively discussed your request and came to the conclusion that we will not follow up on filters for user code. Filtering user code is very controversial and will lead to endless discussions what to filter and not.

In this respect we have to admit that filtering private empty constructors was already a mistake in the first place 😞 .

I hope that you understand that we have set priorities given our very limited resources for this project.
