### ISSUE TITLE
Please comply with ASM license when re-distributing ASM

### ISSUE THREAD

**Issue by vlsi** [jacoco/jacoco#916]
# Steps to reproduce

Download jacoco release jar.
For instance http://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.8.4/

### Expected behaviour

re-distribution should reproduce the required by ASM copyright notice.

### Actual behaviour

1) Most of the time JaCoCo refers to ASM 3.x via "about.txt" (while it embedds asm 7.x or whatever version)
2) The copyright notice is stale.

**Comment by vlsi** [comment]
See also: https://github.com/raphw/byte-buddy/issues/709 , https://gitlab.ow2.org/asm/asm/issues/317880

**Comment by marchof** [comment]
@vlsi Thanks for reporting this. Can you please review PR #918?
