### ISSUE TITLE
Get JaCoCo to work with surefire forkCount=0

### ISSUE THREAD

**Issue by psybsd** [jacoco/jacoco#917]
### Steps to reproduce

JaCoCo version: any
Operating system: OKD v3.x-3.11 / OpenShift v3.x-v3.11,4.1 / Kubernetes
Tool integration: Maven Surefire

### Expected behaviour
I expect JaCoCo to work when surefire does not fork.

### Actual behaviour
If surefire forks; it fails on a kubernetes build-environment. This is because java has an archaic IPC-system which fails due to <reasons> on a kubernetes platform, unless we start tearing down the security-measures. (Run it with anyuid permissions, which is a security leak which we don't want and/or our platform-provider refuses)

The only way the tests succeed on a kubernetes-based build-platform is when surefire does not fork; but when we do this; jacoco stops working.

It would be very helpfull if jacoco would 'just work' when surefire forkcount=0.

**Comment by marchof** [comment]
JaCoCo uses very convenient on-the-fly instrumentation of the classes under test. This is done with a Java agent which needs to be specified on the command line. Therefore we require a forked JVM.

As a work around you might try [offline instrumentation](https://www.jacoco.org/jacoco/trunk/doc/offline.html). But we do not recommend to do so (as I do not recommend running tests in the build JVM itself).

**Comment by Godin** [comment]
@psybsd in addition to what @marchof said, I'm wondering what exactly means

> java has an archaic IPC-system

Isn't it overgeneralization and you'd better talk with developers of `maven-surefire-plugin` about their implementation of  inter-process communication and your inability to use `forkCount` greater than zero?
