### ISSUE TITLE
Keywords in org.jacoco.ant/about.html not expanded

### ISSUE THREAD

**Issue by marchof** [jacoco/jacoco#924]
### Steps to reproduce

[Download](https://search.maven.org/remotecontent?filepath=org/jacoco/org.jacoco.ant/0.8.4/org.jacoco.ant-0.8.4.jar) latest JaCoCo release from Maven Central.

### Expected behaviour

File about.html should show build date.

### Actual behaviour

The keyword `@build.date@` is not replaced.

**Comment by marchof** [comment]
Hi @Godin, do you have any idea why this doesn't work for this plugin only? All others look good.

**Comment by Godin** [comment]
@marchof [org.jacoco.cli-0.8.4.jar](http://repo1.maven.org/maven2/org/jacoco/org.jacoco.cli/0.8.4/org.jacoco.cli-0.8.4.jar) looks fine to me, so seems that this is only about `org.jacoco.ant` and hence might be related to https://github.com/jacoco/jacoco/blob/v0.8.4/org.jacoco.ant/pom.xml#L92-L116 introduced in #211, what to me seems like the only difference of `org.jacoco.ant/pom.xml` from others.

**Comment by Godin** [comment]
That seems to be it - seems that `maven-bundle-plugin` supports only substitution of "standard" patterns like `${build.date}` and doesn't use [our customization for `maven-resources-plugin`](https://github.com/jacoco/jacoco/blob/v0.8.4/org.jacoco.build/pom.xml#L481-L489). After replacement of `@build.date@` on `${build.date}` substitution happens and final `about.html` inside jar looks good to me. So just need to dig a bit to understand why we used custom delimiter `@` - maybe not needed anymore.
