### ISSUE TITLE
UncatigorizedMongoDbException: Query failed with error code 2 and error message "unknown top level operator: $jacocoData" on server

### ISSUE THREAD

**Issue by sunmoondeer** [jacoco/jacoco#928]
<img width="630" alt="error" src="https://user-images.githubusercontent.com/9718565/63739416-aee40a80-c8bf-11e9-8308-42453e3bdce8.png">
My service is a jar. I started the jacoco service through java -javaagent command. I encounted this error from the log file.

### Steps to reproduce

JaCoCo version: 0.8.2
Operating system: Centos 7.2
Tool integration: Maven/Ant/API/Other

**Comment by Godin** [comment]
Please read FAQ - http://www.jacoco.org/jacoco/trunk/doc/faq.html :

> #### My code uses reflection. Why does it fail when I execute it with JaCoCo?
>
> To collect execution data JaCoCo instruments the classes under test which adds two members to the classes: A private static field $jacocoData and a private static method $jacocoInit(). Both members are marked as synthetic.
>
> Please change your code to ignore synthetic members. This is a good practice anyways as also the Java compiler creates synthetic members in certain situation.
