### ISSUE TITLE
Lambda Expression Body was not covered in Jacoco 0.8.4

### ISSUE THREAD

**Issue by GnanaJeyam** [jacoco/jacoco#929]
There is already two issues regarding Lambda Expression
 https://github.com/jacoco/eclemma/issues/92
https://github.com/jacoco/jacoco/pull/232 @marchof 

But still now it is not covering the lambda expression.

My compiled lambda method was starting with **lambda$**

I tried with multiple jacoco versions but it was failed to cover it.

### Steps to reproduce

JaCoCo version: 0.8.4
Operating system: Linux
Tool integration: Maven
Java Version: Java 11

**Comment by marchof** [comment]
As you can see the issue has been fixed long time ago. If you experience a new problem please provide minimal executable reproducer for it.

**Comment by GnanaJeyam** [comment]
I attached sample code that missed lambda expression body in JaCoCo code coverage.
![Screenshot from 2019-08-27 14-35-34](https://user-images.githubusercontent.com/28224298/63763670-cbde0500-c8e2-11e9-99cd-778f4079213c.png)
![Screenshot from 2019-08-27 15-43-01](https://user-images.githubusercontent.com/28224298/63763671-cbde0500-c8e2-11e9-86ad-f4204962f3bf.png)

**Comment by Godin** [comment]
@GnanaJeyam screenshot is not **executable** reproducer. What is shown on this screenshot is that body of lambda was not executed and no one will be able to prove opposite just looking on this screenshot.

Complete and executable example in https://github.com/jacoco/jacoco/issues/885#issuecomment-494388663 shows that there is no problems with lambdas.

Place breakpoint inside lambda body and execute your tests in debug mode - will breakpoint be reached?

**Comment by GnanaJeyam** [comment]
@Godin  I checked with breakpoint it was not reaching it.

**Comment by marchof** [comment]
Then the code was not executed. This is what the report shows.
