### ISSUE TITLE
Improving report viewing of branch coverage

### ISSUE THREAD

**Issue by mleegwt** [jacoco/jacoco#933]
Branch coverage is currently shown with a yellow background when some of the branches are covered. A great improvement would be to be able to know which branches are covered.

```diff
# if( // either line coverage (green) or aggregated coverage (yellow)
+      a  == b // fully covered 
!     && c == d // partially covered 
-    && e == f // uncovered 
# ) {
-    // regular line coverage 
# }
```

The partially covered part could also be more complicatedly formatted to show which branch is covered and which is not by coloring the upper and lower part of the line. For the lower part the false condition can be shown. The true condition in the upper part.

Either formatting approach would improve the readability of the coverage report. Is it possible to achieve the new formatting?

**Comment by marchof** [comment]
JaCoCo works on Java bytecode. It does not parse Source code. The line highlighting is derived from debug information embedded in the class files.

The JDK compiler has experimental support for intra-line debug information which could be used to differentiate between branches on the same line. @Godin created a prototype for this some time ago: #317 

But still we will not parse source code and will therefore not re-format it.
