### ISSUE TITLE
Delta code coverage report

### ISSUE THREAD

**Issue by shubhamc183** [jacoco/jacoco#935]
Jacoco gives only the percentage of code covered w.r.t the jar used but doesn't provide a means to give us the DELTA code coverage i.e the amount of **diff code covered when compared against the last or any other version of jar**.

Because for a new version jar which has only 100 lines of code added/modified **we are focused on whether get got changed or not instead of all the lines in that jar**.

Let's say I have a Jar **A** version 1.0.0 which has 1000 lines of code and now I have version 1.1.0 which has 1100 lines of code so 100 lines of code are added. Now when I do testing I am focused on whether all the 100 new added + the modified lines in the previous 1000 lines are touched or not instead of the complete 1100 lines.

Is there any way to get a report which shows focuses on the **delta code coverage**? 

But this would be against the [Class Ids](https://www.jacoco.org/jacoco/trunk/doc/classids.html)  I guess.

@marchof @Godin @brockj @mfriedenhagen

**Comment by jjlharrison** [comment]
I have written a tool that measures coverage of new code introduced compared to a specific Git branch. We’ve been using it extensively within my organisation for months. I’ve been meaning to open source it.

It does the comparison based on a diff of the source code, not based on JARs. The measure is branch and line coverage of new and changed lines. It doesn’t tell you how overall coverage has changed. In its current state it requires that you use Git, JaCoCo, and Maven (it’s a Maven plugin). Would this be of any use to you?

Either way, I intend on putting it on GitHub this week (don’t hold me to that).

**Comment by marchof** [comment]
JaCoCo does not provide such an feature. You might consider using SonarQube which offers "coverage on new code".

Please use our mailing list for general discussions.

**Comment by shubhamc183** [comment]
hi @marchof  I know that SonarQube offers "coverage on new code" but I am not sure how can I use that particular feature as an API to achieve this delta code covered here. Can you point me out to that API in SonarQube?

TIA

**Comment by marchof** [comment]
@shubhamc183 I don't know SonarQube APIs. As said before: The mailing list is the place for discussions with a wider audience.

**Comment by shubhamc183** [comment]
@jjlharrison can you show me the code or add it on Github I am excited to see your work. 

TIA

**Comment by jjlharrison** [comment]
@shubhamc183: I've published the repository here: https://github.com/jjlharrison/coverage-maven-plugin

I'm planning on deploying it to Maven Central soon.
