### ISSUE TITLE
class visited but has not coverd lines

### ISSUE THREAD

**Issue by arthur657834** [jacoco/jacoco#938]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version: 0.8.4
Operating system: CentOS Linux release 7.5.1804 (Core) 
Tool integration: Maven/Ant/API/Other

### Expected behaviour
classe has covered lines

### Actual behaviour
classe has not covered lines

**Comment by arthur657834** [comment]
<img width="215" alt="1" src="https://user-images.githubusercontent.com/9419700/64664644-5a758900-d482-11e9-8586-9551aa20f600.png">
<img width="645" alt="3" src="https://user-images.githubusercontent.com/9419700/64664645-5b0e1f80-d482-11e9-9cf3-003692c4be95.png">
<img width="440" alt="2" src="https://user-images.githubusercontent.com/9419700/64664646-5b0e1f80-d482-11e9-9d6d-8a3ba9a168bc.png">

**Comment by marchof** [comment]
@arthur657834 The HTML report hast a "Sessions" link on top right corner. Please have a look at this page:

1) Is the class in question listed here?
2) Does it have a link on it?

**Comment by marchof** [comment]
@arthur657834 Also, when you click on the page of `EditorPreviewLogic`: Can you see a warning message here?

**Comment by arthur657834** [comment]
no,it is all good @marchof

**Comment by Godin** [comment]
> it has not link on it, what do you mean warning message?

In presence of the class name in "Sessions" page without link, you should be able to see message
```
A different version of class was executed at runtime.
```
on a page with list of methods of class (#819).

This is described in FAQ (https://www.jacoco.org/jacoco/trunk/doc/faq.html):

> Sessions link on the top right corner of the HTML report and check whether the class in question is listed. If it is listed but not linked the class at execution time is a different class file. [...] Note that some tools (e.g. [...] mocking frameworks) might modify your class files at runtime.

Your screenshots do not prove that real `EditorPreviewLogic` was executed. And in your particular case one can make guess and bet on mocking - see https://stackoverflow.com/questions/53944008/why-spring-service-methods-appear-with-0-code-coverage-in-jacoco/53949847#53949847

Anyway betting and guessing are counterproductive and unless you provide **complete executable example**, then there is nothing to add to the above explanations.
