### ISSUE TITLE
Jacoco is adding a $jacocoInit method in my interface when running unit tests

### ISSUE THREAD

**Issue by shubham7jain** [jacoco/jacoco#946]
I am getting a unnecessary method $jacocoInit when adding the defaut method in interface. My interface looks like this:

    @Value.Immutable
    public interface Customer {
    
        
        Optional<@NotBlank String> name();
    
        default Object getObject(final String abc) {
            return null
        }
    
        default void getObject() {
    
        }
    }

When I am doing

    for (Method method : Customer.class.getDeclaredMethods()) {
        System.out.println(method.getName());
    }

then, I am getting

    name
    getObject
    $jacocoInit

If I remove the default method from it, then it does not give $jacocInit method. I am not sure why it is happening?

**Comment by Godin** [comment]
Please read FAQ - http://www.jacoco.org/jacoco/trunk/doc/faq.html :

> #### My code uses reflection. Why does it fail when I execute it with JaCoCo?
>
> To collect execution data JaCoCo instruments the classes under test which adds two members to the classes: A private static field $jacocoData and a private static method $jacocoInit(). Both members are marked as synthetic.
>
> Please change your code to ignore synthetic members. This is a good practice anyways as also the Java compiler creates synthetic members in certain situation.
