### ISSUE TITLE
Offline instrumentation breaking Test with JDK11 [MAVEN]

### ISSUE THREAD

**Issue by nilson-aguiar** [jacoco/jacoco#961]
### Steps to reproduce

JaCoCo version: 0.8.4
Operating system: used this docker image maven:3-jdk-11-slim
Tool integration: Maven

### Expected behaviour

Complete code coverage equally on different JDK's

### Actual behaviour

Tests breaking on JDK11 and working ok with JDK8

I've created a [repository](https://github.com/RogerSilva2/JaCoCo-PowerMock-Error) to show the problem. I know that the integration between PowerMock and JaCoCo needs to work with offline instrumentation and I've created a test project to try it. So I got these results:

- On branch master uses java11 with online instrumentation. The code coverage on DummyService is 15%

- On branch java8 uses java8 with offline instrumentation. The code coverage on DummyService is 100%

- On branch java11 uses java11 with offline instrumentation. The tests are broken with the error bellow:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.368 s <<< FAILURE! - in br.com.testing.jacocoerror.service.DummyServiceTest
[ERROR] initializationError(br.com.testing.jacocoerror.service.DummyServiceTest)  Time elapsed: 0.01 s  <<< ERROR!
java.lang.IllegalStateException: Failed to transform class with name br.com.testing.jacocoerror.service.DummyServiceTest. Reason: java.io.IOException: invalid constant type: 17 at 49
Caused by: java.lang.RuntimeException: java.io.IOException: invalid constant type: 17 at 49
Caused by: java.io.IOException: invalid constant type: 17 at 49
```

I'm not sure this is caused by offline instrumentation, but I'm opening the ticket to get some help.

**Comment by Godin** [comment]
For Java 11+ class files JaCoCo version 0.8.4 uses dynamic class-file constant introduced in Java 11 (https://openjdk.java.net/jeps/309) - #845

> Caused by: java.io.IOException: invalid constant type: 17 at 49

`CONSTANT_Dynamic` has tag `17` in bytecode - https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.4

> java.lang.IllegalStateException: Failed to transform class with name br.com.testing.jacocoerror.service.DummyServiceTest.

is thrown by PowerMock - 
https://github.com/powermock/powermock/blob/powermock-2.0.3/powermock-core/src/main/java/org/powermock/core/classloader/javassist/JavassistMockClassLoader.java#L119

So similarly to #896 and #909 I'm pretty sure that version of PowerMock that you use also doesn't correctly/fully support Java 11 bytecode. Please report this to developers of PowerMock. As a temporary workaround while waiting for the fix in PowerMock, you can use JaCoCo version 0.8.3.

**Comment by nilson-aguiar** [comment]
Thanks!
