### ISSUE TITLE
JaCoCo fails to generate reports if maven-surefire-plugin has the argline --illegal-access=permit

### ISSUE THREAD

**Issue by lucasoares** [jacoco/jacoco#964]
# Steps to reproduce

* JaCoCo version: 0.8.5
* Operating system: Both Windows and Linux has the same problem.
* Tool integration: Maven
* Steps:

Using the following plugins configurations (surefire, compiler and JaCoCo):
```xml
  <properties>
    <argLine>-Dfile.encoding=UTF-8</argLine>
    <java.version>8</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <jacoco.version>0.8.5</jacoco.version>
  </properties>

  <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>${jacoco.version}</version>
        <executions>
          <execution>
            <id>report</id>
            <goals>
              <goal>prepare-agent</goal>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>${maven.compiler.source}</source>
          <target>${maven.compiler.target}</target>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.22.2</version>
        <configuration>
          <argLine>
            --illegal-access=permit
          </argLine>
        </configuration>
     </plugin>
  </plugins>
```

The `report` goal on all modules of my application are logging:
```
[INFO] --- jacoco-maven-plugin:0.8.5:report (report) @ ticket-oplog-formatter ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
```

If I remove the `argLine` configuration from `maven-surefire-plugin` all JaCoCo reports are created just fine.

I'm creating a `parent` that must be valid for either Java 8 and Java 11.
To use Java 11 on my Sring applications I need to set the `illegal-access=permit` to execute my tests and for Java 8 using this argument JaCoCo doesn't generate the reports.

**Comment by Godin** [comment]
This has nothing to do with `--illegal-access=permit` - please carefully read documentation  https://www.jacoco.org/jacoco/trunk/doc/prepare-agent-mojo.html that states:

> If your project already defines VM arguments for test execution, be sure that they will include property defined by JaCoCo.
>
> One of the ways to do this in case of maven-surefire-plugin - is to use syntax for [late property evaluation](http://maven.apache.org/surefire/maven-surefire-plugin/faq.html#late-property-evaluation):
> ```
>   <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-surefire-plugin</artifactId>
>     <configuration>
>       <argLine>@{argLine} -your -extra -arguments</argLine>
>     </configuration>
>   </plugin>
> ```
>
> You can define empty property to avoid JVM startup error `Could not find or load main class @{argLine}` when using late property evaluation and jacoco-maven-plugin not executed.
>
> Another way is to define "argLine" as a Maven property rather than as part of the configuration of maven-surefire-plugin:
> ```
>   <properties>
>     <argLine>-your -extra -arguments</argLine>
>   </properties>
>   ...
>   <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-surefire-plugin</artifactId>
>     <configuration>
>       
>     </configuration>
>   </plugin>
> ```

**Comment by teresadsprio** [comment]
file.encoding cannot be set as system property, use <argLine>-Dfile.encoding=...</argLine> instead

**Comment by teresadsprio** [comment]
file.encoding cannot be set as system property, use <argLine>-Dfile.encoding=...</argLine> instead Me aparece este error en NetBeans? Tiene que ver con dependencias ?
