### ISSUE TITLE
report-aggregate goal generates jacoco.xml only for the last module in the multimodule project

### ISSUE THREAD

**Issue by mstefantsiv** [jacoco/jacoco#966]
### Steps to reproduce
Here is my configuration in **root** pom:

```<plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <version>0.8.5</version>
          <configuration>
            <outputDirectory>${session.executionRootDirectory}/target/jacoco-coverage-aggregate</outputDirectory>
            <destFile>${session.executionRootDirectory}/target/jacoco-coverage/jacoco.exec</destFile>
            <append>true</append>
          </configuration>
          <executions>
            <execution>
              <id>coverage-initialize</id>
              <goals>
                <goal>prepare-agent</goal>
              </goals>
            </execution>
            <execution>
              <id>report</id>
              <phase>test</phase>
              <goals>
                <goal>report</goal>
              </goals>
            </execution>
            <execution>
              <id>report-aggregate</id>
              <phase>test</phase>
              <goals>
                <goal>report-aggregate</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
```

Configuration in child modules:
```<build> 
  <plugins>
     ...
     <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
      </plugin>
      ...
   </plugins>
</build>
```

JaCoCo version:  0.8.5
Operating system: Windows
Tool integration: Maven

### Expected behaviour
I expect **report-aggregate** to generate a report for all submodules that have **jacoco-maven-plugin** dependecy.

### Actual behaviour
Report in **outputDirectory** folder is overridden module by module and contains information only about last executed module.

**Comment by Godin** [comment]
> I expect report-aggregate to generate a report for all submodules that have `jacoco-maven-plugin` dependecy.

`report-aggregate` doesn't work this way and this is not a bug - please carefully read documentation https://www.jacoco.org/jacoco/trunk/doc/report-aggregate-mojo.html that states 

> The report is created from all modules this project depends on.
