### ISSUE TITLE
when i got the report i found the class definition has mark red

### ISSUE THREAD

**Issue by xiaoyi8837** [jacoco/jacoco#967]
i got the report by using java code
just like this
![image](https://user-images.githubusercontent.com/20347806/67192827-d91cf900-f426-11e9-9cae-185fb4391eba.png)

then  i  got the report  like this
![image](https://user-images.githubusercontent.com/20347806/67192859-f0f47d00-f426-11e9-8973-fd219fbe947c.png)

 the class implements an interface

**Comment by Godin** [comment]
As stated in template which was ignored by you - we do not answer questions in GitHub, for questions please use forum.

And especially we do not answer poorly written questions such as this one, which contain only statements and where question itself is absent.

The generated report "like this" is absolutely correct and expected one: line of class definition corresponds to the default constructor, it is red when there is no data about its execution.
