### ISSUE TITLE
java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system) (again, with solution)

### ISSUE THREAD

**Issue by mikehardy** [jacoco/jacoco#968]
Please note: this is more of an interaction between tools. I don't think it is actually a jacoco bug.

There is **a solution below** that I have tested and is working.

There was no exactly on-target information I could find to resolve this.

It is my hope others that search for this problem see this and self-help, so you can focus your efforts on developing this fantastic project :-)

I will close this after logging it.

### Steps to reproduce

* JaCoCo version:  0.8.4 vs 0.8.5 (it's a difference on upgrade)
* Tool integration: Gradle + Android instrumented tests + JaCoCo
* Complete executable reproducer: https://github.com/mikehardy/Anki-Android/commit/dfca8ff89a9276f17042c8f2bc1933a78c63e15a (with jacoco-agent.properties it works with 0.8.5, without it 0.8.4 works but 0.8.5 fails)
* Steps: Demonstrating a subtle interaction between that stack of integrated tools versus the change in 0.8.5 that fails-fast on "config errors"

### Expected behaviour

0.8.5 works without changes when upgrading from 0.8.4

### Actual behaviour

0.8.5 crashes as it attempts to open '/jacoco.exec' during startup, as a test for file-system write access.

There is something in the android instrumented test plugin that starts with that configuration but does not actually use it - as coverage is actually written to `/data/data/<android package name>/coverage.ec` which is always writable.

So this configuration used to work fine even though it is technically in error from jacoco's perspective, but in 0.8.5 it now fails on startup.

## Solution

The solution is well-documented in jacoco but for Android people, what you need is to add the file in `/src/androidTest/resources/jacoco-agent.properties` with the contents `output=none` so jacoco can startup without failing, and coverage will be written as normal and transferred correctly later by the android gradle plugin coverage implementation.

This commit shows the required change for the upgrade:
https://github.com/mikehardy/Anki-Android/commit/dfca8ff89a9276f17042c8f2bc1933a78c63e15a

That (as well as a fully-working integrated instrumented + unit test coverage report) will later show up in https://github.com/ankidroid/Anki-Android in case the commit hash is lost.

Cheers

**Comment by mikehardy** [comment]
For the avoidance of doubt: I don't think this was a bug and it has a solution. Hopefully it helps others that search and land here. Closing now, cheers

**Comment by marchof** [comment]
@mikehardy Thanks for sharing this information!

**Comment by Godin** [comment]
@mikehardy Thank you for sharing! :thumbsup: :heart:

For the record: intentional change in 0.8.5 to not ignore startup failures - is #910

**Comment by gavra0** [comment]
@Godin Should Android Gradle plugin always set `output=none` in `jacoco-agent.propertie`? I am working on fixing https://issuetracker.google.com/151471144 in order to remove noisy logcat, but I'd like to make sure adding this option will not hide any issues. Thanks!

**Comment by mikehardy** [comment]
From my perspective / memory as I looked at this, it was definitely unexpected behavior that for the standard Android use case I had to add a file containing the `output=none` directive, so it should help people if were the default AGP behavior.

In case your comment doesn't see an authoritative maintainer response, from memory in my read of the code while figuring this out, it would fix the common/documented integration of these tools but would not hide anything.

Would be great if this were fixed, excited it is getting some attention!

**Comment by TWiStErRob** [comment]
@marchof @Godin can you please help @gavra0 out? It would be nice to see this fixed in "otherproject".

**Comment by marchof** [comment]
@TWiStErRob @gavra0 I really not into the Android SDK. If the execution data is always read via JaCoCo's runtime API you can always set `output=none`. There are no side effects except that no data is written.

**Comment by TWiStErRob** [comment]
For the record an example stack trace in LogCat for OP "Actual behavior":
```
W System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
W System.err: 	at java.io.FileOutputStream.open(Native Method)
W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
W System.err: 	at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
W System.err: 	at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.startup(FileOutput.java:49)
W System.err: 	at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:122)
W System.err: 	at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
W System.err: 	at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
W System.err: 	at org.jacoco.agent.rt.internal_8ff85ea.Offline.getProbes(Offline.java:51)
W System.err: 	at com.example.App.$jacocoInit(App.java)
W System.err: 	at com.example.App.<init>(App.java)
W System.err: 	at com.example.test.instrumentation.TestApp.<init>(TestApp.kt:7)
W System.err: 	at java.lang.Class.newInstance(Native Method)
W System.err: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1007)
W System.err: 	at android.app.Instrumentation.newApplication(Instrumentation.java:992)
W System.err: 	at com.example.test.instrumentation.UiTestJUnitRunner.newApplication(UiTestJUnitRunner.kt:40)
W System.err: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5377)
W System.err: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
W System.err: 	at android.os.Looper.loop(Looper.java:154)
W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by kkogut95** [comment]
@mikehardy Thanks for the solution! But shouldn't the path to the file created in solution be changed to `/src/main/resources/jacoco-agent.properties` it didn't work form me in `../androidTests/..` but following solution from your commit I managed to fix it, so thank you once again 🙇

**Comment by mikehardy** [comment]
Unsure about your setup, but in a standard Android Studio instrumented test setup, the instrumentation is from the androidTests directory, you'll note that I linked to actual commits that are then exercised in Travis CI so I have proof it worked for me in androidTests. Perhaps my solution isn't general enough though? :thinking: at which point I suppose I'd want it in src/debug/resources/jacoco-agent.properties really? I avoid putting things in main unless I have to. That said hopefully there is a fix upstream for this combination of tools such that they interact safely by default via work by @gavra0

**Comment by TWiStErRob** [comment]
We put it in `src/androidTest/resources/jacoco-agent.properties`, and it works:
![image](https://user-images.githubusercontent.com/2906988/85429271-67c5b500-b576-11ea-97ba-911c8c7fef72.png)
It's not production code (androidTest), but it needs to be on Java classpath (resources).

**Comment by TWiStErRob** [comment]
@mikehardy what you describe in OP and what you show in commit is different.

**Comment by mikehardy** [comment]
:scream: totally correctly @TWiStErRob - my mistake on my commit to my project, after I spent so much careful time documenting it for future testing explorers. THanks

**Comment by kkogut95** [comment]
Yep, it turned out that we were running jacoco on app start in some module. Thanks for the help! 😄

**Comment by ZacSweers** [comment]
@mikehardy I noticed you [reverted](https://github.com/ankidroid/Anki-Android/commit/6d31710da59b91505d7ec2a23e42b0960721bf99) that change. Did it end up not working?

**Comment by mikehardy** [comment]
@ZacSweers it did not. No idea why. I had to have the file in src/main - an unexpected (but unequivocal) result for us. Contradicts reported success so I'm lost but moved on

**Comment by ZacSweers** [comment]
Thanks for confirming. We found the same, only works in src/main

**Comment by alex-dorokhov** [comment]
For those who is in doubt where to put the **jacoco-agent.properties** file, it all depends for which flavour you have the testCoverageEnabled set to true.

E.g. if you have:
```
android {
    buildTypes {
        debug {
            testCoverageEnabled true
        }
    }
}
```
That means you have enabled the coverage for the **debug** buildConfig/flavour. In that case just put the properties file into _src/**debug**/resources_

Then you will not see the stacktrace in both cases: while running your app in debug mode and when running the instrumentation tests.

If you put the properties file to src/androidTest/resources, then you will only get rid of the stacktrace while running the instrumentation tests, but it will be still there, when you run the app in debug mode.

Putting it to _src/main/resources_ does the trick in any case, because those sources are included in any flavour, but this can be ugly, because the file will be included into the release build of your app/library.

**Comment by nikitha2** [comment]
Hi @mikehardy , after I added -jacoco-agent.properties file under debug/resources, fileNotFoundException is gone. Where am I supposed to see the readable coverage report in testlab? I can only find coverage.ec file under /artifacts/sdcard in testlab that is not readable

**Comment by mikehardy** [comment]
Sorry, I can't provide detailed support on all use cases, all I can say is that the agent will successfully create a coverage report (that `coverage.ec` file with this workaround, so there's no issue here with jacoco

**Comment by ersen-lw** [comment]
Big thanks to @mikehardy and all in this thread. I encountered this issue yesterday and was able to resolve it. I used the solution posted here https://github.com/jacoco/jacoco/issues/968#issuecomment-672996619. 

Below is my journey in case it helps someone else. 

I recently updated the Android project I work on to Kotlin 1.5.20. During that update I encountered the following issue:
https://github.com/jacoco/jacoco/issues/1155. 
Updating to Jacoco 0.8.7 is the solution but I had a problem where 0.8.7 was not being used. Others in that issue thread encountered the same issue but using the solution posted here https://github.com/jacoco/jacoco/issues/1155#issuecomment-859109608 forces Jacoco to use that version.

After updating, this is when I began to encounter this issue. I think the Jacoco plugin used by the Android instrumented test plugin could be outdated may have used version 0.8.4 or earlier which ignored start-up failures. This is just a theory though I am not sure. 

Anyways, if you got a multi library module where each module has instrumented tests, I added the following code to my root `build.gradle` file to ensure the file is present for those modules and can be auto generated if a new module is made. 

```
subprojects {

    afterEvaluate { project ->
           def isAndroidLibrary = project.plugins.hasPlugin("com.android.library")
           def isAndroidApplication = project.plugins.hasPlugin("com.android.application")

           if (isAndroidLibrary || isAndroidApplication) {
                File debugResourcesDirectory = project.file("src/debug/resources")
                File jacocoAgentProperties = new File(debugResourcesDirectory, "jacoco-agent.properties")
                if(!jacocoAgentProperties.exists()){
                    debugResourcesDirectory.mkdirs()
                    jacocoAgentProperties.setText("output=none")
                }
          }
}
```

**Comment by TWiStErRob** [comment]
Please don't do that @ersen-lw, File I/O should be avoided in Gradle build scripts, that's for the tasks to do.

Something like this (untested) should do the same, but the Gradle way:
```gradle
subprojects {
    afterEvaluate { project ->
        def isAndroidLibrary = project.plugins.hasPlugin("com.android.library")
        def isAndroidApplication = project.plugins.hasPlugin("com.android.application")

        if (isAndroidLibrary || isAndroidApplication) {
            def generateJacocoAgent = project.tasks.register("generateJacocoAgentProperties") {
                File propsFile = new File(project.file("src/androidTest/resources"), "jacoco-agent.properties")
                outputs.file(propsFile)
                doLast {
                    if (!propsFile.exists()) {
                        propsFile.parentFile.mkdirs()
                        propsFile.text = "output=none"
                    }
                }
            }
            // Hook into the point where this is meant to happen. This will lazily execute only when the androidTest is being processed, so not on unit tests or simple assemble.
            project.tasks.named("generateDebugAndroidTestResources").configure { it.dependsOn(generateJacocoAgent) }
        }
    }
}
```
Could be potentially made even better with the new variants API:
https://medium.com/androiddevelopers/new-apis-in-the-android-gradle-plugin-f5325742e614

**Comment by ryan-krnwn** [comment]
Undefined instruction 0xd5380000 at 0x00007e61a60f6f70
