### ISSUE TITLE
How to use tcpclient while using jacoco agent

### ISSUE THREAD

**Issue by zhangpeng23796** [jacoco/jacoco#969]
when I use jacoco agent to collect coverage ,as follow:
-javaagent:D:\jacoco\jacoco-0.8.5\lib\jacocoagent.jar=includes=*,output=tcpclient,port=6300,address=127.0.0.1

Then I create a socket server,like ExecutionDataServer.java，

```
public final class ExecutionDataServer {

private static final String DESTFILE = "jacoco-server.exec";

private static final String ADDRESS = "127.0.0.1";

private static final int PORT = 6301;

/**
* Start the server as a standalone program.
*
* @param args
* @throws IOException
*/
public static void main(final String[] args) throws IOException {
final ExecutionDataWriter fileWriter = new ExecutionDataWriter(
new FileOutputStream(DESTFILE));
final ServerSocket server = new ServerSocket(PORT, 0,
InetAddress.getByName(ADDRESS));
System.out.println("服务已启动。。。");
while (true) {
final Handler handler = new Handler(server.accept(), fileWriter);
new Thread(handler).start();
}
}

private static class Handler
implements Runnable, ISessionInfoVisitor, IExecutionDataVisitor {

private final Socket socket;

private final RemoteControlReader reader;

private final ExecutionDataWriter fileWriter;

Handler(final Socket socket, final ExecutionDataWriter fileWriter)
throws IOException {
this.socket = socket;
this.fileWriter = fileWriter;

// Just send a valid header:
new RemoteControlWriter(socket.getOutputStream());

reader = new RemoteControlReader(socket.getInputStream());
reader.setSessionInfoVisitor(this);
reader.setExecutionDataVisitor(this);
}

public void run() {
try {
while (reader.read()) {
}
socket.close();
synchronized (fileWriter) {
fileWriter.flush();
}
} catch (final IOException e) {
e.printStackTrace();
}
}

public void visitSessionInfo(final SessionInfo info) {
System.out.printf("Retrieving execution Data for session: %s%n",
info.getId());
synchronized (fileWriter) {
fileWriter.visitSessionInfo(info);
}
}

public void visitClassExecution(final ExecutionData data) {
synchronized (fileWriter) {
fileWriter.visitClassExecution(data);
}
}
}

private ExecutionDataServer() {
}
}
```

But I can't accept data ?
Could you help me?
Thank you!

**Comment by Godin** [comment]
<h3>First and foremost please do not use GitHub for questions, <a href="https://groups.google.com/forum/?fromgroups=#!forum/jacoco">use forum</a> instead</h3>

----

No idea what exactly means 

> can't accept data

If this means that you get exception on

```
server.accept()
```

then this has nothing to do with JaCoCo - please learn how to use sockets somewhere else.

And in case of exceptions please always provide full stack trace.

----

> when I use jacoco agent
> Then I create a socket server

**server should be started before agent**

Also your configuration of agent specifies port `6300`, which does not match port `6301` in your `ExecutionDataServer.java`.

----

After starting our https://www.jacoco.org/jacoco/trunk/doc/examples/java/ExecutionDataServer.java as following

```
javac -cp jacoco-0.8.5/lib/org.jacoco.core-0.8.5.201910111838.jar ExecutionDataServer.java -d server

java -cp jacoco-0.8.5/lib/org.jacoco.core-0.8.5.201910111838.jar:server org.jacoco.examples.ExecutionDataServer
```

Compilation of the following `Example.java`

```
class Example {
    public static void main(String[] args) {
    }
}
```

And execution with agent as following

```
javac Example.java -d classes

java -javaagent:jacoco-0.8.5/lib/jacocoagent.jar=output=tcpclient,sessionid=test -cp classes Example
```

Server produces expected message

```
Retrieving execution Data for session: test
```

and expected file `jacoco-server.exec`.

**Comment by zhangpeng23796** [comment]
Thanks you very much! I have missed the param as follow:
`sessionid=test`

Then with tcpclient, I can only accept data while stopping the  agent, is it possible to accept data timely， it means no need to stop agent？

**Comment by Godin** [comment]
There is already answer in FAQ - http://www.jacoco.org/jacoco/trunk/doc/faq.html :

> ### Can I collect coverage information without stopping the JVM?
>
> Yes, there are three possible ways: The JaCoCo agent can be configured for remote control via TCP/IP sockets. **This allows to collect execution data at any point in time from a running JVM.** ...

So before asking questions please carefully read documentation - https://www.jacoco.org/jacoco/trunk/doc/api/org/jacoco/core/runtime/RemoteControlWriter.html#visitDumpCommand(boolean,%20boolean)

And search for already existing answers, in archive of our forum there are tons of answers on exactly this question:
https://groups.google.com/d/msg/jacoco/V7Bmz5r0P24/PdCC5apIoqgJ
https://groups.google.com/d/msg/jacoco/MUTIM5yS6ZQ/KSA5Og4xBgAJ
