### ISSUE TITLE
*.xlsx  file in the outputDirectory is identified as ContentTypeDetector.ZIPFILE

### ISSUE THREAD

**Issue by lyxiaobei** [jacoco/jacoco#979]
### Steps to reproduce

* JaCoCo version:  0.8.5
* Operating system: Linux 
* Tool integration: Maven
* Complete executable reproducer: (e.g. GitHub Repo)
* Steps: (what exactly are you doing with the above reproducer?)

I hava a maven project with 5 modules. When running `jacoco:report-aggregate` goal, it  throws an `IllegalArgumentException:MALFORMED`, the stack trace is as below.

I wrote a test method and found that the file named "temp.xlsx" is determined as a ContentTypeDetector.ZIPFILE.

1347093252 file /Users/lyxiaobei/Documents/jacoco-0.8.5/jacoco-maven-plugin/classes/static/temp.xlsx

```
Exception in thread "main" java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
	at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:300)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
	at org.jacoco.maven.TestMain.nextEntry(TestMain.java:77)
	at org.jacoco.maven.TestMain.analyzeZip(TestMain.java:67)
	at org.jacoco.maven.TestMain.analyzeAll(TestMain.java:52)
	at org.jacoco.maven.TestMain.analyzeAll(TestMain.java:28)
	at org.jacoco.maven.TestMain.main(TestMain.java:96)
```

### Expected behaviour

The function `ContentTypeDetector.determineType`  can determine type of file correctly. 

### Actual behaviour

It determines a `*.xlsx` file as a Zip file.

```
Caused by: java.lang.IllegalArgumentException: MALFORMED
    at java.util.zip.ZipCoder.toString (ZipCoder.java:58)
    at java.util.zip.ZipInputStream.readLOC (ZipInputStream.java:300)
    at java.util.zip.ZipInputStream.getNextEntry (ZipInputStream.java:122)
    at org.jacoco.core.analysis.Analyzer.nextEntry (Analyzer.java:273)
    at org.jacoco.core.analysis.Analyzer.analyzeZip (Analyzer.java:264)
    at org.jacoco.core.analysis.Analyzer.analyzeAll (Analyzer.java:196)
    at org.jacoco.core.analysis.Analyzer.analyzeAll (Analyzer.java:226)
    at org.jacoco.maven.ReportSupport.processProject (ReportSupport.java:202)
    at org.jacoco.maven.ReportSupport.processProject (ReportSupport.java:185)
    at org.jacoco.maven.ReportAggregateMojo.createReport (ReportAggregateMojo.java:139)
    at org.jacoco.maven.AbstractReportMojo.executeReport (AbstractReportMojo.java:181)
    at org.jacoco.maven.AbstractReportMojo.execute (AbstractReportMojo.java:166)
```

**Comment by Godin** [comment]
As far as I know `xlsx` files are actually ZIP files - see https://docs.microsoft.com/en-us/openspecs/office_standards/ms-xlsx/2c5dee00-eff2-4b22-92b6-0738acd4475e I also can see this on example of empty spreadsheet created using [Numbers application](https://en.wikipedia.org/wiki/Numbers_(spreadsheet))  on macOS and exported into [`test.xlsx`](https://github.com/jacoco/jacoco/files/3913060/test.xlsx):

command `file test.xlsx` shows
```
test.xlsx: Microsoft Excel 2007+
```

command `zipinfo test.xlsx` shows
```
Archive:  test.xlsx
Zip file size: 6327 bytes, number of entries: 10
-rw----     6.2 fat      571 b- defN 19-Dec-02 13:01 _rels/.rels
-rw----     6.2 fat      283 b- defN 19-Dec-02 13:01 docProps/core.xml
-rw----     6.2 fat      215 b- defN 19-Dec-02 13:01 docProps/app.xml
-rw----     6.2 fat      399 b- defN 19-Dec-02 13:01 xl/workbook.xml
-rw----     6.2 fat      681 b- defN 19-Dec-02 13:01 xl/_rels/workbook.xml.rels
-rw----     6.2 fat    21997 b- defN 19-Dec-02 13:01 xl/theme/theme1.xml
-rw----     6.2 fat     5086 b- defN 19-Dec-02 13:01 xl/worksheets/sheet1.xml
-rw----     6.2 fat      156 b- defN 19-Dec-02 13:01 xl/sharedStrings.xml
-rw----     6.2 fat     5087 b- defN 19-Dec-02 13:01 xl/styles.xml
-rw----     6.2 fat     1720 b- defN 19-Dec-02 13:01 [Content_Types].xml
10 files, 36195 bytes uncompressed, 4985 bytes compressed:  86.2%
```

placement of this file as `org.jacoco.core/target/classes/test.xlsx` into JaCoCo build itself where we do use `jacoco:report-aggregate` does not cause any exceptions. Following direct usage of JaCoCo APIs for a directory containing this file also doesn't cause any exceptions
```
import org.jacoco.core.analysis.Analyzer;
import org.jacoco.core.analysis.IClassCoverage;
import org.jacoco.core.analysis.ICoverageVisitor;
import org.jacoco.core.data.ExecutionDataStore;

import java.io.File;
import java.io.IOException;

public class Example {
	public static void main(String[] args) throws IOException {
		Analyzer analyzer = new Analyzer(new ExecutionDataStore(),
				new ICoverageVisitor() {
					public void visitCoverage(IClassCoverage coverage) {
					}
				});
		analyzer.analyzeAll(new File("target/classes/"));
	}
}
```

as well as reading of this file as a ZIP using Java APIs in a way similar to `org.jacoco.core.analysis.Analyzer` doesn't cause any exceptions
```
import java.io.FileInputStream;
import java.io.IOException;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

public class Example {
	public static void main(String[] args) throws IOException {
		ZipInputStream zip = new ZipInputStream(
				new FileInputStream("target/classes/test.xlsx"));
		ZipEntry entry;
		while ((entry = zip.getNextEntry()) != null) {
			if (entry.isDirectory()) {
				System.out.println("dir  : " + entry.getName());
			} else {
				System.out.println("file : " + entry.getName());
			}
		}
		zip.close();
	}
}
```

All of the above therefore makes me think that your file might be really malformed/corrupted, so @lyxiaobei could you please provide it?

---

Also you can exclude `xlsx` files from analysis by specifying following in configuration of `report-aggregate`

```
<excludes>
  <exclude>**/*.xlsx</exclude>
</excludes>
```

or include only `class` files by specifying

```
<includes>
  <include>**/*.class</include>
</includes>
```

see documentation of goal at https://www.jacoco.org/jacoco/trunk/doc/report-aggregate-mojo.html#excludes

**Comment by lyxiaobei** [comment]
Thank you Godin. 
I have added excludes property  and the exception is solved . 
I didn't know xlsx files are ZIP files,  and thought it an issue.   
Thank you again for your reply.

**Comment by Godin** [comment]
@lyxiaobei glad that configuration of exclusion helped. However could you please anyway provide file, which was causing exception?
