### ISSUE TITLE
JaCoCo report should be skipped if test are skipped (and no execution data is found)

### ISSUE THREAD

**Issue by Vampire** [jacoco/jacoco#981]
I wanted to install some project into my local maven repository without running the tests, so I did `mvn install -DskipTests`, but this complained that the JaCoCo report couldn't be produced as the execution data was missing. If tests are skipped and the report file is not found, this should not cause the build to fail.

**Comment by Godin** [comment]
Please always attach steps to reproduce when creating ticket. In case of the usual usage of `jacoco-maven-plugin` - see [example.zip](https://github.com/jacoco/jacoco/files/3935745/example.zip), execution of `mvn clean install` produces report, whereas execution of `mvn clean install -DskipTests` does not fail build while produces following message implemented a long time ago in https://github.com/jacoco/jacoco/issues/19

```
[INFO] --- jacoco-maven-plugin:0.8.5:report (default) @ example ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
```

**Comment by Vampire** [comment]
Sorry for not including an example @Godin, but I guess then the error is back.
What you reference mentions Surefire 2.12.2 and as fix-milestone 0.6.0.
This happened with Surefire 2.22.2 and jacoco-maven-plugin 0.8.4.
To see it yourself, the project where this happened to me is JMockit (https://github.com/jmockit/jmockit1)  on the latest `master` commit.

**Comment by Godin** [comment]
@Vampire in the above `example.zip` from my comment https://github.com/jacoco/jacoco/issues/981#issuecomment-562902249 explicit specification of `maven-surefire-plugin` version `2.22.2` and usage of `jacoco-maven-plugin` version `0.8.4` doesn't change anything.

Furthermore
```
git clone git@github.com:jmockit/jmockit1.git
cd jmockit1/main
mvn -V install -DskipTests
```
works just fine for me - here is [log.txt](https://github.com/jacoco/jacoco/files/3940898/log.txt) as a proof.

**Comment by Vampire** [comment]
Strange, I cannot reproduce it now either. :-/
I even restored the state where it happened from backup.
If I happen to hit the edge-case where it happens again, I'll try to provide more info.

**Comment by ricklkl** [comment]
`<plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.6</version>
                <executions>
                    <execution>
                        <id>report-aggregate</id>
                        <phase>test</phase>
                        **<configuration>
                            <skip>${skipTests}</skip>
                        </configuration>**
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>`
I solved this problem with add a <skip>true</skip> in <configuration> tag，this is also work for other goal for example report or prepare-agent.
Just for your reference.
