### ISSUE TITLE
Coverage on inline-lambda not correct

### ISSUE THREAD

**Issue by barclay-reg** [jacoco/jacoco#985]
Hi,

I have the following code snippet

``` 
public Boolean doSomething(Optional<String> optional)
{
      return optional
         .map(string -> string.contains("pattern"))
         .orElse(Boolean.FALSE);
}
```

meassuring the coverage with input `Optional.empty()` gives me a 100% (line and also condition) code coverage.

Although ` .map(string -> string.contains("pattern"))` is executed (the `map()` part) the lambda `string.contains("pattern")` is never executed, so should not be shown as 'covered'

I would understand, that this is a topic, which cannot be solved by jacoco or any other coverage tool, But I really would like to know, what you think about this.

**Comment by marchof** [comment]
JaCoCo shows the line with the lambda correctly as partial covered:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/1936262/70904893-d2fc6080-2002-11ea-9625-39e7146f5042.png">
