### ISSUE TITLE
org.jacoco.agent.jar 0.8.5 doesn't have pre-main attribute in manifest

### ISSUE THREAD

**Issue by mebigfatguy** [jacoco/jacoco#986]
### Steps to reproduce

* JaCoCo version:  0.8.5
* Operating system: Linux Mint
* Tool integration: Ant

When i pull 
g: org.jacoco
a: org.jacoco.agent.jar
v: 0.8.5

it doesn't have a pre-main attribute in the manifest.

When i pull the jacocoagent jar out of the org.jacoco.ant jar, it does.

### Expected behaviour

The agent jar pulled from maven to have a pre-main attribute

### Actual behaviour

No pre-main attribute

**Comment by marchof** [comment]
The artifact you're referring to is actually an wrapper. See JavaDoc:

https://www.jacoco.org/jacoco/trunk/doc/api/org/jacoco/agent/AgentJar.html

What you're looking can be obtained with the type `runtime`:

    <dependency>
      <groupId>org.jacoco</groupId>
      <artifactId>org.jacoco.agent</artifactId>
      <version>0.8.5</version>
      <type>runtime</type>
    </dependency>

**Comment by mebigfatguy** [comment]
I'm not using maven, so what does this mean? How do i get the artifact that has pre-main, besides unzipping the ant.jar?

**Comment by Godin** [comment]
@mebigfatguy see https://stackoverflow.com/a/53651065/244993

**Comment by mebigfatguy** [comment]
ah! ok. thanks
