### ISSUE TITLE
JaCoCo 0.8.2 seems to conflict with JMockit 1.46 + Junit 5.4.0 in Java 8

### ISSUE THREAD

**Issue by mianbaoji** [jacoco/jacoco#988]
Here I use <prepare-agent> in parent module and  <report-aggregate> in test module  for multiple packages.
```
                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.8.2</version>
                        <executions>
                            <execution>
                                <id>prepare-agent</id>
                                <goals>
                                    <goal>prepare-agent</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
```

```
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.2</version>
                <executions>
                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Then one module add JMockit official  initial configurations
```
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <argLine>
                        -javaagent:${settings.localRepository}/org/jmockit/jmockit/${jmockit.version}/jmockit-${jmockit.version}.jar
                    </argLine>
                </configuration>
            </plugin>
```

`jacoco.exec` file would be lost after package  and coverage  would be 0%.

how to amend my Maven settings?

Thank you!

**Comment by mianbaoji** [comment]
I generate file manually by:
`   <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <argLine>
                        -javaagent:${settings.localRepository}/org/jmockit/jmockit/${jmockit.version}/jmockit-${jmockit.version}.jar
                        -javaagent:${settings.localRepository}/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=target/jacoco.exec
                    </argLine>
                </configuration>
            </plugin>
`

And it worked, I hop to know wheter I can use other method.

**Comment by Godin** [comment]
@mianbaoji please carefully read documentation https://www.jacoco.org/jacoco/trunk/doc/prepare-agent-mojo.html that states:

> If your project already defines VM arguments for test execution, be sure that they will include property defined by JaCoCo.
>
> One of the ways to do this in case of maven-surefire-plugin - is to use syntax for [late property evaluation](http://maven.apache.org/surefire/maven-surefire-plugin/faq.html#late-property-evaluation):
> ```
>   <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-surefire-plugin</artifactId>
>     <configuration>
>       <argLine>@{argLine} -your -extra -arguments</argLine>
>     </configuration>
>   </plugin>
> ```
>
> You can define empty property to avoid JVM startup error `Could not find or load main class @{argLine}` when using late property evaluation and jacoco-maven-plugin not executed.
>
> Another way is to define "argLine" as a Maven property rather than as part of the configuration of maven-surefire-plugin:
> ```
>   <properties>
>     <argLine>-your -extra -arguments</argLine>
>   </properties>
>   ...
>   <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-surefire-plugin</artifactId>
>     <configuration>
>       
>     </configuration>
>   </plugin>
> ```
