### ISSUE TITLE
Maven multi-module build won't detect war during report aggregation

### ISSUE THREAD

**Issue by kid1412621** [jacoco/jacoco#991]
I follow [here](https://github.com/jacoco/jacoco/wiki/MavenMultiModule) to create a dedicate module to aggregate report. My project is made of multi-module. And one of them is meant to package WAR according to maven profile setting.
When I change the profile to package WAR, the aggregation module turns out this error: `Failure to find com.xxx.xxx:jar:3.1.1 in http://repo2.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central-p has elapsed or updates are forced`. But this module should package to WAR, instead of JAR.
 And I specify the type of dependency to WAR in aggregation module. The error is gone.

**Comment by gebitang** [comment]
@kid1412621  
 The same problem happened here. 

as you mentioned here, I specify the type of dependency to war in the dedicated module. such as 

```
<dependency>
      <groupId>com.xxx.yyy</groupId>
      <artifactId>name</artifactId>
      <version>0.1-SNAPSHOT</version>
      <type>war</type>
    </dependency>
```

After add **<type>war</type>**, the finding failure no longer existed. But here is another one while executing `mvn clean install` for the whole project.

>Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.5.4.RELEASE:repackage failed: Unable to find main class -> [Help 1]
