### ISSUE TITLE
Allow filtering of specific methods in Java

### ISSUE THREAD

**Issue by yuvalprtn** [jacoco/jacoco#993]
### Scenario
* JaCoCo version: 0.8.5
* Operating system: Mac OS
* Tool integration: Gradle
* Description of your use case: Java code coverage 

### Current Behavior
Only class level exclusion is available 
### Wanted Behavior
Ability to filter out methods by name pattern. In this case we will be able to remove toString, hashCode, equals as well as specific methods if we choose not to pass through coverage for these.
Specifically toString is quite redundant in our POV.
Using annotations or comments will require us to go class by class for exclusion while a rule of some sort is what we are looking for
### Possible Workarounds
None that we know of

**Comment by nikolim** [comment]
Is this topic still relevant? I think this is a good idea and would like to work with colleagues on this issue

**Comment by better-712** [comment]
I have made a pull request for this issue, it can pass through coverage for toString ,if needed, hashCode, equals can also be added , they can be implemented similarly。

**Comment by better-712** [comment]
I have made a pull request for this issue, it can pass through coverage for toString ,if needed, hashCode, equals can also be added , they can be implemented similarly。Thanks for DanielKraft

**Comment by better-712** [comment]
By name pattern, we can also filter out other methods.

**Comment by marchof** [comment]
To manage expectations: We will not include configurable filtering to JaCoCo as this makes testing and support even harder due to another dimension of complexity. Please understand that this is a pure side project and we need to keep the scope manageable for our limited time budget.
