### ISSUE TITLE
source code with absolute paths on windows

### ISSUE THREAD

**Issue by pdinc-oss** [jacoco/jacoco#994]
related to #939, see follow up commit for discussion.

**Comment by marchof** [comment]
Template ignored, so we have no idea what this is about --> invalid.

**Comment by pdinc-oss** [comment]
see commit https://github.com/pdinc-oss/jacoco/commit/f9265c10440e40106070a9d111e96be7b4c605d0 for what it is about.

**Comment by Godin** [comment]
> What template?

The one that is shown when requesting an enhancement:

<img width="994" alt="1" src="https://user-images.githubusercontent.com/138671/72614778-6b07a580-3933-11ea-9903-f6d251c33aea.png">

<img width="993" alt="2" src="https://user-images.githubusercontent.com/138671/72614898-b621b880-3933-11ea-88e1-d2c8cae11559.png">
